### ISSUE TITLE
Programmatically set active Filter option 

### ISSUE THREAD

**Issue by lorenscott** [running-coder/jquery-typeahead#100]
Using the Beer v1 demo as an example, how could I programmatically set "Ale" as the active filter?

Thanks.

**Comment by running-coder** [comment]
hey loren, I've not tested yet but your best bet would be to look in the documentation for the "Extras" section. Try selecting a dropdown Item and print window.Typeahead['#mySearchInput'].filters.dropdown and then manually set the values you need according to your source item keys. After setting the dropdown filter you will need to trigger a search event manually $('#mySearchInput').trigger('input.typeahead');
