### ISSUE TITLE
Results not displaying

### ISSUE THREAD

**Issue by MystifyBFC** [running-coder/jquery-typeahead#104]
I must be missing something obvious but I have the following jquery;

``` javascript
 $('.typeahead-meals').typeahead({
       minLength: 3,
       dynamic: true,
       hint: false,
       highlight: true,
       display: 'Name',
       source: {
           meals: {
               url: [{
                   type: 'GET',
                   url: 'URL', 
                   dataType: 'json',
                   data: {q: '{{query}}'},
                   callback: {
                       done: function (data, textStatus, jqXHR) {
                           console.log(data);
                           return data;
                       }
                   }
               }],
           },
       },
   })
```

This is returning successfully the following;

``` javascript
[
    {"ID": 248, "Name": "Prawn Ramen Soup Noodles & Crispy Seaweed"},
    {"ID": 576, "Name": "Ham & Emmental"}, 
    {"ID": 821, "Name": "Melting Moments "},
    {"ID": 971, "Name": "Mushroom and Emmental Panini"}
]
```

At least that is what is in data upon writing it out in the console.

However, the data is not displaying under the textbox in question. What am I missing?

**Comment by running-coder** [comment]
Hey MystifyBFC,

your init seems good, can you add debug: true and load the src/jquery.typeahead.js file and check for any notice in the console? Perhaps I'm doing a strtolower that I shouldnt be on the display key

**Comment by MystifyBFC** [comment]
Hi,

Please ignore me - It would have helped had I put the correct classes around the textbox. It seems to work fine now, providing I can style the typeahead-display to be wider than the textbox.

Thanks for your advice.

**Comment by running-coder** [comment]
excellent!
