### ISSUE TITLE
Is there / should there be an implicit order to search results?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#106]
When I search for this string:  MW

I get these results:

![image](https://cloud.githubusercontent.com/assets/2574161/11005832/ce2ea576-8485-11e5-98e2-11aa65428828.png)

I feel the hint should be the second item, as it is a better match (at least the way I look at things).

As another example if I searched for  AP  against diaper and apple I would want the hint to be apple.

I guess this is an enhancement request.

Thanks!

**Comment by running-coder** [comment]
it seems that the issue is with the correlativeTemplate option enabled because I've indeed set the hint as suggested.

**Comment by running-coder** [comment]
can you paste your init code to be sure?

**Comment by running-coder** [comment]
closing due to no reply

**Comment by sdillinger** [comment]
Apologies for not following up with this.  I'm not sure what the root issue was, I just remember I fixed it.  All things considered it was probably some problem on my side...

**Comment by running-coder** [comment]
ah ok np thanks for letting me know
