### ISSUE TITLE
Custom field of correlativeTemplate

### ISSUE THREAD

**Issue by ichuot** [running-coder/jquery-typeahead#109]
@running-coder 
Can you add a new option "correlativeField"...?
ex: correlativeField: '{{name}}' or correlativeTemplate: '{{name}}'

**Comment by running-coder** [comment]
Hi Tuan,

could you provide me an example of how the search currently behave with your dataset and how it should be instead? Or give me an example of a case with that option.

ex you are searching for "term" but the displayed result is "x" within these options "x,y,z"

thanks

**Comment by ichuot** [comment]
ex in my case:
...
correlativeTemplate: true,
template: '{{product_name}} <small><em class="text-info">{{price}} - {{in_stock}}</em></small>',
...
I want to limit field searching. eg: {{product_name}} or {{in_stock}}. Not all fields in template.

**Comment by running-coder** [comment]
gotcha, I'll have a look at your PR as soon as I can, meanwhile could you do your PR on the develop branch as the master branch is meant to be the latest released tag, thanks for the contrib!

**Comment by running-coder** [comment]
You can now use boolean or an array of display keys for the ``correlativeTemplate`` option
