### ISSUE TITLE
Partially selecting.

### ISSUE THREAD

**Issue by kkurt** [running-coder/jquery-typeahead#112]
Please add some property like "partialMatch:true|false" for selecting partial matches:
Example:

Data Set:
Apple iphone 6 case
Apple iphone 6
...
When user write "Apple case", first data should be in the dropdown list.

**Comment by running-coder** [comment]
Have you looked into the `correlativeTemplate` option?

**Comment by kkurt** [comment]
Ok, i missed the option.
Thank you.
