### ISSUE TITLE
Multiple "typeahead-result" containers when source is dynamically changed

### ISSUE THREAD

**Issue by sergefabre** [running-coder/jquery-typeahead#114]
Hello
I have a problem with display when change source data : 
With the first display, when query = 1 for exemple, typeahead display 8 result (maxItem: 8)
When I change data source, and query = 1, and the number résult = 4 for example, the display is the 4 résult AND 4 old result...

Can you help me please ? (sorry for my English)
![one](https://cloud.githubusercontent.com/assets/15171783/11219879/3eae0ffa-8d5d-11e5-88b9-799c236a2d1c.png)
![two](https://cloud.githubusercontent.com/assets/15171783/11219880/3eb44bc2-8d5d-11e5-9ad0-cfa4b528a0fa.png)

**Comment by running-coder** [comment]
Hi serge, you are using the latest Typeahead version right? Also when you say "change data source" you mean the Typeahead source option or the text in the input? Dynamically switching the Typeahead source is not fully supported..

could you provide your typeahead init code?

Thanks.

**Comment by sergefabre** [comment]
Re,
on change source data, une new <div class'typeahead-result'> is make !!

![typeahead](https://cloud.githubusercontent.com/assets/15171783/11220705/88445df0-8d61-11e5-909f-c7a08f130251.png)


My code : 

 //Rames Auto-complete
    function getRames() {
        $.getJSON("Set/GetRames", { IDstf: StfSelected.ID, IDserie: $('#seriesList').val(), IDsousserie: $('#sousseriesList').val() })
        .done(function (json) {
            $('#RameInput').val('');
            RameSelected = { ID: 0, EAB: "0", NumEF: "0", IdRexM: 0, IdSerie: 0, IdSousSerie: 0, Serie: "0", SousSerie: "0", CodeSerie: "0" };
            $('#_stfHidden').val(StfSelected.ID);
            $('#_rameHidden').val(RameSelected.ID);

            $('#rame-AllPanne')[0].classList.add("disabled"); $('#rame-AllPanne').prop("disabled", true);
            $('#rame-AllPanne').css("cursor", "not-allowed");

            //ActualiseData();
            //var tabFilter = new Array();
            //var newData = _.chain(json.data).pluck('SousSerie').unique().value();
            //for (var i = 0; i <= newData.length - 1; i++) { tabFilter.push({ key: "SousSerie", value: newData[i], display: '<strong>SousSerie </strong>' + newData[i] }); }
            //tabFilter.push({ value: "*", display: 'Toutes' });
            $.typeahead({
                input: "#RameInput",
                offset: true,
                searchOnFocus: true,
                highlight: true,
                minLength: 1,
                maxItem: 8,
                maxItemPerGroup: 6,
                order: "asc",
                hint: true,
                emptyTemplate: "Aucune rame n'existe avec {{query}}",
                group: ["SousSerie", "Sous-Série : {{group}} "],
                display: ["EAB", "NumEF"],
                template: "{{EAB}}",
                source: json.data,
                //dropdownFilter:     tabFilter,
                callback: {
                    onSearch: function (node, query) {
                        var t1 = node;
                    },
                    onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
                        var t2 = node;
                    },
                    onClickAfter: function (node, a, item, event) {
                        RameSelected = item;
                        $('#spRameText').removeClass('error-input');
                        $('a[href="#pgh"]')[0].parentElement.classList.remove("disabled"); $('a[href="#pgh"]').attr("data-toggle", "tab");
                        $('a[href="#semelles"]')[0].parentElement.classList.remove("disabled"); $('a[href="#semelles"]').attr("data-toggle", "tab");

                        $('#_stfHidden').val(StfSelected.ID);
                        $('#_rameHidden').val(RameSelected.ID);

                        ActualiseData();
                        GetLibRest();

                        $('#rame-AllPanne')[0].classList.remove("disabled"); $('#rame-AllPanne').prop("disabled", false);
                        $('#rame-AllPanne').css("cursor", "pointer");
                    },
                    onResult: function (node, query, result, resultCount) { RameSelected = result[0]; },
                    onNavigate: function (node, query, event) {
                        if (event.keyCode == 13) {
                            $("#RameInput").val(RameSelected.EAB);
                            $('#spRameText').removeClass('error-input');
                            $('a[href="#pgh"]')[0].parentElement.classList.remove("disabled"); $('a[href="#pgh"]').attr("data-toggle", "tab");
                            $('a[href="#semelles"]')[0].parentElement.classList.remove("disabled"); $('a[href="#semelles"]').attr("data-toggle", "tab");

                            $('#_stfHidden').val(StfSelected.ID);
                            $('#_rameHidden').val(RameSelected.ID);

                            ActualiseData();
                            GetLibRest();

                            $('#rame-AllPanne')[0].classList.remove("disabled"); $('#rame-AllPanne').prop("disabled", false);
                            $('#rame-AllPanne').css("cursor", "pointer");
                        }
                    }
                }
            });
            ActualiseData();
        })
        .fail(function (jqxhr, textStatus, error) {
            var err = textStatus + ", " + error;
            alert("Request Failed: " + err);
        });
    }

and the code Controller
public JsonResult GetRames(int IDstf, int IDserie = 0, int IDsousserie = 0)
        {
            filterRame.IdStf        = IDstf;
            filterRame.IdSerie      = IDserie;
            filterRame.IdSousSerie  = IDsousserie;

            DataAppliDataContext db = new DataAppliDataContext();
            var lstRames = from c in db.T_SNCF_Rames.Where(filterRame.Expression)
                            select new
                            {
                                ID           = c.ID,
                                NumEF        = c.OsmEF.Trim(),
                                EAB          = c.EAB.Trim(),
                                IdRexM       = c.IdRexmat,
                                IdSerie      = c.IdSérie,
                                IdSousSerie  = c.IdSousSérie,
                                Serie        = c.Séries.Série.Trim(),
                                SousSerie    = c.IdSousSérie > 0 ? c.SousSéries.Single(p=>p.ID.Equals(c.IdSousSérie)).SousSérie.Trim() : "Aucune",
                                CodeSerie    = c.CodeSerie.Trim()
                            };
            return Json(new { data = lstRames.ToArray() }, JsonRequestBehavior.AllowGet);
        }

Thank

**Comment by sergefabre** [comment]
Yes, I Use the last version 2.2.0
I change source data with call GetRames();

Thanks

**Comment by running-coder** [comment]
can you change @line ~1293 to fix the multiple typeahead-result containers and see if the error persists?

``` javascript
if (!this.resultContainer) {
    this.resultContainer = $("<div/>", {
        "class": this.options.selector.result
    });

    this.container.append(this.resultContainer);
}
```
to
``` javascript 
if (!this.resultContainer) {
    this.resultContainer = $("<div/>", {
        "class": this.options.selector.result
    });

    this.container.find('.' + this.options.selector.result).remove();

    this.container.append(this.resultContainer);
}
```

**Comment by sergefabre** [comment]
OK  I try...

**Comment by sergefabre** [comment]
THANKS !!! You are the Best !!! :)
But, a other pb .... :( : the value suggest is the old source : 
![Uploading Good.png…]()

**Comment by sergefabre** [comment]
OUPS, I clicked on CLOSE... sorry

**Comment by sergefabre** [comment]
![good](https://cloud.githubusercontent.com/assets/15171783/11221889/d1a39604-8d67-11e5-835c-f5bfae5f5437.png)

Value '30C' is a value of old source data.

Can you , again :), help me ?

**Comment by sergefabre** [comment]
I think is à similar pb, no ?

Copy of Inspect Firefox : 
<span id="spRameText" class="typeahead-query" style="position: relative;">

    <input id="RameInput" class="form-control" type="search" autocomplete="off" placeholder="Rame..." name="RameInput"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

</span>

**Comment by running-coder** [comment]
Multiple you are getting multiple `typeahead-hint` inputs?

**Comment by sergefabre** [comment]
Yes, 
on change Data Source : 

<span id="spRameText" class="typeahead-query" style="position: relative;">

    <input id="RameInput" class="form-control" type="search" autocomplete="off" placeholder="Rame..." name="RameInput"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

<input class="form-control typeahead-hint" type="search" readonly="readonly" unselectable="on" tabindex="-1" style="border-color: transparent; position: absolute; top: 0px; dis…; box-shadow: none; cursor: default; -moz-user-select: none;"></input>

</span>

**Comment by running-coder** [comment]
Perhaps it would be best to put these 2 lines at the top of your `done` function to reset the Typeahead HTML to its initial state

``` javascript
.done(function (json) {
$('.typeahead-hint, .typeahead-result').remove()
...
```

**Comment by sergefabre** [comment]
YES !!
your last soluce work very good.

Thanks.
I delete the first update.

**Comment by sergefabre** [comment]
I close this "issue".
Thank you very much !!

**Comment by running-coder** [comment]
welcome

**Comment by sergefabre** [comment]
I complet for FIlter ... :)
$('.typeahead-hint, .typeahead-result, .typeahead-filter-button, .typeahead-filter').remove();

Thanks
