### ISSUE TITLE
Do not change input text field when navigating through results

### ISSUE THREAD

**Issue by ethaniel** [running-coder/jquery-typeahead#115]
When I am navigating through results (with my mouse or keyboard), I want the original search field to remain unchanged. Right now it is being propagated with result value every time I go up/down in results.

**Comment by running-coder** [comment]
The default behavior is to change the input text to the selected option and when you land back on the input (reach the end of the list and press once more) you get what you started typing. 

I'll check if I can add an option to the `onNavigate` callback to prevent the text from changing

**Comment by running-coder** [comment]
I based myself on Google search input but you are right, it would be nice to have the option to use either

**Comment by ethaniel** [comment]
Thank you so much!
One more thing I would like to suggest is an option to not update the input field when I specifically select a result. I will be processing the click with javascript and redirecting the user to a specific page (or javascript function), the input field shouldn't flicker in those 1-2 seconds while the user stays on the page. Once again - that's how they do it Facebook.

**Comment by running-coder** [comment]
Will now work by using the following code, let me know about the result.

``` javascript
callback: {
    onNavigateBefore: function (node, query, event) {
        if (~[38,40].indexOf(event.keyCode)) {
            event.preventInputChange = true;
        }
    }
}
```
