### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by ethaniel** [running-coder/jquery-typeahead#116]
There is another project - "typeahead.js" which gets much more PR. It actually took me a while to find your project in the search results. Perhaps give it another name? 

Your project is the most advanced in it's niche. It's a shame people miss it.

**Comment by running-coder** [comment]
thanks a lot for the kind words, always warms a cold dev heart. There are indeed countless hours and evenings put into this project which continues to evolve during my lunch time hehe regarding the name i am not a fan or what it currently is but all the good ones were taken.. unless something very good comes up it might just stay as it is and some people (like you) might stumble uppon from time to time

**Comment by ethaniel** [comment]
If you give me a paypal account, I will be more than have to drop you some beer money :)
