### ISSUE TITLE
onClickBefore callback: e.defaultPrevented doesn't work and should be replaced with e.isDefaultPrevented()

### ISSUE THREAD

**Issue by ethaniel** [running-coder/jquery-typeahead#117]
Hi,

I am working with the onClickBefore callback to stop typeahead from updating the input field with the currently selected result.

I noticed that in the code right after the callback you check if I called "e.preventDefault();" by checking for e.defaultPrevented.
However, this is not correct, because "e" is not the original event, it is a jquery result, which for some stupid reason doesn't have the defaultPrevented attribute.

<b>Easy fix.</b> Replace e.defaultPrevented with e.isDefaultPrevented()

jQuery documentation: http://api.jquery.com/event.isDefaultPrevented/

**Comment by running-coder** [comment]
I think it is also dropped in jquery3 if I remember correctly.. good call

**Comment by running-coder** [comment]
Might have to look for a different solution...

![2015-11-18_1852](https://cloud.githubusercontent.com/assets/7377382/11258245/934352be-8e25-11e5-968e-a05649dd5c8f.png)

**Comment by running-coder** [comment]
``` javascript
if (e.originalEvent.defaultPrevented) {
    return;
}
```

did the trick

**Comment by ethaniel** [comment]
I tried the e.originalEvent option too, but JS throwed me an error, when I selected one of the results by pressing Enter. Can you temporarily remove isDefaultPrevented() on your side and see what's the case with the e.originalEvent having problems on Enter keypress?
