### ISSUE TITLE
"white-space: nowrap" causing problems

### ISSUE THREAD

**Issue by ethaniel** [running-coder/jquery-typeahead#119]
Hello, me again :)

I've noticed that you have a style nowrap in your css:
![image](https://cloud.githubusercontent.com/assets/941973/11238469/f1bf7e1e-8df6-11e5-99c1-c33216dc0a03.png)

It's causing problems like this:
![image](https://cloud.githubusercontent.com/assets/941973/11238466/eee870a6-8df6-11e5-88f0-c64913475d2b.png)

Is there a specific need for the nowrap?

I had to use inline css to override this, but still want to bring it to your attention.

**Comment by running-coder** [comment]
Indeed `white-space: nowrap;` was meant to the typeahead-dropdown only
