### ISSUE TITLE
Error on ajax request

### ISSUE THREAD

**Issue by cmcsynth** [running-coder/jquery-typeahead#120]
I'm using a datasource to get data from server:
Here definition
```
source: {
  display: "description",                    
  url: {
    type: "GET",
    url: "/api/test/{{query}}"
  }
}
```

when server goes in error, with a 500 error (Internal Server Error), I'm able to handle error by global ajax error handling
```
$.ajaxSetup({           
  error:
    function (XMLHttpRequest, textStatus, errorThrown) {
      console.log(error)
    }
})
```
All works ok, but after error my next typeahead search throws this error
>Uncaught TypeError: this.xhr[b].abort is not a function
    i.generateSource @ jquery.typeahead.min.js:10
    (anonymous function) @ jquery.typeahead.min.js:10

thanks
regards

**Comment by running-coder** [comment]
thanks for reporting, I'll verify the issue

**Comment by running-coder** [comment]
I am unable to reproduce the issue, are you using the 2.2.0? There was a fix #101 for xhr requests similar to your issue

**Comment by cmcsynth** [comment]
Version 2.2.1 solve my problem!! Your plugin works like a charme!
Thanks a lot.

**Comment by running-coder** [comment]
excellent! thanks
