### ISSUE TITLE
Search problems with letters in Russian.

### ISSUE THREAD

**Issue by berpcor** [running-coder/jquery-typeahead#122]
I get (third party API) the following set of data: ["Палёный", "Паленый"]. My search string for this set of data is "Пале". 
But your plugin shows me only the first value from array in dropdown list. In Russian, if you search 'е' then you should include 'ё' there. But if you search 'ё' you shouldn't include 'е'. How to fix that? I need to show the whole array of data I've got.

**Comment by running-coder** [comment]
hey berpcor, have you tried the `accent: true` configuration?

**Comment by running-coder** [comment]
These characters are available.
```javascript
var _accent = {
    from: "ãàáäâẽèéëêìíïîõòóöôùúüûñç",
    to: "aaaaaeeeeeiiiiooooouuuunc"
};
```
would be a good idea to have them configurable

**Comment by berpcor** [comment]
Yes, that's exactly what I need. High quality plugin. But as you said I had to edit you plugin source (not very good). So yes. Very good idea to make _accent configurable. And one more thing...

**Comment by berpcor** [comment]
I get list of items from api. ```[1,2,3,4,5]``` This list is already sorted by relevance. When your plugin shows me the list, it resort it in some way. How can I save original sorting?

**Comment by running-coder** [comment]
you can use `filter: false` inside the source group as specified under `options.source` in the documentation. It will skip any sorting made from Typeahead and preserve your BE/API sorting

**Comment by berpcor** [comment]
Yes, I am using it.

**Comment by berpcor** [comment]
https://jsfiddle.net/3gyLu0ex/ Here you can see what I mean. Try ty type in "Mosco" and see your browser console.

**Comment by running-coder** [comment]
you were missing a "group", try this init code

``` javascript
$.typeahead({
    input: "#q",
    group: false,
    order: "asc",
    highlight: true,
    accent: true,
    dynamic: true,
    minLength: 3,
    delay: 500,
    source: {
        group: {
            filter: false,
            url: [{
                url: "https://suggest-maps.yandex.ru/suggest-geo",
                type: "GET",
                dataType: "jsonp",
                data: {
                    v: 5,
                    search_type: "tp",
                    part: "город {{query}}",
                    lang: "ru_RU",
                    n: 5,
                    origin: "jsapi2Geocoder"
                },
                callback: {
                    done: function (data, textStatus, jqXHR) {

                        var d = [];
                        for (var i = 0; i < data[1].length; i++) {
                            d[i] = data[1][i][1];
                        }
                        console.log(d);
                        return d;

                        // data has to be returned
                        return data;
                    },
                    fail: function (jqXHR, textStatus, errorThrown) {
                    },
                    complete: function (jqXHR, textStatus) {
                    },
                    always: function (data, textStatus, jqXHR) {
                    }
                }
            }]
        }
    }
});
```

**Comment by berpcor** [comment]
https://jsfiddle.net/3gyLu0ex/1/ Still the same.

**Comment by berpcor** [comment]
Found the reason of such behaviour ) ```order: "asc"```

**Comment by running-coder** [comment]
Haha missed that, indeed that ordering occurs after the data filtering

**Comment by berpcor** [comment]
Well... I found one more strange thing. I use ```accent:true``` with ```hint:true```. When I enter some place which has no any letters from ```_accent``` then hint is correct - first line from dropdown list. But if place has letter with diacritic, then hint shows me not the first line. But... I can't tell you what to type in as you haven't got Russian keyboard. )

**Comment by berpcor** [comment]
Gotcha. Not exactly what I said, but, probably, the reason is not diacritics. https://jsfiddle.net/3gyLu0ex/2/ Try to type in "good"

**Comment by running-coder** [comment]
- When I type `good` the dropdown & console log are in the same order
- adding manual data and then saying filter indeed conflicts... since you are saying the data should not be filtered
- typing `fial` shows no hint because it is not the start of the display key

**Comment by berpcor** [comment]
About 'good'. In previous message I meant that hint is not equals to the first item in dropdown list.

**Comment by running-coder** [comment]
Ah ok, well in order for the hint to be displayed, the search result has to start by what the user started typing (offset 0), if the first element does not start with "good" when the second result will be evaluated, etc.

**Comment by running-coder** [comment]
should be good on the develop branch, will be available in the next tag
