### ISSUE TITLE
Update Source Array - Changes don't show

### ISSUE THREAD

**Issue by cazoobi** [running-coder/jquery-typeahead#124]
I have a simple array Im feeding into the typehead, this array is updated during the user session, I have the dynamic flag on my init but changes to the array are not show.

Is this the point in the dynamic feature?

**Comment by running-coder** [comment]
Hey cazoobi, the `dynamic` option is used to perform an ajax request on every keytype where the backend would perform operation and give you a different result depending on what you are typing. You can see `user_v1` demo for example. Support for dynamic source switching is coming hopefully in the next version if I get some time to code, so busy with other projects..
