### ISSUE TITLE
showing of default selection

### ISSUE THREAD

**Issue by imhubertj** [running-coder/jquery-typeahead#126]
I went through the demo and under advanced, User V1, When I type "the" 2 options came up. First was " an inserted user that is not inside **the** database (contributor) (415849)" and the second was "**The**TechnoMan (contributor) (415849)". Is there any way I can modify such that the first one would not appear unless there is really 0 results?

Anyway, I have to say good work on this project. I am learning to use it and would love to help spread this wonderful plugin.

**Comment by running-coder** [comment]
hey hubert, thanks for the kind words. 

Unfortunately there is currently no way to differentiate the 2 data sets and perform custom filtering operation(s). Kkurt suggested a "matcher" function a couple weeks ago #111 which might be what you are looking for. For example you would add a key to your extra data objects `extra: true` and inside the matcher function you would be able to differentiate which match comes from which set to apply your solution.

``` javascript
source: {
    user: {
        display: "username",
        href: "https://www.github.com/{{username}}",
        matcher: function (data) {
            var extraData = [],
                requestData = [];
            for (var i = 0; i <= data.length; i++) {
                data[i].extra && extraData.push(data[i]) || requestData.push(data[i]);
            }
            return requestData.length && requestData || extraData
        },
        data: [{
            "id": 415849,
            "username": "an inserted user that is not inside the database",
            "avatar": "https://avatars3.githubusercontent.com/u/415849",
            "status": " <small style='color: #777'>(contributor)</small>",
            "extra": true
        }],
        url: [{
            type: "POST",
            url: "/jquerytypeahead/user_v1.json",
            data: {
                q: "{{query}}"
            }

        }, "data.user"]
    }
}
```
