### ISSUE TITLE
Keep results list open if no results

### ISSUE THREAD

**Issue by nop33** [running-coder/jquery-typeahead#127]
Is there a way to add some kind of *"Just use ..."* option in the results list and keep the results list open even if there are no results?
Currently I create a new DOM element and I append it in the results list, like in this example:
![](http://i.imgur.com/tZoNVWb.png)

But if the user keeps adding input and there are no more results to show, the results lists closes, so the *"Just use..."* option is not visible anymore.
To work around this, I add/remove some css classes of the `.typeahead-container` element, but this is more of a hack than a solution.
Any idea how this can be implemented?
Thanks

**Comment by running-coder** [comment]
hey Ilias,

you can use the ``onLayoutBuiltBefore (node, query, result)`` callback and ``emptyTemplate: function (query)`` option

``` javascript
$.typeahead({
    input: "#q",
    // EmptyTemplate doesnt support returning jQuery object for now but this is something I could add
    emptyTemplate: function (query) {
        return "Just use \"" + query + "\""
    },
    callback: {
        onLayoutBuiltBefore: function (node, query, result) {
            return result.append(
                $('<li/>', {
                    "text": "Just use \"" + query + "\"",
                    "class": "my-custom-class"
                })
        }
    }
})
```

**Comment by nop33** [comment]
Thank you, I will give it a try! I would be great if the emptyTemplate could return a jQuery object, then I could have the same function returning the new `<li>` in both `emptyTemplate`  and `onLayoutBuiltBefore`.

**Comment by running-coder** [comment]
my bad I was missing 1 parameter
``` javascript
callback: {
        onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
            return resultHtmlList.append(
                $('<li/>', {
                    "text": "Just use \"" + query + "\"",
                    "class": "my-custom-class"
                })
        }
    }
}
```

**Comment by running-coder** [comment]
Should be available in the develop branch until 2.3.0 is released

**Comment by nop33** [comment]
Thanks for the quick response and fix!

**Comment by nop33** [comment]
Hello again,
I didn't want to create a whole new issue to ask a question, so I am simply replying to this one.
As I read in the [docs "Extras" section](http://www.runningcoder.org/jquerytypeahead/documentation/), you can trigger several Typeahead events programmatically, like `focus.typeahead` etc.. I use `focus.typeahead` to open the results list programmatically and I also need to be able to close it. Unfortunately none of the mentioned events does that. I tried to trigger an `ESC` `keyup` (or `focusout`) but none of these worked so far.
How can I close the results list?
This question is related with the above issue since I want to close the results list when the user clicks on the "Just use ..." `LI`

**Comment by running-coder** [comment]
hey, as of #118 it is possible to call any Typeahead / function from any callback using 'this' scope. You can also reach your instance with the technique given in the Extras. The function to close Typeahead is hideLayout(). so somthing like this.hideLayout() from a callback or Typeahead['#q'].hideLayout() from anywhere else

**Comment by nop33** [comment]
You are right, I did not think of that! Thanks for the help.

**Comment by running-coder** [comment]
yw
