### ISSUE TITLE
How to re-initialize typeahead

### ISSUE THREAD

**Issue by tawalters61** [running-coder/jquery-typeahead#129]
I am using a simple 'source' containing a list of objects. What is the proper way to re-initialize the typeahead when the list changes? I have tried just re-executing the typeahead() call and this causes problems in the displayed search text in the input box, specifically, it overlays the latest typing with previously typed searches.

Thanks.

**Comment by running-coder** [comment]
hey, dynamic source switching is not currently supported but it's in the plans for future versions, meanwhile you can "hack" your way around quite easily after a re-init using the method inside #114

``` javascript
$('.typeahead-hint, .typeahead-result, .typeahead-filter-button, .typeahead-filter').remove();
```
