### ISSUE TITLE
Select a value

### ISSUE THREAD

**Issue by mctdi** [running-coder/jquery-typeahead#130]
hi

after the typeahead is initialized, is there a way via programmation to select a value?

thanks

**Comment by running-coder** [comment]
hey, can you explain your usecase with more details? Depending on which behaviors you are tying to acheive the steps to have a manual select might be different... Ultimately to manually set a selected Item inside Typeahead is

``` javascript
Typeahead['#my-instance'].item = { key: value, moreKey: moreValues}
```

This will not set text inside the input or trigger any callbacks, everything will have to be done manually

**Comment by mctdi** [comment]
my use case is:

a user select a value, save the key in the database.

i would like to do call the server, get the key and select the value from this key.

**Comment by running-coder** [comment]
maybe what you are looking for is ``onClickAfter(node, a, item, event)``? This function gets triggered after a user clicks on an item inside the result list, at this point you can manually send a request using the item param

**Comment by mctdi** [comment]
i will try to explain more clearly

user select an item: key: 1 value apple.
user click a button, value is saved.

user go to a page, ajax call is done to get key 1.
after init of the typeahead,I would like to via this key to see the value automatically in the typeahead.

**Comment by running-coder** [comment]
by seeing the value in typeahead you mean having search results for "apple"?

**Comment by mctdi** [comment]
ya

**Comment by running-coder** [comment]
Inside the doc, Extras section you can find

``` javascript 
// Trigger a manual search from the string inside the input
// See #Game_v2 demo to understand why it is being used at that place
$('#mySearchInput').trigger('input.typeahead');
```

**Comment by mctdi** [comment]
I watched you example but I don't understand more how i could give and brandId id number like 1, 

and see the result Acura 


My typeahead is initialized with this kind of data
[{"brandId":1,"brand":"Acura"},{"brandId":2,"brand":"Alfa Romeo"}]

can't do something like 
$('#brand').val("1");
$('#brand').trigger('input.typeahead');

**Comment by running-coder** [comment]
depends which keys you have in the ``display`` option

``` javascript
$.typeahead({
    input: "#brand",
    display: ["brand"] // search by brand name only,
    display: ["brand","brandId"] // having both will allow you to type either "1" or "acura",
    source: {
        car: {
            data: [{"brandId":1,"brand":"Acura"},{"brandId":2,"brand":"Alfa Romeo"}]
        }
    }
})
```

ideally what you want to do is

``` javascript
$('#brand').val("acura"); // typing "1" will mean nothing to the user
$('#brand').trigger('input.typeahead');
```

**Comment by mctdi** [comment]
ok because my data is stored in localstorage, i checked the value from the key and pass the value to the typeaahead. Seem to fix my problem.

In a parent child relation, actually i put my child typeahead in the onlick event of the parent. Is there a better solution?

**Comment by mctdi** [comment]
is there a way to trigger a click of a typeahead?
