### ISSUE TITLE
Not really an issue but I need help in implementing a simple requirement.

### ISSUE THREAD

**Issue by Bharat1103** [running-coder/jquery-typeahead#133]
hi,

I need help in implementing a simple feature can anyone please guide me on how I can get the required solution.

Problem: I need to get the search results even if the query entered in the input field is in double quotes.

**Comment by running-coder** [comment]
hey Bharat, you might be looking for something similar to (when using 2.3.0)

``` javascript
callback: {
    onSearch: function (node, query) {
        this.query = this.query.replace(/"/g, "")
    }
},
```

**Comment by Bharat1103** [comment]
Hi

Thanks for the prompt reply, I was using version 2.0.0 and tried the above solution using version 2.3.0
The above solution did not solved the issue but it allowed me to refine my problem statement.

Problem: I am using dynamic source for my Typeahead input field, I am using below syntax for making the call
```javascript
source: {
    people: {
        url: [
            {
                type: "GET",
                url: "/searchAll",
                data:{
                    key: "{{query}}"
                },
                filter:false
            },
            "people"
        ]
    }
}
```

```javascript
callback: {
          onSearch: function (node, query) {
                console.log("query recieved in OnSearch callback : " + query)
                this.query = this.query.replace(/"/g, "").trim()
                console.log("query after using regex in OnSearch callback : " + this.query)
        },
}
```

I am getting the result when there are no quotes in the search string Eg: bharat
but the Typeahead  does not produce any result on UI even when I am getting response from the back-end, If i wrap my query string in quotes Eg: "bharat"

![typeahead_key](https://cloud.githubusercontent.com/assets/10626464/12002456/72c046a2-ab24-11e5-9dab-3c5b98fe3405.png)


The problem that I think is related to the `key` used for the second ajax call.
please help me find a solution for this I tried using 

```javascript
data:{
                    key: ("{{query}}").replace(/"/g, "").trim()
                },
```

**Comment by running-coder** [comment]
Can you apply the following modifs

``` javascript
source: {
    people: {
        // filter goes here, not inside "url" object
        filter: false,
        url: [function (query) {

            query = query.replace(/"/g, "").trim();

            return {
                url: "/searchAll",
                data:{
                    key: query
                }
            }
        }, "people"]
    }
}
```

**Comment by Bharat1103** [comment]
Thanks Tom, 

above modifications worked like a charm. Although I am still having some doubts regarding the filter option.

```javascript
source: {
    // filter: false, here would not fire the ajax call and it breaks the app
    people: {
        // putting filter here works fine but applies only for people group as you correctly mentioned
        filter: false,
        url: [function (query) {

            query = query.replace(/"/g, "").trim();

            return {
                url: "/searchAll",
                data:{
                    key: query
                }
            }
        }, "people"]
    }

    // filter: false, here would also not fire the ajax call and so it breaks the app again
},
```

Is there any other way that I can apply filter on all my source groups altogether ?

**Comment by running-coder** [comment]
you are right, I messed this one up.. if filter is applied at the group lever Typeahead will think its a group. It needs to be applied inside the group or at the source level, my bad

**Comment by Bharat1103** [comment]
Thanks, I guess I will have to use filter for each group separately then. I have also made some changes in the suggested answer so that it would not break the app even if the query string is only `" "` i.e. only double quotes.

Also made changes in regex so that It would remove single quotes as well as double quotes from the query.

```javascript
url: [function (query) {
                query = query.replace(/["']/g, "").trim()
                if(query.length != 0){
                    return {
                        url: "/searchAll",
                        data:{
                            key: query
                        }
                    }
                }else{
                    return {
                        url: "/searchAll",
                        data:{
                            key: '" "'
                        }
                    }
                }
            }, "people"]
```

```javascript
callback: {
          onSearch: function (node, query) {
              query = query.replace(/["']/g, "").trim()
              if(query.length != 0){
                  this.query = query
              }else{
                  this.query = '" "'
              }
        },
```

Is there any better way to do this, I mean cleaner way without the if-else construct.

**Comment by running-coder** [comment]
sure, ideally you don't want code to repeat itself because that is were bad copy/paste happens so I would recommend a common function that cleans the string

``` javascript
$.typeahead({
    input: "...",
    filter: false,
    source: {
        people: {
            url: [function (query) {
                return {
                    url: "/searchAll",
                    data: {
                        key: cleanTypeaheadQuery(query)
                    }
                }
            }, "people"]
        }
    },
    callback: {
        onSearch: function (node, query) {
            this.query = cleanTypeaheadQuery(query);
        }
    }
});

function cleanTypeaheadQuery(query) {
    query = query.replace(/["']/g, "").trim();
    if (!query.length) {
        query = '" "'
    }
    return query;
}
```

**Comment by Bharat1103** [comment]
Great ! the code works as expected and looks way more cleaner, it was good to work with you and I would get back in touch if I get any other issue in future.

Thanks Tom

**Comment by running-coder** [comment]
Thanks bharat, same here. gl with your project
