### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by unindented** [running-coder/jquery-typeahead#134]
If server response contains HTML, `jquery-typeahead` blindly inserts it in the DOM, making it vulnerable to XSS. In my case, the endpoint returned this:

```js
[
  {
    "id": "2053",
    "name": "Engineering <script>alert('test')</script>"
  }
]
```

Which caused `jquery-typeahead` to invoke `alert`.

The line responsible for this (although there may be others with the same mistake): https://github.com/running-coder/jquery-typeahead/blob/27b3e1305495b86593d03b50fc6f5e1d8e34a4d3/src/jquery.typeahead.js#L1551

Instead of concatenating bits of HTML, it'd be better to use the appropriate jQuery functions like `text()` which handle escaping for you.

**Comment by running-coder** [comment]
hey, thanks for flagging the issue, I unfortunatly have close to no time to fix it until maybe a week. Perhaps instead of a global escaping it would be best to have <script> and <iframe> escaped so possible react components can still be outputted properly, what do you think?

**Comment by unindented** [comment]
I think it could be a source of bugs and complexity... Handling escaping correctly is really tricky!

I'd do the simplest correct thing by default, which is to escape all displayed values, and leave it at that. If we hear from other people with more complex requirements we can reevaluate?

**Comment by running-coder** [comment]
I added a [sanitize](https://github.com/running-coder/jquery-typeahead/blob/27b3e1305495b86593d03b50fc6f5e1d8e34a4d3/src/jquery.typeahead.js#L2533) string prototype for emptyTemplate and dynamic requests so I could as well apply it to the list items.

**Comment by unindented** [comment]
Sounds good.

**Comment by ThiefMaster** [comment]
There's still XSS possible, e.g. `<img src="invalid" onerror="...">`..
