### ISSUE TITLE
Json files isn't working

### ISSUE THREAD

**Issue by Kassima** [running-coder/jquery-typeahead#135]
I used game v1 demo on my website, but added json files located separately from html page. I couldn't get it to work, even when I tried adding php. Please help how it should look when adding separate php and json files with the following script 

    source: {
            ale: ["/jquerytypeahead/beer_v1.json", "data.beer.ale"]

I just can't make it functioning. Even while using jsonp:
    
    source: {
        url: [{
            url: "http://www.gamer-hub.com/game/list.json",
            dataType: "jsonp"
        }, "data"]

Even with links to the folders located directly on my other domain, it still doesn't work.
Please help.

**Comment by running-coder** [comment]
Hey kassima, jsonp is only for crossdomain requests if you are hosting the files on the same domain you shouldn't go that route. Do you have a plunker or environment I could look at? Please provide your typeahead init code. Is your json file correctly reached when you inspect the network request inside Network/xhr (chrome dev tools)?

**Comment by running-coder** [comment]
closing due to no-reply
