### ISSUE TITLE
Highlight selected option inside the input field

### ISSUE THREAD

**Issue by nop33** [running-coder/jquery-typeahead#138]
Hello,
This is more of a suggestion/feedback than an issue.
Lately I have been working with your library and I can see that you are very active in this repository, so I would like to ask your opinion about a new feature.
One of my requirements is to build a Facebook-like highlighting of the selected option of the typeahead field. I think the following images are pretty self explanatory:

Opening the typeahead dropdown:
    ![](http://i.imgur.com/AjyHT7V.png)

Selecting the first option will highlight the keyword inside the input field:
    ![](http://i.imgur.com/37LClRn.png)

The way I have implemented this, is by adding a `<span class="highlighter">` element with `position: absolute` over the input field, initially hidden. Then, at the callback `onClickAfter` I update the text of the aforementioned `.highlighter` element to match the selected option and I make it visible.
When the user clicks onto the input field again, the results list appears and the '.highlighter' gets hidden again in order to display the text value of the input field.
![](http://i.imgur.com/UClsSJR.png)

Is this feature something you are considering adding in your library? Cheers!

**Comment by running-coder** [comment]
hey,

something like [select2](https://select2.github.io/examples.html#tags) is doing (they call it tags)?
could be interesting for a future version...

Thanks for the suggestion!

**Comment by nop33** [comment]
Yes, something like that, but a bit more simplified, for instance there no need for multiple tags. But yes, the idea is to make clear to the user whether they have chosen a predefined option or a custom option.

**Comment by running-coder** [comment]
Multi select is now enabled on the `develop` banch. You can look at `hockey_v2` demo to get a configuration example and configurations. It is to be documented properly on the website once `2.10.0` is ready.

Feel fett to test and give some feedback at it might need some tweaking.

**Comment by running-coder** [comment]
demo: http://www.runningcoder.org/jquerytypeahead/demo/#form-hockey_v2
documentation: http://www.runningcoder.org/jquerytypeahead/documentation/#options-multiselect
