### ISSUE TITLE
Can't seem to get typeahead results

### ISSUE THREAD

**Issue by kevincollins7** [running-coder/jquery-typeahead#140]
Hello,

I'm having a hard time getting data from my json web service into the typeahead results. I know the ajax call is successful (was able to see in console) but I must be missing a part on how to drill into the json object for the search as I keep getting "No results found" by way of the emptyTemplate function.

I'm hoping this isn't something that is crazy easy and I'm just missing it but I've been staring at this for hours now!

Here is an example of what my AJAX call is returning (I changed the values to protect data):

``` javascript
{"Customer":
  [
    {"customerkey":55555,"name":"Hilltown Customer","city":"Hilltown","state":"NY"},
    {"customerkey":33333,"name":"Hillbilly Customer","city":"Hillplace","state":"CA"}
  ]
}
```

Typing "Hill" into my input results in no matches.

Here is my typeahead:

``` javascript
$("#customer-search").typeahead ({
    dynamic: true,
    delay: 500,
    offset: true,
    minLength: 1,
    maxItem: 15,
    searchOnFocus: false,
    display: "name",
    // can also be an array to search through multiple keys
    // display: ["name", "city"],
    backdrop: {
        "background-color": "#999",
        "opacity": "0.1",
        "filter": "alpha(opacity=10)"
    },
    emptyTemplate: function (query) {
        if (query.length > 0) {
            return 'No results found for "' + query + '"';
        }
    },
    source: {
        customer: {
            // display can also be set by group to override the global config
            // display: "name",
            url: [{
                url: "https://server/api/customer",
                data: { "name" : "{{query}}" },
                headers: {"Authorization" : "Basic " + btoa("userid" + ":" + "password")},
                dataType: "json",
                success: function(response) {
                    console.log(response.Customer);
                }
            }, "Customer" ]
        }
    },
    callback: {
        onResult: function (node, query, result, resultCount) {
            console.log(node, query, result, resultCount);
        },
        onClickAfter: function (node, a, item, event) {
            console.log(item.customerkey)
        }
    },
    debug: true
});
```

I'm pretty sure my issue is where I'm trying to identify the key for the typeahead query. I've tried numerous variations of things like "Customer[0]", "Customer[0].name", etc just to get some kind of results back, but none have worked. 

Ideally I'd like to only search the name of all the Customers that start with the letters I type into the input and only show those names in the results. Then when a user clicks on a result it would populate the CustomerKey in another field. 

Any help would be greatly appreciated.

**Comment by running-coder** [comment]
hey kevin, it seems you are only missing to define the display option to `name`(I've modified your init above)

**Comment by running-coder** [comment]
To populate the CustomerKey you can look into the mustSelectItem option (depending on what you want to acheive) and the onClickAfter callback to perform the action of transfering the id to another input

**Comment by kevincollins7** [comment]
running-coder,

Thank you so much! I honestly swear I tried that last night, what a difference sleep makes! I've got it populating now and I'm passing that CustomerKey as well.

I really appreciate the assist!

**Comment by running-coder** [comment]
yw!
