### ISSUE TITLE
Possible to use the input query in the source url? 

### ISSUE THREAD

**Issue by f7n** [running-coder/jquery-typeahead#141]
Hello,

I've got a webpage serving JSON which takes a query parameter, for example: `/search?q=foobar` returns foobar related data.

I've tried to implement this with typeahead something like this:

    source: {
    url: ["/search?q=" + query]
    }

where `query` is the value of the input bar.

Is this feature supported with jquery-typeahead? Am I doing it wrong?

**Comment by running-coder** [comment]
hey,

yea, inside the doc you can find 
* Note that you can modify the Ajax request to send the query with {{query}} modifier.

``` javascript
source: {
url: ["/search?q={{query}}"]
}
```

here is the example inside ``options.source`` doc

``` javascript
source: {
    user: {
        href: "https://www.github.com/{{username}}",
        data: [{
            "id": 415849,
            "username": "an inserted user that is not inside the database",
            "avatar": "https://avatars3.githubusercontent.com/u/415849"
        }],
        url: [{
            type: "POST",
            // The {{query}} can also be replaced inside the URL
            // url: "/jquerytypeahead/{{query}}",
            url: "/jquerytypeahead/user_v1.json",
            data: {
                q: "{{query}}",
                type: function () { return $('#user-type').val(); }
            }
        }, "data.user"]
    }
}
```

**Comment by f7n** [comment]
hey, thanks for the response.

I've tried your advice but nothing appears, no console errors or anything. Here's my relevant code:

Input:

`<input id="movie-query" name="movie[query]" type="search" placeholder="Search" autocomplete="off">`

JS:

    $('#movie-query').typeahead({
        minLength: 0,
        maxItem: 5,
        source: {
            url: ["/search?q={{query}}"]
        },
    });

And this is what the JSON returns with a query such as: '/search?q=lord%20of%20the%20rings`:

`["The Lord of the Rings: The Return of the King","The Lord of the Rings: The Fellowship of the Ring","The Lord of the Rings: The Two Towers"]`

What am I doing wrong?

**Comment by running-coder** [comment]
This one works for me, perhaps you were missing the html structure (typeahead requires a specific one)

``` html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="../src/jquery.typeahead.css">

    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <!--script src="../dist/jquery.typeahead.min.js"></script-->
    <script src="../src/jquery.typeahead.js"></script>

</head>
<body>

<div style="width: 100%; max-width: 800px; margin: 0 auto;">

    <h1>Movie_v1 Demo</h1>

    <ul>
        <li>
            <a href="http://www.runningcoder.org/jquerytypeahead/documentation/">Documentation</a>
        </li>
        <li>
            <a href="http://www.runningcoder.org/jquerytypeahead/demo/">Demos</a>
        </li>
    </ul>

    <form>
        <div class="typeahead-container">
            <div class="typeahead-field">

            <span class="typeahead-query">
                <input id="q"
                       name="q"
                       type="search"
                       autofocus
                       autocomplete="off">
            </span>
            <span class="typeahead-button">
                <button type="submit">
                    <span class="typeahead-search-icon"></span>
                </button>
            </span>

            </div>
        </div>
    </form>

    <script>

        var data = ["The Lord of the Rings: The Return of the King","The Lord of the Rings: The Fellowship of the Ring","The Lord of the Rings: The Two Towers"]

        $.typeahead({
            input: "#q",
            minLength: 0,
            maxItem: 5,
            source: {
                data: data
            },
            debug: true
        });

    </script>

</div>

</body>
</html>
```

**Comment by f7n** [comment]
That works for me too setting the data to a static array, but when I switch to

    ["/search?q={{query}}"]

it breaks. I think the problem is that it only calls the sourch URL on page load, not when you're actually typing, so it will always load no data (because no query has been passed to `/search`. I can test this by adding a value to the input:

`<input id="movie-query" value="lord of the rings" name="movie[query]" type="search" placeholder="Search" autocomplete="off">`

and the autocomplete search results appear because typeahead performed a GET request on page load:

`127.0.0.1 - - [13/Jan/2016:23:19:17 +0000] "GET /search?q=lord%20of%20the%20rings HTTP/1.1" 200 141 0.0550`.

so is this feature available? hope I explained clear enough, I'm still learning.

**Comment by running-coder** [comment]
can you paste me your json response from ``/search?q=lord%20of%20the%20rings``

**Comment by f7n** [comment]
`["The Lord of the Rings: The Return of the King","The Lord of the Rings: The Fellowship of the Ring","The Lord of the Rings: The Two Towers"]`

**Comment by running-coder** [comment]
``` javascript
$.typeahead({
    input: "#movie-query",
    minLength: 0,
    maxItem: 5,
    dynamic: true,
    source: {
        url: "movies.json?q={{query}}"
    },
    debug: true
});
```

**Comment by f7n** [comment]
Ah wow that worked. Not sure how I messed up in the beginning but thank you for your patience! :+1:
