### ISSUE TITLE
Issue with multiple groups result data display priority

### ISSUE THREAD

**Issue by kujain** [running-coder/jquery-typeahead#142]
When groups: true and with multiple groups data, sometimes one group doesn't show the data even though data is being returned from source. This seems arbritrary as there's no priority set for which group to show more of. eg.
```
      dynamic: true,
      delay: 200,
      group: ["type", function (item) {
        var groups =  {
                        "suggested": "",
                        "recommended": "Recommended Articles",
                      };
        return groups[item.type];
      }],
      groupOrder: "desc",
      maxItem: 15,
      maxItemPerGroup: 5,
      source: {

        suggest: {
          display: "term",
          url: [{
                type: "POST",
                url: "/ajax/autosuggest",
                data: {
                      q: "{{query}}"
                }
          }, "data.suggest"],
          template: "{{term}}"
        },
        
        recommend: {
          display: "project",
          href: function (item) {
            return item.url
          },
          url: [{
                type: "POST",
                url: "/ajax/autosuggest",
                data: {
                      q: "{{query}}"
                }
          }, "data.recommend"],
          template: "{{project}}"
        }
      }
```
For query, 'guide', both groups show 5 (json results for both are 10 each).
For query 'gui', recommend group shows 5 but suggest group shows none, even though json results for both are still 10 each.

Is there some config issue here that I am missing? Is there a way to set a maxItemPerGroup to make sure both groups have results (though that has a logical problem)?

Thanks!

**Comment by running-coder** [comment]
Hey kurjain, I tried to reproduce your usecase based on this sample data and was unable to reproduce the issue where a group wouldn't display its results based on your init options, perhaps you have a different data structure?

``` javascript
{
  "data": {
    "suggest": [
      {
        "term": "wguide",
        "type": "suggested"
      },{
        "term": "seggui",
        "type": "suggested"
      },{
        "term": "tdguibftb",
        "type": "suggested"
      },{
        "term": "guid",
        "type": "suggested"
      },{
        "term": "dbtdgui",
        "type": "suggested"
      },{
        "term": "btgui",
        "type": "suggested"
      },{
        "term": "btdguibtd",
        "type": "suggested"
      },{
        "term": "gvdrgguibtd",
        "type": "suggested"
      },{
        "term": "drgguidwq",
        "type": "suggested"
      },{
        "term": "341gguidwq",
        "type": "suggested"
      }
    ],
    "recommend": [
      {
        "project": "guide",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "seggui",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "tdguibftb",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "guid",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "dbtdgui",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "btgui",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "btdguibtd",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "gvdrgguibtd",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "drgguidwq",
        "type": "recommended",
        "url": "/allo"
      },{
        "project": "341gguidwq",
        "type": "recommended",
        "url": "/allo"
      }
    ]
  }
}
```

![2016-01-22_1120](https://cloud.githubusercontent.com/assets/7377382/12516278/a6b51550-c0fa-11e5-98c2-4be2a8258894.png)

**Comment by running-coder** [comment]
could you provide your sample data for "gui" and "guide" queries? also a screenshot of the typeahead issue where the results are not displayed.

If you don't want any Typeahead filtering, you can look into ``filter: false`` global and source options

**Comment by kujain** [comment]
Thanks for your quick response. Here's more info and screenshots. 
The first screen with the query (st) shows the data in both groups properly. 
The 2nd screen has the query sty and shows only the 2nd group, even though both groups have data.
The 3rd screen has the query styl and now shows correctly. 
This issue is intermittent and occurs in some instances, not sure of the logic of when it shows and when it doesn't.
The data is dynamic but here's some sample captured json data.
![screen-wthout-issue](https://cloud.githubusercontent.com/assets/120631/12517159/755ada8a-c0ff-11e5-9398-62ec5c22c4e9.png)
![screen-wth-issue](https://cloud.githubusercontent.com/assets/120631/12517162/7ac22ac8-c0ff-11e5-9935-0ee145b1072c.png)
![screen-wthout-issue2](https://cloud.githubusercontent.com/assets/120631/12517168/8049d28e-c0ff-11e5-9f84-8e3fbd80cb5e.png)

[sample.txt](https://github.com/running-coder/jquery-typeahead/files/101149/sample.txt)

**Comment by kujain** [comment]
Well thank you! 
```filter: false``` did the trick here!
Now the filtering is happening through each ajax call and is now working beautifully!

**Comment by running-coder** [comment]
cool! I'll flag this as an issue and double check what the problem could be.

**Comment by running-coder** [comment]
Found the issue (which is not really one)... But yea if you are doing extra filtering on the BE, you should be using the mentioned option

![2016-01-22_1412](https://cloud.githubusercontent.com/assets/7377382/12520419/786684e6-c112-11e5-8e03-d700572a3587.png)
