### ISSUE TITLE
Categories dropdown should close when clicked elsewhere

### ISSUE THREAD

**Issue by icemangoa** [running-coder/jquery-typeahead#143]
Hi, first of all THANK YOU SO MUCH for taking the time to make and share something like this. It really helps out.

Now, my question to you: is there a way to close the categories drop-down once the user has clicked somewhere else on her screen?

I thought of something like this > 
callback: {
 onMouseLeave: function (node, a, item, event) {
	$(div).find(".typeahead-container").removeClass("filter");
    }
}

But, naturally, it didn't do the trick :) If and when you have the time, please let me know if I can solve this easily.

Thank you again. Greetings.

**Comment by running-coder** [comment]
Hey Bill, thanks for the kind words! Sharing the plugin allows its to be better from the feedbacks :)

Regarding your issue, is it when ``dropdownFilter: true`` option is activated right? It was behaving like this in the earlier version, I might have broke it trying to optimize the code.

Thanks for raising the issue!

**Comment by running-coder** [comment]
Should be good on develop branch

**Comment by icemangoa** [comment]
It is! Thank you again so much for taking the time not only to fix it, but to do it so quickly too. This might sound corny, but I've gotta say: you're helping, makes the world a better place. Thank you again, greetings!

**Comment by running-coder** [comment]
yw, glad it helped!
