### ISSUE TITLE
The hint doesn't overlap with the input text when the second is too long

### ISSUE THREAD

**Issue by nop33** [running-coder/jquery-typeahead#144]
Here's a self explanatory example:
![screen shot 2016-02-01 at 12 04 54](https://cloud.githubusercontent.com/assets/1579899/12715745/5032f5f0-c8dc-11e5-93fd-da4cb3ac07f7.png)
![screen shot 2016-02-01 at 12 05 08](https://cloud.githubusercontent.com/assets/1579899/12715746/5033569e-c8dc-11e5-936a-805f486a08c9.png)

Once the input text becomes longer than the width of the input field, the hint does not overlap with the text.

**Comment by running-coder** [comment]
Thanks for raising the issue, I'll take a look shortly

**Comment by running-coder** [comment]
http://stackoverflow.com/questions/6406843/detect-if-text-has-overflown Seems like a possible solution, if the text is longer than the input do not display the hint

**Comment by running-coder** [comment]
Should be good on the develop branch

**Comment by nop33** [comment]
Thanks a lot for the help! Keep up the good work!

**Comment by running-coder** [comment]
sure Ilias, np! Thanks for letting me know any issue you find
