### ISSUE TITLE
Is it possible to disable the click event on search result?

### ISSUE THREAD

**Issue by mustig3** [running-coder/jquery-typeahead#145]
I may just not figured out the potential of the Callback function and onClickBefore. But it seem like Im not able to stop the default event to trigger.
My goal are to render the search results without the function to select a item or redirect the user.

**Comment by running-coder** [comment]
hey have you looked into [onClickBefore](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L1639) callback? you simply have to ``e.preventDefault()`` inside the function

``` javascript
callback: {
    onClickBefore: function (node, a, item, event) {
        // Prevent default Typeahead behaviors
        event.preventDefault();

        // My events
    }
}
```

**Comment by mustig3** [comment]
Excellent! I hadn't declared the parameters correctly.
Next step: I have also struggling with the **_onLayoutBuiltBefore_** to try to replace the `a tags` with 'spans'. Is there a more sophisticated way to accomplish that? My current efforts overwrite my template.
Thanks for your help, much appreciated!

**Comment by running-coder** [comment]
[jquery replaceWith()](http://stackoverflow.com/questions/7093417/using-jquery-to-replace-one-tag-with-another) might help you with that!

``` javascript
onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
    // your replaceWith code

    return resultHtmlList;
}
```

**Comment by mustig3** [comment]
Great! I will definitely that.
Thank you for taking the time and help me out!

**Comment by running-coder** [comment]
yw

**Comment by mustig3** [comment]
Here is the combined code that solved my problem :)
```
callback: {
  onLayoutBuiltAfter: function (node, query, result, resultHtmlList) {
    $('.typeahead-item a').replaceWith(function () {
      return $("<span />").append($(this).contents());
    });

    return resultHtmlList;
  },
  onClickBefore: function (node, a, item, event) {
    event.preventDefault();
  }
}
```

**Comment by running-coder** [comment]
yep, you have 2 options, either ``onLayoutBuiltBefore`` or ``onLayoutBuiltAfter``.

callback: {
 onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
    resultHtmlList.find('a').replaceWith(function () {
      return $("<span />").append($(this).contents());
    });
    // onLayoutBuiltBefore requires resultHtmlList to be returned
    return resultHtmlList;
  },
  onLayoutBuiltAfter: function (node, query, result) {
    // no resultHtmlList parameter
    $('.typeahead-item a').replaceWith(function () {
      return $("<span />").append($(this).contents());
    });
  },
  onClickBefore: function (node, a, item, event) {
    event.preventDefault();
  }
}
