### ISSUE TITLE
Hide typeahead-result box on clicking a button

### ISSUE THREAD

**Issue by kujain** [running-coder/jquery-typeahead#147]
Hi there! 
Love the easy and flexibility of your plugin. I am having a small but UI-related issue. I have a clear search box button in my form that clears anything entered in the search box. But how can I also close the currently opened typeahead-result box as well? If I do:
```        $('.typeahead-result').hide(); ```
then the results box never opens on subsequent searches.

thanks!

**Comment by kujain** [comment]
I was able to use an event to handle this feature:
```       
 $('input').val('');
 $('.typeahead').trigger('input.typeahead');
```
By first clearing the field and then triggering the input event, typeahead would have no value to search for and hence would not show.

thanks!

**Comment by running-coder** [comment]
hey kujain, have you been able to achieve the desired result? In a recent change I've made Typeahead methods and variables available inside the callbacks but you can also trigger them from outside a Typeahead init.

``` javascript
// Use of Typeahead function from inside the callbacks
typeof $.typeahead === "function" && $.typeahead({
    input: '#myTypeahead',
    searchOnFocus: true,
    callback: {
        onClickAfter: function () {
            this.hideLayout();
        }
    }
});
    
// Toggle Typeahead function for a specific instance from anywhere
Typeahead['#myTypeahead'].hideLayout();
```

 


```

**Comment by kujain** [comment]
Great to know! I was trying to use those methods on my current version but it didn't work. I will update my library and try this way.

**Comment by running-coder** [comment]
cool, lmk if you have any issue

**Comment by csaSall** [comment]
Hello,
thank you for this beautiful plugin.
i have the same issue of above described as the below:
i have a dropdown with the list of countries as per the below:
`$.typeahead({
        input: '#cmbCountry',
        dynamic: true,
        highlight: false,
        searchOnFocus: true,
        minLength: 0,
        maxItem: 0,
        emptyTemplate: "no result for {{query}}",
        template: '{{name}}',
        templateValue: '{{name}}',
        display: ['id', 'name'],
        source: {
            country: {
                display: ['id', 'name'],
                ajax: {
                    url: "/api/Lookup/ListCountries"
                }
            }
        },
        callback: {
            onClickAfter: function ()
            {
                this.hideLayout(); 
            }
        }
    });`
from the user public id, i need to select the default country, and i used the code below:
`$.ajax({
        'url': 'http://www.freegeoip.net/json/185.99.32.162', //+ IP.value,
        'type': 'GET',
        'success': function (data)
        {
            if (data.country_code !== "")
            {
                $('#cmbCountry').val(data.country_name); 
                $('#cmbCountry').trigger('input.typeahead');
                Typeahead['#cmbCountry'].hideLayout();
            }
        }
    });`
the selected value list will not hide.
can yo help me for the above issue?

**Comment by running-coder** [comment]
hey @csaSall I've just tested the `Typeahead['#cmbCountry'].hideLayout();` function and it removes the result list as expected. Are you sure your code is getting inside `if (data.country_code !== "")`? you can also open your console and validate from there that the result list hides when typing the command

**Comment by csaSall** [comment]
Hello, 

thank you for your reply,
you can find an example to reproduce the issue using the following [https://hubic.com/home/pub/?ruid=aHR0cHM6Ly9sYjEwNDAuaHViaWMub3ZoLm5ldC92MS9BVVRIXzkzYjdiNTljOThiYWM2Mjc4NjdiMDgzZjViNDExYmRlL2RlZmF1bHQvLm92aFB1Yi8xNDk1NDM5Nzc3XzE0OTYzMDM3Nzc/dGVtcF91cmxfc2lnPTIxMjQ0ZjBkMGEzNDBiMmJmNTJiNWIzNzA1MDBkYjBhOWYyMzhhZWYmdGVtcF91cmxfZXhwaXJlcz0xNDk2MzAzNzc3#](link)

**Comment by running-coder** [comment]
Issue comes from the order the script is called

```javascript
$(document).ready(function ()
    {
        $.typeahead({
            input: '#cmbCountry',
            dynamic: true,
            highlight: false,
            searchOnFocus: true,
            minLength: 0,
            maxItem: 0,
            emptyTemplate: "no result for {{query}}",
            template: '{{name}}',
            templateValue: '{{name}}',
            display: ['id', 'name'],
            source: {
                country: {
                    display: ['id', 'name'],
                    ajax: {
                        url: "data/countries"
                    }
                }
            },
            callback: {
                onClickAfter: function ()
                {
                    this.hideLayout();
                },
                onReceiveRequest: function ()
                {
                    console.log('Typeahead received request.')
                }
            }
        });
        $.ajax({
            'url': 'http://www.freegeoip.net/json/185.99.32.162',
            'type': 'GET',
            'success': function (data)
            {
                console.log('geoip request.')
                if (data.country_code !== "")
                {
                    $('#cmbCountry').val(data.country_name);
                    $('#cmbCountry').trigger('input.typeahead');
                    Typeahead['#cmbCountry'].hideLayout();
                }
            }
        });
    });
```

Geoip console logs before Typeahead receiveRequest. Geoip closes the result list but then Typeahead displays it back (script order issue). You may want to put that geoip detection inside one of the Typeahead callbacks or re-arrange the requestorders.

```javascript
$.typeahead({
    ...
    callback: {
        ...
        onReceiveRequest: function ()
        {
            doGeoipRequest(this.query, this.result)
        }
    }
});
function doGeoipRequest (query, result) {
    console.log('~~~~~~Query')
    console.log(query)
    console.log('~~~~~~Results')
    console.log(result)

    $.ajax({
        'url': 'http://www.freegeoip.net/json/185.99.32.162',
        'type': 'GET',
        'success': function (data)
        {
            console.log('geoip request.')
            if (data.country_code !== "")
            {
                $('#cmbCountry').val(data.country_name);
                $('#cmbCountry').trigger('input.typeahead');
                Typeahead['#cmbCountry'].hideLayout();
            }
        }
    });
}
```

**Comment by csaSall** [comment]
thank you again.
the testing example should do the following:
on form is loaded, it should detect the user country and set the value automatically in the dropdown.
currently it will work but it will leave the dropdown expanded.
the first image is for the current result, and it should be like the next image.
![current result](https://cloud.githubusercontent.com/assets/28846671/26321269/cee64f2c-3f2e-11e7-9706-56b09dddb020.png)
![it should be](https://cloud.githubusercontent.com/assets/28846671/26321268/cee08178-3f2e-11e7-80fc-687dec143d00.png)

**Comment by bcolflesh** [comment]
resultContainer: false,

**Comment by running-coder** [comment]
by using `resultContainer: false` your subsequent research will not display any results. I miss understood how your Typeahead was working, thanks for explaining.

Using triggerHandler should do the trick. It will perform the search and use the `done` function as the callback when the search is completed.
```javascript
Typeahead['#cmbCountry']
    .node
    .val(data.country_name)
    .triggerHandler('input')
    .done(function () {
        Typeahead['#cmbCountry'].hideLayout();
    });
```

**Comment by bcolflesh** [comment]
Cool, didn't know about hideLayout().

**Comment by csaSall** [comment]
thank you very much for your help.
