### ISSUE TITLE
Support for Mobiles

### ISSUE THREAD

**Issue by kujain** [running-coder/jquery-typeahead#149]
Wondering if there's any support for mobile actions. For example:

1. Currently clicking outside the typeahead box hides the box. This is fine on desktop (mouse) but on mobile, this action happens even on tap and scroll page. It hides the box before the user has a chance to scroll through the entire list of suggestions. This works only if you scroll within the box but thats risky. If would be great if there's a way for the plugin to currently recognize tap-scroll, tap-drag etc. events. If not, can you suggest a workaround?

2. An alternative view for mobiles. For mobiles, clicking in the field shows the system keyboard that takes up half the screen, making most of the typeahead box get hidden under the keyboard. This makes scrolling more important but that doesn't really work as per the point above.Perhaps a simpler single scrollable list could work? 

Thanks!

**Comment by running-coder** [comment]
Hey, mobile should be supported but not entirely tested. If you have time I'm open to PR or it will have to wait a lil

**Comment by running-coder** [comment]
Hey kujain the modifs are on `develop` branch, let me know if everything works correctly
