### ISSUE TITLE
Passing search term to function

### ISSUE THREAD

**Issue by nazimmacbeth** [running-coder/jquery-typeahead#15]
Please consider the following code snippet:

$('#country_v1-query').typeahead({
    order: "desc",
    source: {
        data: getData(searchText)             
    },
    callback: {
        onInit: function (node) {
            console.log('Typeahead Initiated on ' + node.selector);
        }
    }
});

Pardon my naivete, but how do I reference the search text? I would like to pass it to "getData()" as a parameter.  Please advise...

Thanks!
Nazim

**Comment by running-coder** [comment]
Hi nazimmacbeth,

the source.data object is meant to contain all of the possible search results, in that case every countries inside an array ['country1', 'country2', 'etc.']. The Typeahead handles the filtering depending on what was typed in the input to give the matching results, it is not for you to manually filter them with the searchText.

Not sure if it answered your question? Or perhaps I misunderstood your question and in that case I would need more details as of what you are trying to accomplish, the code of getData function and searchText variable value.

Let me know,

Thx
