### ISSUE TITLE
dynamicFiltering by value

### ISSUE THREAD

**Issue by Guntiss** [running-coder/jquery-typeahead#155]
Hello! Is there any way I could filter items by value? For example, It would be great If it was possible to do like this:
        dynamicFilter: [{
            selector: '#location',
            key: '|location_id',
            value: '3'
        },
so it displays items that match location_id=3. Currently as I suppose It only checks value true/false and ignores value parameter.

Thanks, awesome plugin by the way!

**Comment by Guntiss** [comment]
I managed to solve my problem using matcher, however it would still be convenient to use above suggestion, in my opinion.

**Comment by running-coder** [comment]
Hey Guntiss, indeed that would be a cool idea. As you found out, `matcher` and `filter` functions are there as the backup plan for any filtering needs. If you are up to the challenge I'm open to PR inside the develop branch.

lmk

**Comment by running-coder** [comment]
Were you trying to accomplish your filtering on an input checkbox? In that case I would go with adding a value attribute on the html instead of the configuration.

Using the game_v3 demo

``` html
<input type="checkbox" id="attack" value="10">
<label for="attack">
    Attack 10
</label>
```

``` javascript
// inside dynamicFilter Typeahead option
{
    selector: '#attack',
    key: '&info.attack'
}
```

[This line](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L2126) needs to be replaced with
``` javascript
value = tag.checked && tag.value || tag.checked || null;
```

**Comment by running-coder** [comment]
https://jsfiddle.net/runningcoder/14epn93f/
