### ISSUE TITLE
Typescript support..

### ISSUE THREAD

**Issue by SorenMuller** [running-coder/jquery-typeahead#156]
Hi,
Are there any support for typescript.. 
Any *.d.ts files ??? 

Bloodhound support ??

**Comment by running-coder** [comment]
Hey Soren, unfortunately there is no support for neither. I was looking into converting into ES6 a while back but It would require more time that I have available. For now the plugin is in bug fixing / small feature implementation mode. Sorry.

**Comment by gs-smuthyam** [comment]
Hi, Any update on creation of a d.ts file for this library that will support typescript?

**Comment by running-coder** [comment]
ES6 should occur in version 3.0, maybe from there I'll find a plugin to generate a .ts from w/ gulp from the function's jsdoc comments

**Comment by HamidTheGeek** [comment]
Hi All,
I knew it's an old-closed issue but for future reference. There is a type definition for it [here](https://www.npmjs.com/package/@types/jquery-typeahead)
