### ISSUE TITLE
How I can populate suggestion list on focus the input?

### ISSUE THREAD

**Issue by keem1201** [running-coder/jquery-typeahead#157]
By "French v1" example, we can set `minLength: 0`. But it will show up all lists. What to do if I only want some best suggested list upto 10 lists on focusing the input. 

Thanks

**Comment by running-coder** [comment]
Hey keem, what do you mean by "best suggested list"? You can use the `matcher` or `filter` function to define yourself a "default set" if the Typeahead input is empty.

``` javascript
matcher: function (item, displayKey) {
    // If a query is set inside the input, match anything
    if (this.query.length) return true;
    
    // If the query is empty only the "item.name" that has a value of item1, item2 or item3 will be displayed
    if (~['item1', 'item2', 'item3'].indexOf(item.name)) {
        return true;
    }
    return;
}
```

**Comment by running-coder** [comment]
Closing due to no reply
