### ISSUE TITLE
Dynamically updating items

### ISSUE THREAD

**Issue by Guntiss** [running-coder/jquery-typeahead#158]
Hello! My project requires updating items dynamically. I am achieving this by modifying object throught

> window.Typeahead['#input_query'].source.inventory

But for changes to appear I need to trigger search using
> $('#input_query').trigger('input.typeahead');

Issue with this is that it redraws everything and therefore causes scrolling to top of the page. Is there any way to achieve updating without causing scrolling?
Further on I am planning to implement live item updating through socket connection, so that all online users see changes immediately.

I tried updating object and DOM elements directly, it works, but the problem is, I can't find any way to reuse template that generates every entry.

**Comment by running-coder** [comment]
hey, dynamic data update is not fully supported atm, you found the quick way to do it but internally it has to go through the populateSource function to adjust a few extra key on every objects such as group or compiled (if you are using correlativeTemplate option) or write insite localStorage / sessionStorage

I'm not sure why it scrolls, there is no such code inside Typeahead or perhaps its related to how your implementation is made... perhaps you can use the onSearch callback as see if you can prevent any scrolling from there?

Sounds like a cool idea to update Typeahead's data from a socket connection! Dynamically updating Typeahead's source is planned for the next version. What do you mean by reusing the template? Could you provide screenshot / code sample via jsfiddle?

**Comment by Guntiss** [comment]
I am using Game V3 example. Scrolling is caused because resetLayout sets container content to empty. I managed to fix scrolling issue using simple fix. Saving scroll position before resetting layout

> scroll_t = $('body').scrollTop();
> this.resetLayout();

and loading scroll position at the end of searchResult()
> $('body').scrollTop(scroll_t);

All callbacks ar executed after resetLayout(), so I had no choice to modify source code.
I think this should be definitely implemented in plugin :)

**Comment by running-coder** [comment]
indeed for some obscure reasons the template scrolls up (reproducable via [game_v3](http://www.runningcoder.org/jquerytypeahead/demo/#form-game_v3)

I'll see what I can do

**Comment by running-coder** [comment]
Issue was with [this.resultContainer.html('');](https://github.com/running-coder/jquery-typeahead/commit/e1f8b87c7ea77698ec511a30a4a29e1bc4f6ad59#diff-fd35b9a6d01c422794aa3fb6236ba920L2185)

Let me know if it fixed the scrolling part, thx

**Comment by Guntiss** [comment]
Yes, this worked flawlessly :) Thanks!
