### ISSUE TITLE
Search multiple data item.elements, but always return the same data item.element?

### ISSUE THREAD

**Issue by zigmoo** [running-coder/jquery-typeahead#159]
Running-Coder, thanks so much for this great tool you've built! (It is replacing typeahead.js for me!)

My question is: 
Given JSON data:
```
[{"tail_number":"4K-AI07","aircraft_type":"A320","serial_number":"6285","id":"1432"},
{"tail_number":"4K-AI08","aircraft_type":"A340","serial_number":"779","id":"1449"}]
```
and
`display: ["tail_number","aircraft_type"]`

Is there a setting that allows populating my input (tail_number) with only the item.tail_number value, even if user selects the data row based on typing a partial item.aircraft_type?

Thanks in advance for any help!

And, thanks again for this great tool! I'm really enjoying it!

**Comment by running-coder** [comment]
Hey zigmoo, thanks for the kind words, always appreciated

good question, I've never tested it but using the following method it should provide you with the result you are looking for

``` javascript
$.typeahead({
    ...
    callback: {
        onClickAfter: function(node, a, item, event) {
            node.val(item.aircraft_type)
        }
    }
})
```

**Comment by zigmoo** [comment]
Tom, that worked perfectly! Thanks SO much!

**Comment by running-coder** [comment]
Welcome :)
