### ISSUE TITLE
"&amp;" instead of "&" in displayed result.

### ISSUE THREAD

**Issue by vindolin** [running-coder/jquery-typeahead#163]
Whenever I have an ampersand in my search string, it leads to all the special chars getting converted and displayed as "\&amp;", "\&gt;" etc.
Any ideas what I'm doing wrong?

Good:
![typeahead_good](https://cloud.githubusercontent.com/assets/834347/13663995/16bafdcc-e6a5-11e5-942d-f8b70d3c92b7.png)

Bad:
![typeahead_bad](https://cloud.githubusercontent.com/assets/834347/13664073/701bd184-e6a5-11e5-9e4e-7a959e038340.png)

Here's my code and JSON source:
https://gist.github.com/vindolin/68b7d97bf1f9dab0caa3

**Comment by running-coder** [comment]
Hey Vindolin, this issue is caused by #134, I'll have a look shortly on how we can resolve this.

Thanks for pointing it out

**Comment by running-coder** [comment]
the sanitize function was introduced to prevent from XSS in case you are pulling data from an untrusted source. While waiting for a fix in 2.4 you can simply comment [both sanitize calls](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L1646) when building the template

This task might take a bit longer than a quick fix

**Comment by running-coder** [comment]
Should be good now on the `develop` branch, let me know
