### ISSUE TITLE
Submit on item select (enter)

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#164]
I know this was an issue before but is there already a solution ?

I'd like to submit the form by clicking the left mouse button in the resultlist
without having to click enter.

Do I have to do this with a callback like 

onClickAfter: function (node, a, item, event) {
                        ->  submit form here....
            }

**Comment by running-coder** [comment]
Hey,

as you probably noticed, the behavior was discussed in #54, the onClickAfter is the current way to go to submit on click. As one of the latest modifs on the `develop` branch you can push your submit conditions a little bit further, for ex:

``` javascript
onClickAfter: function (node, a, item, event) {
    node.closest('form').submit()
},
onSubmit: function (node, form, item, event) {
    // adding extra validation in case some item must not submit the form while others must
    // returning false will not submit the form
    return !!item.someProperty;
}
```

**Comment by GDM70** [comment]
If I use document.getElementById("...").innerHTML I can get what I want but I'm not sure if that's the a good solution.
Before I had angular bound fields like {{clients.name}}, {{clients.phone}},... but pressing ENTER was mandatory to fill in those fields.
With manipulating the dom I can fill in the fields just by selecting an item out of the list, no need to click the enter key.
If I'm completely missing the point here please let me know.

**Comment by running-coder** [comment]
What are you achieving with `document.getElementById`, is this in your onClickAfter callback? Are you still with angular where you could use ng-model on the input and use the callback to assign the value. I'm not sure of the exact behavior.. perhaps you could build a quick demo on jsfiddle and send me a link.

**Comment by GDM70** [comment]
I had my scopes wrong, with $rootScope I got it back to work.
Thanx for the help :-)

**Comment by running-coder** [comment]
sure, np
