### ISSUE TITLE
Submitting form with typeahead inside

### ISSUE THREAD

**Issue by mic4ael** [running-coder/jquery-typeahead#165]
Together with my teammates today we stumbled upon an error in one of our custom jQuery widgets which uses the typeahead library internally. The problem was caused by calling `hideLayout` when submitting a form. After some investigations we found the lines which are the main culprit.
[Link to the source code](https://github.com/running-coder/jquery-typeahead/blob/82ff06ce929746794eeeea73598a171a4f900f09/src/jquery.typeahead.js#L2165)

```javascript
// Means the container is already hidden
// if (!this.container.hasClass('result')) return;
```

It kind of makes sense to check if layout is already shown and if there is a necessity to hide it, thus my question is if this comment is intended? If it is, then, can we get exaplanation why?

**Comment by ThiefMaster** [comment]
Did you post markdown with a broken URL or is that a GitHub bug (your link points to `https://github.com/running-coder/jquery-typeahead/issues/url`)

**Comment by mic4ael** [comment]
Sorry for the mistake. The url has been corrected.

**Comment by running-coder** [comment]
Hey mic4ael,
I've commented this line to implement a backdrop/fullpage search option recently. This ticket and investigation made me realize that show/hide layout is not handled properly. The functions are indeed not fired at the proper time depending on the used configuration.

So you get a better understanding of the backdrop search: http://jsfiddle.net/runningcoder/xd0q4co1/

**Comment by running-coder** [comment]
I've uncommented the code and fixed the backdrop option so it behaves properly with "Esc" key.

**Comment by mic4ael** [comment]
That is great. Thanks for your professionalism and quick response.

**Comment by running-coder** [comment]
Thanks for raising the issue! let me know if everything works as expected

**Comment by mic4ael** [comment]
It looks like the fix solves the issue for us.
