### ISSUE TITLE
How to submit a different value than is being displayed?

### ISSUE THREAD

**Issue by davemarkle** [running-coder/jquery-typeahead#168]
Hello,

I have a typeahead instance coded like this: 

`
$('##' + i).typeahead({
                            order: "desc",
							minLength: 3,
						    maxItem: 20,
						    dynamic: true,
                            hint: true,
                           display: ["display","type"],
                           source: {
                                supps: {
                                    url: [{
                                        type: "POST",
                                        url: "function/to/get/file.json",
                                        data: {
                                            searchString: "{{query}}"
                                        },
                                        callback: {
                                            done: function (data, textStatus, jqXHR) {
                                                return data;
                                            },
                                            fail: function (jqXHR, textStatus, errorThrown) {},
                                            complete: function (jqXHR, textStatus) {},
                                            always :function (data, textStatus, jqXHR) {}
                                        }
                                    }]
                                }
                            },
                          
                        });

}
`

dynamically populated with JSON that looks like this:

`[{"display":"Hotel du Louvre","id":478,"type":"HOTEL"},{"display":"Louvre Entrance","id":2464,"type":"ATTRACTION"}]`

This typeahead is part of a form.  I want the submitted value to be the ID field, not the DISPLAY field.  I figure it must be simple... but I can't find it in the docs.  How do I do this?

Thank you very much!

**Comment by running-coder** [comment]
hey Dave,

I would recommend to have a hidden input inside your form that gets updated with the proper `id` when the user selects an item.

```javascript
$('##' + i).typeahead({
    ...
    source: {
        supps: {
            url: [{
                type: "POST",
                url: "function/to/get/file.json",
                data: {
                    searchString: "{{query}}"
                }
            }]
        }
    },
    onClick: function (node, a, item, event) {
        $('#mySuppsId').val(item.id)
    }
});

<input type="hidden" id="mySuppsId">
```

**Comment by davemarkle** [comment]
Great Idea.  Worked perfect.  Though it would be handy to fire onClick when the value is deleted from typeahead box.  Is there an event that fires when a value is deleted?

**Comment by running-coder** [comment]
yea, you can use either onSearch or onResult depending of your needs. Look at the doc for the list of available callbacks and the flowchart should show you they moment they are triggered. They are all scoped within the Typeahead object so doing console.log(this); from a callback should also give you the property list of your instance

**Comment by running-coder** [comment]
Ah, I see that these callbacks were added after the flowchart was made. will update that
