### ISSUE TITLE
Working in developer environment but not working on live environment

### ISSUE THREAD

**Issue by w-sharp** [running-coder/jquery-typeahead#176]
Not a bug but a trouble in my environment.

Working in my PC perfectly, but not in live site. I have checked everything. No luck.

Json data URL is valid. Works fine. When i enter my keywords it is loaded from URL and content is proper. There is no any JS error on the page. I have analyzed almost everything with Firefox and Chrome developer tools, firebug etc. Nothing helps.

Didn't know whom to ask :(

Here is my code:

$('#mySearchBox').typeahead({
minLength: 2,
maxItem: 5,
group: false,
hint: true,
highlight: true,
display: ["title", "writer", "supporter", "owner", "target", "description1", "description2"],
template: "{{title}}, <small><em>{{writer}}</em></small>",
backdrop: {
"background-color": "#333"
},
source: {url: ["ProductList.json"]}, // This is a URL. Dynamic page to be exact. Returns json data.
callback: {
onClickAfter: function (node, a, item, event) {
event.preventDefault();
window.location = (item.target);
$('.js-result-container').text('');
},
onResult: function (node, query, obj, objCount) {
}
},
debug: false
});

**Comment by running-coder** [comment]
hey, perhaps you could try to use the unminified version and `debug: true` in production to see if any notice comes up in the console? Your json request in via the same domain right?

**Comment by w-sharp** [comment]
hi, i didn't use unminified version but i have tried with debug true. yes json request is in same domain.

ı will try with unminified version immediately

**Comment by w-sharp** [comment]
i just tested with unminified version with debug true.
i found this error:
"#mySearchBox"	"Ajax.callback.fail()"	""	"Request failed"

but it loads json data properly. I am confused

**Comment by running-coder** [comment]
ok that would explain why there is no data showing, perhaps you can declare the .fail function and print out the debug? perhaps we will find answers in there..

``` javascript
url: [{
    type: "GET",
    url: "ProductList.json",
    callback: {
        done: function (data, textStatus, jqXHR) {
            console.log(data);
            // IMPORTANT: data has to be returned
            return data;
        },
        fail: function (jqXHR, textStatus, errorThrown) {
            console.log('--------------')
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
            console.log('--------------')


        },
        complete: function (jqXHR, textStatus) {},
        always :function (data, textStatus, jqXHR) {}
    }
}]
```

**Comment by running-coder** [comment]
also perhaps the dataType of your content on your prod server is not set to `json`, in that case specify:
``` javascript
url: [{
    type: "GET",
    url: "ProductList.json",
    dataType: "json",
    ...
```

**Comment by w-sharp** [comment]
hey man, thanks. actually huge thanks.

SyntaxError: JSON.parse: bad escaped character at line 1028 column 267 of the JSON data

Apparently it was about the json data loaded on the prod site. There was an item that does not exist in the dev but exist in the live and it has a bad character. Still dont know which character creates the problem but i now have a place to look at and it is clear it is not the script.

Thanks again for your help and for this great script.

**Comment by running-coder** [comment]
no prob, yw

**Comment by running-coder** [comment]
from my experience there is a blank character created by windows software when copy-pasting that might look like a space but is not. I recommend deleting the spaces characters at that location and re-writing them. Perhaps something else... GL

**Comment by w-sharp** [comment]
it was a back slash which is not allowed in json. so when i fix it everything stat working properly.
