### ISSUE TITLE
Can't get results to show?

### ISSUE THREAD

**Issue by tgmweb** [running-coder/jquery-typeahead#178]
I'm currently feeling kinda stupid, but the following isn't working:

```
$.typeahead({
    filter: false,
    dynamic: true,
    source: {
      contacts: {
        url: [{
          type: "POST",
          url: "/search/contacts",
          data: {
            term: "{{query}}"
          },
          callback: {
            done: function(data) {
              var returnData = [];
              $.each(data.hits.hits,function(index,value) {
                returnData.push(value._source);
              });
              console.log(returnData);
              return returnData;
            }
          }
        },"data"]
      }
    },
    callback: {
      onResult: function (node, query, result) {
        console.log(result);
      }
    }
  });
```
My console output shows me getting back the results from the server, but the onResult callback is showing nothing in the results.

**Comment by tgmweb** [comment]
ok, doing:
````
var returnData = {};
returnData.data = [];
$.each(data.hits.hits,function(index,value) {
  returnData.data.push(value._source);
});
return returnData;
````
fixed the issue - sorry this can be closed!

**Comment by tgmweb** [comment]
Sorted - I was being stupid!

**Comment by running-coder** [comment]
Hey, since you are reformatting your data array, you may not need to use the extra "data" configuration  inside the url key

``` javascript
// Before
url: [{
    type: "POST",
    url: "/search/contacts",
    data: {
        term: "{{query}}"
    },
    callback: {
        done: function (data) {
            var returnData = [];
            $.each(data.hits.hits, function (index, value) {
                returnData.push(value._source);
            });
            console.log(returnData);
            return returnData;
        }
    }
}, "data"]

// After
url: {
    type: "POST",
    url: "/search/contacts",
    data: {
        term: "{{query}}"
    },
    callback: {
        done: function (data) {
            var returnData = [];
            $.each(data.hits.hits, function (index, value) {
                returnData.push(value._source);
            });
            console.log(returnData);
            return returnData;
        }
    }
}
```

**Comment by komprehend** [comment]
guys i can't see to make this work here are my info:


`$.typeahead({
    input: '.address-search-lg',
    minLength: 3,
    order: "asc",
    hint: true,
    dynamic: true,
    delay: 300,
    debug: true,
    backdrop: {
        "background-color": "#fff"
    },
    template: function (query, item) {
        var color = "#777";

        return '<span class="row">' +
            '<span>{{address}} ({{id}})</span>' +
        "</span>";
    },
    emptyTemplate: "Nothing found for <b>{{query}}</b>",
    display: ['address'],
    source: {
        addrs: {
            href: "/p/{{address|slugify}}/{{id}}",
            ajax: {
                type: 'POST',
                url: '/s',
                data: {
                    q: '{{query}}'
                },
                path:'results.addrs',
                callback: {
                    done: function (data) {
                        console.log(data);
                        return data;
                    }
                }
            }
        }
    },
`


![image](https://user-images.githubusercontent.com/1045334/30513104-a1917260-9acb-11e7-9c1d-b9cd3732c4f9.png)
