### ISSUE TITLE
If a group, wrap in its own DIV or UL

### ISSUE THREAD

**Issue by PixelPop** [running-coder/jquery-typeahead#179]
Hi, great library! This is more of a tweak I think... If I have two groups:

source: {
            entities: {
                template: "<span class='poop'>{{primary}}</span>",
                display: ["primary", "secondary"],
                url: ["/i/" + entityData.leid + "/search/all", "data.entities"]
            },
            users: {
                template: "<span>{{primary}}</span>",
                display: ["primary", "secondary"],
                url: ["/i/" + entityData.leid + "/search/all", "data.users"]
            }
        }

Would it be possible to have it so that each group is wrapped in its own DIV or UL? Or perhaps have it as an option like "wrapGroups: true". This would make it easier for multi-column search result panes.

Thanks

**Comment by tgmweb** [comment]
+1 for this.

Perhaps:
````
group: {
    template: "<div id='groupheader>{{group}}</div> {{groupresults}} <div id='groupfooter'></div>"
}
````

**Comment by running-coder** [comment]
Hey Pixel, possibly something like #69?

**Comment by PixelPop** [comment]
Yes like that....Apologies, I can't believe I didn't see that open item lol :)

**Comment by tgmweb** [comment]
That's exactly what I'm looking to do too. WHen you have 5 groups and 10-15 items per group the dropdown get's huge :)

On another note, is there a way to limit maxItem per group? At present it seems to limit all items - so if I want a max of 10 per group I'm having to do that in source.url.callback...

**Comment by running-coder** [comment]
for the `maxItemPerGroup` you can check [beer_v1 demo](http://www.runningcoder.org/jquerytypeahead/demo/#form-beer_v1)

**Comment by running-coder** [comment]
@PixelPop This feature is next on the list ;)

**Comment by running-coder** [comment]
I'll close this one, you can refer to the original ticket #69 to follow the status, thx
