### ISSUE TITLE
Remove dependency of own form

### ISSUE THREAD

**Issue by charlietfl** [running-coder/jquery-typeahead#18]
Great plugin since it has no other library dependencies like bootstrap or jQueryUI!

Should be able to use a typeahead (autocomplete) within a larger form however.

Current CSS for search icon is based on `type="submit"` but adding another `submit` in a larger form where the typeahead field is just one of many fields can be problematic as is adding another submit handler using `onSubmit` callback

**Comment by running-coder** [comment]
Hi charlietfl,

do you have a snapshot of what you are trying to accomplish? It seem to me that perhaps you should have multiple forms as there should only be 1 submit button per form.

Also you are free to edit / override the CSS file, it is only there as a demo of what the search input could look.
