### ISSUE TITLE
IE8 incompatibility caused by fix #105

### ISSUE THREAD

**Issue by gulima** [running-coder/jquery-typeahead#181]
In Internet Explorer 8, `Object.defineProperty()` can be used only on DOM objects [1].
Calling this method on an "generic" object literal (like the `xhrObject`) throws an error that says object does not support this action, and the code execution is halted.
That way, jquery-typeahead is not compatible (when we need AJAX requests, at least) with IE8.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by running-coder** [comment]
thanks for raising the issue gulima, will take a look at possible alternatives

**Comment by running-coder** [comment]
Should be good now
