### ISSUE TITLE
onSubmit triggered twice if there is result for the search

### ISSUE THREAD

**Issue by w-sharp** [running-coder/jquery-typeahead#182]
Hi;
I am using version 2.4.0. When i use an alert in obSubmit it is triggered twice if there is a result in the list so alert shown twice. If there is no result in the list it is ok and it is showing alert once.

Am i doing something wrong?

Here is my code

```

var originalQuery = '';

	$('#sb').typeahead({
		minLength: 2,
		maxItem: 5,
		hint: false,
		highlight: true,
		mustSelectItem: false,
		emptyTemplate: "No Result",
		display: ["title", "writer", "supporter", "owner", "target"],
		template: "{{title}}, <small><em>{{author}}</em></small>",
		backdrop: {
			"background-color": "#333"
		},
		source: {
			url: ["ProductList.json"],
        dataType: "json"
		},
		callback: {
			onClickBefore: function (node, a, item, event) {
				// Save the query to be re-used in onClickAfter
				originalQuery = this.query;
			},
			onClickAfter: function (node, query, item, event) {
				event.preventDefault();
				window.location = (item.target+'?q='+originalQuery);
			},
			onSubmit: function (node, form, item, event) {
				alert('You should select an item in result');
				return false;
			},
		},
		
		debug: false
	});

```

**Comment by running-coder** [comment]
Hey sharp, I'll double-check this afternoon your init seems fine might be a problem on Typeahead's side. Thanks for letting me know

**Comment by w-sharp** [comment]
I have upgraded to 2.5.1 to test. I didnt find any note or doc for upgrading but i have found in the demo that html part is changed so i also changed in my implementation. But i have seeing and error and i couldn't get it work.

[http://share.pho.to/A6xYX/ut/original](http://share.pho.to/A6xYX/ut/original)
[http://share.pho.to/A6xYX/tx/original](http://share.pho.to/A6xYX/tx/original)

**Comment by running-coder** [comment]
I was able to reproduce the error (i think), it is caused by searching for an undefined key (see screenshot)

**Comment by running-coder** [comment]
Regarding the upgrade notes, you can look at [version page](http://www.runningcoder.org/jquerytypeahead/version/) the template was updated as well as group and dropdownFilter options

**Comment by w-sharp** [comment]
Yes, you right. When i found and remove -for the moment- the key that sometime not present in the json it is working.

Then i was able to make the test to see if submit problem (triggered twice) occurs in the version 2.5.1. Unfortunately it is the same with latest version too.

Thanks

**Comment by running-coder** [comment]
found out the issue, it comes from [here](https://github.com/running-coder/jquery-typeahead/blob/develop/src/jquery.typeahead.js#L1230) will include a fix in the next commit

**Comment by running-coder** [comment]
Should be good now, lmk

**Comment by w-sharp** [comment]
Yeap, it seems both issues (submitting twice and undefined key) are done. Script works fine. Thanks again.

**Comment by running-coder** [comment]
amazing, thanks
