### ISSUE TITLE
Invalid encoded characters on dynamic requests for `{{query}}` inside $.Ajax.url

### ISSUE THREAD

**Issue by nicodewet** [running-coder/jquery-typeahead#184]
When performing an HTTP GET with a dynamic configuration, a forward slash in the request appears to be sanitised away whereas in my case I'm expecting and need URI encoding. 

It may well be that onSendRequest (node, query) callback is what one should use (for hand-crancked uriEncoding), but having stepped through the execution, the sanitisation happens after onSendRequest gets called.

So, my question is basically, if I do a HTTP GET request, and need for a forward slash in {{query}} to be URI encoded (%2F) in the outgoing request, how do I make this happen?

Just to add some context to the cited use case, in my case the need for the preservation and URI encoding of a forward slash in {{query}} stems from the need to search addresses backed by a RESTful endpoint. When it comes to addresses a forward slash will be common e.g. when specifying say an apartment number then street number e.g. 23/100 Foo rd.

I'm on 2.5.0 of jquery-typeahead.

**Comment by running-coder** [comment]
Hey nico, thanks for raising the issue. Indeed i was sanitizing the string instead of applying `encodeURIComponent`. If you want to modify further the request before it gets sent you can wrap your ajax request in a function, ex:

```
source: {
    myGroupName: {
        // ajax key is replacing url key for version 2.6.0+
        ajax: [function (query) {
            // Modify the query here
            return {
                url: "/myData.json?q="+query,
                // OR
                data: {
                    q: query
                }
            }
        }, "data"]
    }
}
```

**Comment by running-coder** [comment]
Should be good now on the `develop` branch. The next version `2.6.0` should be available today / tomorrow. Let me know if anything.

Thanks

**Comment by bpadamata** [comment]
Hi, I am working with the latest version (2.6.1) and I could not see the fixed changes of applying encodeURIComponent in it.  So I am still having this issue.

The earlier version (2.6.0) includes the changes as below
xhrObject.request.url = xhrObject.request.url.replace('{{query}}', encodeURIComponent(scope.query));

However it is missing in the current release and this is how source looks like 
xhrObject.request.url = xhrObject.request.url.replace('{{query}}', scope.query);

**Comment by bpadamata** [comment]
It appears that you have modified this solution during fixing '#189 - Twice url encoding'

**Comment by running-coder** [comment]
Hey @bpadamata, I think I removed it because jQuery was already encoding the characters which was causing a double encoding, see #189

**Comment by bpadamata** [comment]
With the latest release I am unable to use a forward slash in {{query}} for the outgoing request. So I am restricted to used only the fixed version (2.6.0).

**Comment by running-coder** [comment]
Just tested... here is my result:

```javascript
// no encodeURIComponent
url: '/test.json?q={{query}}',

// jQuery handles encodeURIComponent
url: '/test.json',
data: {
    q: '{{query}}'
},
```

Are you using the first example? can you switch to the second example?

**Comment by running-coder** [comment]
This commit should fix the Ajax.url case.
