### ISSUE TITLE
Vertical scrollbar?

### ISSUE THREAD

**Issue by lw1990** [running-coder/jquery-typeahead#185]
Is there a vertical scrollbar for long lists?

**Comment by running-coder** [comment]
hey, you can have a look at [country_v2 demo](http://www.runningcoder.org/jquerytypeahead/demo/#form-country_v2)
- The ul.typeahead__list has max-height: 300px; and is scrollable
- onNavigateAfter is set to scroll the result container if arrow UP or DOWN are pressed to the .active item
