### ISSUE TITLE
sorting on more than one "display" key

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#186]
Hello,

Is it already possible to sort on more than one "display" key ?

**Comment by running-coder** [comment]
hey, the sorting occurs on all the keys specified inside the `display` option.

``` javascript
// key1 will be sorted asc, then key2
// it is not possble atm to say sort key1 asc and key2 desc
order: "asc",
display: ["key1","key2"]
```

**Comment by GDM70** [comment]
hmm, here it only sorts on the first column :-(
I hoped that updating typeahead would fix it but it didn't

this is my code again

```
$.typeahead({
    input: "#input_l01",
    order: "asc",
    maxItem: 50,
    minLength: 3,
    hint: true,
    backdrop: false,
    dynamic: true,
    display: ["t128straat", "t128gemeente"],
    template: function () {
        return '{{t128straat}}' + ', ' + '{{t128postcode}}' + ' ' + '{{t128gemeente}}' + ', ' + '{{t128land}}';
    },
    emptyTemplate: "geen resultaten gevonden voor {{query}}",

```

**Comment by running-coder** [comment]
I've re-tried and now sure as of why we do not have the same result, here is my experiment

city Anaheim(X)is the second filtering key
![screen shot 2016-05-12 at 12 40 22 pm](https://cloud.githubusercontent.com/assets/7377382/15222669/d9ab7260-183e-11e6-8f60-1f07ec4c5679.png)

I'm using `desc` in this example
![screen shot 2016-05-12 at 12 42 06 pm](https://cloud.githubusercontent.com/assets/7377382/15222703/fe763472-183e-11e6-8864-0947858f90c4.png)

![screen shot 2016-05-12 at 12 42 37 pm](https://cloud.githubusercontent.com/assets/7377382/15222719/0ad621c8-183f-11e6-9660-3efa15999f30.png)

**Comment by GDM70** [comment]
perhaps because I don't use group ?

**Comment by running-coder** [comment]
Tried w/o group option, options are sorted properly
