### ISSUE TITLE
Twice url encoding

### ISSUE THREAD

**Issue by ivan-ilinov** [running-coder/jquery-typeahead#189]
`source: {
    suggestion: {
        ajax: {
            url: 'path/suggestions',
            data: {
                key: '{{query}}'
            }
        }
    }
}`

Example.
I type "иван" and send request to "path/suggestions?key=%25D0%25B8%25D0%25B2%25D0%25B0%25D0%25BD".
But correct encoding is "%D0%B8%D0%B2%D0%B0%D0%BD".

**Comment by nop33** [comment]
Did you try using the built-in function `encodeURIComponent`?

**Comment by ivan-ilinov** [comment]
I didnt try using any URL encode/decode function.

**Comment by running-coder** [comment]
Hey Ivan, thanks for flagging the issue, I was indeed adding an extra encoding not knowing that the ajax object / browser request was already handling this.
