### ISSUE TITLE
Setting data result target

### ISSUE THREAD

**Issue by i7nvd** [running-coder/jquery-typeahead#19]
This is such a great library; extremely useful! Thanks for making it available.

Right now, the library creates a div called typeahead-results and typeahead-list, etc.

Is there a way to have the results instead target an existing div? If I have ul class="myList" 
can I say "instead of creating ul class="typeahead-list", push the results to ul class="myList"?

**Comment by running-coder** [comment]
Hey i7nvd,

thanks for the feedback! unfortunately for now you can only display the results in the predefined container just below the search input. You can modify the typeahead selector classes using options.selector (or perhaps that's something you are trying to accomplish?)

```javascript
$.typeahead({
    ...
    selector: {
        list: "my-list"
    }
})

```

**Comment by i7nvd** [comment]
Yes, saw selector, but indeed, I was trying to push results into an existing div that needs to be placed outside typeahead-container. Thanks for your prompt response, and please consider this an enhancement request :) :+1:
