### ISSUE TITLE
Strange JS-code fragment in href attribute value in result list

### ISSUE THREAD

**Issue by ivan-ilinov** [running-coder/jquery-typeahead#190]
My settings:

`{
    dynamic: true,
    display: 'suggestion',
    source: {
        suggestion: {
            ajax: {
                url: Drupal.settings.basePath + 'prlib_sf/suggestions?code=' + value.prlib_data.code + '&key={{query}}',
            }
        }
    }
}
`

I use last 2.6.0 version in master branch.

In result list i get JS fragment like this:
`<li class="typeahead__item"><a href="function () {&#10;                            if (_href) {&#10;                                if (typeof _href === &quot;string&quot;) {&#10;                                    _href = _href.replace(/\{\{([^\|}]+)(?:\|([^}]+))*}}/gi, function (match, index, options) {&#10;&#10;                                        var value = scope.helper.namespace(index, _item, 'get', '');&#10;&#10;                                        // #151 Slugify should be an option, not enforced&#10;                                        options = options &amp;&amp; options.split(&quot;|&quot;) || [];&#10;                                        if (~options.indexOf('slugify')) {&#10;                                            value = scope.helper.slugify.call(scope, value);&#10;                                        }&#10;&#10;                                        return value;&#10;                                    });&#10;                                } else if (typeof _href === &quot;function&quot;) {&#10;                                    _href = _href(_item);&#10;                                }&#10;                                _item.href = _href;&#10;                            }&#10;                            return _href || &quot;javascript:;&quot;;&#10;                        }" data-group="suggestion" data-index="1"><span class="typeahead__display"><strong>Иван</strong>ов Н.И. Николай <strong>Иван</strong>ович</span></a></li>`

Or (in minified version):
`<li class="typeahead__item"><a href="function (){return h&amp;&amp;(&quot;string&quot;==typeof h?h=h.replace(/\{\{([^\|}]+)(?:\|([^}]+))*}}/gi,function(t,e,i){var n=o.helper.namespace(e,l,&quot;get&quot;,&quot;&quot;);return i=i&amp;&amp;i.split(&quot;|&quot;)||[],~i.indexOf(&quot;slugify&quot;)&amp;&amp;(n=o.helper.slugify.call(o,n)),n}):&quot;function&quot;==typeof h&amp;&amp;(h=h(l)),l.href=h),h||&quot;javascript:;&quot;}" data-group="suggestion" data-index="2"><span class="typeahead__display">Кондря Т. И. Татьяна <strong>Иван</strong>овна</span></a></li>`

**Comment by ivan-ilinov** [comment]
I have this problem in jQuery ver. 1.8.3
In ver. 1.10.2 all works fine.

**Comment by kavin-90** [comment]
Everything is okay with using Jquery 2.2.3

**Comment by running-coder** [comment]
Hey Ivan, the Typeahead is supposed to support jQuery 1.7.2+, I'll double-check on this issue. Thanks

**Comment by running-coder** [comment]
Should be good now, thanks for reporting!
