### ISSUE TITLE
Add element if not existing

### ISSUE THREAD

**Issue by mctdi** [running-coder/jquery-typeahead#191]
hi

is there something who exist to add an element if the one the user type is not existing?

thanks

**Comment by nop33** [comment]
What do you mean exactly? Can you explain it with an example? By element I suppose you mean a `<li>` in the results container. What is this element supposed to contain/do?

**Comment by running-coder** [comment]
hey @mctdi, as @nop33 said we will need more details about what you are trying to achieve, is it editing the html or manipulating the search results before the html gets formatted. Please provide more details
