### ISSUE TITLE
Clicking on a suggested option does not select it on IE10/11

### ISSUE THREAD

**Issue by nop33** [running-coder/jquery-typeahead#193]
Hello,

When the typeahead is set to `searchOnFocus`, the aforementioned problem occurs on IE11 (11.0.9600.18282). It requires 2 clicks on the option you want to choose and one more outside in order to close the dropdown.
Here is a jsfiddle to reproduce it: http://jsfiddle.net/eyetea/ucjfo4ed/3/

![jsfiddle](https://cloud.githubusercontent.com/assets/1579899/14915590/7d2478fe-0e14-11e6-9892-cefdb67d441c.gif)

**Comment by running-coder** [comment]
Should be good now, the error was happening on all IEs

**Comment by nop33** [comment]
Hello and thanks for your quick response!
The problem is not completely fixed. The first problem remains. Clicking on a suggested option from the dropdown list will lead to showing the placeholder inside the input field (instead of the newly selected value). A second click on the suggested option will effectively choose it and close the dropdown.
Just by opening this jsfiddle in any IE will reproduce this issue: http://jsfiddle.net/eyetea/ucjfo4ed/3/
Thanks again!

**Comment by running-coder** [comment]
Thought it was fixed, I'll double-check as soon as I get some extra time

thx Ilias

**Comment by running-coder** [comment]
Found out IE11 is triggering `input` event if a placeholder is set which is causing the issue. Damnit IE...
https://connect.microsoft.com/IE/feedback/details/810538/ie-11-fires-input-event-on-focus

**Comment by nop33** [comment]
We all know how easier life would be if not for IE...

**Comment by nop33** [comment]
Any ideas for workarounds 😒 ? Apart from not using a placeholder...

**Comment by running-coder** [comment]
I started working on it the other day adding hacks all around and reverted everything cuz at some point it started to pollute the logic ... don't know for now :/

**Comment by dkaleky** [comment]
We    have an IE 11  issue. http://florida.com/iwannto    the drop down for cities  -- happens in 4 places on the website

**Comment by nop33** [comment]
You just posted a `404` page. What dropdown for cities are you talking about?

**Comment by dkaleky** [comment]
Sorry....  when you are here...     all drops  do not work properly


http://www.florida.com/questions
http://www.florida.com/i-want-to

https://goo.gl/LNtM7V
https://goo.gl/sfjPtG
https://goo.gl/cxMspC



 http://www.florida.com/business/business/add

**Comment by nop33** [comment]
Try to reproduce the problem in [jsfiddle](https://jsfiddle.net/). If it's still broken there, it's a bug of the library. If not, it's a bug in your website and has nothing to do with this issue.
Cheers!

**Comment by dkaleky** [comment]
you can't reproduce it in jsfiddle with Live data.... only dummy data...

**Comment by running-coder** [comment]
I'll give IE another round of testing and hopefully fix this issue without polluting Typeahead with workarounds. Do you have the placeholder issue @dkaleky or is it something else? I am unable to see the issue from the screenshots. Also I'll need your init config to reproduce.

**Comment by dkaleky** [comment]
Yes, @dkaleky is correct.  I need to ask my coders about the "init config", as I dont know what that is. 

Here is a video to show the issues. Eventually very quickly the browser freezes

https://goo.gl/rCniD6   give a few moments for it to show live.

**Comment by dkaleky** [comment]
Here is the Init config

http://pastebin.com/ngyQihF5

**Comment by running-coder** [comment]
Perf, I'll have a look as soon as possible, most likely this weekend unless one of you guys got some time to have a look and open a PR.

**Comment by dkaleky** [comment]
My guys  are too slow.

**Comment by nop33** [comment]
I am sorry, I can't help it but to respond!

Until this point you have not provided any hint as to what kind of issue you found at the library. Did you find something broken in the library's code? Essentially, that's what the Github issue tracker is for. For me it looks like the code your coders wrote is buggy, since your website doesn't even work on Chrome and I find it hard to believe that all of the errors are the library's fault! There is one problem that this issue refers to and that's the one of using placeholders in IE (which is proven to be an IE bug at the end and @running-coder is trying to find a workaround).

So, asking the developer and the community of a library to solve problems of your website's code seems not very right! It could be a thousand things that break the functionality of the search fields in your website, not necessarily the library itself. For example, there might even be other event handlers in the JS code that mess up with what Typeahead does. But that's not a Typeahead problem :smile: 

I hope I don't end up being misunderstood! I just believe that trying to find the error is more important that just reporting a general problem and leaving others find the error for you.

**Comment by running-coder** [comment]
@nop33 I was referring to the issue you also had at the beginning of the video [https://goo.gl/rCniD6](https://goo.gl/rCniD6) where the user clicks a suggestion but gets a blank result (IE placeholder). If there is something more to do I must have missed it.

**Comment by dkaleky** [comment]
@running-coder   the issue-- 

>  clicks a suggestion but gets a blank result

  When user clicks on the city DROPdown, one of 2 things happens, takes a couple clicks to drop, and clicking on city, will not fill in the drop field. 

  It all works well on ALL browsers on ALL os's, (mac, win10)  except as far as I can tell IE 11.~     (havent retested on less than IE 11~ )   Edge also works fine.

**Comment by dkaleky** [comment]
@nop33 
>  since your website doesn't even work on Chrome 

Well Chrome what? Checking now. Works on Mac. Havent seen windows issue.  

Thanks for the heads up!

**Comment by nop33** [comment]
@dkaleky try to click on the city field here: http://www.florida.com/i-want-to and navigate using the down arrow to Miami for example. Then press the `ENTER` key. It doesn't select Miami. Same for all the fields here: http://www.florida.com/questions

**Comment by dkaleky** [comment]
@nop33  I tried that on all browsers, and that is true issue for all. I never caught that. It is not major, and since it is true on all it is not you  but us.  However when there is a type ahead, enter does work
thanks though.  The major issue though IE 11 only

**Comment by hsdhott** [comment]
I am having a similar issue as @nop33. Typeahead works great in all browsers but in IE11. Only issue is, as @nop33 stated, it takes 2 clicks to get the option selected. First to get focus out of input, second for the selection. I've tried that removing placeholder from the input works great.  Please let us know if you've found a workaround? Thank you :)

**Comment by dkaleky** [comment]
Thanks @hsdhott for validating my concerns!   @running-coder  is  really responsive, so I hope it will get a quick fix!

**Comment by running-coder** [comment]
Let me know if this fix corrected the issue. (develop branch)

**Comment by hsdhott** [comment]
@running-coder Seems like issue has been fixed. It's working great for me. I appreciate your help and thank you for your quick response. :+1:

**Comment by hsdhott** [comment]
Will this fix be coming in the next release? Right now I added the fix in my local js file but it will be great to have it in the library's minified files.

**Comment by running-coder** [comment]
@hsdhott Yes, it's part of the 2.7.0 milestone, I only have a few issues left to resolve before releasing it. You can also use the minified file from this commit, it also contains the fix.

As a side-note (some people might not be aware) If you are using bower or npm you can always specify a commit hash instead of the tag version to have the fix when you are pulling / building your assets so you don't have to wait for the next tag to be created.
