### ISSUE TITLE
code fails after updating from version 2.3.4 -> 2.6.1

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#194]
Hi, 

My Typeahead code fails after updating from 2.3.4 to 2.6.1
How can i fix it ?

This is my code

$.typeahead({
        input: "#input_l01",
        order: "asc",
        maxItem: 50,
        minLength: 3,
        hint: true,
        backdrop: false,
        dynamic: true,
        display: ["t128straat"],
        template: function () {
            return '{{t128straat}}' + ', ' + '{{t128postcode}}' + '  ' + '{{t128gemeente}}' + ', ' + '{{t128land}}';
        },
        emptyTemplate: "geen resultaten gevonden voor {{query}}",
        source: {
            straten: {
                url: [{
                        type: "GET",
                        url: "/vf/rest/straten/search?",
                        data: {
                            q: "{{query}}"
                        }
                    }, "waarden"]
            }
        },
        callback: {
            onNavigateAfter: function (node, query, event) {
                if (~[38, 40].indexOf(event.keyCode)) {
                    var resultList = node.closest("form").find("ul.typeahead-list"),
                            listItem = resultList.find("li.typeahead-item"),
                            activeListItem = listItem.filter(".active"),
                            offsetTop = activeListItem[0] && activeListItem[0].offsetTop - (resultList.height() / 2) || 0;

                    resultList.scrollTop(offsetTop);
                }
            },
            onClickAfter: function (node, a, item, event, data) {
                
                node.val(item.t128straat);
                
                vm.klant.t118straat = item.t128straat;
                vm.klant.t118postcode = item.t128postcode;
                vm.klant.t118gemeente = item.t128gemeente;
                vm.klant.t118land = item.t128land;
                                                
            }

        }
    });

**Comment by running-coder** [comment]
Hey you can take a look at the changes [here](http://www.runningcoder.org/jquerytypeahead/version/)

After updating your html to something like:

``` html
<form>
    <div class="typeahead__container">
        <div class="typeahead__field">
 
            <span class="typeahead__query">
                <input class="js-typeahead"
                       name="q"
                       type="search"
                       autocomplete="off">
            </span>
            <span class="typeahead__button">
                <button type="submit">
                    <span class="typeahead__search-icon"></span>
                </button>
            </span>
 
        </div>
    </div>
</form>
```

Your init should look like:

``` javascript
$.typeahead({
    input: "#input_l01",
    order: "asc",
    maxItem: 50,
    minLength: 3,
    hint: true,
    backdrop: false,
    dynamic: true,
    display: ["t128straat"],
    template: function () {
        return '{{t128straat}}' + ', ' + '{{t128postcode}}' + ' ' + '{{t128gemeente}}' + ', ' + '{{t128land}}';
    },
    emptyTemplate: "geen resultaten gevonden voor {{query}}",
    source: {
        straten: {
            // Ajax key instead of url
            ajax: {
                type: "GET",
                // Your object path inside the response
                path: "waarden",
                url: "/vf/rest/straten/search?",
                data: {
                    q: "{{query}}"
                }
            }
        }
    },
    callback: {
        // Updated onNavigateAfter
        onNavigateAfter: function (node, lis, a, item, query, event) {
            if (~[38,40].indexOf(event.keyCode)) {
                var resultList = node.closest("form").find("ul.typeahead__list"),
                    activeLi = lis.filter("li.active"),
                    offsetTop = activeLi[0] && activeLi[0].offsetTop - (resultList.height() / 2) || 0;

                resultList.scrollTop(offsetTop);
            }
        },
        onClickAfter: function (node, a, item, event, data) {

            node.val(item.t128straat);

            vm.klant.t118straat = item.t128straat;
            vm.klant.t118postcode = item.t128postcode;
            vm.klant.t118gemeente = item.t128gemeente;
            vm.klant.t118land = item.t128land;

        }

    }
});
```

**Comment by GDM70** [comment]
ok thanks, it works again :-)

**Comment by running-coder** [comment]
cool, np
