### ISSUE TITLE
onCancel callback

### ISSUE THREAD

**Issue by text3** [running-coder/jquery-typeahead#195]
:+1:

**Comment by running-coder** [comment]
hey,

which use-case would you need an onCancel event for?

**Comment by text3** [comment]
I use TypeAhead to filter bills by customers sometimes I want to cancel the filter and restore the original status...
:+1:

**Comment by rtack** [comment]
my use case is to show/hide another dropdown depending on they type of selection in the typeahead. When the input field is empty I have to hide two elements.

I've added an input event listener on the input field but that doesn't get triggered if the ESC key is used or the cancel button clicked.

**Comment by running-coder** [comment]
@rtack Perhaps you can try the `onSearch` callback? This one gets triggered every time the input changes

**Comment by rtack** [comment]
@running-coder Thanks. The onSearch callback works perfectly for what I need to do.
ps http://www.runningcoder.org/ is offline

**Comment by running-coder** [comment]
@rtack Thanks for letting me know, had to pay the bill hehe, should be back up within a couple hours

**Comment by running-coder** [comment]
I've added the `onCancel` callback that gets triggered when there was text in the input and the text gets cleared (esc, ctrl+x, backspace, etc.) You can detect from which event the text got cleared if you need a specific action to happen depending on which case.

```javascript
callback: {
    onCancel: function (node, event) {
        console.log(event.originalEvent)
    }
},
```

Let me know if there is anything.
