### ISSUE TITLE
Using an async function as a data source

### ISSUE THREAD

**Issue by rcarickhoff** [running-coder/jquery-typeahead#198]
I have a requirement to use a dynamic data source from a web service that is fairly complicated (not a REST API).  I am trying to use a function as a data source so I have a hook to make a call to the service for data.  I see the source.data documentation says it can be an array or function that returns an array but am unable to get the function that returns an array to work.  

Question 1: Is this supported and if so is there an example or some documentation on how to get it to work?

Question 2: Is there a better way to get to get a dynamic data source working without using the ajax option on the source object?

**Comment by rcarickhoff** [comment]
One other comment on this... Found this thread discussing this concern.  https://github.com/running-coder/jquery-typeahead/issues/13

A common async implementation for providing data is to pass in a callback that the custom data function calls when data is ready.  I was hoping this is what the documentation is suggesting when it says a function is supported.

**Comment by running-coder** [comment]
Hey, the `data` parameter only support synchronous data atm through an array or function as you noticed while `ajax` allows asynchronous. As an example, which transport would you use inside an asynchronous `data` param?

**Comment by rcarickhoff** [comment]
I have a few objects that wrap ajax calls to get data.  Each exposes the same method that can be called to get different types of data.  I would like to use this layer with typeahead.  So ideally there is an abstraction between the typeahead plugin and ajax calls for data.  I guess this would be similar to Twitter's Bloodhound.  Basically, the typeahead plugin works with a class that can have different implementations of remote data access as long as the the same inputs and outputs are implemented.  An async data function would be a simpler way to get this same functionality.  Any thoughts on how I may be able to implement this?

**Comment by running-coder** [comment]
Sure, totally makes sense to be able to use other ways of getting the data. If you wanna take a shot at it feel free to open a PR, or I'll see what I can do in a couple of days.

Thanks!

**Comment by rcarickhoff** [comment]
Sounds good, thanks.  It would be much faster for you to add it if you have the time but if you can't get to it, I can take a crack at it.  I am thinking just allowing something like function(query, callback) to be set on the data property or something similar for dynamic use.

**Comment by running-coder** [comment]
Sorry it took quite some time @rcarickhoff @samlanning.

The feature is now in the `develop` branch waiting for the rest of the `2.7.0` features before it's merged to master

You can now use the `source.group.data` option as an async object to gather your data in any way possible. The only requirement is to create a [`$.Deferred` jquery object](https://api.jquery.com/category/deferred-object/) and return it

```javascript
source: {
    teams: {
        data: function () {

            var deferred = $.Deferred();

            // Gather your data, and resolve the deferred object with an array of objects
            // setTimeout is used only to show that the data is async, received after 2 seconds in my demo
            setTimeout(function () {
                deferred.resolve(data)
            }, 2000);

            deferred.always(function () {
                console.log('yay! :D')
            });

            return deferred;
        }
    }
},
```

Let me know if you have any question / issues

Thanks!

**Comment by RohiniJindam** [comment]
Can you please share your thoughts on how I can access the query parameter inside the data function?

**Comment by running-coder** [comment]
@RohiniJindam `this.query` should be accessible from any function set in your initialization object

```javascript
source: {
  group: {
    data: function () {
      console.log(this.query);
    }
  }
}
```
