### ISSUE TITLE
Cannot disable cancelButton

### ISSUE THREAD

**Issue by AndreasScheffczyk** [running-coder/jquery-typeahead#199]
Hello Running Coder-Team,

first of all thank you for this great plugin.

I am using the latest version 2.6.1 and want to disable the cancelButton. In your documentation it is mentioned, that I could do this by the setting the option **cancelButton** to **false**. But for me that doesn't have an effect. Am I doing something wrong or is this maybe a bug?

Also, for the case that I would like to style the cancelButton instead of disabling it, could you help me where and how to style this button? I searched everywhere in the dev tools, but couldn't find where the element is inserted and where the styling is applied.

Regards, Andreas

**Comment by running-coder** [comment]
Hey Andreas, this should do the trick to disable the cancel button, you can also check [game_v2 demo](http://www.runningcoder.org/jquerytypeahead/demo/#form-game_v2)

``` javascript
$.typeahead({
    input: '.js-typeahead-game_v2',
    minLength: 1,
    maxItem: false,
    cancelButton: false,
    ...
});
```

for styling the button, you can check [the scss classes](https://github.com/running-coder/jquery-typeahead/blob/f6625287e897cc0256cbe5a062c8a565f46d55b1/src/jquery.typeahead.scss#L426) and override the one you need #196 

``` css
/* typeaheadOverride.css */
.myTypeahead .typeahead__cancel-button {
   top: 10px;
   right: 10px;
}
```

**Comment by AndreasScheffczyk** [comment]
Thank you for the quick answer.

I feel kinda stupid, because I now realized, that the cancelButton was indeed disabled the whole time. The cancel-button I saw, was of Chrome itself. I didn't knew about this Chrome-feature up until now.

Sorry for the trouble. ;-)

**Comment by running-coder** [comment]
np, this option was added because `input[type="search"]` doesn't behave the same or is missing through the different browsers. This option simply ensure Typeahead is the same across the board.
