### ISSUE TITLE
Partial search inside specific sources using `:` prefix, Ex ":users"

### ISSUE THREAD

**Issue by elegos** [running-coder/jquery-typeahead#201]
Hello! I'm trying out this plugin and so far, so good. I have a question though: is it possible to disable an ajax source depending on the query string?

The idea is to let the user search for users only if the query string contains "user:whatever". I've tried using a function as per ajax parameter, setting the return's url to false, null, the entire return to null, false, whatever.... but Typeahead just stops working... My workaround is to set the data's query to an empty string, but still the call is fired and I don't like it.

Any hint?

Thanks :+1:

**Comment by running-coder** [comment]
Hey elegos,

perhaps this would work for your implementation, try using the `onSendRequest` callback which allows to cancel requests by returning `false` [here](https://github.com/running-coder/jquery-typeahead/blob/b0869002f4c202719f54b165ba211b3cdfe89608/src/jquery.typeahead.js#L833)

```javascript
$.typeahead({
    input: '.js-typeahead',
    source: '...',
    ...
    callback: {
        onSendRequest: function (node, query) {
            if (this.query.substr(-5) !== "user:") {
                return false;
            }
        }
    }
}
```

**Comment by elegos** [comment]
Thanks, that's perfect :)

**Comment by running-coder** [comment]
I did not think of this when building the Typeahead but it would indeed be great if there was the possibility to perform some kind of partial matching based on keywords and not only a full string match like your example.

`something :user more text :anothersearchkey`

If you want "per source" results, your best bet would be to use the `matcher` source function to look into the query and return undefined for the sources you with to skip
