### ISSUE TITLE
xhr php jason search stops after one word

### ISSUE THREAD

**Issue by ariedeleen** [running-coder/jquery-typeahead#202]
Is it possible te seach for "fruit apple", "ipad apple"

Data to collect via xhr, ajax like search.php?q=fruit%20apple
But it stopt after fruit when typed in, in the input field.
So how to search for the second word. Fruit and apple combined.

I use sphinx search to collect relevant data via ajax, xhr in json format. Key value.

**Comment by running-coder** [comment]
Hey,

yes the search is very flexible, only depends how you set your Typeahead options. If "fruit" and "apple" are on different object keys you need to specify them inside the `display` option. Also you can match any string part in any order using the `correlativeTemplate` option.

Dig some more inside the doc and the demos, you should be able to find what you are looking for. LMK if you have more questions.

**Comment by ariedeleen** [comment]
Thanx for the responce, i'll look into it. RTFM ;-)
