### ISSUE TITLE
How to continue gracefully after an error from an ajax request (e.g. 404 from the server)?

### ISSUE THREAD

**Issue by epitomus** [running-coder/jquery-typeahead#203]
I am having a problem handling errors from callbacks. I can get the fail() callback to run fine, however I want to simply acknowledge the errors and continue. The following shows what I'm trying to achieve (note, I'm running with ```dynamic: true```):
```javascript
    source: {
        groupName: {
            href: "/{{type}}/{{id}}",
            ajax: {
                url: '/search/{{query}}',
                callback: {
                    fail: function(jqXHR, textStatus, errorThrown) {
                        # set the message in the dropdown to "An error has occurred, try again later!"
                        # continue on and do not show any errors in the console
                    }
                }
            }
        }
    }
```

The problem is that I can't see how to make this happen - there's always a jquery error in the console, no way to populate the drop-down, and the search spinner will never go away.

Thanks

**Comment by running-coder** [comment]
Hey, I don't believe there is way to get around the error message in the console unless there is try/catch surrounding the request and even then... I'm pretty sure you can do manual operations in the fail callback to inject your error message in the dropdown and hide the loading anim.

```javascript
this.resultContainer.html('<ul><li>"An error has occurred, try again later!"</li></ul>');
```

let me try on my side I'll need to re-scope the fail function to be using `this` properly as the root Typeahead class

**Comment by running-coder** [comment]
You should now be able to view some results
