### ISSUE TITLE
It started with an /S

### ISSUE THREAD

**Issue by ariedeleen** [running-coder/jquery-typeahead#204]
404 picture not found
If the name of the picture file starts with a S (uppercase s) after a slash then somehow
it get 'parsed' to /images/manufacturers/%3Cstrong%Samsung%3C/strong%3Elogo.jpg or (Not Found)
/images/manufacturers/%3Cstrong%3ESeagate%3C/strong%3Elogo.jpg 404 (Not Found)

the /S will translate to a strong open en closing tag

template: '<span>' +
'<div><img src="./../images/' + '{{picpath}}"></div>' +
'</span>',
correlativeTemplate: true,

**Comment by kavin-90** [comment]
i got that error but its related to display[]

**Comment by running-coder** [comment]
hey, perhaps the documentation was not clear so here is the explaination. When using the `highlight: true` option (default) all of the `display` keys are searched and modified with the <strong> tag if any match occured. It is possible when printing your template to specify that you do not want these <strong> tags using `{{myDisplayKey|raw}}`.

**Comment by ariedeleen** [comment]
Ok, thanx this enlightens the behavior. 
This is one of the most comprehensive typeahead plugins ever worked with.
