### ISSUE TITLE
Reload ajax source?

### ISSUE THREAD

**Issue by ichuot** [running-coder/jquery-typeahead#205]
How to reload ajax source without refresh page or enable `dynamic`??

**Comment by ariedeleen** [comment]
Hi, thats the beauty, the essense of ajax/xhr.  To do not have to reload/refresh the whole page.
Can you give example code,  so to examine it and find out where it goes wrong.

**Comment by kavin-90** [comment]
Looking forward to it.

**Comment by running-coder** [comment]
Hi ichuot, there were several request a while back to be able to replace Typeahead's source based on condition. Example having 2 inputs where the first correspond to a country and the second corresponds to a state. On selecting a country you would like to update the state list of the second input therefore changing the source. 

Another way to approach the problem and is already available for you to use is the `matcher` source function. So let's say your source for the second input looks like this:

```json
// country.json
[{
    country: 'united-states'
}, {
    country: 'canada'
}]

// state.json
// List all states with a country attached to validate in the matcher function
[{
    country: 'united-states',
    state: 'new-york'
}, {
    country: 'canada',
    state: 'quebec'
}]
```
```javascript
$.typeahead({
    input: '.js-typeahead-country',
    source: {
        country: {
            data: country
        }
    }
});

$.typeahead({
    input: '.js-typeahead-state',
    source: {
        state: {
            data: states,
            matcher: function (item, displayKey) {
                // Check for a selected country if the first Typeahead
                if (!Typeahead['.js-typeahead-country'].item || item.country !== Typeahead['.js-typeahead-country'].item) return;
                
                // If the searched item's country matches the selected country, display the item in the search list
                return true;
            }
        }
    }
});
```
