### ISSUE TITLE
Mutliple Search Boxes Generated From JavaScript Loop

### ISSUE THREAD

**Issue by skiotterjeffa** [running-coder/jquery-typeahead#207]
I have multiple search boxes on a page. They are dynamically created by a JavaScript loop, which assigns a unique id to each search field. That is used as the selector. What is the syntax for initializing typeahead so that the result list appears below the search box that has the current focus?  Right now, regardless of which field has focus, the search results appear under the search field that was rendered first.  When an option is selected, the value is placed in every search field as well, not just the one which has focus.

I've looked at the examples, and can't find one where multiple search boxes are used.

This is the code as it sits now:

	    var tf = "#searchField" + participant.get('id');
		
		$(tf).typeahead({
	   
	    order: "asc",
	    minLength: 1,
	    display: "fullname",
	    source: {
	       // Ajax Request
	       ajax: {
	            url: "/api/nmfocontacts",
	            dataType: "json"
	            //path: "fullname"
	        }
	        
	    }
	});

Thank you.
Great plug-in.

**Comment by skiotterjeffa** [comment]
It appears the selector option is what I need. Apologies for not looking at the documentation more closely.

**Comment by running-coder** [comment]
Hey skiotterjeffa, thanks for using Typeahead and for the feedback! if you enter your console and type "Typeahead" you should get the list of your instances. Make sure you have 1 init per selector and ideally use the recommended init `input: ".your-input-selector"` so it works with the different jQuery versions.

![2016-06-02_1252](https://cloud.githubusercontent.com/assets/7377382/15753473/2c0a7b4a-28c1-11e6-9c7a-40249e4b9b0c.png)

**Comment by skiotterjeffa** [comment]
Thanks. Knowing that was there helped locate the problem, which was that the fields weren't in the DOM yet apparently, when I was initializing Typeahead. Once I moved that line, things started working. I was also concerned that the rest of the required HTML structure would be a problem, but they are not.  That's what I thought I was fighting.

**Comment by adcockcarl** [comment]
It looks like the onClick bind if broken when creating multiple search bars unless dynamic is set to true.  And then it works every other click.  Thoughts?
