### ISSUE TITLE
No distinction between "click" and "enter" selection in onClick callbacks

### ISSUE THREAD

**Issue by bornytm** [running-coder/jquery-typeahead#208]
When onClick callbacks are called, `event.which` is equal to 1 even if the item is selected from the dropdown with the enter key.

**Comment by running-coder** [comment]
Right... because the `enter` key triggers the click event. Do you know if `event.which` is a readonly property? I haven't investigated yet but indeed could set `13` if possible.

**Comment by running-coder** [comment]
I've added the "enter" event inside e.originalEvent for you to manipulate / distinguish the click event

in your code you can now do something like
```javascript
if (e.originalEvent && e.originalEvent.keyCode === 13) {
    console.log('Enter pressed!')
}
```
