### ISSUE TITLE
Removing All option in the dropdownFilter

### ISSUE THREAD

**Issue by cris-barredo** [running-coder/jquery-typeahead#209]
Hi - Is there an option to not show the default "all" selection in the dropdownfilter?

**Comment by running-coder** [comment]
hey cris,

the `dropdownFilter` option has no way of not including the all selection (not sure why you would not like to go back to selecting all your results). What is currently possible to do is use css to target the element and `display:none;` on the element.

`.group-all-bears { display: none; }`
![screen shot 2016-06-13 at 9 49 38 am](https://cloud.githubusercontent.com/assets/7377382/16009841/6cf30c92-314c-11e6-9af0-b2d962083d6f.png)
