### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by agasoftadmin** [running-coder/jquery-typeahead#21]
i wish to populate 2 inputs , something like countries and states, where after the country is selected, it populates the states, and when that state is selected, i get the id of the state and the country. 

i am able to get one working , tried to put the second one on the callback of the first one, with the result, but something is missing, 

just cant get it working.

help would be appreciated.

(wish to add that i am complete new to github and my level in javascript is basic)
regards

**Comment by running-coder** [comment]
hi agasoftadmin,

currently there is no support in the typeahead to modify (or filter) a list of data based on an external value. However it seems a good idea for improvement!

For now you can use the onClick callback function to manually modify the data of your second instance.

```javascript
typeof $.typeahead === 'function' && $.typeahead({
    ...
    source: {
        country: ['/json/list/country/', 'data'],
    },
    callback: {
        onClick: function (node, a, obj, e) {
            e.preventDefault();
            // Destroy & rebuild second Typeahead instance with filtered data
        }
    }
});
```

I will try to think of a more straight-forward implementation inside the Typeahead itself for the next version.

**Comment by marccollin** [comment]
i do a similar thing but with car and model.


```
        $('#brand').typeahead({
            minLength: 2,
            source: {
                brand: {
                    display: "brand",
                    url: {
                        type: 'GET',
                        url: '/brands'
                    }
                }
            },
            callback: {
                onClick: function (node, a, item, event) {

                    console.log('onClick function triggered');
                    $('#brandId').val(item.brandId);
                    $('#model').typeahead({
                        minLength: 0,
                        source: {
                            model: {
                                display: "model",
                                url: {
                                    type: 'GET',
                                    url: '/brands/' + item.brandId + '/models'
                                }
                            }
                        },
                        callback: {
                            onClick: function (node, a, item, event) {
                                $('#modelId').val(item.modelId);
                            }
                        }
                    });

                }
            }
        });
```

**Comment by running-coder** [comment]
Please use the new matcher function, unfortunately Typeahead will not support dynamic source switching.
