### ISSUE TITLE
Allow scss customization via !default 

### ISSUE THREAD

**Issue by rtack** [running-coder/jquery-typeahead#213]
At the moment it's not possible to get rid of the radius without changing the jquery.typeahead.scss file.

If 
$typeahead-radius: 2px;
was written as
$typeahead-radius: 2px !default;

it would be easy to override that. See https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss and https://robots.thoughtbot.com/sass-default for why it's useful.

I could provide a PR.

**Comment by running-coder** [comment]
Hey, indeed the variables should be declared as defaults so it is possible for you to declare them from inside your code.

will change that, thanks for raising the issue
