### ISSUE TITLE
"main" property in bower.json

### ISSUE THREAD

**Issue by shimikano** [running-coder/jquery-typeahead#215]
Shouldn't `bower.json` have

```json
"main": ["dist/jquery.typeahead.min.js", "dist/jquery.typeahead.min.css"]
```

instead of

```json
"main": "jquery.typeahead.min.js"
```

?

Tools such as [wiredep](https://github.com/taptapship/wiredep#what-can-go-wrong) rely on proper file paths specified in the `main` property. Moreover, the CSS file may be included to.

**Comment by running-coder** [comment]
Hey, indeed the bower file was not modified as the project evolved. Thanks for pointing it out!
