### ISSUE TITLE
Any option for invalid data

### ISSUE THREAD

**Issue by mctdi** [running-coder/jquery-typeahead#216]
hi

if user type any information who don't exist, are there any option for that?

thanks

**Comment by kavin-90** [comment]
did you mean by empty template?

**Comment by mctdi** [comment]
if in the data we have: New York, Boston, Florida and It type Chrismas... I would like to do something to said to the user, this entry is not existing...

**Comment by kavin-90** [comment]
that what empty template does.

**Comment by running-coder** [comment]
As @kavin-90 suggested you can use the `emptyTemplate` and pass it a string or a function that returns a string. In complement, you can also use the `onResult (node, query, result, resultCount, resultCountPerGroup)` callback and verify the result Array if empty and query not empty

```javascript
callback: {
    onResult: function () {
        if (query !== "" && !result.length) {
            // text is typed and result is empty
        }
    }
}
```

**Comment by mctdi** [comment]
ok thanks after some try, need to add more security.

is there something for manage this case

Data are


Mountain
Mouse
Mount
Mercier
Mess

if the user type only mou

onresult will return  3 but mou is not a complete word... it's only a part of a word it's there a way to know if it a full word of the data?

**Comment by running-coder** [comment]
you can implement a similar custom check using the `options.source.group.filter` option. For example:

```javascript
source: {
  teams: {
    data: ["Mountain", "Mouse", "Mount", "Mercier", "Mess"],
    filter: function (item, displayValue) {
        if (this.query.toLowerCase() !== displayValue.toLowerCase()) return;
        return true;
// return undefined to skip to next item
// return false to attempt the matching function on the next displayKey
// return true to add the item to the result list
// return item object to modify the item and add it to the result list
    }
  }
}
```

**Comment by mctdi** [comment]
don't really do the job.

if it type, mou, i see nothing... need to type all the word...

i use a ajax call to save data so, mustSelectItem: true don't work.

i think i would like to add an event when input will lost focus

**Comment by running-coder** [comment]
thought you were looking for a solution for exact text match, you can play around with the matcher function and try different stuff. `mustSelectIem` will not let you submit the form unless you clicked an item from the list

**Comment by mctdi** [comment]
i don't really use a submit, 

jQuery.ajax... it's in that case useless for mustSelectItem.
