### ISSUE TITLE
Catch cancel button click

### ISSUE THREAD

**Issue by s-friscia** [running-coder/jquery-typeahead#219]
Hi,
There is the possibility to catch cancel botton click? I tried with this

`$(document).on('click', '.typeahead__cancel-button', function () {
     console.log('cancel click');
});` 

but it doesn't work. Any ideas?

Any way thanks for the library, it's very usefull :)

**Comment by running-coder** [comment]
hey! You can start using the [onCancel callback](https://github.com/running-coder/jquery-typeahead/issues/195) callback in the develop branch and look for a click event inside the event.originalEvent

**Comment by running-coder** [comment]
The `click` event doesn't get called because the cancel button gets hidden on `mousedown`, using the `onCancel` callback will solve your issue.

```javascript
callback: {
    onCancel: function (node, event) {
        if (event.originalEvent.type === "mousedown") {
            console.log('cancel clicked! :D')
        }
    }
}
```

**Comment by s-friscia** [comment]
Thank for the answer.
Cheers
