### ISSUE TITLE
On form reset, input field clears but the value persists.

### ISSUE THREAD

**Issue by hsdhott** [running-coder/jquery-typeahead#221]
As you can see in the gif below that when reset button is clicked the input field clears but the previously selected option persists. Only way to clear the previously selected option is to press **esc** when input is in focus.

Here is the jsfiddle to reproduce it: https://jsfiddle.net/hsdhott/k2zo2n5t/

![query typeahead - jsfiddle20160803133408](https://cloud.githubusercontent.com/assets/8837658/17381120/395e4170-597f-11e6-981e-5f4610b66d0d.gif)

**Comment by running-coder** [comment]
hey, thanks for pointing it out. Indeed the Typeahead's input `input` event does not get triggered from the reset button. Might have to trigger a manual event in that case.

**Comment by running-coder** [comment]
Should fix the issue.

**Comment by hsdhott** [comment]
Hi @running-coder 
Sorry, for late reply, I've been out and didn't get to test this out until now. It is working great, but I've noticed that when we click reset, the dropdown opens up with (when searchOnFocus: true).

Additionally, this is for support I believe. When we use Javscript to empty the typeahead input filed. Is there a way to reset the dropdown list as well?
Behavior (searchOnFocus: true): 
- if the dropdown list includes ["Afghanistan", "Albania", "Algeria", "Andorra"]
- Type "af" in the input filed so that Afghanistan is the first choice. Then use js to remove text from input field
- Going back to the typeahead, when click inside the filed dropdown only shows Afghanistan

Let me know if you have any questions, I can create a jsfiddle.

Thank you for your help again.

**Comment by running-coder** [comment]
after changing Typeahead's input value via script you simply need to trigger a "search event" using the `input` event.

inside the documentation in the Extras section you should be able to see `$('#mySearchInput').trigger('input.typeahead');`

so in your usecase it should be `$('#mySearchInput').val('').trigger('input.typeahead');`
