### ISSUE TITLE
having trouble adapting demo to real use case with postcode service

### ISSUE THREAD

**Issue by trevorclarke** [running-coder/jquery-typeahead#223]
Hi,

I'm using the typeahead to call a php postcode service and then returns the first level matches with their id values.
So that then the selected postcode/address can be retrieved from those results and applied to the form.

Almost their on the first part via adapting the user_v1 demo but not quite, The json result is returned in network panel e.g.

PHP service side returns: when query is BH8 8PJ
{"status":true,"error":null,
"data":
	{"postcodes":
		[
		{"id":"GBR|1809033","postcode":"BH8 8PJ, xyz Malmesbury Park Road, Bournemouth ","description":""},
etc, etc

PHP client side code:
[user2.txt](https://github.com/running-coder/jquery-typeahead/files/409222/user2.txt)

But it says no results on the page although in the console I can log out the data of the addresses/
I'm happy to donate/pay for some assistance as I'm obviously missing some key aspect.

**Comment by running-coder** [comment]
can you paste your Typeahead config as well?

**Comment by trevorclarke** [comment]
I think this is what you want: live test code is:
http://chittak.co.uk/test/postcode/postcode2.php

Cut down version from userv1 demo:
http://chittak.co.uk/test/postcode/user2.php

<script>
$(document).ready(function () 
{
$.typeahead({
    input: '.js-typeahead-user_v1',
    minLength: 1,
    order: "asc",
    dynamic: true,
	cache: false,  
    delay: 500,
    backdrop: {
        "background-color": "#fff"
    },
    template: function (query, item) {
		
		//alert("in template");
		console.log('Item:'+item.username);
        var color = "#777";
        if (item.status === "owner") {
            color = "#ff1493";
        }
 
        return '<span class="row">' +
            '<span class="avatar">' +
                
            '</span>' +
            '<span class="username">{{username}} <small style="color: ' + color + ';">({{status}})</small></span>' +
            '<span class="id">({{id}})</span>' +
        "</span>"
    },
    emptyTemplate: "no result for {{query}}",
    source: {
        postcoderow: {
            display: "username",
            href: "https://www.github.com/{{username|slugify}}",

            ajax: function (query) {
                return {
                    type: "GET",
                    url: "/test/postcode/user23json.php",
                    path: "data.user",
                    data: {
                        q: "{{query}}"
                    },
                    callback: {
                        done: function (data) {
							
							//alert(JSON.stringify(data));
							//alert(JSON.stringify(data.data));
							
							/*
                            for (var i = 0; i < data.data.postcodes.length; i++) {
								
								
								console.log(data.data.postcodes[i].username);
                              
							  if (data.data.postcodes[i].username === 'running-coder') {
                                    data.data.postcodes[i].status = 'owner';
                                } else {
                                    data.data.postcodes[i].status = 'contributor';
                                }
                            }
							*/
							alert(JSON.stringify(data));
                            return data;
                        }
                    }
                }
            }
			
			
 
        }
        
    },
    callback: {
        onClick: function (node, a, item, event) {
 
            // You can do a simple window.location of the item.href
            alert(JSON.stringify(item));
 
        },
        onSendRequest: function (node, query) {
            console.log('request is sent')
        },
        onReceiveRequest: function (node, query) {
            console.log('request is received')
        }
    },
    debug: true
});
});
</script>

**Comment by running-coder** [comment]
you are only missing the `display` option :)

```javascript
display: ['postcode']
```

**Comment by trevorclarke** [comment]
Thanks for your quick reply. I'm not sure if I'm running into caching in browser or just looking at it too long, 
I've tried your suggestion in a few places/combinations without joy so far, I also tried 'postcodes' as that is the outer value in the data returned.

http://chittak.co.uk/test/postcode/postcode2.php
search term in first input box: bh88pj

The ajax query return values can be seen via: http://chittak.co.uk/test/postcode/postcode_lookup2.php?q=bh88pj
 e.g. "data":{"postcodes":[{"id":"GBR|1809033","postcode":"BH8 8PJ, 7, 

All the 40 answers are being output to the console log now.

$.typeahead({
    input: '#postcodesearch',
    debug: true,
    minLength: 4,
    order: "asc",
    dynamic: true,
    delay: 500,
    cache: false,
    backdrop: {
        "background-color": "#fff"
    },
   template: function (query, item) {
	//alert("in template");
        var color = "#777";
 
        return '<span class="row">' +
            '<span class="avatar">' +
            "</span>" +
            '<span class="postcode">{{postcode}} <small style="color: ' + color + ';">({{status}})</small></span>' +
            '<span class="id">({{id}})</span>' +
        "</span>"
    },
    emptyTemplate: "no result for {{query}}",
    display: ['postcode'],
    source: {
        postcodes: {
            //display: "username",
	   //display: "postcodes",
            // href: "postcode_lookup.php",
            ajax: function (query) {
                return {
                    type: "GET",
			url: "/test/postcode/postcode_lookup2.php",
                    path: "data.postcodes",
                    data: {
                        q: "{{query}}"
                    }
		/* */
					,
                    //display: ['postcode'],
					
		callback: {
                        done: function (data) {	
				console.log('data:'+data);
				console.log('data2:'+data.data);
				console.log('data length:'+data.data.postcodes.length);
				alert(JSON.stringify(data.data));
							
                            for (var i = 0; i < data.data.postcodes.length; i++) {
                                if (data.data.postcodes[i].id.length > 4) {
				// A postcode with a searchable id has been found
                                    //data.data.postcodes[i].status = 'owner';
				console.log('data record:'+data.data.postcodes[i].id+'Suggestion:'+data.data.postcodes[i].postcode);
                                } else {
                                    data.data.postcodes[i].status = 'contributor';
                                }
                            }
                            return data;
                        }
                    }
					
                }
            }
	,template: '<span>' +
                '<span class="project-logo">' +
                    '<img src="/">' +
                '</span>' +
                '<span class="project-information">' +
                    '<span class="project">{{id}} <small>{{postcode}}</small></span>' +
                '</span>' +
            '</span>'
        }
    },
    callback: {
        onClick: function (node, a, item, event) {
 
            console.log(node)
            console.log(a)
            console.log(item)
            console.log(event)
            console.log('onClick function triggered');
			
	    // You can do a simple window.location of the item.href
            alert(JSON.stringify(item));
        },
        onSendRequest: function (node, query) {
            console.log('request is sent')
        },
        onReceiveRequest: function (node, query) {
            console.log('request is received')
        }
    }
	});

**Comment by running-coder** [comment]
k so a couple things:
- You have 2 templates defined for 1 source? lets clean that up
- entering "bh8 8pj" gives you results but "bh88pj" is empty because Typeahead didn't EXACT match. If you already filter results through the backend, use `filter:false` on your group (read documentation for more details on that option)
```javascript
source: {
        postcodes: {
            display: ['postcode'],
            filter: false,
            ajax: function (query) {
```
-

**Comment by trevorclarke** [comment]
Great, got that working now and increased the display results to 50.Now just need to call the final answer from the 2nd web service in the onClick handler which I have alerting the id value need. So I guess it will be a standard bit of jQuery ajax call there something like thiscallback: {        onClick: function (node, a, item, event) {             alert('Item id to retrieve data from 2nd webservice:'+item.id);              $.ajax({                    method: "POST",                    url: "url-to-service-yet-to-be-created",                    data: { id:  item.id},                    cache: false        })          .done(function( data ) {                // update web form with address1, 2 etc individual values          });Regards,Trevor Original Message --------
Subject: Re: [running-coder/jquery-typeahead] having trouble adapting
demo to real use case with postcode service (#223)

**Comment by running-coder** [comment]
Yep, that would work!
