### ISSUE TITLE
Targeting internal pages 

### ISSUE THREAD

**Issue by kylrynr** [running-coder/jquery-typeahead#224]
Hi, There is a website that I am working on with the Beer_v1. I have parent pages leading to internal pages (Ex. Equipment -> Rentals -> Dozers). How would I go about targeting the internal pages?

**Comment by running-coder** [comment]
hey @kylrynr, I'll need more details on what you are trying to acheive, perhaps code example as well. Are you talking about setting a `href` option to send to different pages?

**Comment by kylrynr** [comment]
Hi, 

Thank you for responding to my question. 
I am using the Beer_v1 demo. What I am trying to achive is adding the page url of a child page.
For Example (www.webpage.com/Services/Construction/One/Two). When I do a search for "Two" the url would be "www.webpage.com/Services/Construction/Two". What would be a good way to add the missing path? I am trying different methods. 

Javascript Page:

$.typeahead({
    input: '.js-typeahead-beer_v1',
    minLength: 1,
    maxItem: 20,
    order: "asc",
    hint: true,
    loadingAnimation: true,
    group: {
        template: "{{group}}"
    },
    maxItemPerGroup: 4,
    backdrop: {
        "background-color": "#fff"
    },
	display: ["name",  "url"],
    href: "/beers/{{group|slugify}}/{{display|slugify}}/{{url}}",
    dropdownFilter: "All Names",
    emptyTemplate: 'No result for "{{query}}"',
    source: {
        "Services": {
            ajax: {
                url: "/neffrental/wp-content/themes/theme47711/empdata.json",
                path: "data.services"
            }
        },
		 "Rentals": {
            ajax: {
                url: "/neffrental/wp-content/themes/theme47711/empdata.json",
                path: "data.rental"
            }
        },
         "Careers": {
            ajax: {
                url: "/neffrental/wp-content/themes/theme47711/empdata.json",
                path: "data.careers"
            }
        },
         "Contact Us": {
            ajax: {
                url: "/neffrental/wp-content/themes/theme47711/empdata.json",
                path: "data.contactus.contact"
            }
        }
    },
    callback: {
        onClickAfter: function (node, a, item, event) {
 
            event.preventDefault;
 
            // href key gets added inside item from options.href configuration
            alert(item.href);
 
        }
    },
	template: '<span class="name">{{name}}</span>',
    debug: true


});

---------------------------
Json:

{  
   "status":true,
   "error":null,
   "data":{  
         "services":[  
			{
				"name":"Construction", 
				"url": "/services/construction/"
			},
            {
				"name":"Golf Course and Athletic Field", 
				"url": "/services/golf-course-and-athletic-field/"
			},
			{
				"name":"Government", 
				"url": "/services/government/"
			}
         ],
         "rental":[  
			{
				"name":"Earth Moving Equipment", 
				"url": "/equipment/rental/earth-moving/"
			},
			{
				"name":"Trucks and Trailers", 
				"url": "/equipment/rental/trucks-and-trailers/"
			},
			{
				"name":"Backhoe", 
				"url": "/equipment/rental/earth-moving/backhoes/"
			}
         ],
         "careers":[
         	{
         		"name":"Career Paths",
         		"url": "/careers/careers-paths/"
         	}
         ],
         "contactus":{
         	"contact":[
         		"Plan A","Plan B","Plan C","Plan D",

         	]
         }

   }
}

**Comment by running-coder** [comment]
Have you tried `href` as a function? It will evaluate for every item... so

```javascript
href: function (item) {

    console.log(item);
    console.log(this)

    if (condition A) {
        return "/{{group|slugify}}/{{url}}/";
    } else {
        return "/{{url}}/";
    }
}
```
