### ISSUE TITLE
tab press overriding .val setting in onClickAfter

### ISSUE THREAD

**Issue by trevorclarke** [running-coder/jquery-typeahead#227]
Hi,

I've been able to solve my problem below as I've been able to modify the dynamic data returned but I wondered if there is a better way of going about it in the future if I wasn't able to control the data output.

So I search for an address and returned sample:
id:GBR|19276604 
postcode:PO9 2SE, 9, Nightingale Park, Havant

This was then applied by the following template:
<span class="project" data-postcode-address-id="{{id}}"> <small>{{postcode}}</small></span>
 
On clicking this the 2nd ajax call is made:
`onClickAfter: function (node, a, item, event) {
			$.ajax({
				method: "POST",
				url: "/postcode_retrieve.php",
				data: {id: item.id},
				dataType: 'json',
				cache: false
			}).done(function (data) {
	// update web form with address1, 2 etc individual values
				$("#postcodesearch").val(data.data.address[0].PostalCode);`

This overwrites the search input field with the data item value from the second call.
Now if you click to another part of the form or page it is all happy and stays as it was told to.

**But** if you press TAB key it moves the focus and overwrites the #postcodesearch field with the query field 'PO9 2SE, 9, Nightingale Park, Havant'.

I tried different callbacks to try to pin down where the focus point was, so I could intercept or overwrite it again without any luck. 

Lucky, I've been able to break up the data in the first response up on this occasion and that now leaves just the postcode in the search box whether you click or tab away now.
<span class="project" data-postcode-address-id="{{id}}"> <small>{{postcode}}, {{address}}</small></span>

Could I have solved it a different way at all or did I always need to do the above?

**Comment by running-coder** [comment]
Hey trevor, there is a way to cancel Typeahead's click behavior, perhaps that would be a possibility.

[e.preventDefault()](https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L1925)

`onClickBefore: null,        // -> Improved feature, possibility to e.preventDefault() to prevent the Typeahead behaviors`

```
onClickBefore: function (node, a, item, event) {
    event.preventDefault();
    // Perhaps re-do some of Typeahead's canceled behaviors such as filling the input with item.property
}
