### ISSUE TITLE
ajax configuration help

### ISSUE THREAD

**Issue by fuwifi** [running-coder/jquery-typeahead#228]
I am having trouble getting an AJAX source working, and I can't figure out what I am missing in my configuration. My API returns this:

> [{"Id":0,"Name":"Other"},{"Id":1,"Name":"Residential"},{"Id":2,"Name":"Residential Lease"},{"Id":3,"Name":"Residential Income"},{"Id":4,"Name":"Manufactured in Park"},{"Id":5,"Name":"Land"},{"Id":6,"Name":"Commercial Sale"},{"Id":7,"Name":"Commercial Lease"},{"Id":8,"Name":"Business Opportunity"},{"Id":9,"Name":"Farm"}]

And my configuration looks like this:
```
source: { 
  'Propery Type': {
    ajax: {
      url: "http://localhost:1111/property-types",
      path: 'data',
      display: 'Name',
      callback: {
        always :function (data, textStatus, jqXHR) {
          console.log('Data: ' + JSON.stringify(data));
        }
      }
    }
  }
}
```

Console.log output:
> Data: [{"Id":0,"Name":"Other"},{"Id":1,"Name":"Residential"},{"Id":2,"Name":"Residential Lease"},{"Id":3,"Name":"Residential Income"},{"Id":4,"Name":"Manufactured in Park"},{"Id":5,"Name":"Land"},{"Id":6,"Name":"Commercial Sale"},{"Id":7,"Name":"Commercial Lease"},{"Id":8,"Name":"Business Opportunity"},{"Id":9,"Name":"Farm"}]

Is there something I am missing?

**Comment by running-coder** [comment]
hey,

if your API returns the array of result, you don't need ´path: data´. This configuration is used to point your array of items in case you receive an object. Also the ´display: 'Name'´ goes on the same level as ´ajax:´ not inside.

**Comment by fuwifi** [comment]
Thank you!
I had tried it with different path options, including none. My issue was the display level.

**Comment by running-coder** [comment]
cool!
