### ISSUE TITLE
Changing the Search Image to an Icon

### ISSUE THREAD

**Issue by philbertphotos** [running-coder/jquery-typeahead#229]
Was trying to find a easy with to change the search image with either a FontAwsome or different image ... how easy would that be?

**Comment by kavin-90** [comment]
if you're asking for magnify glass icon then its easy. I use my own font icon.

**Comment by running-coder** [comment]
hey phil, as kavin said it should be quite easy and straight forward. Either alter the Typeahead css or simply put your own html inside the button tag
