### ISSUE TITLE
Highlight disable not working on properly on dynamic call

### ISSUE THREAD

**Issue by ldrrp** [running-coder/jquery-typeahead#23]
I am not able to disable filtering when performing a dynamic call.

```javascript
$(document).ready(function(){
	$('#search-field').typeahead({
		maxItem: 12,
		minLength: 2,
		order: null,
		dynamic: true,
		accent: true,
		highlight: false,
		filter: false,
		source: {
			zipcode: {
				url: [
					{
						type: "POST",
						url: "/includes/send/index/search.php",
						data: { search: "{{query}}" }
					},
					"data"
				]
			}
		},
		selector: {
			dropdown: "dropdown-menu",
			list: "dropdown-menu"
		},
	});
});
```

**Comment by running-coder** [comment]
hey ldrrp,

I've tried your code and the filters does not display on my end. Would it be possible that there is a second typeahead instance on your page? or using an old version?

If you have a live demo I could look at it would be easier for me to debug.

Thanks.

**Comment by ldrrp** [comment]
Im sorry i wrote the title incorrectly, i meant highlight.

The issue im having is typing in an address like "601 North division street"

the data response is "601 N division st" <- i want this to show up but it is somehow not shown.

**Comment by ldrrp** [comment]
@running-coder Do you know when this will be fixed or an option provided so that all my "data": [] is shown instead of nothing.

**Comment by running-coder** [comment]
Hey, 

have you tried with the latest version 2.0? 
Is your example https://dev.usfoodorder.com/ updated?

Could you explain the steps to reproduce, current behavior and expected behavior please? I'm not sure I'm getting it right.

Thanks

Tom

**Comment by ldrrp** [comment]
Yes, im on the latest 2.0

{"status":true,"error":null,"search":"601 n division st buffalo","data":{"postal":[],"city":[],"address":[{"text":"601 N Division St, Buffalo NY","longitude":0,"latitude":0}]}}

data is there but the dropdown does not show.

**Comment by ldrrp** [comment]
Notice my search doesn't include the comma, so it is then filtered out from the dropdown. I basically want my server side code to handle the result outputs not the frontend js.

**Comment by running-coder** [comment]
I'm still thinking which one would be best:
- skip ponctuation option global or per group (similar to accent option) would accept and " ' . , etc
- ignore filtering option global or per group (takes data from request and doesnt do any filtering operation)
- ignore characters option global or per group, ignores anything set in configuration

**Comment by ldrrp** [comment]
ignore filtering option global or per group (takes data from request and doesnt do any filtering operation)

That would probably be the best option to integrate first by group i would think so users have more control.
