### ISSUE TITLE
Invalid data type, must be Array type

### ISSUE THREAD

**Issue by ethorz** [running-coder/jquery-typeahead#230]
Hello, 

A few hours, I'm trying to understand where the error, ajax works.
This code of configuration:

```
$.typeahead({
        input: '#searchField',
        minLength: 3,
        maxItem: false,
        highlight: false,
        hint: true,
        dynamic: true,
        delay: 300,
        cancelButton: false,
        display: 'Groups',
        template: function (query, item) {
           return '<span>' +
                       '<span class="name">{{Groups.ItemList}}</span>' +
                   '</span>';
        },
        source: {
            itemlist: {
                href: "{{ItemLink}}",
                path: 'data.Groups',
                ajax: function (term) {
                    return {
                        url: GlobalSiteConfig.DynamicDomain2 + '/Search/FastSearch.json',
                        dataType: "jsonp",
                        data: {
                            term: "{{query}}"
                        }
                    }
                }
            },
        },
        callback: {
            onClickAfter: function () {
                showIndicator();
            },
        },
        debug: true,
    }); 
```

and data from the request 

`callback_itemlist({"Groups":[{"Name":"Поиск предложений по детали","Category":"ShopSearch","Position":0,"ItemList":[{"Name":"AIKO C1011 ФИЛЬТР МАСЛЯНЫЙ","Position":0,"ImageLink":null,"ItemLink":"/Shop/Search.html?DetailNumber=C1011\u0026MakerId=911\u0026BrandId=0"},{"Name":"SAKURA C1011 ФИЛЬТР МАСЛ. SAKURA C1011","Position":0,"ImageLink":null,"ItemLink":"/Shop/Search.html?DetailNumber=C1011\u0026MakerId=226\u0026BrandId=0"},{"Name":"ROMIX C10113 КЛИПСА!\\ VW POLO 95-01","Position":0,"ImageLink":null,"ItemLink":"/Shop/Search.html?DetailNumber=C10113\u0026MakerId=2547\u0026BrandId=0"},{"Name":"LYNX C1011LR ОПОРА ШАРОВАЯ ПЕРЕД ПРАВ ЛЕВ","Position":0,"ImageLink":null,"ItemLink":"/Shop/Search.html?DetailNumber=C1011LR\u0026MakerId=0\u0026BrandId=6"}]}]})`

After request in console appears error message: "Invalid data type, must be Array type.", where problem? 
Thank you in advance

**Comment by running-coder** [comment]
hey

the 'path' configuration is used by Typeahead to tell where to look for a searchable data set of type Array. The path configuration goes inside the Ajax request so inside your return beside the datatype jsonp.

also check for the correct path from your response

"path: Groups.ItemList"
