### ISSUE TITLE
Suggestion/ Request :- Tab click emulate right arrow click to autocomplete

### ISSUE THREAD

**Issue by rohithnair** [running-coder/jquery-typeahead#232]
But can we make tab click on textbox search do the same as autocomplete right arrow click?

What code should I amend to do the same?

Thanks
Rohith

**Comment by running-coder** [comment]
I was unsure of what `tab` should do... https://github.com/running-coder/jquery-typeahead/blob/40e1239c48ee9cb6701341a5be06a03cc185178f/src/jquery.typeahead.js#L1290

perhaps I got my answer! Still have to look into other typeahead's behaviours such as facebook and google and grab the best one. Selecting the element is definitely an option

**Comment by running-coder** [comment]
I've decided to leave it unchanged for `tab` after looking at various typeaheads, the expected behavior of a tab is to move to next element (for example next field inside a form)

if you wish to have the same functionality for right arrow and tab just add it inside the condition around line 1343
```javascript
if (e.keyCode === 39 || e.keyCode === 9) {
```
