### ISSUE TITLE
Need help in resolving issue with tooltip!

### ISSUE THREAD

**Issue by gs-smuthyam** [running-coder/jquery-typeahead#233]
Hi There,

Below is what I defined as my template

``<span` class="person-type {{personType}}"></span>`
`<div><div class="asset-header-col gs-col">`
`<span tooltip="{{name}}">{{name}}</span></div></div>`
`<div><div class="header-col gs-col">`
`<span title="{{personHierarchy}}"><small><em>{{personHierarchy}}</em></small></span>`
`</div></div>``

Because of highlighting of matched text, part of the display attribute values getting surrounded with <strong>. As a result expected result is not appearing in tooltip and the class for the matched personType attribute based on which I'm trying to display different style. 

Any help in addressing this issue is appreciated.

**Comment by running-coder** [comment]
hey @gs-smuthyam, I've encountered that issue as well when building the examples.. I added `|raw` modifier to get only the raw result unmodified by highlight

From the doc:
> If you need to print the item values inside HTML data attributes, it is possible to use {{variable|raw}}. That optional modifier will make sure to get the unmodified value.
