### ISSUE TITLE
How to add element value into source url

### ISSUE THREAD

**Issue by rbsevilla** [running-coder/jquery-typeahead#24]
I've a dynamic hidden input : hdnTeamID

And I want to pass it to the typeahead source url like this:

playerandteam: {
               url: ["/js/Players3.json", $('#hdnTeamID').val()]
                                }

but it's not working. Please help! Thanks

**Comment by rbsevilla** [comment]
I've also tried this:

Players: {
                  url: "/Home/Players",
                  data: { teamid: $('#hdnTeamID').val() },
                  success: function (data) { 
                        return data;
                   }
              }

But no luck. :( Please help!!!
Thanks

**Comment by running-coder** [comment]
Hey rbsevilla,

if I understand correctly depending on the selected team you want to be able to only display the players of that team inside the search results.

Unfortunately the typeahead does not currently support that behavior internally. You will have to call a .destroy() and then re-init when the selected team changes.

I am currently in the process of writing the version 2.0 so I'll note it as a feature to include!

The new version should be available within a couple days.

Thanks

**Comment by rbsevilla** [comment]
Cool.. Thank you.

**Comment by running-coder** [comment]
perhaps this was related to your question? https://github.com/running-coder/jquery-typeahead/issues/48
