### ISSUE TITLE
Turkish Letter "İ" issue on Chrome

### ISSUE THREAD

**Issue by w-sharp** [running-coder/jquery-typeahead#240]
Hi;

I am having a trouble on Chrome with letter "i" in Turkish language.

In English there is dot on small case "i" but there is no dot on Capital "I". So this two latter is same but case if different. But in Turkish they are different. There is Capital "I" and small case "ı". And there is Capital "İ" and small case "i"

So

```
I = ı
İ = i
```

When i type something like "İstanbul" or "istanbul" typehead gives me result in Firefox. So everything is OK. When i search "İstanbul" in Chrome it gives me results because my records includes keyword "İstanbul" but when i search "istanbul" it does not gives results.

I didn't understand why it is OK on Firefox but not OK on Chrome.

Andy idea on it? How to fix it?

Some background info on Turkish "I" issue:
(https://en.wikipedia.org/wiki/Dotted_and_dotless_I
http://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you-should-care.aspx
https://blogs.msdn.microsoft.com/qingsongyao/2009/02/13/introduce-the-turkish-i-issue)

**Comment by running-coder** [comment]
hey @w-sharp,

I only got trouble with the "ı" letter in my version on chrome. It is possible to use the `accent` option and define character equivalent. here is an example

```
input: ".js-typeahead-input",
minLength: 0,
order: "asc",
accent: {
    from: "iİıI",
    to: "iiii"
},
hint: true,
emptyTemplate: "no result for {{query}}",
source: {
    turkish: {
        data: ["ihey", "İhi", "ıhello", "Iheya"]
    }
},
debug: true
```

**Comment by w-sharp** [comment]
Thanks for the lead. I didn't pay attention on accent option.

Unfortunately it didn't fix my problem. I had to add another string in to my json but this one was fully lowercase. Then i add it to "display". So when i type some string in lowercase it is matching with this lowercase extra string.

This is not a desirable solution since it is increasing json data size (repeated string in the json) and matched string is not highlighted (because this extra repeated string is not included to template) but it is resulting the keyword for now.

Thanks again for your help.

**Comment by running-coder** [comment]
rignt... would it be possible for you to build a jsfiddle so I could have a look? saying which query to search and the results vs expected results? Perhaps there is a better way

**Comment by w-sharp** [comment]
sure. i will create one and let you know. thanks

**Comment by w-sharp** [comment]
Sorry i could not manage place all resources in to js fiddle. Is it ok if i am giving you a zip package? (Below link)

http://www.filenurse.com/download/053d9a7941795ae5e9c818645a4f97b3.html
(To make the html and script work i had to place it under a web server)

You may search for "istanbul". When you do that it will not result because the string in json is starts with capital "İ"

If you search as "İstanbul" than it works.

This issue is on chrome. Firefox works well.

**Comment by running-coder** [comment]
I've just looked at your demo and indeed there is an issue with Chrome, even with the highlight function that messes up the "matched key index" and highlight the wrong text, works fine on firefox. Unfortunatly not much I can do.. sorry

**Comment by w-sharp** [comment]
thanks for your help. i'll keep it that way for now. maybe i can look deep into that later.
