### ISSUE TITLE
Catch callback and not redirect

### ISSUE THREAD

**Issue by marcosxp** [running-coder/jquery-typeahead#241]
Catching JUST like the result, without the URL redirection.
the result would be displayed in the DIV with the return of id, but without the redirect URL

```javascript
href: "{{group}}-{{display}}",
dropdownFilter: "Todas as cidades",
emptyTemplate: 'Nenhum resultado para "{{query}}"',
source: {
	"São Paulo": {
		data: data.SP
	}
},
callback: {
        onClickAfter: function (node, a, item, event) {
		//event.preventDefault();
		//	var r = confirm("You will be redirected to:\n" + item.href + "\n\nContinue?");
		//	if (r == true) {
		//		window.open(item.href);
		//	}
		$('#retorno').text(item.href);
	}

}
```

**Comment by running-coder** [comment]
if you don't want the redirection, you have to remove the `href` attribute

**Comment by marcosxp** [comment]
Ja removed, however in return DIV how do I get the same parameters that comes in the URL


I need to get these two parameter settings "{{group}} - {{display}}"

**Comment by running-coder** [comment]
if you `console.log(item)` from inside the `onClickAfter` function you should the the item that was clicked.
```
onClickAfter: function (node, a, item, event) {
    console.log(item)
}
```

**Comment by marcosxp** [comment]
Thank you, something so simple and I breaking my head !!

It worked now

**Comment by running-coder** [comment]
haha, np enjoy
