### ISSUE TITLE
Invalid data type, must be Array type.

### ISSUE THREAD

**Issue by zdokadia** [running-coder/jquery-typeahead#242]
I am trying ti implement the "Game V1" demo provided on the runningcoder website.

My environment is Lotus Domino 8.5.3. As you will see below, I have modified one of the AJAX calls in the sample code to call a Lotus Domino agent.

$.typeahead({
    input: '.js-typeahead-game_v1',
    minLength: 1,
debug: true,
    maxItem: 0,
    order: "asc",
    hint: true,
    group: true,
    maxItemPerGroup: 5,
    dropdownFilter: "all",
    source: {
        game: {
            data: [{
                id: 777,
                display: "Sky Shooter"
            }, {
                id: 1001,
                display: "Elite shooter 6"
            }],
            ajax: {
                url: "http://www.gamer-hub.com/game/list.json",
                dataType: "jsonp",
                path: "data"
            }
        },
        category: {
            ajax: {
                url: "http://www.gamer-hub.com/category/list.json",
                dataType: "jsonp",
                path: "data"
            }
        },
        tag: {
            ajax: {
                url: "/bestp/domrep.nsf/JSON?OpenAgent",
                dataType: "text",
                path: "data"
            }
        }
    },
    callback: {
        onNavigateBefore: function (node, query, event) {
            if (~[38,40].indexOf(event.keyCode)) {
                event.preventInputChange = true;
            }
        },
        onClick: function (node, a, item, event) {
            window.open(
                "http://www.gamer-hub.com/" +
                    item.group + "/" +
                    item.id + "/" +
                    item.display.replace(/[\s]|:\s/g, "-")
                        .replace("'", "-")
                        .toLowerCase()
                    + "/"
            );
        },
        onMouseEnter: function (node, a, item, event) {
            if (item.group !== "game") {
                return false;
            }
 
            if (!$(a).find(".popover")[0]) {
 
                $(a).append(
                    $("<div/>", {
                        "class": "popover fade right in",
                        "html": $("<div/>", {
                            "class": "popover-content",
                            "html": $("<img/>", {
                                "src": "http://cdn.gamer-hub.com/images/" +
                                    item.display.replace(/[\s]|:\s/g, "-")
                                        .replace("'", "-")
                                        .replace(/-+/g, "-")
                                        .toLowerCase()
                                    + ".jpg"
                            })
                        }).prepend($("<div/>", {
                            "class": "arrow"
                        }))
                    })
                );
 
            } else {
                $(a).find(".popover").removeClass("out").addClass("in");
            }
        },
        onMouseLeave: function (node, a, item, event) {
            if (item.group !== "game") {
                return false;
            }
 
            $(a).find(".popover").removeClass("in").addClass("out");
        }
    }
});

The agent returns the following:

{"status":true,"urlPattern":"\/tag\/#id#\/#display#\/","data":[{"id":"E5ABD9C19EEAFE43852573440074C403","display":"Best Practices in Designing Effective Brand Teams: Brand Governance and Brand Team Management Report Summary"},{"id":"52B47BA1BAF91908652579090068E04D","display":"Communications Excellence Report Summary: Tactics Used by Executives to Increase Organizational Effectiveness"},{"id":"9BED8A3069F1763485257688002FF572","display":"Competitive Intelligence Excellence Services Excerpt"},{"id":"67844A3D086B126C85257C92004A1B9F","display":"Deploying the iPad or Android-Based Tablet to Sales and Managed Markets Teams: Benchmarking Training and Effectiveness (Updated 2014)"},{"id":"D3A504B101BC1AAD85257682005306A0","display":"Excerpt: Pharma Quality Excellence Services"},{"id":"4DCF7FC510796B5385257A22005014A1","display":"From Classroom to Boardroom: Training Can Propel Market Researchers 
from Order-Takers to Trusted Business Advisers"}]}

In the debug console, I see "Invalid data type, must be Array type." error. I am very new to jQuery and AJAX. Appreciate any assistance from your side.

**Comment by zdokadia** [comment]
Please ignore this issue. Since I am dynamically fetching data from a Domino view, I realised my data had some carriage returns, line feeds, etc. which caused formatting issues in my JSON. I am now replacing all such characters with spaces and it works ok now.

**Comment by running-coder** [comment]
cool, lmk if anything
