### ISSUE TITLE
On form reset, all input drop-down open up if "minLength:0" and "searchOnFocus: true"

### ISSUE THREAD

**Issue by bharath4u3** [running-coder/jquery-typeahead#243]
As you can see in hte git below that when reset button is clicked the input fields clear but the dropdown opens up.

Additionally for support: is there anything I can trigger a close of the dropdown on input blur (i.e. going to a different tab on the browser.)

Here is the jsfiddle to reproduce the issue: https://jsfiddle.net/bharath4u3/dh9cyabb/
![dit fiddle - jsfiddle20160930185609](https://cloud.githubusercontent.com/assets/18652772/19011006/1a68e15a-8740-11e6-8947-29cd19217d39.gif)

**Comment by running-coder** [comment]
hey @bharath4u3 thanks for letting me know, looks like I misunderstood what @hsdhott was trying to say in #221 hehe

**Comment by hsdhott** [comment]
@running-coder that's exactly what I was talking. @bharath4u3 thank you for point it out.

On that note, I'm also noticing that when we clear input field through jquery/js ($('#mySearchInput').val('').trigger('input.typeahead') - as mention in #221). It open the dropdown field. Can we avoid that as well?

Additionally, how can I close the dropdown on blur (i.e. going to a different browser or tab).

Thank you so much for your help.

**Comment by running-coder** [comment]
you can always call the hideLayout function, Typeahead['.js-selector'].hideLayout()
