### ISSUE TITLE
Issue when query typed has Leading Space

### ISSUE THREAD

**Issue by kunalgithub** [running-coder/jquery-typeahead#244]
I have the following JSON : 
{  "data":   {  "beer":  { "ale":  **[**  "Credit",  "CreditWorthiness" **]**  } } }

and the following setting : 
```javascript
minLength: 3,
maxItem: 3,
order: "asc",
hint: true,
maxItemPerGroup: 5,
cache : false,
correlativeTemplate: true,
source: {
    "typeahead": {
        ajax: {
            url: "/typeahead.json?startTime=" + (new Date()).getTime(),
            path: "data.beer.ale"
        }
    }
},
callback: {
    onLayoutBuiltBefore: function (node, query, result, resultHtmlList) { 
        // resultHtmlList is blank when text box is typed with space infront of the work**
        resultHtmlList.find('li[data-search-group="game"]').remove();  return resultHtmlList;  
    }
}
```

Initially the JSON has the above two words , then I add "Credit Cards" to the JSON. 

Step 1. Type Credit in the textBox -- > All the options are displayed as in the JSON
Step 2: Change the JSON to have "Credit Cards"
Step 3.  Type Credit with a space after Credit "Credit " - > **No Query is fired** 
and onLayoutBuiltBefore returns resultHtmlList as Null. 

How to resolve this ? **Version user 2.7.0**

**Comment by running-coder** [comment]
a couple things:
- if you want requests to be sent on every `keypress`, you have to enable `dynamic:true` option
- the issue is caused due to a javascript error in `resultHtmlList.find('li[data-search-group="game"]').remove();`.
- this line says to search for an element group name "game" which is not in your source, you renamed it "typeahead" and your group option is not enabled (`group: true`)

**Comment by kunalgithub** [comment]
Hi Tom,

Thanks for your reply ..
Apparently I found the issue in our actual code where for a specific
response path was not matching as well as the case where response Did not
contain matching pattern.

I will close this item

Thanks for your continued support

**Comment by running-coder** [comment]
you welcome, let me know if anything
