### ISSUE TITLE
Dynamic Ajax GET query with NO delay wont generate dropdown list some times

### ISSUE THREAD

**Issue by seltix5** [running-coder/jquery-typeahead#248]
hi,
great plugin first of all!
i want o have a search field with instant dynamic autocomplete but it is not working correctly. with delay it works nice but it is not really a good option because the user need to stop write. i wold like to have the dropdown autocomplete list updating has the user type each letter, and because of that i set the delay to a value like 0 or even 100 ms.

apparently because of that the var "generatedGroupCount" is not always set to 0 and because of that in first check on the "incrementGeneratedGroup" function the process stop and the suggestions list is not updated.

i just comment the "return;" on line 1273 (jquery-typeahead-2.7.1/src/jquery.typeahead.js -> function incrementGeneratedGroup) and now it works but maybe this wold cause problems elsewhere?

any idea about this?

thanks :D

**Comment by mitosch** [comment]
+1

I analysed the behaviour and it fails to load the list, after one json request was canceled. See example:
![image](https://cloud.githubusercontent.com/assets/922559/19680932/c6ad106a-9aa7-11e6-9d0c-a15957dbdc48.png)

I'm trying to debug it further, but I'm now stuck at the jquery code at deferred.fail() http://api.jquery.com/deferred.fail/

**Comment by seltix5** [comment]
hi,
this is in chrome right? how do i get this requests listed?

about the problem, i think because there are made multiple requests too quickly, the previous one is canceled by jquery (im just guessing)...

apparently the problem is "populateSource()" is run anyway and "this.generatedGroupCount" is incremented. after that the last request works but because "this.generatedGroupCount" as a wrong count the dropdown is not populated.

possible solution... on fail the "populateSource()" should not execute?

**Comment by mitosch** [comment]
Hi

Yes, Chrome. Left mouse button -> inspect element -> network.

Ok. I'll take a look at it, but I need to dig into jquery.typeahead source.

**Comment by seltix5** [comment]
Yes i did check on the network tab but i dont get the GET requests from typeahead listed :s strange...

**Comment by mitosch** [comment]
Are you using ajax as a source for typeahead?

I just tested one thing. By removing the line 714, the calls won't get aborted:

```javascript
            if (!this.helper.isEmpty(this.xhr)) {
                for (var i in this.xhr) {
                    if (!this.xhr.hasOwnProperty(i)) continue;
                    //this.xhr[i].abort();
                }
                this.xhr = {};
            }
```

No clue about the side effects.

**Comment by seltix5** [comment]
so, i was wrong, the abort really is requested on the code... humm

**Comment by running-coder** [comment]
Hey guys, I was able to reproduce the issue. Populate was called with invalid data (aborted requests) let me know if this fix resolved the issue.

**Comment by mitosch** [comment]
Thank you, I'll check it out in the upcoming days.

Btw: Thanks for the cool plugin, great work!

**Comment by seltix5** [comment]
hi! thank you.

it is working for me now, i dint detect any problem now, thanks :D

**Comment by running-coder** [comment]
can't beleive the issue has been there for so long, thanks for reporting it guys

**Comment by seltix5** [comment]
no problem, your'e doing a great job! congrats :D

**Comment by mitosch** [comment]
Hi

I can also confirm that the bug is fixed.

Thank you!

**Comment by seltix5** [comment]
hi, i update my version to the last one and i noticed a bug where it does not generate the dropdown list. this ocurs when i write too fast.
for example with the dynamic mode for countries list and a 100 ms delay, if i type "portugal" fast the dropdown wont update and will show "no options found".
do you have a sandbox mode to isolate the problem? i havethis online right now if you want the link to check it.
Thanks.
