### ISSUE TITLE
Fill suggest text with tab

### ISSUE THREAD

**Issue by bertin1990** [running-coder/jquery-typeahead#252]
In the documentation i could find nothing on how to use the tab key to fill-in the suggest text. Is there an option that needs to be enabled.

**Comment by running-coder** [comment]
hey @bertin1990, the tab key was discussed in #232. Perhaps it could be possible to leave it as the browser behavior (next tabindex) or fill in the suggest text (emulate right arrow key).

**Comment by running-coder** [comment]
Found this solution
```
callback: {
    onNavigateAfter: function (node, lis, a, item, query, e) {
        // If TAB key is pressed
        if (e.keyCode === 9) {
            e.preventDefault();

            var newEvent = jQuery.Event("keydown");
            newEvent.keyCode = 39; // Simulate Right arrow press

            node.trigger(newEvent)
        }
    }
}
```
