### ISSUE TITLE
Doesn't work with pajax/turbolinks

### ISSUE THREAD

**Issue by gudata** [running-coder/jquery-typeahead#253]
If you navigate with a mouse clicks to a page with a jquerytypeahead it doesn't get activated. 

I have made a demo rails app showing the problem.

https://jquerytypeahead.herokuapp.com/

It is amazing how much work you have done with typeahead!

**Comment by running-coder** [comment]
Hey @gudata thanks for the kind words! It appears to me that it is because of your condition

```javascript
$(document).ready(function() {
  $('.js-typeahead').typeahead({
```

On the document ready, the element `.js-typeahead` is not on the page yet. Depending on the application you are using you might want to bind that to a "state change" ready function

**Comment by gudata** [comment]
You were right, I have totally forgotten to add it to the turbolinks "state change" ready function. Then it works.

```
document.addEventListener("turbolinks:load", function() {
   $('.js-typeahead').typeahead({
