### ISSUE TITLE
Search from multidimensional array

### ISSUE THREAD

**Issue by bertin1990** [running-coder/jquery-typeahead#254]
Is it possible to search value from a multidimensional array like this:

```
$data = array(
	array(
		"cat_id"       => 1250,
		"search_name"  => "cat product 1",
		"search_type"  => "General",
		"link"         => "/search/general",
		"products"     => array(
			array(
				"product_id"   => 25,
				"search_name"  => "product1",
				"search_type"  => "Specific",
				"link"         => "/prodoct/product1/"
			),
			array(
				"product_id"   => 26,
				"search_name"  => "product2",
				"search_type"  => "Specific",
				"link"         => "/prodoct/product2/"
			),
			array(
				"product_id"   => 27,
				"search_name"  => "product3",
				"search_type"  => "Specific",
				"link"         => "/prodoct/product3/"
			)
		)
	),
);
```

When user clicks an category it will go to a specific general page with all the underlying products. But when a user clicks on a product (specific search) it needs to go to the product page itself.

WHen the user clicks on a specific product, is it possible to get there parent (cat_id)??

**Comment by running-coder** [comment]
Hey @bertin1990 , I'm assuming you are passing the `products` dimension to Typeahead? There could be a way to do it without altering your backend code.

here is how you could do it, but I'll need your full Typeahead config to validate:
typeof $.typeahead === "function" && $.typeahead({
...
	source: {
		general: {
			ajax: {
				url: "/your.endpoint.url",
				callback: {
					done: function (data, textStatus, jqXHR) {
						// Copy the cat_id in all of the products so it's reachable via {{item.cat_id}}
						if (data && data.products) {
							for (var i = 0, ii = data.products.length; i < ii; ++i){
								data.products[i].cat_id = data.cat_id
							}
						}
						
						return data;
					}
				}
			}
		}
	}
})

**Comment by bertin1990** [comment]
I have solved it be creating to arrays. One for category and products. Within the source i have two Ajax calls to get them. At the end its saves me time in backend creating to arrays instead of combining thouse two

**Comment by dave7777** [comment]
Bertin can you please share the code? I also need multidimentional autocomplete on one project!)
