### ISSUE TITLE
Add function clear

### ISSUE THREAD

**Issue by JordyMiljaar** [running-coder/jquery-typeahead#256]
First of all, you have build the best typeahead! ;)

I think that it should be a good idea to add a clear function. Sorry if this already exists but I couldn't find it.

Typeahead.prototype.clear = function() {
	this.node.val('');
    this.item = null;
    this.query = '';
    this.rawQuery = '';
}

**Comment by running-coder** [comment]
Hey @JordyMiljaar thanks for the kind words!

Typeahead has something similar called `resetLayout` which handles more of the dropdown list of result. I'll add `resetInput` that suits your description.

**Comment by neobenedict** [comment]
`resetInput()` is very buggy (dropdown breaks after using it), the 4 lines of code above should be used instead.
