### ISSUE TITLE
Cancel the ajax request

### ISSUE THREAD

**Issue by tsamaya** [running-coder/jquery-typeahead#257]
Hi,
I did not found an out of the box function to Cancel the ajax request if I know the query will not return any result. 
As a workaround : in the ajax function I returned false. That's tigger an internal error but does the job.
```javascript
ajax: function(query) {
var m = theRegex.exec(query);
if(m !== null) {
   // return the correct ajax json Object to make the ajax request
} else {
  // workaround to cancel request:
  // fire a internal error but prevent ajax request
  // and no error logged in console
  return false;
}
```

so it is not an issue but more a question.
Thanks
Arnaud

**Comment by running-coder** [comment]
Hey Arnaud, I've fixed the condition to return false or object from an Ajax function. If a group returns false the other ones will still be generated. You shouldn't see a javascript error in the console anymore. Let me know

**Comment by tsamaya** [comment]
That's great stuff ! 
thank you for your work
