### ISSUE TITLE
Function to call the parameter tagged to the searched string

### ISSUE THREAD

**Issue by BenjaminUAV** [running-coder/jquery-typeahead#258]
If there is a "symbol" tagged to the searched string. Able to create a function to call the "symbol" tagged to the "searched variable" after the user typed the "variable" and pressed "enter".

Much tanks in advance :)

**Comment by running-coder** [comment]
Hey @BenjaminUAV, I am unsure what you mean by a symbol tagged to the searched string, perhaps you can provide a use case example?

Perhaps you meant to trigger a function when a search query is typed? In that case you can use the `onSearch (node, query)` callback

```javascript
$.typeahead({
    ...
    callback: {
        onSearch: function (node, query) {
            console.log(query);
        }
    }
})

```

**Comment by running-coder** [comment]
Closing, no reply
