### ISSUE TITLE
Can't get ajax working properly

### ISSUE THREAD

**Issue by pruhstal** [running-coder/jquery-typeahead#259]
So my server is returning an object of nested objects, which contain the results, however, I can't seem to hook up to the plugin properly.

My server returns this:

<img width="728" alt="screen shot 2016-11-23 at 8 01 29 pm" src="https://cloud.githubusercontent.com/assets/624807/20586320/d53081c2-b1b7-11e6-90de-8b75089c581c.png">

But I'm getting no results found...
<img width="256" alt="screen shot 2016-11-23 at 8 01 37 pm" src="https://cloud.githubusercontent.com/assets/624807/20586328/e5a002f8-b1b7-11e6-99b5-47b9b52edb05.png">

What am I doing wrong?

```
    $.typeahead({
      input: '.js-typeahead-input',
      dynamic: true,
      minLength: 1,
      emptyTemplate: 'No result for {{query}}',
      source: {
        all: {
          ajax: ((query) => {
            return {
              type: 'GET',
              url: this.model.url(),
              data: {
                q: '{{query}}'
              },
              callback: {
                done: function (data) {
                  if (data && data.results) {
                    if (data.results.strains && data.results.strains.length) {
                      return data.results.strains;
                    }

                    if (data.results.articles && data.results.articles.length) {
                      return data.results.articles;
                    }
                  }
                  return data;
                }
              }
            }
          })
        }
      }
    })
```

**Comment by kavin-90** [comment]
You're missing **`display: ["name"],`**

**Comment by running-coder** [comment]
Indeed as @kavin-90 mentionned you are missing the display option to tell Typeahead which of your keys to search inside.

Since your callback is an object and your data is not at the root, you also need to specify the `path` to your data. I see that you also have multiple groups of data so you will also need multiple groups in the source option. Not sure how you are trying to structure your data using the callback.done function, but this could be an alternative

```javascript
$.typeahead({
	input: '.js-typeahead-input',
	dynamic: true,
	minLength: 1,
	emptyTemplate: 'No result for {{query}}',
	display: ['name'],
	source: {
		strains: {
			ajax: ((query) => {
				return {
					type: 'GET',
					url: this.model.url(),
					path: 'results.strains', // Tell Typeahead to look for this key inside your response
					data: {
						q: '{{query}}'
					}
				}
			})
		},
		articles: {
			ajax: ((query) => {
				return {
					type: 'GET',
					url: this.model.url(),
					path: 'results.articles',
					data: {
						q: '{{query}}'
					}
				}
			})
		}
	}
})
```

**Comment by pruhstal** [comment]
@running-coder Thank you so much! This is the perfect plugin. Keep up the good work, my friend.

**Comment by komprehend** [comment]
guys i am having the same issue, can't seem to get it to work:

$.typeahead({
    input: '.address-search-lg',
    minLength: 3,
    order: "asc",
    hint: true,
    dynamic: true,
    delay: 300,
    debug: true,
    backdrop: {
        "background-color": "#fff"
    },
    template: function (query, item) {
        var color = "#777";

        return '<span class="row">' +
            '<span>{{address}} ({{id}})</span>' +
        "</span>";
    },
    emptyTemplate: "Nothing found for <b>{{query}}</b>",
    display: ['address'],
    source: {
        addrs: {
            href: "/p/{{address|slugify}}/{{id}}",
            ajax: {
                type: 'POST',
                url: '/s',
                data: {
                    q: '{{query}}'
                },
                path:'results.addrs',
                callback: {
                    done: function (data) {
                       
                        return data;
                    }
                }
            }
        }
    }
});


![image](https://user-images.githubusercontent.com/1045334/30513166-745e8e44-9acc-11e7-954f-d4c30170fc56.png)

**Comment by running-coder** [comment]
are you using 2.10.1? (just released) it includes a fix for slugify modifier

**Comment by komprehend** [comment]
i am using the latest

**Comment by komprehend** [comment]
is the path setting relative to what data return from ajax.done? if i have

data.results.addrs 

if i return data from ajax.done, should path be set to results.addrs?
if i return data.results from ajax.done should path be set to addrs?
if i return data.results.addrs from ajax.done what should path be set to?

**Comment by running-coder** [comment]
the path will be applied on the done data after you reformatted, since you are using the done option you could remove the path and return an array of items from the done function, I'm away from home now but I can have a look later if that doesnt work

**Comment by komprehend** [comment]
i got rid of path setting and change done to

` done: function (data) {
                        var returnData = [];
                        $.each(data.results.addrs, function (index, value) {
                            returnData.push(value);
                        });
                        return returnData;
                    }
`

**Comment by komprehend** [comment]
I got rid of path setting and change done, still the same result



```

$.typeahead({
    input: '.address-search-lg',
    minLength: 3,
    order: "asc",
    hint: true,
    dynamic: true,
    delay: 300,
    debug: true,
    backdrop: {
        "background-color": "#fff"
    },
    template: function (query, item) {
        var color = "#777";
        return '<span class="row"> <span>{{address}} ({{id}})</span> </span>';
    },
    emptyTemplate: "Nothing found for <b>{{query}}</b>",
    display: ['address','id'],
    source: {
        addrs: {
            href: "/p/{{address|slugify}}/{{id}}",
            ajax: {
                type: 'POST',
                url: '/s',
                data: {
                    q: '{{query}}'
                },
                callback: {
                    done: function (data) {
                        var returnData = [];
                        $.each(data.results.addrs, function (index, value) {
                            returnData.push(value);
                        });
                        return returnData;
                    }
                }
            }
        }
    },
    callback: {
        onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
            //console.log(result);
        },
        onClick: function (node, a, item, event) {
            console.log('onClick function triggered');
        },
        onSubmit: function (node, form, item, event) {
            console.log('onSubmit override function triggered');
        }
    }
});

```

**Comment by running-coder** [comment]
It's working for me assuming the following json response and your Typeahead configuration
```json
{
    "results": {
        "addrs": [
            {
                "id": 1,
                "address": "address"
            }
        ]
    }
}
```

**Comment by komprehend** [comment]
running-coder, thanks for your help, i am embarrassed, i discover my error :) 

i have been entering data to search that didn't exist, so i keep getting to data returned!

thanks again
