### ISSUE TITLE
Autofocus doesn't work with the typeahead

### ISSUE THREAD

**Issue by MikeHoffert** [running-coder/jquery-typeahead#26]
The `autofocus` HTML attribute allows a form element to be focused by default (so the user can start typing without having to click the form). If autofocus is applied to a typeahead, the typeahead does not show suggestions (or hints, etc) until we unfocus (eg, by clicking away) and refocus (eg, by clicking the input).

I eventually managed to get it to work by calling `$("#typeaheadInput").focus()` after the typeahead was created (perhaps the issue is that the input was being focused before the typeahead was ready?), but it seems ideal to either document this somewhere or provide an official attribute so that those searching the documentation will be able to find how to autofocus the typeahead.

At any rate, perhaps this issue will save someone else time in the future.

**Comment by running-coder** [comment]
Hi Mike,

good catch, the Typeahead source is generated on focus (line 317 of jquery.typeahead.js) but it doesnt take into account that the input can be focused by the html attribute. I'm currently re-writing the plugin to version 2.0 and I will include the behavior compatibility.

Thanks for the feedback the next version should be available within a couple days.
