### ISSUE TITLE
Add a dropdownFilter change callback

### ISSUE THREAD

**Issue by kylrynr** [running-coder/jquery-typeahead#262]
Hi,

I have been trying to figure this out. Trying to find out if there is a way to change the placeholder text based on what is selected on the list? (For Example: "Search" is change to "Ale" when Ale is selected from the dropdown list) I have been looking for this on the documentation.

**Comment by running-coder** [comment]
hey, there is currently no event that listens for the `dropdownFilter` change. That could be a good feature to implement giving the number of results and perhaps other data in the callback params.

meanwhile you can implement it on your own with something like:

```javascript
$(document).on('click', '.typeahead__dropdown-item', function (e) {
    // Get value of the dropdown item that was clicked
    // Update Typeahead's input placeholder
})
```

**Comment by kylrynr** [comment]
Thank you. 

I will use that.

**Comment by running-coder** [comment]
Added in the develop branch
