### ISSUE TITLE
Struggling with AJAX

### ISSUE THREAD

**Issue by jtabachnick** [running-coder/jquery-typeahead#263]
I was trying to work off the example for User V1 on the coderunner site, and I have not been able to get anything to display. The response comes in fine and I have gotten to the point where there are no errors showing up with debug set to true, but I don't understand why nothing is happening with the search bar. 

here is my JSON response: 
```JSON
{"error":null,"status":true,"data":[
    {"name":"go pro 1","sku":"abc","listingid":"110525893"},
    {"name":"go pro 2","sku":"def","listingid":"110525880"},
    {"name":"go pro 3","sku":"ghi","listingid":"110525888"},
    {"name":"go pro 4","sku":"klm","listingid":"110525892"},
    {"name":"go pro 5","sku":"nop","listingid":"110530928"},
    {"name":"go pro 6","sku":"qrs","listingid":"110530936"},
    {"name":"go pro 7","sku":"tuv","listingid":"110530940"}
]}
```

and here is the code for set up. 
```javascript
$.typeahead({
        input: "#headerMenuControl_menuSearchTextBox",
        dynamic: true,
        minLength: 1,
        emptyTemplate: 'No result for {{query}}',
        display: "sku",
        source: {
            all: {
                ajax: function (query) {
                    return {
                        type: "POST",
                        url: "listing/search",
                        path:"data",
                        data: {q: "{{query}}"}
                    }
                },
                template: '<div style="border:1px solid red">{{sku}}</div>'
            }
        },
        callback: {
            onClick: function (node, a, item, event) {

                // You can do a simple window.location of the item.href
                alert(JSON.stringify(item));
            },
            onSendRequest: function (node, query) {
                console.log(query);
            },
            onReceiveRequest: function (node, query) {
                console.log('request is received');
            }
        },
        debug: true
    });
}
```

I have also tried this alternative:

```javascript
display: "data",
    source: {
        all: {
            ajax: function (query) {
                 return {
                     type: "POST",
                      url: "listing/search",
                      data: {q: "{{query}}"}
             }
         },
         template: '<div style="border:1px solid red">{{sku}}</div>'
   }
```

Any help anyone can provide would be greatly appreciated.

**Comment by running-coder** [comment]
hey @jtabachnick, I'm getting Typeahead results given your configuration...
<img width="539" alt="screen shot 2016-11-29 at 11 14 17 pm" src="https://cloud.githubusercontent.com/assets/7377382/20739563/addcc992-b689-11e6-995e-547eddf0bec5.png">

**Comment by kavin-90** [comment]
I use source: { ajax call,"data"}

"data" here is array which contain all data. i.e "data":[ ]

**Comment by jtabachnick** [comment]
@running-coder I am getting the JSON back from my API. I copy pasted that from my network tab. I get no response from the input when I enter something in the text box. In the console I get the log of the query string, and that I get a response as expected based on the callbacks. Is it possible that another plug-in is interfering with the typeahead plug-in?

**Comment by running-coder** [comment]
try filter: false first. this option will tell Typeahead do not do the filtering (in case your backend code already does it)

**Comment by jtabachnick** [comment]
Still nothing with filter set to false, I am assuming that belongs outside of the source option.

**Comment by running-coder** [comment]
outside for global, in group to apply only to that group. At this point there might be other stuff interfeering... is the Typeahead result list generated but hidden when you inspect the dom? You might have to put debug code in the buildHtml function and check if any results are passed

**Comment by kavin-90** [comment]
for fun 😄 
```
display: ["sku","name"],
    source: {
        all: {
            ajax: function (query) {
                 return {
                     type: "POST",
                      url: "listing/search",
                      data: {q: "{{query}}"}
             }
         ,"data"},
         template: '<div style="border:1px solid red">{{sku}}</div>'
   }
```

**Comment by jtabachnick** [comment]
The buildHtmlLayout function is receiving and processing the data. I can see it creating the divs from the template, but it is not returning anything up to the buildLayout function.  I stripped out all of my other plug-ins and js fiels and am working in just a blank html page, and I am getting nothing to display. Even if I send in no data, I do not get the empty template to display.  I tried @kavin-90 's suggestion,  but I got nothing there as well.  

I feel like I am missing something very simple, but I don't  know what that could be.

**Comment by running-coder** [comment]
hmm if its processing the data and building the html, then I feel like the error might be in the part when that built html is attached to the div. Have you used the base html template or did you change some of it's selector?

**Comment by jtabachnick** [comment]
I think I figured it out. I need to make the HTML containers match yours more closely., It was not adding classes properly so the DOM was not building. Thanks for the help.

**Comment by running-coder** [comment]
You can use the `selector` option and change the containers Typeahead is expecting if needed
