### ISSUE TITLE
Jquery type ahead

### ISSUE THREAD

**Issue by shrikantu** [running-coder/jquery-typeahead#264]
Hi All,
I am new to the jquery  and using the jquery type ahead library. I configured it as per below but getting the issue to populate the type ahead text box. please suggest 

Invalid data type, must be Array type.
Invalid data path.

Log Reference
==========================
--- jQuery Typeahead Debug ---
jquery.typeahead.js:2502 obj1{"OK - Typeahead activated on #branchName":{"node":"#branchName","function":"init()","arguments":"","message":"OK - Typeahead activated on #branchName"}}
jquery.typeahead.js:2504 propOK - Typeahead activated on #branchName
jquery.typeahead.js:2924 --- jQuery Typeahead Debug ---
jquery.typeahead.js:2502 obj1{}
jquery-2.1.3.min.js:4 XHR finished loading: GET "http://localhost:28080/Abc/getBranchNames?branchName=B".send @ jquery-2.1.3.min.js:4ajax @ jquery-2.1.3.min.js:4(anonymous function) @ jquery.typeahead.js:960handleRequests @ jquery.typeahead.js:1041generateSource @ jquery.typeahead.js:810(anonymous function) @ jquery.typeahead.js:635dispatch @ jquery-2.1.3.min.js:3r.handle @ jquery-2.1.3.min.js:3
branch.js:102 [{"id":12,"name":"Balla"},{"id":17,"name":"Bal"},{"id":18,"name":"Ball"},{"id":19,"name":"Bal"},{"id":20,"name":"Bal"}]
jquery.typeahead.js:1057  Array.isArray(data) true
jquery.typeahead.js:1058  group branchName
jquery.typeahead.js:1059  path data.name
jquery.typeahead.js:1064  test1 true
jquery.typeahead.js:2502 obj1{"Invalid data path.":{"node":"#branchName","function":"populateSource()","arguments":"data.name","message":"Invalid data path."}}
jquery.typeahead.js:2504 propInvalid data path.
jquery.typeahead.js:2924 --- jQuery Typeahead Debug ---
jquery.typeahead.js:2502 obj1{"Invalid data type, must be Array type.":{"node":"#branchName","function":"populateSource()","arguments":"{\"group\":\"branchName\"}","message":"Invalid data type, must be Array type."}}
jquery.typeahead.js:2504 propInvalid data type, must be Array type.
jquery.typeahead.js:2924 --- jQuery Typeahead Debug ---
jquery.typeahead.js:2502 obj1{}
jquery.typeahead.js:2502 obj1{}
branch.js:126 0
jquery.typeahead.js:2502 obj1[] 

branch.js
===========================
$("#branchName").typeahead({
		input : ".js-typeahead-input",
		minLength : 1,
		order : "asc",
		group : true,
		maxItemPerGroup : 3,
		groupOrder : function() {
			var scope = this, sortGroup = [];
			for ( var i in this.result) {
				sortGroup.push({
					group : i,
					length : this.result[i].length
				});
			}
			sortGroup.sort(scope.helper.sort([ "length" ], false, function(a) {
				return a.toString().toUpperCase()
			}));
			return $.map(sortGroup, function(val, i) {
				return val.group
			});
		},
		hint : true,
		template : "{{display}}, <small><em>{{group}}</em></small>",
		emptyTemplate : "no result for {{query}}",
		source : {
			branchName : {
				display : "name",
				/*data: [{
				    "id": 415849,
				    "name": "Bhp"
				},{
				    "id": 415859,
				    "name": "Bbct"
				}],*/
				ajax : function(query) {
					return {
						type : "GET",
						url : "getBranchNames",
						path : "data.name",
						data : {
							"branchName" : "{{query}}"
						},
						callback : {
							done : function(data) {
								console.log(JSON.stringify(data));
								return data;
							}
						}
					}
				}
			}
		},
		onClickAfter : function(node, a, item, event) {
			event.preventDefault();
		},
		callback : {
			onResult : function(node, query, obj, objCount) {
				console.log(objCount)
				var text = "";
				if (query !== "") {
					text = objCount + ' elements matching "' + query + '"';
				}
			}
		},
		debug : true
	});

**Comment by running-coder** [comment]
hey @shrikantu ! thanks for using typeahead. Indeed you had 2 `/` characters that prevented the data from being declared properly. Also your template needs to contain valid keys from your objects, ex: `{{name}}` (the `display` key was not declared in your object).

```javascript
$.typeahead({
    input: ".js-typeahead-input",
    minLength: 1,
    order: "asc",
    group: true,
    maxItemPerGroup: 3,
    groupOrder: function () {
        var scope = this, sortGroup = [];
        for (var i in this.result) {
            sortGroup.push({
                group: i,
                length: this.result[i].length
            });
        }
        sortGroup.sort(scope.helper.sort(["length"], false, function (a) {
            return a.toString().toUpperCase()
        }));
        return $.map(sortGroup, function (val, i) {
            return val.group
        });
    },
    hint: true,
    template: "{{name}}, {{group}}",
    emptyTemplate: "no result for {{query}}",
    source: {
        branchName: {
            display: "name",
            data: [{
                "id": 415849,
                "name": "Bhp"
            }, {
                "id": 415859,
                "name": "Bbct"
            }],
            ajax: function (query) {
                return {
                    type: "GET",
                    url: "getBranchNames",
                    path: "data.name",
                    data: {
                        "branchName": "{{query}}"
                    },
                    callback: {
                        done: function (data) {
                            console.log(JSON.stringify(data));
                            return data;
                        }
                    }
                }
            }
        }
    },
    onClickAfter: function (node, a, item, event) {
        event.preventDefault();
    }
    ,
    callback: {
        onResult: function (node, query, obj, objCount) {
            console.log(objCount)
            var text = "";
            if (query !== "") {
                text = objCount + ' elements matching "' + query + '"';
            }
        }
    },
    debug: true
});
```

**Comment by shrikantu** [comment]
Below is the response and while populating this response to the fields it gives and invalid data path


[{"id":12,"name":"Balla"},{"id":17,"name":"Bal"},{"id":18,"name":"Ball"},{"id":19,"name":"Bal"},{"id":20,"name":"Bal"}]

**Comment by running-coder** [comment]
If this is the response you get, then you don't need to specify a path. The path is used if you have an object as a response, like this:

```javacript
// Typeahead
ajax: {
    url: '...',
    path: 'data.moreData'
}

// Response
{
    data: {
        moreData: [{"id":12,"name":"Balla"},{"id":17,"name":"Bal"},{"id":18,"name":"Ball"},{"id":19,"name":"Bal"},{"id":20,"name":"Bal"}]
    }
}
```

**Comment by shrikantu** [comment]
![image](https://cloud.githubusercontent.com/assets/24422159/21106777/59c6db00-c0b5-11e6-92e1-693ec2ec3a3f.png)

Please take a look i remove the path but the console says path is undefined. Could you please suggest.

**Comment by running-coder** [comment]
No issue when I try to reproduce, https://jsfiddle.net/runningcoder/n0pkc5zo/
