### ISSUE TITLE
onDropdownFilter not working

### ISSUE THREAD

**Issue by sergefabre** [running-coder/jquery-typeahead#273]
Hello,
it is normal the event 'onDropdownFilter' do not working before using the typeahead ?
finaly I use $(document).on('click', '.typeahead__dropdown-item', function (e) {blablabla});

can you help me please ?

**Comment by running-coder** [comment]
hey @sergefabre sorry for the delay, I've verified the feature and it's working properly on my side.

![screen shot 2017-01-10 at 11 57 58 am](https://cloud.githubusercontent.com/assets/7377382/21815899/333bc954-d72c-11e6-99ac-3528504160b3.png)

**Comment by sergefabre** [comment]
Hello (sorry for my English, I'm French... :))

Thank you for your reply

I will try again this week


2017-01-10 17:59 GMT+01:00 Tom Bertrand <notifications@github.com>:

**Comment by sergefabre** [comment]
Hello,
sorry but the event onDropdownFilter is not fired when change value dropdown

my code =
$.when(GetUniqOfTable(json.data, 'SousSerie')).then(function (_tblSousSerieUnique) {
                $.each(_tblSousSerieUnique, function (i, item_ss) { _tblFilterTypeHead.push({ key: "SousSerie", value: item_ss, template: item_ss, all: 'toutes' }); });
                $.typeahead({
                    input: "#RameInput", offset: true, searchOnFocus: true, highlight: true, minLength: 1, maxItem: 8, maxItemPerGroup: 6, order: "asc", hint: true, loadingAnimation: true, cancelButton: true, 
                    emptyTemplate: "Aucune rame n'existe avec {{query}}",
                    group: { key: "SousSerie", template: "{{group}} SousSérie" }, group: "SousSerie",
                    display: ["EAB", "NumEF"],
                    template: "{{EAB}}",
                    source: json.data,
                    dropdownFilter: _tblFilterTypeHead, 
                    callback: {
                        onClickAfter: function (node, a, item, event) {   
                            RameSelected = item; 
                        },
                        onResult: function (node, query, result, resultCount) {
                            if (resultCount == 1) { RameSelected = result[0]; $("#RameInput").val(RameSelected.EAB); }

                            if (resultCount > 0)    RameSelected = result[0];  
                            else                    RameSelected = { ID: 0, EAB: "0", NumEF: "0", IdRexM: 0, IdSerie: 0, IdSousSerie: 0, Serie: "0", SousSerie: "0", CodeSerie: "0", IdFlotteOsm: 0 };

                            if ((query != '' && resultCount == 1) || RameSelected.EAB == '0') actualiseDataSemelle();
                            },
                        onNavigateAfter: function (node, lis, a, item, query, event) { if (item) RameSelected = item; },
                        onNavigateBefore: function (node, query, event) {
                            if (event.keyCode == 13) {
                                $("#RameInput").val(RameSelected.EAB);
                                if (query != '') 
                                    actualiseDataSemelle();
                            }
                        },
                        onCancel: function (node, event) {
                            RameSelected = { ID: 0, EAB: "0", NumEF: "0", IdRexM: 0, IdSerie: 0, IdSousSerie: 0, Serie: "0", SousSerie: "0", CodeSerie: "0", IdFlotteOsm: 0 };
                            actualiseDataSemelle();
                        },
                        onDropdownFilter: function (node, query, dropdownFilter, result) {
                            var t = 1;
                        }
                    }
                });
            });

**Comment by sergefabre** [comment]
hum... onDropdownFilter is fired hen I select an element in dropdownlist, but after used on shot then inputbox... ??

**Comment by sergefabre** [comment]
onDropdownFilter is not call if I use DropDownFilter in first, before I whrite in the SearchInputText

**Comment by running-coder** [comment]
yep, `onDropdownFilter` will be called when a filter is changed, if you need an event to be fired on load you can `onReady` or another callback
