### ISSUE TITLE
event onCancel version 2.7.6

### ISSUE THREAD

**Issue by sergefabre** [running-coder/jquery-typeahead#274]
Hello,
When I use version 2.7.1, the callback onCancel work with a click of cancelButton.
With the version 2.7.6, callback onCancel is not trigged...

Can you help Me please ?

**Comment by aellis** [comment]
I was experiencing this as well and found it was tied to line 653 where it currently says this:

`if (scope.rawQuery === "" && scope.query !== "") {`

In my testing, rawQuery was "" here but query was as well which caused lines 654 and 655 to not be hit.  I believe 2 minor edits resolve this:

1. Move line 658 before line 653 (I think it is being evaluated before it is being tested here).
2. Change line 653 to read like so:

`if (scope.rawQuery === "" && scope.query === "") {`

Unless I am missing something completely - but in my testing this seemed to resolve everything with no newly introduced issues.

**Comment by aellis** [comment]
One more note - I am still learning my way around GitHub in order to know how to formally submit this the correct way, but if you want to test out the change I forked it to here with the changes:

https://github.com/aellis/jquery-typeahead

**Comment by running-coder** [comment]
Hey, thanks for flagging the issue!

It is indeed caused by a regression introduced by `resetInput` function clearing the query before triggering the `input` event. I'll add a test and modify the code to @aellis 's suggestion if it does not impact anything.
