### ISSUE TITLE
how to fetch data from function instead of ajax or json data URL?

### ISSUE THREAD

**Issue by kanjaniparersh** [running-coder/jquery-typeahead#277]
function OfflineSearch($FormName,$FieldName) 
    {
    
    $.typeahead({
        input: $FieldName,
        minLength: 3,
        order: "asc",
        dynamic: true,
        delay: 500,
        backdrop: {
            "background-color": "#fff"
        },
        template: function (query, item) {

            return '<div class="searchresultrow" style="vertical-align:top">' +
                '<span class="PatientPhoto">' +
                '<img src="./image/HeadIcon.png" height=30 width=30 class="img-circle">' +
                '</span>' +
                '<span class="LastName">&nbsp;{{FirstName}} {{LastName}} &nbsp;({{Qualifications}})</span><div style="margin:0px 0px 0px 30px;"><small>&nbsp;<i class="fa fa-phone" style=""></i>&nbsp;{{PhoneNumber}}</small></div>' +
                '<span class="ID" style="display:none">({{ID}})</span>' +
                '</div>'

        },
        correlativeTemplate: ["FirstName", "LastName"],
        emptyTemplate: "",
        source: {
            user: {
                display: ["FirstName", "LastName", "PhoneNumber"],
                data: [OfflineSearchDoctorData()]
               
            }
        },
        callback: {
            onClick: function (node, a, item, event) {
                $(FormName).val(item.ID);
                if($FormName == "ShareChartForm")
                {
                    
                    $('#ShareChartForm').formValidation('revalidateField', 'SearchedDoctorID');
                    DrawDoctorDetailOnShareCahrt(item);
                }
            },
            onResult: function (node, query, result, resultCount, resultCountPerGroup) {
                if (resultCount == 0) {
                    $("#SearchedDoctorID").val("");
                }
            }
        }
    });

}
    function OfflineSearchDoctorData() 
    {

        var datainjson='{"data":[{"ID":"1","LastName":"Shah","FirstName":"Santosh","PhoneNumber":"5555555555","Qualifications":"Awards and Recognitions","Details":"Awards and RecognitionsAwards and RecognitionsAwards and RecogniAwards and RecognitionsAwards and RecognitioAwards and RecognitioAwards and Recognitionsnsnstions","DoctorPhoto":"upload_user_pic\/3.jpg"},{"ID":"12","LastName":"Shah","FirstName":"Santosh","PhoneNumber":"Not Available","Qualifications":"","Details":"","DoctorPhoto":"\/upload_user_pic\/NoPhotoYet.png"},{"ID":"13","LastName":"Shah","FirstName":"Santosh","PhoneNumber":"Not Available","Qualifications":"","Details":"","DoctorPhoto":"\/upload_user_pic\/NoPhotoYet.png"},{"ID":"14","LastName":"Shah","FirstName":"Santosh","PhoneNumber":"Not Available","Qualifications":"","Details":"","DoctorPhoto":"\/upload_user_pic\/NoPhotoYet.png"}]}';
           
            var json_data=JSON.parse(datainjson);

            return json_data.data;

        
    }

**Comment by running-coder** [comment]
hey, doesnt "data: OfflineSearchDoctorData()" works?

**Comment by running-coder** [comment]
you can also use async function (Promises), examplefrom the doc:

```
// Async request using the data function
source: {
    teams: {
        data: function () {
 
            var deferred = $.Deferred();
 
            // Gather your data, and resolve the deferred object with an array of objects
            // setTimeout is used only to show that the data is async
            setTimeout(function () {
                if (Array.isArray(data) {
                    deferred.resolve(data);
                } else {
                    deferred.reject("Invalid data.");
                }
            }, 2000);
 
            deferred.always(function () {
                console.log('yay! :D')
            });
 
            return deferred;
        }
    }
}
```
