### ISSUE TITLE
How to set initial value?

### ISSUE THREAD

**Issue by AliAkbarLatifi** [running-coder/jquery-typeahead#278]
I'm trying to initialize a typeahead input field with a previously saved option. What's the right way to go about selecting the option in the form?

**Comment by running-coder** [comment]
Hey, if I get you right you want to load a page with a query already in the input and generate results? There is currently no option for that but you can use Typeahead events to generate it. You can look into the doc in the extra section and write something like: Typeahead[SELECTOR].node.val('thevalueyouwant').trigger('input.typeahead');

**Comment by running-coder** [comment]
closing, no reply
