### ISSUE TITLE
Dynamically building source

### ISSUE THREAD

**Issue by ajaichandran** [running-coder/jquery-typeahead#279]
I would like to serach by multiple categories and source will be dynamic.http://www.runningcoder.org/jquerytypeahead/demo/#form-user_v1
in above example user and project .Some times user,project,grade..
i will pass search param as object like this {name:"name",project:"project"} .How can i build source inside a loop .Is it possible.
The code i am trying is below

```javascript
source: function(query, process)
{
    var values = [];
    var params = {name:"name",project:"project"}
    $.each(params, function(key,val) {

        values.push(
            {key:{
                display: key,
                ajax: function (query) {
                    return {
                        type: "POST",
                        url: base_url+"search/suggestEntity",
                        path: "data."+key,
                        data: {
                            search_text: query,entity:entity
                        },
                        callback: {
                            done: function (data) {
                                return data;
                            }
                        }
                    }
                },
                template: function (query, item) {
                    var template =  '<span class="row">' +
                        '<span class="name">{{'+key+'}} ';


                    template +=  "</span>";
                    return template;
                }
            }
            }

        );
    });

    return values;
},
```

**Comment by running-coder** [comment]
hey @ajaichandran, the source option is only evaluated once, on the init. So if you define 2 groups and afterwards you need a 3rd one it will be too late. You can define all your groups in the source option and from inside the ajax function return false (to not do the request for group z if condition x).

**Comment by ajaichandran** [comment]
Thank you for the help.

I have to implement search in different page with different groups.The groups will be different for different searches.Some pages it is user and project.Some other page it will be group and activities ...
So what  i thought to implement a common function like below

FILTER		={					
                show_filter : function(filter_obj,search_param,entity)
				{         
                  	$('#'+filter_obj).typeahead({
						minLength: 1,
						order: "asc",
						group: true,
                        debug: false,
                        dynamic: true,
                        maxItem: 0,
						delay: 500,
                        backdrop: {
                            "background-color": "#fff"
                        },                                       
                        source: {/*dynamic source by iterating search_param*/}						
						});              
                    }
			 };
             
  Then i will call this function in html pages like this .My aim is not to hardcode groups in
  js file.Instead group will bind dynamically to object.If there are ten groups, defining it in
  js wont be a good practice. I think I have explained it properly. 
 -------------------------------------------------------------------------------            
 FILTER.show_filter('user_filter',{name:{"name","username"},project:"project"},'users');
 FILTER.show_filter('group_filter',{name:"name",activity:"activity"},'groups');
 /* user filter and gorup_filter are ids of input text*/
 /* second parameter is group.I want to search by user and project */
 -------------------------------------------------------------------------------          
 Once again thank you for replying

**Comment by running-coder** [comment]
a couple of things to change
```javascript
FILTER = {
    show_filter: function (filter_obj, search_param, entity) {
        $('#' + filter_obj).typeahead({
            minLength: 1,
            order: "asc",
            group: true,
            debug: false,
            dynamic: true,
            maxItem: 0,
            delay: 500,
            backdrop: {
                "background-color": "#fff"
            },
            source: (function () {
                var groups = {};
                for (var group in search_param) {
                    (function (group, keys) {
                        groups[group] = {
                            display: keys,
                            ajax: function (query) {
                                return {
                                    type: "POST",
                                    url: base_url + "search/suggestEntity",
                                    path: "data." + group,
                                    data: {
                                        search_text: query, entity: entity
                                    },
                                    callback: {
                                        done: function (data) {
                                            console.log(data)
                                            return data;
                                        }
                                    }
                                }
                            },
                            template: function (query, item) {
                                var template = '<span class="row">' +
                                        '<span class="name">{{' + group + '}}</span>';
                                template += "</span>";
                                return template;
                            }
                        }
                    })(group, search_param[group])
                }
                console.log(groups)
                return groups;
            })(),
            debug: true
        });
    }
}

FILTER.show_filter('user_filter', {name: ["name", "username"], project: "project"}, 'users');
```

**Comment by ajaichandran** [comment]
Many thanks.We will test above code .
