### ISSUE TITLE
Default Suggestions

### ISSUE THREAD

**Issue by sambenne** [running-coder/jquery-typeahead#280]
This is a nice plugin. But I am wanting to do something which I am unsure if this can do it. Basically what I want to do is when clicking the input it will automatically show some suggestions just like the results. When you start typing the suggestions go away unless the input is empty.

**Comment by running-coder** [comment]
Hey @sambenne I had this idea a while back but never implemented it. This could be used to save the "previous searches" as well up to X input characters. Definitly a cool thing to implement in a future release

**Comment by running-coder** [comment]
A demo is added inside `develop` branch on how to use it
