### ISSUE TITLE
Issue from multi level deep data inside source objects

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#281]
I've got a dataset which is an array of objects, something like this :
```json
{"waarden2":[{"klant":{"t118achternaam":"Verberck , ... },"patient":{"t120naam":"Aiko", ...}},{"klant":{"t118achternaam":"Ibens", ...},"patient":{"t120naam":"Aiko", ... }}]}
```
My code 
```javascript
$.typeahead({
        input: "#l01b",
        order: "asc",
        maxItem: 50,
        minLength: 3,
        cancelButton: false,
        dynamic: true,
        display: ["patient.t120naam", 
                    "patient.t120ras",
                    "patient.t120ras2",
                    "patient.t120identificatie",
                    "patient.t120paspoort",
                    "patient.t120opmerking",
                    "patient.t120anafylaxie",
                    "patient.t120soort",
                    "klant.t118achternaam",
                    "klant.t118straat",
                    "klant.t118postcode",
                    "klant.t118gemeente"],
        template: function () {
            return "{{patient.t120naam}}" + " " + "{{klant.t118achternaam}}" + ",  " + "{{patient.t120ras}}" + "<br/>" + "{{klant.t118straat}}" + " " + "{{klant.t118huisnummer}}" + ",  " + "{{klant.t118postcode}}" + " " + "{{klant.t118kenletters}}" + " " + "{{klant.t118gemeente}}";
        },
        emptyTemplate: "geen resultaten gevonden voor {{query}}",
        source: {
            klanten: {
                ajax: function (query) {
                    return {
                        type: "GET",
                        path: "waarden2",
                        url: "/vf/rest/patienten/T120_05?",
                        data: {
                            q: query
                        }
                    };
                }
            }
        },
        callback: {
            onResult: function (node, query, result, resultCount) { 
                if (resultCount === 1) {
                    vm.input_l01a = result[0]; 
                    vm.resultCount_l01a = resultCount;
                }
            },
            onNavigateBefore: function (node, query, event) {
                if (event.keyCode === 13 && vm.resultCount_l01a === 1) {
                    vm.findPatient(vm.input_l01a.patient.t120klantid, vm.input_l01a.patient.t120patientid);
                    $("[tabindex=2]").focus();
                }
            },
            onNavigateAfter: function (node, lis, a, item, query, event) {
                if (~[38,40].indexOf(event.keyCode)) {
                    var resultList = node.closest("form").find("ul.typeahead__list"),
                        activeLi = lis.filter("li.active"),
                        offsetTop = activeLi[0] && activeLi[0].offsetTop - (resultList.height() / 2) || 0;
                    resultList.scrollTop(offsetTop);
                }
            },
            onClickAfter: function (node, a, item, event, data) {
                vm.input_l01a = item;
                $("[tabindex=2]").focus();
                vm.findPatient(item.patient.t120klantid, item.patient.t120patientid);
            }
        }
    });
```
everything works fine untill i select a line, then i get the error :

Uncaught TypeError: Cannot read property 'toString' of undefined
    at HTMLLIElement.<anonymous> (jquery.typeahead.js:1852)
    at HTMLLIElement.dispatch (jquery-2.1.0.min.js:3)
    at HTMLLIElement.r.handle (jquery-2.1.0.min.js:3)

Can't figure it out how to fix this issue :-(

**Comment by GDM70** [comment]
When I use OnClick instead of OnClickAfter it works but I still get the same error mentioned above.

**Comment by running-coder** [comment]
Hey @GDM70 would you be able to provide me a complete JSON response of 2-3 items? Would need it for debuging

**Comment by GDM70** [comment]
Hi Tom,

 

I send it via email because it contains actual data :

 

{"waarden":[{"klanten":{"t118achternaam":"Van Hecke","t118afhaal":false,"t118debet":0.0000,"t118dierenarts":"","t118doorgestuurd":false,"t118gemeente":"Putte-Kapellen","t118gsm":"0473/45.50.94","t118gsminfo":"Tinneke","t118huisnummer":"26","t118id":228,"t118klantid":233,"t118korting":0,"t118laatste":"2004-01-02T00:00:00+01:00","t118land":"BelgiÃ«","t118nieuwsbrief":false,"t118postcode":"2950","t118praktijk":1,"t118status":"A","t118straat":"Partizanenstraat","t118taal":"nederlands","t118tel":"664.02.19","t118voornaam":"Tinneke","t118wachtdienst":false,"t118zone":" 03"},"patienten":{"t120emailverzonden":false,"t120emailverzonden2":false,"t120geboortedatum":"1997-06-10T00:00:00+02:00","t120geslacht":"VN","t120gewicht":27.6000,"t120haarkleur":"blond","t120id":301,"t120idg":4,"t120klantid":233,"t120letter":"m","t120letterras":"A","t120naam":"Babette","t120patientid":306,"t120praktijk":1,"t120printen":true,"t120printen2":true,"t120ras":"Golden Retriever","t120rasid":245,"t120soort":"Ca","t120status":"D","t120verzonden":false,"t120verzonden2":false,"t120vp":false}},{"klanten":{"t118achternaam":"Stoffels","t118afhaal":false,"t118debet":0.0000,"t118dierenarts":"","t118doorgestuurd":false,"t118gemeente":"Kapellen","t118id":1163,"t118kenletters":"","t118klantid":1224,"t118korting":0,"t118laatste":"2004-08-18T00:00:00+02:00","t118land":"BelgiÃ«","t118nieuwsbrief":false,"t118postcode":"2950","t118praktijk":1,"t118status":"A","t118straat":"Roerdomplei","t118taal":"nederlands","t118wachtdienst":false,"t118zone":" 03"},"patienten":{"t120emailverzonden":false,"t120emailverzonden2":false,"t120geboortedatum":"2002-11-21T00:00:00+01:00","t120geslacht":"V","t120gewicht":38.0000,"t120haarkleur":"normaal","t120id":1718,"t120identificatie":"967000000659952","t120idg":4,"t120klantid":1224,"t120letter":"n","t120letterras":"A","t120naam":"Babette","t120patientid":1773,"t120praktijk":1,"t120printen":true,"t120printen2":true,"t120ras":"Berner Sennenhond","t120rasid":73,"t120soort":"Ca","t120status":"L","t120verzonden":false,"t120verzonden2":false,"t120vp":false}},{"klanten":{"t118achternaam":"Van Bokhorst","t118afhaal":false,"t118debet":0.0000,"t118dierenarts":"","t118doorgestuurd":false,"t118gemeente":"Stabroek","t118gsm":"0485/72.88.53","t118gsminfo":"Deborah","t118huisnummer":"16","t118id":2170,"t118kenletters":"","t118klantid":2016,"t118korting":0,"t118land":"BelgiÃ«","t118nieuwsbrief":false,"t118opmerking":"Sofie Van Dijck","t118postcode":"2940","t118praktijk":1,"t118status":"A","t118straat":"Abtsdreef","t118taal":"nederlands","t118wachtdienst":true,"t118zone":" 03"},"patienten":{"t120beharing":"langharig","t120emailverzonden":false,"t120emailverzonden2":false,"t120geboortedatum":"2009-03-01T00:00:00+01:00","t120geslacht":"V","t120gewicht":2.5000,"t120haarkleur":"blue creme","t120id":3090,"t120idg":41,"t120klantid":2016,"t120letter":"n","t120letterras":"B","t120naam":"Babette","t120patientid":3040,"t120praktijk":1,"t120printen":false,"t120printen2":false,"t120ras":"Scottish Fold","t120rasid":505,"t120soort":"Fe","t120status":"L","t120verzonden":false,"t120verzonden2":false,"t120vp":false}},{"klanten":{"t118achternaam":"Jansen","t118afhaal":false,"t118debet":0.0000,"t118doorgestuurd":false,"t118gemeente":"Putte-Kapellen","t118huisnummer":"43","t118id":2644,"t118kenletters":"","t118klantid":2395,"t118korting":0,"t118land":"BelgiÃ«","t118nieuwsbrief":false,"t118opmerking":"niet komen opdagen op hervaccinatie \r\nop datum van 17/08 18.20u","t118postcode":"2950","t118praktijk":1,"t118status":"A","t118straat":"Pannenhoefdreef","t118taal":"nederlands","t118tel":"664.09.15","t118voornaam":"Louis","t118wachtdienst":false,"t118zone":" 03"},"patienten":{"t120beharing":"kortharig","t120emailverzonden":false,"t120emailverzonden2":false,"t120geboortedatum":"2012-05-01T00:00:00+02:00","t120geslacht":"VN","t120haarkleur":"tijger + wit","t120id":6347,"t120idg":41,"t120klantid":2395,"t120letter":"m","t120letterras":"B","t120naam":"Babette","t120patientid":6281,"t120praktijk":1,"t120printen":false,"t120printen2":false,"t120ras":"Fv","t120rasid":236,"t120soort":"Fe","t120status":"L","t120verzonden":false,"t120verzonden2":false,"t120vp":false}}]}

 

 

 

Sincerely,

Gert De Meulenaere

 <http://www.vet-files.com/> www.vet-files.com

info@vet-files.com

TEL : +3236056238

Logo-r

 

Van: Tom Bertrand [mailto:notifications@github.com] 
Verzonden: dinsdag 17 januari 2017 16:24
Aan: running-coder/jquery-typeahead
CC: GDM70; Mention
Onderwerp: Re: [running-coder/jquery-typeahead] problem with array (#281)

 

Hey @GDM70 <https://github.com/GDM70>  would you be able to provide me a complete JSON response of 2-3 items? Would need it for debuging

**Comment by GDM70** [comment]
Hey can I email it to you ?

**Comment by running-coder** [comment]
Hey Gert, thanks for sending the data I was able to reproduce the issue. Not many tests were made from the muti level deep data from source objects. The issue was caused from not selecting the proper `matchedKey`, it should be resolved now in the `develop` branch and will go in the next release.

Let me know if you get other issues, Thanks again.

**Comment by GDM70** [comment]
Thank You ! Works perfect.
Great app, couldn't do without it anymore.
