### ISSUE TITLE
How to make one of the data tagged to the searched "term" in var data a php variable?

### ISSUE THREAD

**Issue by BenjaminUAV** [running-coder/jquery-typeahead#282]
Hi, I am a beginner to website programming and trying to learn the Jquery search bar. I am very interested in your work which gave me the idea to try it out. However when I'm trying, I encounter some issue with trying to get the "searched-term" saved as a variable in PHP. I am using $area=$_GET["area"]. Of all the 3 data displayed, I only want to send the "area" data to be a PHP variable, $area.

Please help to enlighten me, pardon for my poor knowledge in PHP and jquery :)

What I did:
Downloaded the demo file and opened demo-hockey_v1.html. I edited the var data (see below) and its corresponding display, template etc...  ---> Tested and is working well on HTML.

<span class="typeahead__query">
                <input class="js-typeahead-input"
                       company="q"
                       type="search"
                       autofocus
                       autocomplete="off">

var data = [
           {
            "company": "ABC ",
            "area": "north",
            "value": "1",
 
        }, {
            "company": "DEF ",
            "area": "south",
            "value": "5",
           
        }, {
            "company": "GHI ",
            "area": "east",
            "value": "3",
           
        }
		];

**Comment by running-coder** [comment]
Hey @BenjaminUAV welcome to programming! Where you will spend a great amount of sleepless nights hehe. Regarding your question there multiple ways you can do it. You can have an hidden input in your form named "area" and with the `onClickBefore` callback from Typeahead you populate that input with the area data (so it will get submitted into your form Here are some pesudo code.

```
<form method="GET">
    Typeahead code here...
    <input type="hidden" name="area" value="">
</form>

$.typeahead.init({
    ...
    callback: {
        onClickBefore: function (node, a, item, event) {
            $('input[name=area]').val(item.area);
        }
    }
})
```

**Comment by BenjaminUAV** [comment]
Thanks for the advice :) I am quite noob here. I encountered another problem when I save the demo_hockey_v1.html as a php file, the jquery does not seem to work

**Comment by BenjaminUAV** [comment]
I did what you advise too, but I seem to break the code somewhere. Very lost here :(

<form method="GET">
        <div class="typeahead__container">
            <div class="typeahead__field">
            <span class="typeahead__query">
                <input class="js-typeahead-input"
                       name="area"
                       type="hidden"
                       autofocus
                       autocomplete="off">
            </span>
            <span class="typeahead__button">
                <button type="submit">
                    <span class="typeahead__search-icon"></span>
                </button>
            </span>
            </div>
        </div>
</form>

    <script>

        var data = [{
            "shape": "CNMC Goldmine Holdings Limited ",
            "area": "10m2",
            "volume": "10",
           
        }, {
            "shape": "Nordic Group Limited ",
            "area": "5m2",
            "volume": "10",
           
        },
		];

        typeof $.typeahead === 'function' && $.typeahead({
            input: ".js-typeahead-input",
            minLength: 0,
            maxItem: 8,
            maxItemPerGroup: 6,
            order: "asc",
            hint: true,
            searchOnFocus: true,
            group: {
                key: "volume",
                template: function (item) {

                    var volume = item.volume;
                    if (volume.toLowerCase() === "10") {
                        volume += " Yay!123";
                    }

                    return volume;
                }
            },
            emptyTemplate: 'no result for {{query}}',
            groupOrder: ["10", "5"],
            display: ["shape", "area"],
            correlativeTemplate: true,
            dropdownFilter: [{
                key: 'volume',
                template: '<strong>{{volume}}</strong> volume',
                all: 'volumes'
            }, ],
            template: '<span>' +
            '<span class="shape">{{shape}}</span>' +
            '<span class="area">({{area}}, {{volume}} volume)</span>' +
            '</span>',
            callback: {
				onClickBefore: function (node, a, item, event) {
					$('input[name=area]').val(item.area);
					}
				}
            debug: true
        });

    </script>

**Comment by running-coder** [comment]
you removed the source?

your init needs
```
source: {
    GROUPNAME: {
        data: data
    }
}
```

**Comment by BenjaminUAV** [comment]
I updated the code with the source inside and the html file is able to run but I still cannot get the "searched-term" into a php variable. Is there a documentation with step by step guide that I can look up?

**Comment by BenjaminUAV** [comment]
Hey, I tried everyday thinking how to solve it and managed to get it working :). I am using OnClickAfter callback.

How can I allow the users to search with 1st suggestion if the user did not click on the suggestion? Is there a function to allow automatic search based on first suggestion?

**Comment by running-coder** [comment]
you can use the `onResult (node, query, result, resultCount, resultCountPerGroup)` callback to modify the input's text with the `result[0]` object if you want. Is that what you need?
