### ISSUE TITLE
Hide autocomplete suggestions when tabbed out of input

### ISSUE THREAD

**Issue by hsdhott** [running-coder/jquery-typeahead#284]
Hello,

I am using tabs to navigate through multiple typeaheads. When I tab over input, the focus goes to autocomplete suggestions. Is there a way that tabbing would takes the focus to next input box instead of suggestions.

https://jsfiddle.net/hsdhott/r6dybacw/

**Comment by running-coder** [comment]
hey @hsdhott the TAB was discussed a numerous times but I think your solution might be optimal. I'll implement an option to have either.

**Comment by running-coder** [comment]
Should be good now, tab now also closes the Typeahead if it's focusing it out.

**Comment by hsdhott** [comment]
Hi,

Thank you for the quick response. It is working great.

One thing I wanted to suggest was that in current version it takes 2 tabs to get focus on next item as you can see in provided jsfiddle.

https://jsfiddle.net/hsdhott/r6dybacw/

When the focus in first input (results open of that input box). It take 2 tabs to get focus onto next input. Then 2 more to get the focus on the following anchor tag. Would it be possible that one tab would also get the focus on next item in line.

Thank you

**Comment by running-coder** [comment]
Hey @hsdhott is it a very weird behavior... it takes 2 in chrome but 1 in firefox, I'll investigate if it's possible to have 1 crossbrowser. Meanwhile you can always the HTML5 tabindex.

**Comment by running-coder** [comment]
This attempt should be the good one!

**Comment by hsdhott** [comment]
Hey Tom,

I just checked. It's looking great.

Thanks
