### ISSUE TITLE
Using dynamic, groupOrder and groupTemplate options, the results are empty after the second search

### ISSUE THREAD

**Issue by tgmweb** [running-coder/jquery-typeahead#286]
I know I opened this ticket a few weeks ago, but what I thought fixed it, didn't.

I've created a fiddle to demonstrate the issue

https://jsfiddle.net/qrq5m948/5/

Basically, search for something (anything), and you'll get 2 results (dynamic search is on, filter is off, but it's just returning json so you should get the same results every time). 

Search again however, and nothing is returned. Search again (for the same thing as the first time), and once again nothing is returned.

Remove the groupTemplate and group :{template} options and it works as expected - it returns a result each time.

I'm guessing the combination of the template and the dynamic:true and filter:false is causing this when it doesn't cause issues in other scenarios...

Thanks,

Tom.

**Comment by running-coder** [comment]
This was not related with the previous issue we had, it was due to a combination of options, let me know if it fixed the issue

Thanks for reporting!

**Comment by tgmweb** [comment]
Yep, that's resolved it!

Awesome! 👍
