### ISSUE TITLE
Number of shown results

### ISSUE THREAD

**Issue by franszo** [running-coder/jquery-typeahead#287]
Hi there , again. 

Just wondering is there any possibility to add a new option where user could define how many results would be great to see in the list.

For example I am searching maxItem = 20, but filtering with a select field, so results can be 10 - 15 items, BUT i would like to only see the first 3, so an option with Number of shown results would be really awesome.  (ie: limit : 3 )

Please let me know if any above needs clarification.

Best regards : franszo

**Comment by franszo** [comment]
Hey,

Thanks for quick response,

Had exactly the same idea , sorted my propblem already , just wanted propose as a new , easy and quick idea.

Many thanks btw ;)

Thanks for still supporting this!

**Comment by running-coder** [comment]
no problem, I try to avoid adding option for edge cases else there would be too many. The matcher and filter are supposed to be used for such customization.

Thanks for the feedback

**Comment by franszo** [comment]
Hi @running-coder 

Sorry have to say 

```
matcher: function (item, value) {
   console.log('matcher');
}
```

the function not even running, nor in / outside the source {}, any thoughts?

**Comment by franszo** [comment]
oh I see, If I use filter, marcher will not be interpreted
