### ISSUE TITLE
Show item list on search fields focus/click

### ISSUE THREAD

**Issue by pradeshc** [running-coder/jquery-typeahead#29]
I want to display the dropdown list of available options when I click on the search field, (or focus on it).

Currently, I am forced to type a search filter in the search field in order to trigger the dropdown portion.

**Comment by running-coder** [comment]
hey pradeshc,

if I understand correctly, you would like an option to display the results on focus in if there is a search string inside the input?

**Comment by pradeshc** [comment]
correct, running-coder, similar to 
http://xdsoft.net/jqplugins/autocomplete/

Notice that the dropdown list is selected when you click the search field

**Comment by running-coder** [comment]
Gotcha, that's indeed a cool feature to add! It will go into the 2.0 version, hopefully I get some time to complete and build a RC within a couple days.

Thanks for the suggestion!

**Comment by pradeshc** [comment]
Works well. Thank you for accepting my request.

**Comment by running-coder** [comment]
Good to hear! You are very welcome to continue giving your feedback & suggestions!

Thanks
