### ISSUE TITLE
Android Keyboard disappears

### ISSUE THREAD

**Issue by jtabachnick** [running-coder/jquery-typeahead#293]
When clicking into the search bar the keyboard comes up, but then immediately disappears. Other inputs on the site do not seem to have this issue. Any suggestions?

**Comment by running-coder** [comment]
No idea, might get caused by a change of focus on the input? Will have to grab one of these device and investigate what happens

**Comment by running-coder** [comment]
I've tested from the runningcoder.org demos and could not reproduce. It can be the options you are using, can you add your init configuration?

**Comment by kavin-90** [comment]
same here i try it on localhost but when i click on search filed it hide keyboard and search box.

**Comment by running-coder** [comment]
Will have to do more testing. Are you using an android phone? nexus, galaxi, pixel, other?

**Comment by kavin-90** [comment]
I'm using Le1s eco phone to browser is google chrome.

**Comment by jtabachnick** [comment]
I tired on both Samsung Galaxy S5 and a Pixel. We think it is caused by a CSS issue, but have not fully diagnosed the problem yet.

**Comment by kavin-90** [comment]
Maybe that effect only on chrome.

**Comment by running-coder** [comment]
possible cause? http://stackoverflow.com/questions/36529050/jquery-on-android-focus-makes-keyboard-appear-disappear

**Comment by kavin-90** [comment]
I do have `$(window).resize` event to show search when screen resize > 500+ maybe that cause it gonna test it now. thanks @running-coder

**Comment by running-coder** [comment]
@jtabachnick can you confirm this issue is also curring for you? In that case, not much Typeahead can do, you'll have to resize and then re-focus the field `window.Typeahead['.SELECTOR'].node.focus()`
