### ISSUE TITLE
question promise instead ajax?

### ISSUE THREAD

**Issue by publicocean0** [running-coder/jquery-typeahead#296]
hi in possible to pass a promise , not ajax ?

**Comment by running-coder** [comment]
hey, yes it's hidden somewhere in the `options.source` documentation

```javascript
// Async request using the data function
source: {
    teams: {
        data: function () {
 
            var deferred = $.Deferred();
 
            // Gather your data, and resolve the deferred object with an array of objects
            // setTimeout is used only to show that the data is async
            setTimeout(function () {
                if (Array.isArray(data) {
                    deferred.resolve(data);
                } else {
                    deferred.reject("Invalid data.");
                }
            }, 2000);
 
            deferred.always(function () {
                console.log('yay! :D')
            });
 
            return deferred;
        }
    }
}
```

**Comment by publicocean0** [comment]
thanks just another question:

it is possible to pass different container for typeahead? 
I thought to use your plugin in my plugin that use inside it. But if you put div with position absosolute bottom  input text ... it create a problem

**Comment by running-coder** [comment]
you can look into [game_v3 demo](http://www.runningcoder.org/jquerytypeahead/demo/#form-game_v3)
> Defining resultContainer: '#champion-list' means that the Typeahead results will be displayed inside the specified container

**Comment by publicocean0** [comment]
cool :) i think i will use your plugin instead to write from scratch. 
Just a suggestion for future emprovements. 
Considering this plugin has multiple usage and multiple platform (mobile,brower,...) you could add preprocessing flag so developer can produce a light javascript file targetting for the specific use. 

In my case i begun to develop some simple plugin using it. Using bower & bindep i can produce the specific js file just with a command line for a entire web project (using multiple plugins).

**Comment by running-coder** [comment]
thanks for the feedback @publicocean0 , indeed this plugin is doing tons of stuff in most cases people might not need. The project started 3 years ago if i remember and the code is getting pretty old already (aka no es6/7).
