### ISSUE TITLE
Force selection

### ISSUE THREAD

**Issue by legionio** [running-coder/jquery-typeahead#298]
Hi,

Is it possible with this plugin to force the user to use one of the suggestions? I don't want them to be able to have any other value besides what has been selected. I have multiple fields that will be dynamically generated on the page. They all need this functionality...

Is this possible?

```
$.typeahead({
    input: ".searcht",
    display: ["brand.name", "name"],
    source: {
      ajax: {
        url: '/find',
        dataType: 'json',
        data: {
            q: '{{query}}'
        }
      }
    }
  },
    maxItem: 0,
    debug: true,
    dynamic:true,
    hint:true,
    cancelButton:true,
    mustSelectItem: true
});
```

This is not a traditional form, it would be a lot easier if we can avoid checking values server sided. The typeahead searches products in my database and I plan to bind the product id that's passed inside my data to each input. This way I know what products have been selected when I submit the form, to match with database product id's. They all need to be unique too... hmmm.

**Comment by running-coder** [comment]
Hey @legionio , yes `mustSelectItem` should prevent you from sending the form unless an item have been selected (from the typeahead input). If you have multiple Typeaheads you can always use the `matcher` function to filter out other Typeahead's values, ex:

```
$.typeahead({
...
matcher: function(item) {
// This will filter out the other selected items from other Typeaheads (adjust the condition)
    if (item.id === idStoredInHiddenInput) {
        return;
    }
    return true;
// return undefined to skip to next item
// return false to attempt the matching function on the next displayKey
// return true to add the item to the result list
// return item object to modify the item and add it to the result list
}
})
```

best would be if you can build a demo on jsfiddle or some other website and we would go from there
