### ISSUE TITLE
Two non-correlative words

### ISSUE THREAD

**Issue by khanatos** [running-coder/jquery-typeahead#30]
Help enough to introduce two words and the script look both in a sentence
for example:

search [France Paris]

and the phrase "Paris is the capital of France"

**Comment by running-coder** [comment]
Hey khanatos,

this is a feature in the upcoming version 2.0

you will be able to set:

``` javascript
display: ["city", "country", "third index", "etc"]
```

**Comment by khanatos** [comment]
great!

**Comment by giantocotpus** [comment]
Hi guys - not sure if this is currently implemented of if I'm interpreting this incorrectly but i have the following setup:

display: ["name", "primary_variation","category"]

and

template: "{{name}}, {{primary_variation}} <small><em>{{category}}</em></small>",

but if I search for a for two non correlative words, It doesn't seems to work across the name, primary and category fields

**Comment by running-coder** [comment]
hey octopus,

perhaps I was the one to missunderstand the original question.. the display array is meant to search through multiple object keys. The feature currently does not combine them so you have to search for only 1 term at a time... 

If I understand correctly you wish to be able to type multiple keys and still see the search result if these keys belong to the same object?

**Comment by giantocotpus** [comment]
Hey thanks for the speedy response - very much appreciated

Yes essentially I want to search for '**oak**' and '**chairs**'

In my template output ( "{{**name**}}, {{**primary_variation**}} {{**category**}}" ) I might show something like:
**Big Chair**, **White Oak**, **Dining Chairs**

If I would search for **chair** or **oak** I would get the result above, but if I used both terms I then I don't.

Does that makes sense? Sorry I'm finding it difficult to explain clearly.

**Comment by running-coder** [comment]
Got it, your example is pretty clear. I've thought of implementing it a while ago but if I remember correctly I did not have a clear & simple solution. Perhaps I can give it another try once I'm done with the new dynamicFilter option.

Thanks for using the plugin and the suggestion, I'll reopen this issue and reference it once it's ready

**Comment by giantocotpus** [comment]
Legend - thanks for a great plugin and being very proactive
