### ISSUE TITLE
How to set the submitted variable?

### ISSUE THREAD

**Issue by superciccio14** [running-coder/jquery-typeahead#300]
Hi there. I'm sorry if this question could be trivial. I'm consuming via AJAX a list of objects like the following:

    { 
      'foo' : 'fooooooo'
      'bar' : 'baaaaaar'
      'baz' : 'baaaaaaz'
    }

I use `jquery-typeahead` displaying `foo` and `bar` values. It's great! Once an object is selected by user, I would like to pass to another url the value of `baz` (e.g., `http://myurl/baaaaaaz`). How can I do that?

**Comment by running-coder** [comment]
hey @superciccio14 , when an item is selected it goes through the onClick callback and the item is passed as a param. From there you can do anything (generate a url from the item properties, populate a hidden field)

**Comment by superciccio14** [comment]
Ok I'll add `location.href=...` inside that callback.

Thanks : )

**Comment by running-coder** [comment]
You can also check into the `href` option, that might be more useful if you plan on setting up links

**Comment by superciccio14** [comment]
`href="myurl/{{baz}};` is even better. The only drawback is that you cannot use the button with the `typeahead__search-icon` anymore. But, no problem  :)

Now the `name` attribute of the input is useless, I guess...

**Comment by running-coder** [comment]
hehe, you welcome let me know if you have more questions / issues
