### ISSUE TITLE
Whitespace stop results.

### ISSUE THREAD

**Issue by kavin-90** [running-coder/jquery-typeahead#301]
As title says `Hello World  `is query which has whitespace after world and ajax results return data but jquery typeahead show no results.

Any suggestion?

Demo can be tested at `http://www.runningcoder.org/jquerytypeahead/demo/`

**Comment by running-coder** [comment]
Hey @kavin-90, which demo? Also if you add a space at the end of your query Typeahead treats the space the same as any other character, if it's not in the item keys it won't be displayed. If you are already filtering the results in backend I recommend using `filter: false` to bypass Typeahead's filtering and directly display your results

**Comment by kavin-90** [comment]
@running-coder i tested it on 1st demo of Country v1 i got same results.

**`filter: false`** worked.
