### ISSUE TITLE
Dynamic Ajax GET query with NO delay wont generate dropdown list some times - 2

### ISSUE THREAD

**Issue by seltix5** [running-coder/jquery-typeahead#303]
hi again, i'm creating this issue because apparently i cant reopen another case :

https://github.com/running-coder/jquery-typeahead/issues/248

this is issue is there again, i updated to the last version and now it is happening again, with dynamic = true and delay = 100 if i type something quick enought the dropdown is not generated, again because :

in the function incrementGeneratedGroup() in this check "this.groupCount !== this.generatedGroupCount" (https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L1293) the counters are diferent and the execution is canceled.

Please help.
Thanks :D

**Comment by seltix5** [comment]
PS : version 2.7.6

**Comment by running-coder** [comment]
Hey, indeed there might have been issues with that... I've modified most of the requests logic when doing #275, can you test on the latest develop branch commit and let me know if it still occurs?

**Comment by seltix5** [comment]
hi, i just test it with v2.7.6 (2017-2-20) and i had the same problem :S do you need me to test something else?
thanks.

**Comment by running-coder** [comment]
Can you retry with this commit? I think I've removed it by mistake.. indeed this was a fix from #248

**Comment by seltix5** [comment]
hi,
yes it is working now, thanks :D

**Comment by running-coder** [comment]
Added a test, should never come back. Thanks for raising the issue!

**Comment by seltix5** [comment]
no problem, thank you for this great plugin :D
