### ISSUE TITLE
Dynamic Search: No Results displayed, altough JSON Result has 1 Entry

### ISSUE THREAD

**Issue by fsteinbauer** [running-coder/jquery-typeahead#305]
For example I enter `kreuzwirt`. This results in two requests: 
- First request: `/search?q=kreuz` cancelled
- Second request: `/search?q=kreuzwirt` Response:

```
[{"text":"Gasthaus \u0022kreuzwirt\u0022","id":22652,"address_street":"Annaplatz 2","address_city":"8020 Graz","icon":"fa fa-glass"}]
```
I get the `No entries found` message instead.

Now I remove the last character, searching for  `kreuzwir`, and get the same JSON response from the server and one result is shown.

If i add the the `t` again, searching for `kreuzwirt` I still get the same JSON response, and still the result is shown.

This is my configuration:

```javascript
$.typeahead({
            input: '#js-typeahead-search',
            minLength: 1,
            order: "asc",
            dynamic: true,
            delay: 250,
            hint: true,
            backdrop: {
                "background-color": "#000"
            },
            template: function (query, item) {

                return '<span class="row">' +
                        '<i class="{{icon}}"></i> '+
                        '<span class="name">{{text}}</span>' +
                        '<span class="address_street">{{address_street}}</span>' +
                        '<span class="address_city">{{address_city}}</span>' +
                    "</span>"
            },
            emptyTemplate: "Kein Ergebnis für {{query}}",
            source: {
                lokal: {
                    display: "text",
                    ajax: function (query) {
                        return {
                            type: "GET",
                            url: "/app_dev.php/lokale/search",
                            data: {
                                q: "{{query}}"
                            }
                        }
                    }
                },
            },
            debug: true
        });
```

This is the Json repsonse:
```json
[{"text":"Gasthaus \u0022kreuzwirt\u0022","id":22652,"address_street":"Annaplatz 2","address_city":"8020 Graz","icon":"fa fa-glass"}]
```

**Comment by fsteinbauer** [comment]
No results is shown before the request is finished.

**Comment by running-coder** [comment]
hey @fsteinbauer are you using the latest commit on the develop branch (2.8.0 soon to be released)?

**Comment by fsteinbauer** [comment]
No I am running 2.7.6.

Currently I cannot reproduce the Error. The result.json file is generated dynamically by a Symfony-PHP application. I changed the generation from dev to prod (faster responses) and now I get results on the first try for the same query I used yesterday.

**Comment by running-coder** [comment]
Ok, if your search results are coming from the backend I always recomment turning off the Typeahead filtering `filter: false` to display every BE results regardless of the matched keys. You can check into the option in the doc. 2.8.0 should come out today / tomorrow let me know if you can reproduce on the latest version and we will reopen this one. Thanks for the feedback.
