### ISSUE TITLE
Allow Typeahead to be initialized on <textarea> and <div> with content editable

### ISSUE THREAD

**Issue by thathurtabit** [running-coder/jquery-typeahead#306]
Hi all,

I hope I'm missing something here, but I can get the plugin to work with an `<input>`, but not with a `<textarea>` tag. Is this correct?

Thank you.

**Comment by running-coder** [comment]
Hey @thathurtabit , exact Typeahead is only for inputs, would there be a usecase for a textareas? Maybe you can explain what you are trying to achieve / build?

**Comment by thathurtabit** [comment]
Hi, I'm building a textarea (it needs to be a textarea for multi-lines) that looks up data and lets users know if it's already been added/submitted before.

**Comment by running-coder** [comment]
Should be good to go in the next release, let me know if any issue
