### ISSUE TITLE
Using the plugin in content editable div

### ISSUE THREAD

**Issue by gs-smuthyam** [running-coder/jquery-typeahead#308]
Hi
Was trying to use the same plugin in a content editable span. Since this plugin is tightly coupled with input field, tried below ways and here are my findings:
1) Make typeahead container hidden and trigger the keyup/input event explicitly by setting the current value; Nothing seems worked.
       This was because the query attribute was not being set and hence results did not appear.
2) make it float right and change the width(kinda hack but tried to see if it works) to 0. Set the value on the input field and triggered the events and got below error: And search result did not appear for the first time.
```
Uncaught TypeError: Cannot read property 'prepend' of null
    at Typeahead.buildLayout (jquery.typeahead.js:1757)
    at HTMLInputElement.<anonymous> (jquery.typeahead.js:688)
    at HTMLInputElement.dispatch (jquery-1.10.2.min.js:5)
```
Now I tried setting generateOnLoad:true, issue of results for the first time is fixed but still getting above error. 

Any help in fixing this error will be appreciated. Also any inputs on handling this situation in a better manner with this plugin.

**Comment by running-coder** [comment]
hey, indeed Typeahead only support `<input>` tags for now. To be honest, I've never saw the use of any other html tag / tested using anything else.

**Comment by running-coder** [comment]
Closing in favor of #306

**Comment by running-coder** [comment]
Ready to be tested in develop branch inside #306
