### ISSUE TITLE
Add option to have the result list displayed above, below or auto detect relative to the input location

### ISSUE THREAD

**Issue by davidenco** [running-coder/jquery-typeahead#309]
Can I set the typeahead to open above the input instead of below? In my case, the typeahead input is at the bottom of the page and it would make more sense if the typeahead were to pop up above the input so the user doesn't have to scroll the page to see the typeahead filter results.

**Comment by running-coder** [comment]
hey @davidenco there is a `resultContainer` option that allows you to output the result in a different container than the default Typeahead one. Regarding an option to prepend instead of happend or auto-detect the window scroll, there is currently none.
