### ISSUE TITLE
GET instead of POST ?

### ISSUE THREAD

**Issue by Keirodev** [running-coder/jquery-typeahead#31]
Hi there,

Thanks for your work on this plugin. However i have a little problem using this code : 

```javascript
var elementsValues = {action:"something"};

$('#input').typeahead({
	source: { 		url: {
						type: 'POST',
						url: 'controler.php',
						data: {'data':JSON.stringify(elementsValues)}
					}
	},
	debug : true
});
```

The browser say this code send a GET method instead of the POST i defined.

Do i use badly this code, or there is a real issue ?

**Comment by running-coder** [comment]
Hey Keirodev,

is this the only configuration you have? when using AJAX requests you are supposed to switch dynamic option to true.

You can refer to this example: http://www.runningcoder.org/jquerytypeahead/demo/#form-user_v1
I've verified the requests and they are showing as POSTs (in the example)

Also can you try naming your group? (perhaps there is some bad merge on my side when the group is not named)

``` javascript
$('#input').typeahead({
    dynamic: true,
    source: {       
        yourgroupname: {
            url: {
                type: 'POST',
                url: 'controler.php',
                data: {'data':JSON.stringify(elementsValues)}
            }
        }
    },
    debug : true
});
```

let me know if it fixed the issue

thanks for using the plugin
