### ISSUE TITLE
When `href` option is set, pressing Enter should follow the link

### ISSUE THREAD

**Issue by superciccio14** [running-coder/jquery-typeahead#311]
Hello, in my jquery-typeahead options I visualize data in async mode via REST API.  I display a `{{ displayed_value }}` and I submit the relative `{{ id }}` as param for another url. In fact in my options I have:

`href: "myurl?q={{id}}",`

All is fine when I click on the elment in the dropdown list or when I press the right arrow.

Instead if I press enter, the dropdown list disappears and the `{{ displayed_value }}` is visualized inside the form and nothing happens. 
Is there a way to go directly to `myurl?q={{id}}` when enter is pressed (exactly like it happens for right arrow?)

**Comment by running-coder** [comment]
hey @superciccio14 could be something that was missed out (regarding the right arrow), it should not submit. I'll think about adding an option to submit `onClick`. Some people uses Typeahead inside of forms with multiple inputs so it needs to not submit by default.

Meanwhile you can add a `onClick` callback and add a `window.location.href` inside

```javascript
callback: {
  onClick: function(node, a, item, event) {
     window.location.href = "myurl?q=" + item.id
  }
}
```

**Comment by superciccio14** [comment]
Hello @running-coder, thank you: it works perfectly. 

Glad for having helped you in identifying a little bug (i.e., right arrow).

Bye!

**Comment by running-coder** [comment]
Issue comes from jQuery http://stackoverflow.com/questions/7999806/jquery-how-to-trigger-click-event-on-href-element. Added a fix inside `develop` branch
