### ISSUE TITLE
Add a Typeahead.refresh(options) method

### ISSUE THREAD

**Issue by xkris6x** [running-coder/jquery-typeahead#312]
I have a "select" and I would like to load the data of the value of the select doing a query to the database. I am not being able to refresh myself with new data from the database.
And a great contribution thanks for the search engine is very good.

**Comment by running-coder** [comment]
Hey @xkris6x, a refresh method is not yet implemented but will definitely consider adding one!

**Comment by tcoakley** [comment]
This would be handy.  I was attempting to update the source ajax url in the onSendRequest.  Switching to post filtering, but I'd rather have let the database filter.
