### ISSUE TITLE
Please help it wont work at all

### ISSUE THREAD

**Issue by nandafirmans** [running-coder/jquery-typeahead#313]
Hi, sorry I'm noob af, 
the ajax request is running well but, how can I display the response ? 

heres my code : 

        $.typeahead({
            input : "#destinationSearch",
            minLength : 3,
            dynamic : true,
            order : "asc",
            template: function (query, item) {
                var content = (
                    "{{CityName}}"
                );
                return content;
            },
            source : {
                "city" : {
                    ajax: function(keyword){
                        return {
                            url: urlDest,
                            type : "POST",
                            path: "data.CityList",
                            data: {
                                keyword : keyword
                            },
                            callback : {
                                done : function(data){
                                    console.log(data);
                                    return data.CityList;
                                }
                            }
                        }
                    }
                }
            },
            debug : true
        });

**Comment by running-coder** [comment]
hey @nandafirmans , you probably need to define the `display` option to tell Typeahead for which keys to search inside.

**Comment by nandafirmans** [comment]
it works!! 
Thanks... your plugin is awesome @running-coder  🍺
