### ISSUE TITLE
how to refresh the source

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#314]
Hi,

I have 2 typeaheads. The source of the second typeahead gets filled after something was chosen in the first typeahead. So far so good.
The problem is that the second typeahead isn't available untill I manually refresh the window.
$scope.$apply doesn't work either (I'm using Angular).

Should I trigger something ?

**Comment by running-coder** [comment]
There is not much done about destroying / refreshing Typeahead instances. You can manually rebuild the second instance after the first item is selected. Not optimal but should work until a `Typeahead['node'].refresh(options)` is created. 

If the fact is that it does work with angular then I might be clueless... Is it possible for your to build a quick jsfiddle that shows the issue that you could share here and we could tweak?

**Comment by GDM70** [comment]
I solved it by calling   $("#ras1").val(search).trigger("input.typeahead")
everytime ngModel is changed

**Comment by running-coder** [comment]
Glad you figured it out, might be too framework-specific to apply any kind of fix to Typeahead.
