### ISSUE TITLE
Tweak Typeahead CSS / containers to allow different order (input, dropdown, search button)

### ISSUE THREAD

**Issue by jgassie** [running-coder/jquery-typeahead#315]
Hello, is there a way to move the typeahead filter (w/dropdown) in front of the query span?
well i suppose i could add some absolute positioning with css...

**Comment by running-coder** [comment]
hey @jgassie it's currently not supported, there might be a way to "hack" it with css. Would be a good feature to add.

**Comment by pcout** [comment]
any news on this ?
