### ISSUE TITLE
Search two columns of data (mimicking Bloomberg/Eikon Autocomplete)

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#316]
Hello!
I think I have found the BEST AUTOCOMPLETE PLUG-IN AVAILABLE TO THE HUMAN RACE LOL)! I wanted to ask if your script can be made to search through two or three columns at once similar to how it is done at Bloomberg/Eikon terminals. I have attached their screenshots for your reference!)

https://blogs.thomsonreuters.com/financial-risk/wp-content/uploads/sites/12/2016/09/eikon-data-visualization-screenshot2.png

http://s3.amazonaws.com/libapps/accounts/10680/images/Bloomberg.jpg

**Comment by dave7777** [comment]
had a very short additional question - if you think your script can be styled similar to the Bloomberg/Eikon terminals?

**Comment by running-coder** [comment]
hey dave, thanks for the kind words! Yes Typeahead can search through multiple object keys, look into the `display` option. Let's say you have a dataset of items and one item looks like:

```json
{
  name: "myItemName",
  id: "42",
  description: "description of my item",
  category: {
    name: "aCategoryName",
    id: "12"
  }
}
```

you could define the Typeahead search keys like:

`display: ['name', 'description', 'category.name']`

**Comment by dave7777** [comment]
the results will appear as multiple columns right? do you think you can create such a demo - for the more geek ones like me :)

**Comment by running-coder** [comment]
The columns in your example can be simulated using a `template` option with custom styles (float left float right blocks). Unfortunately I do not have a lot of time to work on Typeahead (more example or providing extra support). I can answer quick questions but It would be up to you to find your way through the plugin :) There might be extra examples in the `/example` folder in the project that are not on the website that maybe help.

**Comment by dave7777** [comment]
thank you!) closing this one. I investigated all the examples and would love to see more in future releases!)
