### ISSUE TITLE
sorting on specific field

### ISSUE THREAD

**Issue by GDM70** [running-coder/jquery-typeahead#317]
I have different fields.
You can order on "null", "asc" or "desc" but he takes the first property in the object to sort on.
But how can you order on a certain property, something like : order:"['name'] asc"
or is that not possible ?

**Comment by running-coder** [comment]
Hey @GDM70, If I remember correctly the sorting will be done by the first key that is defined in your `display` option.

```javascript
display: ['name', 'secondkey', 'morekey']
```
