### ISSUE TITLE
Follow Link With ENTER

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#318]
Hello!
In your **Beer_v1 Demo** I can click on result to follow link - can I ALSO JUST ENTER THE KEY WORD AND PRESS ENTER TO FOLLOWS THE SAME LINK? That would make it similar to some high end autocomplete widgets (Bloomberg Search)!)
Dave

**Comment by dave7777** [comment]
one follow up question - cannot find a demo with unique urls assigned to each search result  - can it be done? as I see you append list values to wikipedia or that site - what if I need unique url for each search result?

**Comment by running-coder** [comment]
Hey @dave7777 I've just fixed this issue yesterday inside #311, there was an issue with jQuery. Regarding your question you can use a function for the `href` option.

As written in the doc (nothing prevents you from doing more complex stuff inside that function):
```javascript
href: function (item) {
    return "/location/" + item.group + "/" + item.display + ".html"
}
```

**Comment by dave7777** [comment]
glad to hear you fixed it so recently! as for the links - do you think they can be called from same array? it woudl include the beer make in its case and its url?

**Comment by running-coder** [comment]
do you have a code example you would like to achieve with your links? I'm not sure I fully understand the issue.

**Comment by dave7777** [comment]
thnak you for your kind reply. here is an example code:

http://jsfiddle.net/2RNFj/3/

it allows to specify unique url for each result...can it be done with your script?

**Comment by running-coder** [comment]
yes, definitly!

http://jsfiddle.net/runningcoder/7e17217d/1/

**Comment by dave7777** [comment]
amazing!) you just created this fiddle right? thank you so much!) as a matter of fact I need to modify your advanced demo to include the links - can you please help me with that? The Beer_v1 Demo - This autocomplete suits me perfectly - can you please add the links to it?????? if I could donate to you here I woudl do it immediately!) why do not they employ this feature?)

**Comment by running-coder** [comment]
yea just created it, unfortunately I cannot help with your integration but if you have more questions with the options that are not documented I would be glad to help!

**Comment by dave7777** [comment]
I tried creating the array with the links that you showed earlier and plug it into your beer demo:

```
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="../src/jquery.typeahead.css">

    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script src="../src/jquery.typeahead.js"></script>

</head>
<body>

<div style="width: 100%; max-width: 800px; margin: 0 auto;">

    <h1>Beer_v1 Demo</h1>

    <ul>
        <li>
            <a href="http://www.runningcoder.org/jquerytypeahead/documentation/">Documentation</a>
        </li>
        <li>
            <a href="http://www.runningcoder.org/jquerytypeahead/demo/">Demos</a>
        </li>
    </ul>

    <form>
        <div class="typeahead__container">
            <div class="typeahead__field">

                <span class="typeahead__query">
                    <input class="js-typeahead"
                           name="q"
                           type="search"
                           autofocus
                           autocomplete="off">
                </span>
                <span class="typeahead__button">
                    <button type="submit">
                        <span class="typeahead__search-icon"></span>
                    </button>
                </span>

            </div>
        </div>
    </form>

    <script>

        var myData = "ale": [{name: "abc", link: "http://abc.com"}, 
             {name: "nbc", link: "http://nbc.com"}];

  $.typeahead({
    input: ".js-typeahead-input",
    minLength: 0,
    source: {
        myGroup: {
            display: "name",
            href: "{{link}}",
            data: myData,
            dropdownFilter: "all beers",
            emptyTemplate: 'No result for "{{query}}"',
            source: {
                ale: {
                    data: data.ale
                }
            },
            callback: {
                onReady: function (node) {
                    this.container.find('.' + this.options.selector.dropdownItem + '.group-ale a').trigger('click')
                },
                onDropdownFilter: function (node, query, filter, result) {
                    console.log(query)
                    console.log(filter)
                    console.log(result)
                }
            },
            debug: true
        });

    </script>

</div>

</body>
</html>
```

maybe you can check it shortly to see why it is not working and I will add the rest on my own? thanks a lot for this beautiful script Tom!

**Comment by dave7777** [comment]
Can anyone help me with this?

**Comment by dave7777** [comment]
Tom - I just created the fiddle with two sets of results for EURUSD and GBPUSD respectively - can you help me create the groups for each of theses sets?

http://jsfiddle.net/runningcoder/7e17217d/1/
