### ISSUE TITLE
Addign custom URLS to categorized autcomplete

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#320]
I wonder if someone has previously added custom URLS to the autocomplete results (grouped)? If yes - can you please share the code/fiddle with me? I love this script but cannot find a way to modify the demo (Beer_v1 Demo).

**Comment by running-coder** [comment]
Custom urls could be acheived using `href` as a function and have your own custom solution to build them. Ex:

```javascript
href: function (item) {
  if (item.name == "special_name" && item.category == "special_category") {
    return 'http://www.special-url.com';
  } else {
    return item.url;
  }
}
```

This should allow you to look for your item's properties and build urls depending on and of it's carasteristics.

**Comment by dave7777** [comment]
Thank you Tom - the URLS that I need to assign to the search results are rather uniform to be defined by a function. I loved your simple example with the demo links.....http://jsfiddle.net/runningcoder/7e17217d/1/
maybe you can create a more complex example using categories and the rest based on it?

**Comment by running-coder** [comment]
try to start something using your data, send me a link if you are blocked and we will go from there :) If you data is too sensitive then you may replace it with fake stuff it's alright

**Comment by dave7777** [comment]
Tom - your assistance is so much appreciated!!!! 

I recently created the fiddle with two sets of results for EURUSD and GBPUSD respectively - can you help me create the groups for each of theses sets?

http://jsfiddle.net/Line7/2e3yf1o8/

**Comment by running-coder** [comment]
From there what you might want to do is to split your data into 2 distinct groups, `EURUSD` and `GBPUSD` and populate the data for each of these groups

```javascript
$.typeahead({
    input: ".js-typeahead-input",
    minLength: 0,
    source: {
        EURUSD: {
            display: "name",
            href: "{{link}}",
            data: myEURUSDData
        },
       GBPUSD: {
            display: "name",
            href: "{{link}}",
            data: myGBPUSDData
        }
    }
});
```

This will allow you to use the `group` option and to segment / handle use case per group. For example soecific template for `GBPUSD` as shown in the Doc.

**Comment by dave7777** [comment]
all done - thanks a lot!)
