### ISSUE TITLE
Non-contagious keyword autocomplete

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#321]
Hello! I wonder if your script can be made to simultaneously search through multiple terms - lets say I have this entry - NEW YORK TRANSPORT SYSTEM - the scrip woudl pick it up by theses combos of keywords: 
NEW SYSTEM and NEW TRANSPORT.

**Comment by dave7777** [comment]
Example is here:
http://jsfiddle.net/W8MKt/7/

**Comment by running-coder** [comment]
Hey dave!, at the moment it can only search with `NEW YORK TRANSPORT SYSTEM` term. There is an option you could use to break up the words and allows you for a much more flexible search. Look into `correlativeTemplate` option, that option breaks every word "new", "york", "transport", "system" and attempt to match them in your dataset.

**Comment by dave7777** [comment]
Cool - I guess such search is a little bit over-powerful for me right now - will stick to your beautiful example at http://jsfiddle.net/runningcoder/7e17217d/1/
