### ISSUE TITLE
Following URL after pressign Enter

### ISSUE THREAD

**Issue by lo-ve-ly** [running-coder/jquery-typeahead#322]
Hello,
Thank you for your script Running-Coder. I checked the links demo at this link and can see that it does not follow links after pressing ENTER: 
http://jsfiddle.net/runningcoder/7e17217d/1/
Can you please correct the fiddle when you have time?
Oliver

**Comment by running-coder** [comment]
The url for https://cdn.rawgit.com/running-coder/jquery-typeahead/develop/src/jquery.typeahead.js was cached at ` * @version 2.7.6 (2016-12-23)` I've went to that address and hard refreshed the file (ctrl shift r) to `* @version 2.8.0 (2017-3-20)`. It appears to be working now

**Comment by lo-ve-ly** [comment]
thank you for your reply....http://jsfiddle.net/runningcoder/7e17217d/1/
still does not go to http://abc.com and you type ABC and press ENTER...can you please recheck?

**Comment by running-coder** [comment]
typing ABC in the search will submit as a POST indeed, I was talking about selecting the Item and pressing enter. Typeahead should not follow link of an unselected item even if it's the only result... If you want to generate a url for a search that does not have an item associated, you can use the `onClick` function, there are a couple example on the doc/demo site

**Comment by lo-ve-ly** [comment]
Thank you - continuing with that fiddle (http://jsfiddle.net/runningcoder/7e17217d/1/) - it has this JS code:

var myData = [{name: "abc", link: "http://abc.com"}, 
             {name: "nbc", link: "http://nbc.com"}];
```

$.typeahead({
    input: ".js-typeahead-input",
    minLength: 0,
    source: {
        myGroup: {
            display: "name",
            href: "{{link}}",
            data: myData
        }
    }
});
```
do I need to insert this code to make it follow the url after pressing ENTER:

```
onClickAfter: function (node, a, item, event) {
    event.preventDefault();
    // Do extra operations when a `href` item is "enter" or "right arrow"
},
```

**Comment by running-coder** [comment]
hey, sorry @lo-ve-ly, instead of the onclick (which is reserved to selecting items) you might want to use `onSubmit`, I've updated your demo http://jsfiddle.net/runningcoder/7e17217d/4/

**Comment by lo-ve-ly** [comment]
Thank you very much - it does not still follow the link when I type ABC and press ENTER...can you please take a look just one more time?

**Comment by running-coder** [comment]
Yea, the part that would get the link from `myData` is commented, uncomment it and run it again ;)

**Comment by lo-ve-ly** [comment]
spectacular! thank you so much! The code you added reacts to click and to ENTER - just as I needed! I have a suggestion - why not make a commercial plug-in and sell it on codecanyon? Your functionality is so immense!

**Comment by running-coder** [comment]
I've taken so much from the open-source community, this is some kind of payback. Also A LOT of feedback and testing from people following / using the project made it really great just by flagging issues / suggesting features / opening pull-requests so might as well keep it that way and benefit everyone :)

https://github.com/running-coder/jquery-typeahead/issues?q=is%3Aissue+label%3ABug+is%3Aclosed

**Comment by lo-ve-ly** [comment]
just a show follow-up it appears that the ENTER is not working when the entered phrase has characters which differ in CASE - for example **NBC** will not trigger link while **nbc** will - do you think this can be corrected ?

**Comment by running-coder** [comment]
yep, you can make sure both strings match by comparing both lowercase

http://jsfiddle.net/runningcoder/7e17217d/5/

**Comment by lo-ve-ly** [comment]
Fantastic!) thank you so much!) It is all working perfectly now!)

**Comment by lo-ve-ly** [comment]
I had a small question regarding this fiddle http://jsfiddle.net/runningcoder/7e17217d/5/
The data is in the following format:

```
var myData = [{name: "abc", link: "http://abc.com"}, 
             {name: "nbc", link: "http://nbc.com"}];
```
Do you think there can be a quick and easy way to place this data into an external file (as my list will be huge)?
