### ISSUE TITLE
Static item at bottom of menu

### ISSUE THREAD

**Issue by khalidadil** [running-coder/jquery-typeahead#323]
I'm trying to create a menu similar to this in the material style:
<img src="https://cloud.githubusercontent.com/assets/2343076/24264385/420fdba2-0fce-11e7-8ef8-b7d912cb1398.png" width="150">

I'm using [MaterializeCSS](http://materializecss.com/dropdown.html), for which the dropdown code looks like:
```
<ul id='dropdown1' class='dropdown-content'>
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
</ul>
```

For my menu, I'd like the dynamic results to be provided by typeahead, but a static item always present at the bottom of the menu for "Add Item" with an "add-item" class to attach a jQuery listener.

Is there a way built into typeahead to do this, or would I be better off just using jQuery?

**Comment by running-coder** [comment]
so you would have an input (which acts as a Typeahead) and a menu beside (your screenshot) that gets constructed depending on the search results?

```javascript
var newItemHtml = '<a href="javascript:;" class="new-item" onclick="newItem()">New Item</a>';

$.typeahead({
    input: ".js-typeahead",
    minLength: 0,
    order: "asc",
    searchOnFocus: true,
    source: {
        group: {
            data: ['one', 'two', 'tree']
        }
    },
    emptyTemplate: newItemHtml,
    callback: {
        onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
            var divider = '<li class="divider"></li>';
            var itemHtml = '<li>' + newItemHtml + '</li>';

            if (resultHtmlList && result.length) {
                resultHtmlList.append(divider + itemHtml)
            }
        }
    },
    debug: true
});

function newItem() {
    alert('New item!')
}
```

**Comment by khalidadil** [comment]
Thanks so much for responding so quickly!

I've almost got it working - one thing I'm noticing is that the emptyTemplate cannot be selected with  the "down" arrow key because there's an extra empty link being added.

You can find an animation of the behavior I'm seeing [here](https://cl.ly/0F2M2B110i00/Screen%20Recording%202017-03-24%20at%2009.58%20AM.gif).

The animation shows that the arrow keys work on the normal template (once I added the right classes to the itemHtml), but it doesn't work on the empty template. On inspecting the emptyTemplate, I'm seeing this in the `typeahead__empty` list item:

![image](https://cloud.githubusercontent.com/assets/2343076/24300027/07105a3a-1079-11e7-9386-0e937462e89e.png)

Do you have any idea why this may be happening?

**Comment by khalidadil** [comment]
I just checked again and tried removing the empty list item from the DOM through the inspector and it seems like I still can't select the New Item with the down arrow key. 

There may be more to this and this may end up being a feature enhancement since I see that for the normal results you're adding extra "active" classes, etc.

**Comment by running-coder** [comment]
There we go, this version should be better

```javascript
$.typeahead({
    input: ".js-typeahead",
    minLength: 0,
    order: "asc",
    searchOnFocus: true,
    source: {
        groupName: {
            data: ['one', 'two', 'tree']
        }
    },
    template: function (query, item) {
        var template = '{{display}}';
        if (item.addNewItem) {
            template = 'New Item';
        }
        return template;
    },
    callback: {
        onResult: function (node, query, result, resultCount, resultCountPerGroup) {
            result.push({
                addNewItem: true,
                group: 'groupName'
            });
        },
        onClick: function (node, a, item, event) {

            if (item.addNewItem) {
                event.preventDefault();
                alert('Create new item!')
            }

            console.log(item)

        }
    },
    debug: true
});
```

**Comment by khalidadil** [comment]
This is very, very close, but it looks like it is resetting the input text when the "Add" menu item is being selected. A gif of that can be found here: https://cl.ly/1N1Q3N2Z0n0C

**Comment by khalidadil** [comment]
I figured it out - thanks for all the help! I used the `onNavigateAfter` function to put the query value back in the input with jQuery.

```
$.typeahead({
    input: ".js-typeahead",
    minLength: 0,
    order: "asc",
    searchOnFocus: true,
    source: {
        groupName: {
            data: ['one', 'two', 'tree']
        }
    },
    template: function (query, item) {
        var template = '{{display}}';
        if (item.addNewItem) {
            template = 'New Item';
        }
        return template;
    },
    callback: {
        onResult: function (node, query, result, resultCount, resultCountPerGroup) {
            result.push({
                addNewItem: true,
                group: 'groupName'
            });
        },
        onClick: function (node, a, item, event) {
            if (item.addNewItem) {
                event.preventDefault();
                alert('Create new item!')
            }
            console.log(item)
        },
       onNavigateAfter: function (node, lis, a, item, query, event) {
           if (item.addNewItem) {
               $('.input-fact').val(query);
	   }
       }
    },
    debug: true
});
```
