### ISSUE TITLE
Inverse Color Scheme

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#324]
Hello!
I wonder if maybe you have an Inverse Color Scheme for your scrip - dark input field, dark drop down menu and bright charter highlight colour? This can all be modified via the CSS file right?
Dave

**Comment by dave7777** [comment]
I managed to inverse the default colour scheme - I have one last thing to change - the colour which highlights the matching strings in the results - I now have the bold highlight - want to change it to red....can it be done?

<a href="http://tinypic.com?ref=15h05n8" target="_blank"><img src="http://i63.tinypic.com/15h05n8.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by running-coder** [comment]
sure! only add a style to target the `<strong>` field
```css
.typeahead__list > li > a strong {
  color: red;
}
```

**Comment by dave7777** [comment]
Thank you Tom - your help is so much appreciated!
