### ISSUE TITLE
Different width of input field in Firexof and Chrome

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#325]
Hello!
I am seeing different widths of input field in Firexof and Chrome - not sure why this is happening - I have attached the screenshots:

<a href="http://tinypic.com?ref=azjt46" target="_blank"><img src="http://i65.tinypic.com/azjt46.png" border="0" alt="Image and video hosting by TinyPic"></a>

<a href="http://tinypic.com?ref=1t6kvn" target="_blank"><img src="http://i68.tinypic.com/1t6kvn.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by running-coder** [comment]
Interesting... in theory Typeahead's width (100%) is determined by the parent container. Could you give me your sample of code to quickly paste it in my file?

**Comment by dave7777** [comment]
Thank you for your kind reply...sure:

```
$.typeahead({
    input: ".js-typeahead-input",
    minLength: 0,
	 maxItem: 20,
    source: {
        myGroup: {
            display: "name",
            href: "{{link}}",
            data: myData
        }
    },
    callback: {
    		onSubmit: function (node, form, item, event) {
    			event.preventDefault();
        
          for (var i=0, ii=myData.length; i<ii; ++i) {
            if (this.query.toLocaleLowerCase() == myData[i].name.toLocaleLowerCase()) {
              window.location.href = myData[i].link;
              break;
            }
          }
          
          // OR build url from the query string
          console.log(this.query)
    
				}
    }
})
    </script>
```

**Comment by running-coder** [comment]
I'm unable to reproduve the issue perhaps it's due to some extra css you added or your parent html element properties

**Comment by dave7777** [comment]
I guess I messed up with the code. :) All is back to working now) Thank you for your time Tom!

**Comment by dave7777** [comment]
The reason it did not work in Firefox is that I added this style to the head of the page

```
  <style>
body {
 float:left
}
</style>
```

This is unexpected?
