### ISSUE TITLE
Improve Up / Down / Tab navigation to have only 1 "selected" item

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#326]
Up and Down arrows do not move the selected row. When I type full search string the search - hover mouse over the result row and start pressing up and down arrows the original row KEEPS HIGHLIGHTED. is this a bug or I changed something?:)

<a href="http://tinypic.com?ref=dlniiv" target="_blank"><img src="http://i66.tinypic.com/dlniiv.png" border="0" alt="Image and video hosting by TinyPic"></a>

thanking you for your fabulous script!

**Comment by running-coder** [comment]
hey dave, indeed that selectable item could be improved and programmed similat to google's search bar, good idea!

**Comment by dave7777** [comment]
yes - can you please help me remove the confusion from your otherwise awesome script?) the up and down arrows should take the highlighted row and move up and down  - the original cursor highlighting can be turned off after that?

**Comment by dave7777** [comment]
I can send you the link to the webpage  to your email at tomlebrute ?

**Comment by running-coder** [comment]
yes, that works too!

**Comment by running-coder** [comment]
I am able to replicate this issue, link would be useful for #325

**Comment by dave7777** [comment]
Love the way you renamed the subject) Adds more clarity.... when do you think this can be corrected? I will try to generate the link for 325 in a few moments.

**Comment by running-coder** [comment]
Should be good on `develop` branch
