### ISSUE TITLE
Place data into an external file

### ISSUE THREAD

**Issue by lo-ve-ly** [running-coder/jquery-typeahead#328]
I had a small question regarding this fiddle http://jsfiddle.net/runningcoder/7e17217d/5/
The data is in the following format:
```
var myData = [{name: "abc", link: "http://abc.com"}, 
             {name: "nbc", link: "http://nbc.com"}];
```

Do you think there can be a quick and easy way to place this data into an external file (as my list will be huge)? - and just link to it from the LINK DEMO?

In love with your script)

**Comment by running-coder** [comment]
yep, the plugin is made to support json format, look at the advanced demos you can setup an url on your website to act as a endpoint or use a relative path to a json file when doing an ajax configuration
