### ISSUE TITLE
Feature Enhancement: Follow link on ENTER - after Partial Match

### ISSUE THREAD

**Issue by lo-ve-ly** [running-coder/jquery-typeahead#329]
Hello!
I wanted to ask if your script can be made to follow link on ENTER - after partial match has been found and it is a SINGLE result? that way someone can follow a result without typing full result name? 

Try pressing **BBC NEWS** here:

http://jsfiddle.net/Line7/89gqt9un/1/

the full result is "**bbc news today"** and it is the single result - - so I would need to type it all BBC NEWS TODAY and only then it woudl allow me to press the ENTER - can I just press ENTER when there is a single result in the search menu?

Thanking you warmly!

Oliver

**Comment by dave7777** [comment]
yes - do you think Tom this can be done?

**Comment by dave7777** [comment]
Do you think this can be done Tom?

**Comment by running-coder** [comment]
by pressing `enter` on the input, it should trigger the `onSubmit` callback. From there you can check if `this.result` is empty, if not grab the item from that array and generate a link of your choice. Remember to `event.preventDefault();` if you are redirecting because the form will submit by default.

**Comment by dave7777** [comment]
Thank you Tom

From there you can check if this.result is empty, 

Can it be made to check if there is a SINGLE RESULT?

**Comment by running-coder** [comment]
`if (this.result.length === 1)`

**Comment by dave7777** [comment]
Thank you Tom - where do I put this in your beautiful code:

```
$.typeahead({
    input: ".js-typeahead-input",
    minLength: 1,
    source: {
        myGroup: {
            display: "name",
            href: "{{link}}",
            data: myData
        }
    },
    callback: {
    		onSubmit: function (node, form, item, event) {
    			event.preventDefault();
        
          for (var i=0, ii=myData.length; i<ii; ++i) {
            if (this.query.toLocaleLowerCase() == myData[i].name.toLocaleLowerCase()) {
              window.location.href = myData[i].link
              break;
            }
          }
          
          // OR build url from the query string
          console.log(this.query)
    
				},
    }
});
```

**Comment by dave7777** [comment]
I tried this and it did not work:

```
    ];

    $.typeahead({
        input: ".js-typeahead-input",
        minLength: 2,
        maxItem: 10,
        cancelButton: true,
        emptyTemplate: 'No result for "{{query}}"',
        source: {
            myGroup: {
                display: "name",
                href: "{{link}}",
                data: myData
            }
        },
        callback: {
            onSubmit: function (node, form, item, event) {
                event.preventDefault();

                for (var i=0, ii=myData.length; i<ii; ++i) {
                    if (this.result.length === 1)
                        if (this.query.toLocaleLowerCase() == myData[i].name.toLocaleLowerCase()) {
                        window.location.href = myData[i].link;
                        break;
                    }
                }

                // OR build url from the query string
                console.log(this.query)

            }
        }
    })
</script>
```

**Comment by running-coder** [comment]
hey @dave7777 , I've shorten your code a bit, some of the stuff in there you shouldnt need. For example you know that if you have only ONE result, pressing on enter should trigger that link, you don't have to match anything, Typeahead did it for you (showing you 1 result)

```javascript
$.typeahead({
    input: ".js-typeahead-input",
    minLength: 2,
    maxItem: 10,
    cancelButton: true,
    emptyTemplate: 'No result for "{{query}}"',
    source: {
        myGroup: {
            display: "name",
            href: "{{link}}",
            data: myData
        }
    },
    callback: {
        onSubmit: function (node, form, item, event) {
            event.preventDefault();

            if (this.result.length === 1) {
                window.location.href = this.result[0].link;
                return false;
            }
        }
    }
})
```

**Comment by dave7777** [comment]
Thank you for your generous help Tom - but now when there is a short result and it is not single it is not automagically selected when I press ENTER - earlier this worked this way(( can you please take a look?

**Comment by dave7777** [comment]
Tom, do you think we can combine the previous functionality (assign and follow link on FULLY TYPED result - even if there are more suggestions) with the new function of selecting link when there is only one result visible?

**Comment by dave7777** [comment]
Tom can you help me add this feature to the code? This is the central feature which will MAKE A LOT OF PEOPLE HAPPY~~))

JUST TO RECAP:

Try pressing BBC NEWS here:

http://jsfiddle.net/Line7/89gqt9un/1/

the full result is "bbc news today" and it is the single result - - so I would need to type it all BBC NEWS TODAY and only then it woudl allow me to press the ENTER - can I just press ENTER when there is a single result in the search menu?

**Comment by running-coder** [comment]
hey @dave7777, yes thats the code I've submitted to you above http://jsfiddle.net/runningcoder/89gqt9un/2/

**Comment by dave7777** [comment]
THANKING YOU HEARTILY - i GUESS IT CHECKS FOR DUPLICATES WHEN THERE ARE TWO MATCHES FOR SHORT ENTRIES?

**Comment by dave7777** [comment]
for some reason it does not select
bbc news
at
http://jsfiddle.net/Line7/89gqt9un/3/

**Comment by dave7777** [comment]
Tom, do you think the code can combine the two capabilities:

1) follow link on ENTER when there is a FULLY TYPED result (like at this page http://jsfiddle.net/Line7/89gqt9un/1/)
2) And follow link on ENTER when there is a SINGLE result (like you showed before http://jsfiddle.net/Line7/89gqt9un/3/)

Maybe these conditionals can be combined in sequence...

Hoping to hear from you soon!)
Dave

**Comment by running-coder** [comment]
hey @dave7777, yes everything is possible. At this point you have to wrint custom code that matches your application needs (outside Typeahead generic code). These callbacks were made to accept any implementation specificity.

http://jsfiddle.net/runningcoder/89gqt9un/4/ should handle both cases, but this code is for your to write.

**Comment by dave7777** [comment]
yes thank you very much Tom - I have tried this code and for some reason it does not work when there is a single result and I have not yet finished typing - eg typing ` bbc news t` and pressing ENTER does not work(((((( can you please look one last time?:)))

**Comment by running-coder** [comment]
on my bad! I've forgot to remove the return false :)

http://jsfiddle.net/runningcoder/89gqt9un/6/

**Comment by dave7777** [comment]
spectacular - it works as required now - thank you so much Tom - have a beautiful weekend!)

**Comment by dave7777** [comment]
now Tom.....before I close this - I had a short question - I guess final about this code - if I wanted to add the description to the main search terms (eg BBC) - how woudl I add the second column for that in this code? lets say I have this data with descriptions:

var myData = [
  {name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
  {name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
  {name: "bbc news today", link: "http://abc.com", descr: "Entertainment Channel"},
  {name: "bbc news", link: "http://abc.com", descr: "Entertainment Channel"},
  {name: "nbc", link: "http://nbc.com", descr: "Entertainment Channel"},
];

Maybe there is some magical code snippet that will add the second column for descriptions to this already fabulous code?

**Comment by dave7777** [comment]
I managed to add the descriptions - Hurray!)
http://jsfiddle.net/Line7/89gqt9un/11/

 but how do I force the second column to show uniformly? like you see here 
http://s3.amazonaws.com/libapps/accounts/10680/images/Bloomberg.jpg

or here (they have right alignment for the second column)

https://blogs.thomsonreuters.com/financial-risk/wp-content/uploads/sites/12/2016/09/eikon-data-visualization-screenshot2.png

**Comment by dave7777** [comment]
you mentioned this earlier:

The columns in your example can be simulated using a template option with custom styles (float left float right blocks). Unfortunately I do not have a lot of time to work on Typeahead (more example or providing extra support). I can answer quick questions but It would be up to you to find your way through the plugin :) There might be extra examples in the /example folder in the project that are not on the website that maybe help.

Can you point me to an example of the two-column template Tom?

**Comment by dave7777** [comment]
Your  **Hockey v1**  example places icons to the far right column - can it be done with the text?

**Comment by dave7777** [comment]
I tried to add the SPACE between the `name `and the `descr `with this

  template: '<span>' +
        '<span class="name">{{name}}</span>' + '<span>' +
        '<span class="descr">{{descr}}</span>' +     
    '</span>',

and it did not work(

**Comment by running-coder** [comment]
http://jsfiddle.net/runningcoder/89gqt9un/12/

**Comment by dave7777** [comment]
wow - thank you so much Tom - this works so beautifully - I wish you will be spectacularly successful in all of your future projects!))

one final question - is there a way to make the second column left-aligned (like the first column)? Can you please show me where you style the columns?

Thanking you heartily!)
Dave

**Comment by dave7777** [comment]
For some reason the columns show on my PC differently from your fiddle Tom:

<a href="http://tinypic.com?ref=10ymazq" target="_blank"><img src="http://i68.tinypic.com/10ymazq.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by dave7777** [comment]
ahhh you added the styles - sorry!)

**Comment by dave7777** [comment]
figured out how to align it to the left!) clever me!)

**Comment by dave7777** [comment]
one more question - is there a way to change the width of the columns? that seems to be fixed right?

**Comment by dave7777** [comment]
I figured it out (in the styles) - Hurray!!!! what a day!))))) thank you so much!) #

**Comment by lo-ve-ly** [comment]
Yes Dave it is all working fabulously now - thank you all!
