### ISSUE TITLE
Adding Categories to Link Demo

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#330]
Hello Tom!)
I am trying to add the categories to your LINK DEMO (http://jsfiddle.net/runningcoder/7e17217d/5/) but have only managed to destruct the code:) - can you please help me with it?  Please show me how to add just one category and I will do the rest myself Tom.
Dave

**Comment by running-coder** [comment]
Perhaps this is answered in #320 or #329 ? I suggest experimenting / using different examples. The example combines different sets of options and demonstrates most of what it can do.

**Comment by dave7777** [comment]
yes all done today!)
