### ISSUE TITLE
Add option to wrap / unwrap <a> tag on result items

### ISSUE THREAD

**Issue by LDSign** [running-coder/jquery-typeahead#334]
Hi

I would like to have multiple links with a custom template for each item. But every result item is wrapped in an an-tag automatically which is a invalid markup. Is it possible to avoid this (switch off the surrounding a tags)?

Thanks,
Frank

**Comment by running-coder** [comment]
Hey Frank, right now everything is wrapped within a `<a>` tag as you noticed for navigation and selecting items. I've never tried to output multiple links within a same "result item". That could be a feature that Typeahead supports in the future. For now if you really need it (it can be done but will be dirty) you can use the `onLayoutBuiltBefore` callback and unwrap the `resultHtmlList` items from `<a>`

**Comment by LDSign** [comment]
Hi

Thanks for your answer :) Could you have a look at the following code and if you like it - can you put in your project?

[http://www.ldsign.de/src.zip](url)

The href-options will now accept "false" which will replace the a tag with a span and remove the href-attribute. Addionally the span-tag has become the styling of the former a-tag. The links can than be put in a custom template.

Frank

**Comment by running-coder** [comment]
hey, good idea having the href false determining if there will be a A tag. I've started looking at it yesterday and that would work. I'll have a look in the coming days and this should be in the next release. Thanks for your contribution!

**Comment by LDSign** [comment]
Wonderful. Thank you, Tom :)
