### ISSUE TITLE
Input Tags

### ISSUE THREAD

**Issue by sjarifHD** [running-coder/jquery-typeahead#335]
Is it possible to use it for managing tags? Like [Bootstrap Input Tags](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
If yes, how I can do that?

**Comment by running-coder** [comment]
hey @sjarifHD, this has been requested a year ago and is currently sitting in the backlog #138. There is currently no option available to do it.

**Comment by running-coder** [comment]
closing this one in favor of the previously created ticket
