### ISSUE TITLE
Start typeahead to new input fields when rows are duplicated.

### ISSUE THREAD

**Issue by jorgeanr** [running-coder/jquery-typeahead#336]
Hi, is it possible to make something like this with this plugin:

http://www.bootply.com/61431 ?

I can't make it work.

Tks

**Comment by running-coder** [comment]
Definitly, this is a rather basic implementation and should be relatively easy, you just need a re-usable typeahead object definition and everytime you click a button you would call an action to append a typeahead html block and init a typeahead on it
