### ISSUE TITLE
Plugging JSON file into LINK DEMO

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#339]
Hello Tom!
I hope you are doing fine!) I wanted to ask if it is possible to easily replace myData from your link demo (http://jsfiddle.net/runningcoder/89gqt9un/12/) with the JSON file containing the same data?

>    var myData = [
> {name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
> {name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
> {name: "bbc news today", link: "http://abc.com", descr: "News Channel"},
> {name: "bbc news", link: "http://abc.com", descr: "News Channel"},
> {name: "nbc", link: "http://nbc.com", descr: "Entertainment Channel"},
> 

I guess the json file will be of the following format:

```
[
{name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
{name: "abc", link: "http://abc.com", descr: "Entertainment Channel"},
{name: "bbc news today", link: "http://abc.com", descr: "News Channel"},
{name: "bbc news", link: "http://abc.com", descr: "News Channel"},
{name: "nbc", link: "http://nbc.com", descr: "Entertainment Channel"}
]
```
I think a JSON file plugged in your LINK DEMO would break the internet (as the best autocomplete example ever!)

**Comment by running-coder** [comment]
hey @dave7777, yes! you can look at the demos on how to `ajax` an external data source

```javascript
...
source: {
    groupName: {
        ajax: {
            url: 'location/to/my/data.json'
        }
    }
}
...
```

**Comment by dave7777** [comment]
Thank you very much Tom. I converted the Mydata variable in this JSON file:

> [
> 	{
> 		"id": 1,
> 		"name": "abc",
> 		"link": "http://abc.com",
> 		"descr": "Entertainment Channel}"
> 	},
> 	{
> 		"id": 2,
> 		"name": "abc",
> 		"link": "http://abc.com",
> 		"descr": "Entertainment Channel}"
> 	},
> 	{
> 		"id": 3,
> 		"name": "bbc news today",
> 		"link": "http://abc.com",
> 		"descr": "News Channel}"
> 	},
> 	{
> 		"id": 4,
> 		"name": "bbc news",
> 		"link": "http://abc.com",
> 		"descr": "News Channel}"
> 	},
> 	{
> 		"id": 5,
> 		"name": "nbc",
> 		"link": "http://nbc.com",
> 		"descr": "Entertainment Channel}"
> 	}
> ]


I updated your fiddle with this JSON file:
http://jsfiddle.net/Line7/89gqt9un/13/

Can you please take a quick look if there might be some code mistakes by me (amateur fan of yours:)?

**Comment by running-coder** [comment]
looking good! just that extra `}` at the end of "descr"

**Comment by dave7777** [comment]
thnak you Tom - woudl be so kind to also check the code which I wrote earlier which adds the categories to the link demo? #337

**Comment by dave7777** [comment]
The code is here:
http://jsfiddle.net/Line7/vw05enbj/5/
