### ISSUE TITLE
Start Chat Script from Typehead

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#340]
Hello!
I wonder if it can be possible to start a chat scrip (any kind of script, eg ZENDESK ) after typing and pressing HELP in the typeahead? This functionality would be so extremely helpful!)
We could use the LINK DEMO but not sure how this can be done:
http://jsfiddle.net/Line7/vw05enbj/5/
Dave

**Comment by running-coder** [comment]
hey @dave7777, pretty much anything can be done, on your `onClick` function you can match the word "help" from your query and `e.preventDefault` the regular action to then call your script if that word was entered

**Comment by dave7777** [comment]
thank you Tom) I need to start the ZENDESK chart with the HELP term - will let you know how it goes)
