### ISSUE TITLE
Add a button within the search result

### ISSUE THREAD

**Issue by chris-appeagle** [running-coder/jquery-typeahead#343]
Hi
How do I add a button within the search results? The results are wrapped within an 'a tag'.

Thanks!

**Comment by running-coder** [comment]
hey @chris-appeagle, this feature has been requested and shall be in the next release. In most cases people needs their search results to be wrapped within an `a` tag to have interaction over it. It will be possible to `unwrapResult` to remove the surrounding `a`

**Comment by running-coder** [comment]
Closing in favor of #334
