### ISSUE TITLE
jquery-typeahead doesn't pass the term to PHP

### ISSUE THREAD

**Issue by robojax** [running-coder/jquery-typeahead#345]
Hi,
I am trying to pass the search term to php, but it doesn't pass the search term to php
here is my code. Please help.

I used this:

 data: {myKey: $("input[name=word]").val()}
it did not work.
then I created the variable word. did not work either. It passes the key **"myKey**" but not the value

```javascript
var word = $("input[name=word]").val();
$.typeahead{
    source: {
        country: {
            ajax: {
                url: "demo-country-ajax.php",
                path: "data.country",
                data: {myKey: word}
            }
        },
        capital: {
            ajax: {
                type: "POST",
                url: "demo-country-ajax.php",
                path: "data.capital",
                data: {myKey: word}
            }
        }
    }
```

**Comment by running-coder** [comment]
hey @robojax, the issue is that you store the `word` value before init, instead of dynamically pulling it when a search is made, here is how you can do it.

```javascript
$.typeahead({
    source: {
        country: {
            ajax: function (query) {
                return {
                    url: "demo-country-ajax.php",
                    path: "data.country",
                    data: {
                        myKey: $("input[name=word]").val()
                    }
                }
            },
            capital: {
                ajax: function (query) {
                    return {
                        type: "POST",
                        url: "demo-country-ajax.php",
                        path: "data.capital",
                        data: {
                            myKey: $("input[name=word]").val()
                        }
                    }
                }
            }
        }
    }
})
```

**Comment by running-coder** [comment]
More info on how to declare the source option can be found http://www.runningcoder.org/jquerytypeahead/documentation/#options-source

**Comment by robojax** [comment]
Not working. it seems $("input[name=word]").val() is not working inside the source:

in my demo-country-ajax.php file, I have the following code to make sure I am getting the submitted date
but shows the key which is "myKey" and no value.

$file = 'query.txt';

$infoToSave = file_get_contents($file);
foreach($_REQUEST as $k=>$v){
    $infoToSave .= "$k\t$v\n";
  file_put_contents($file, $infoToSave);
  
}

**Comment by running-coder** [comment]
Don't forget that by default Typeahead is in "static" mode, meaning it will only pull the data once.
```javascript
$.typeahead({
    input: ".js-typeahead",
    source: {
        country: {
            ajax: function (query) {
                return {
                    url: "country.json",
                    path: "data.country",
                    data: {
                        q: query,
                        myKey: $("input[name=word]").val()
                    }
                }
            },
        },
    }
})
```
<img width="509" alt="2017-05-19_1135" src="https://cloud.githubusercontent.com/assets/7377382/26255420/89af1b36-3c87-11e7-8039-530a7ab1847a.png">

If you want to be sending that `myKey` everytime there is a request you will need `dynamic: true`

```javascript
$.typeahead({
    input: ".js-typeahead",
    dynamic: true,
    source: {
        country: {
            ajax: function (query) {
                return {
                    url: "country.json",
                    path: "data.country",
                    data: {
                        q: query,
                        myKey: $("input[name=word]").val()
                    }
                }
            },
        },
    }
})
```
<img width="575" alt="2017-05-19_1139" src="https://cloud.githubusercontent.com/assets/7377382/26255538/ed619c4e-3c87-11e7-94f9-d00791b732f7.png">
