### ISSUE TITLE
Search on click with custom button on page

### ISSUE THREAD

**Issue by devocodes** [running-coder/jquery-typeahead#346]
Having issue On clicking the search button, it fires a submit action and reload the entire page, and is there a way to trigger the search event by setting a different button id?

**Comment by running-coder** [comment]
hey @devocodes, you can simply call `e.preventDefault` from the onSubmit callback

```javascript
callback: {
  onSubmit: function (node, form, item, event) {
    event.preventDefault(); //No submit will occur, set your custom actions here
  }
}
```
