### ISSUE TITLE
attaching to non-existent (yet) input

### ISSUE THREAD

**Issue by Zabanya** [running-coder/jquery-typeahead#348]
i could not attach it to input which not yet added to dom. normally in jQuery i could do 
`$('body').on('click', '#my-button', function () {`

i tried 
`$.typeahead({
            input: '#wbs input.form-control.rincian',`

and 
`$('#wbs input.form-control.rincian').typeahead({`

but both does not work

**Comment by running-coder** [comment]
Hey @Zabanya you might be able to use a `focus` event on your input? Here is a sample, I've not tested but it might be a solution you can be looking at. Worst case it it possible to init  in the same function your input gets injected?
```javascript
var isTypeaheadInitialized = false
$('body').on('focus', '#my-input', function () {
  if (!isTypeaheadInitialized) {
    isTypeaheadInitialized = true
    // init Typeahead
  }
})
```

**Comment by Zabanya** [comment]
thanks, it is working.
