### ISSUE TITLE
Hockey v1 Demo

### ISSUE THREAD

**Issue by BenjaminUAV** [running-coder/jquery-typeahead#349]
Hi,

May I know if the drop down filter's variable can be assigned as an PHP variable?
If possible, how do I go about doing it?

Appreciate your help :) 👍 

Regards,
Benjamin

**Comment by running-coder** [comment]
Hey @BenjaminUAV it all depends on which framework / how your software is built. In most cases I would assume Typeahead init's inside a `.js` file, in that case you will need to print your javascript variable inside your footer template and get it from there. Or you can do a second endpoint to get your dropdown filters and get the data before initializing Typeahead. This is more of a framework question more than a Typeahead one. Let me know if you have Typeahead specific question. Sry I can't help further as it depends on the technology you use
