### ISSUE TITLE
Search more than one keyword from the selector input 

### ISSUE THREAD

**Issue by anshu8858** [running-coder/jquery-typeahead#350]
Our search bar is properly work on 1 input word but not on more than 1 words and also not search by phrase and display only  "No Result".
Please resolve this issue.

![screenshot from 2017-05-21 16-57-17](https://cloud.githubusercontent.com/assets/20580082/26283453/acf24f26-3e46-11e7-85da-e022391e9cbb.png)
![screenshot from 2017-05-21 16-56-42](https://cloud.githubusercontent.com/assets/20580082/26283452/acf18e6a-3e46-11e7-8dc0-93a185fce83c.png)

**Comment by running-coder** [comment]
hey @anshu8858 if "car showroom" gives you no result it means that there is no consecutives "car showroom" words in your search results. You can add flexibility by adding `correlativeTemplate: true` option in your Typeahead init to match any word in any order.
