### ISSUE TITLE
html codes in template string using `correlativeTemplate` option

### ISSUE THREAD

**Issue by jgassie** [running-coder/jquery-typeahead#351]
If I define a character code such as &#60; (amersand-pound-number60) in a template string, it displays fine when listed, but if I arrow over or select an option, the js-typeahead-input displays the coded value instead of the less than symbol for example... although I can decode the value in the onClickAfter... but it still shows code if I arrow over partial match options with the keyboard before selecting.  Not sure if there is a way around that.

**Comment by running-coder** [comment]
hey @jgassie , I was able to reproduce the issue. This is more of a "format data operation" and outside of the Typeahead's scope. What you can do is convert your entities as you receive the data. 

```javascript
...
source: {
    groupName: {
        ajax: {
            url: "url/to/my/data.json",
            callback: {
                done: function (data, textStatus, jqXHR) {
                    // Convert htmlEntities inside data
                }
            }
        }
    }
}
...
```

**Comment by jgassie** [comment]
Thank you for the response.  The source data doesn't have greater-than less-than, I was wanting to add in the display.  Had to use the codes since they are special xml/html characters.  
I was wanting to use a fairly common RFC 822 look "Display Name" <emailaddress>
But I will probably just use something else like a dash, Name-email.

**Comment by running-coder** [comment]
are you using the `correlativeTemplate` option? Seems like I'm only able to repro using it

**Comment by jgassie** [comment]
Yes, correlativeTemplate is true.  I'll just use something other than those special characters, thank you!

**Comment by running-coder** [comment]
You can try the newest develop version, should work

**Comment by jgassie** [comment]
thank you i will try again when i get a chance!

**Comment by jgassie** [comment]
Works great, thank you!  :)

**Comment by running-coder** [comment]
Amazing, thanks for the feedback!

**Comment by jgassie** [comment]
Well for my original scenario, it worked great, although in another I had a "span" inserted into the template string, and the span tag and properties displayed..

**Comment by running-coder** [comment]
oh yea, I might have missed that case... :rip: going to have to work some more on that regex https://github.com/running-coder/jquery-typeahead/commit/155ae709b28bfc41af77856ac671019271c77bea#diff-fd35b9a6d01c422794aa3fb6236ba920R1247

**Comment by running-coder** [comment]
What this one does is supposed to do is extracting every strings from a template excluding the html tags. The text then gets inserted in every object key named `compiled`, so `correlativeTemplate` searches though your complete template and not only in 1 key.

**Comment by jgassie** [comment]
I see, thank you for all your effort... haven't used Jasmine before, something more to check out :) .

**Comment by running-coder** [comment]
So I've let the previous regex to remove anything between <> inclusively (aka removing html tags), but you will be able to add your own using the previously mentionned method `&#60;{{email}}&#62;`

**Comment by running-coder** [comment]
I highly recommend using jasmine or any other test framework on everything you do, in the case of Typeahead it avoided so many regressions and unhappy people ;)

**Comment by jgassie** [comment]
Thanks for the advice, the last commit 41118e6c49... certainly does the trick!
