### ISSUE TITLE
Preexisting text in Search Box

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#352]
Thank you for your fabulous script Tom - do you think it is possible to have a text in a Search box after it is loaded and which disappears after the typing is started? Like (Press HELP to chat).
Kindest regards!
Dave

**Comment by running-coder** [comment]
You think you could use the placeholder attribute?

```html
<input 
  class="js-typeahead"
  name="q"
  placeholder="Press HELP to chat"
  type="search"
  autocomplete="off">
```

**Comment by dave7777** [comment]
thank you - working great!)
