### ISSUE TITLE
Using groupTemplate and group.template

### ISSUE THREAD

**Issue by tgmweb** [running-coder/jquery-typeahead#353]
How can I customise the header when I'm using groupTemplate?

My code is as follows:
```
groupTemplate: '<div class="row"><div class="col-md-3">{{group}}</div></div>',
group: {
  template: '<h2 class="searchResultType {{group}}"> {{group}}</h2>'
},
```

But my headings aren't wrapped in an h2, which I presumed they would be?

Am I missing/doing something wrong?

**Comment by tgmweb** [comment]
It's ok - using a function instead of a string seems to work:
```
group: {
  template: function (item) {
    return '<h2 class="searchResultType ' + item.group + '"> ' + item.group + '</h2>';
},
```

Thanks,


Tom.

**Comment by running-coder** [comment]
Hey @tgmweb , I'll leave this one open and investigate why the string format was not working, it's supposed to!
