### ISSUE TITLE
Can't include {{query}} in templateValue

### ISSUE THREAD

**Issue by eric-appeagle** [running-coder/jquery-typeahead#354]
templateValue is a great idea.
All I want is when a user types in a partial word, like "boo" instead of "book" for the input to display "boo" after they've clicked an item.

The obvious way would be to have templateValue: "{{query}}" but this doesn't seem to do the job.

**Comment by running-coder** [comment]
hey @eric-appeagle, indeed "{{itemKey}}" is only allowed using the templateValue. However you can setup the option to be a function.

```javascript
templateValue: function() {
    return this.query;
},
```

When using functions through Typeahead, you are able to use `this` and retrieve the complete instance.

**Comment by eric-appeagle** [comment]
Great solution, thanks for the quick response, works well.
