### ISSUE TITLE
Single `$.Ajax` request for multiple groups doesn't populate the modified data from the `done` callback

### ISSUE THREAD

**Issue by tgmweb** [running-coder/jquery-typeahead#356]
Hey Tom,

I'm running into a similar issue as https://github.com/running-coder/jquery-typeahead/issues/34

Unfortunately you didn't answer his original question, which was related to combining ajax calls into a single request.

My framework overhead means each ajax call is taking around 250ms - and I have four groups, so the search doesn't display for nearly a second. I know I could get that down to 350ms if I only did one ajax call.

Is this possible using the onSearch callback or something similar?

Thanks,

Tom.

**Comment by running-coder** [comment]
Hey @tgmweb , you can verify the [beer_v1 demo](http://www.runningcoder.org/jquerytypeahead/demo/#form-beer_v1). Even if there are 4 groups, they all share the same `group.ajax.url` so only 1 call is made. Is this feature not working properly for you?

https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L896
http://www.runningcoder.org/jquerytypeahead/beer_v1.json

**Comment by tgmweb** [comment]
ahhh - I didn't see that in the beer demo.

Thanks,


Tom.

**Comment by tgmweb** [comment]
hmm, actually that doesn't work. I only get the last group.

I have a callback for each group, perhaps that's why it's not working?

I've changed my callback for each group so it only checks the object in question (my data is now data.[groupname]....)

````
ajax: {
          type: "POST",
          url: "/eunify/search/all",
          data: {
            term: "{{query}}"
          },
          callback: {
            done: function (data) {
              var retO = [];
              $.each(data.documents.hits,function(index,value) {
                var thisO = {};
                thisO.name = value._source.name;
                thisO.id = value._source.id;
                thisO.fileType = value._source.fileType;
                thisO.timeSensitive = value._source.timeSensitive;
                thisO.description = value._source.description;
                retO.push(thisO);
              });
              return retO;
            }
          }
        }
````

**Comment by running-coder** [comment]
hey @tgmweb I was able to reproduce the issue when the modified data gets corrupted. This commit should fix the issue, let me know.
