### ISSUE TITLE
Dropdown not closing

### ISSUE THREAD

**Issue by ldrrp** [running-coder/jquery-typeahead#36]
The dropdown is not closing after item selected, Seems to be an issue after this commit 5f617a3c134f80d99919157808d9cd8c4c45699a

Worked before this, Demo: http://dev.usfoodorder.com

**Comment by ldrrp** [comment]
On RC2

**Comment by running-coder** [comment]
have you updated the css? the dropdown and other menu are now closing by classname isntead of javascript

**Comment by ldrrp** [comment]
It would be nice if you had an unstyled css so users dont have to strip the styling out of your css files. I added the css but i never see any of these DOM elements created to hide them.

    .typeahead-container .typeahead-list,
    .typeahead-container .typeahead-dropdown,
    .typeahead-container .typeahead-hint,
    .typeahead-container + .typeahead-backdrop {

HTML created by javascript

    <div class="typeahead-result">
        <ul class="dropdown-menu">
            <li class="typeahead-group" data-search-group="postal"><a href="javascript:;">postal</a></li>
            <li class=""><a href="javascript:;" data-group="postal" data-index="0"><span>14201</span></a></li>
            <li class=""><a href="javascript:;" data-group="postal" data-index="1"><span>14202</span></a></li>
            <li class=""><a href="javascript:;" data-group="postal" data-index="2"><span>14203</span></a></li>
            <li class=""><a href="javascript:;" data-group="postal" data-index="3"><span>14204</span></a></li>
            <li class=""><a href="javascript:;" data-group="postal" data-index="4"><span>14205</span></a></li>
            <li><a href="javascript:;" data-group="postal" data-index="5"><span>14206</span></a></li>
            <li><a href="javascript:;" data-group="postal" data-index="6"><span>14207</span></a></li>
            <li><a href="javascript:;" data-group="postal" data-index="7"><span>14208</span></a></li>
            <li><a href="javascript:;" data-group="postal" data-index="8"><span>14209</span></a></li>
            <li><a href="javascript:;" data-group="postal" data-index="9"><span>14210</span></a></li>
        </ul>
    </div>

**Comment by ldrrp** [comment]
found the issue, my old code had the 


		selector: {
			dropdown: "dropdown-menu",
			list: "dropdown-menu"
		}
