### ISSUE TITLE
Safari pressing Tab brings back to the first tabbable item

### ISSUE THREAD

**Issue by HerrNiklasRaab** [running-coder/jquery-typeahead#360]
I'm using the control on our website. We have a Formular where tabbing is no Problem. But on Safari the curser jumps into the textbox, but not to next input, instead the first tabbable control on the site is focused.

The last working Version is 2.6.1.
The current version with the bug is 2.8.0.

Does anyone know how to solve?

Thank you very much !

Love this project,

Niklas

**Comment by running-coder** [comment]
hey @HerrNiklasRaab I was able to reproduce, will look into this

**Comment by running-coder** [comment]
Apparently it was the `this.node.blur()` that was causing the issue. Can't remember why I've added that as it is working correctly without on other browsers... Let me know if it solves your issue.

Thanks

**Comment by HerrNiklasRaab** [comment]
Yes, this fixes the issue. Thank you very much.
