### ISSUE TITLE
Game v3 demo don't work

### ISSUE THREAD

**Issue by satodavan** [running-coder/jquery-typeahead#362]
Server global.api.pvp.net has DNS error

**Comment by running-coder** [comment]
Hey @satodavan thanks for letting me know! LoL has recently changed their API endpoints & Permissions. I need to register an App and wait to get approved to have a permanent API_KEY. I've started the process and show have some news back soon.

**Comment by running-coder** [comment]
Should be good now! Let me know if more issues arise

**Comment by Chryogenic** [comment]
Seems to be broken again?

**Comment by running-coder** [comment]
Hey @Chryogenic indeed the `API_KEY` expired, It should be resolved now 👍
