### ISSUE TITLE
JS Error when `null` is returned in a response

### ISSUE THREAD

**Issue by Decklock** [running-coder/jquery-typeahead#364]
Hi Tom,

I'm having trouble getting the **emptyTemplate** to display for my data...

HTML...

```
<form>
    <div class="typeahead__container">
        <div class="typeahead__field">
            <span class="typeahead__query">
                <input id="main-search" name="main-search" class="js-typeahead" type="search" placeholder="Search..." autocomplete="off">
            </span>
            <span class="typeahead__button">
                <button type="submit">
                    <i class="typeahead__search-icon"></i>
                </button>
            </span>
        </div>
    </div>
</form>
```

Javascript...

```
$(document).ready(function ()
{
    $('#main-search').typeahead({
        delay: 300,
        filter: false,
        hint: true,
        maxItem: 8,
        minLength: 3,
        source:
        {
            'Patients':
            {
                ajax:
                {
                    url: 'Patient/Patient/Patient_Search/{{query}}',
                    dataType: 'json'
                },
                dynamic: true,
                href: 'Patient/{{id}}',
                template: '<div class="search-title">{{name}}</div>',
                emptyTemplate: 'No patients found'
            },
        }
    })
});
```

Sample data for query "**jordan**"...

`[{"id":123456,"name":"Arnold, Jordan"}, {"id":987654,"name":"Baker, Jordan"}]`

Works great when something is found. The query results are coming from a database search, so "filter" is set to false for the typeahead.

Sample data for query "**notfound**"...

`[]`

Originally, just null was returned for no results, but that caused the following JavaScript error...

> Uncaught TypeError: Cannot read property 'promise' of null
>     at Object.<anonymous> (jquery.typeahead.min.js:10)
>     at i (jquery.min.js:5)
>     at Object.fireWith [as resolveWith] (jquery.min.js:5)
>     at z (jquery.min.js:12)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:13)

So I tweaked the data to return an empty array for no results found. That avoids the error, but I'm not seeing the emptyTemplate message like I was expecting to.

The **typeahead__result** div is generated, but it's empty...

`<div class="typeahead__result"></div>`

Really appreciate your work on this excellent plugin.

Thanks in advance for the help! Let me know if you need any additional information for trouble-shooting.

-- Deck

**Comment by running-coder** [comment]
Hey @Decklock, thanks for the details I was able to reproduce the Javascript error. Regarding the `emptyTemplate` it is a Typeahead "global" option and not a group option, it needs to be placed at the top level. The reason why the `template` option can be set in the groups is because each groups might be presented / have different data structure. For an empty template that means there was no results across all the groups so it has to be a "global" option.

```javascript
$('#main-search').typeahead({
    delay: 300,
    filter: false,
    hint: true,
    maxItem: 8,
    minLength: 3,
    source: {
        'Patients': {
            ...
        },
    },
    emptyTemplate: 'No patients found'
});
```

**Comment by Decklock** [comment]
Arrrggh! Can't believe the emptyTemplate fix was that simple. Totally makes sense.

Thanks!!

**Comment by running-coder** [comment]
Should be good now when `null` is received as a response 👍
