### ISSUE TITLE
Add support for `disabled` item selection

### ISSUE THREAD

**Issue by mlalitthapa** [running-coder/jquery-typeahead#365]
Can we have a default option where we can decide if an item can be selected or not? If there is a disabled item then it cannot be selected and while pressing up and down arrow keys it will skip the disabled item.

**Comment by running-coder** [comment]
hey @mlalitthapa good idea, shouldn't be hard to implement 👍

**Comment by mlalitthapa** [comment]
@running-coder so far I am just able to send the empty value to the input box if the disabled item is clicked with updater option.

Can you give some idea on how to achive this?

**Comment by running-coder** [comment]
I've added support for `disabled` items. You can either set a `disabled: true` property on your item data or use the `matcher` option to set the item key `disabled` to `true`.

https://jsfiddle.net/runningcoder/hzr7uLse/

**Comment by mlalitthapa** [comment]
Great. Really appreciate it @running-coder
