### ISSUE TITLE
How to display objects obtained using ajax using a template. 

### ISSUE THREAD

**Issue by Alesan** [running-coder/jquery-typeahead#366]
Hello,
I have a REST system that sends users using JSON but I can not display them correctly.

The code I have is shown at the bottom of the page.

The json reception does it correctly, I can debug the data and see how it is received. but I can not show that data.

The JSON data format is:
{
   'exito': 'True',
   'data':"[{"username": "juan", "id": 1, "avatar": "foto.png"}, 
  {"username": "Pepe", "id": 3, "avatar": "foto.png"}]"

```
typeof $.typeahead === 'function' && $.typeahead({
    input: '.js-typeahead',
    minLength: 1,
    order: "asc",
    dynamic: true,
    delay: 500,
    backdrop: {
        "background-color": "#fff"
    },
    template: function (query, item) {
        var color = "#777";
        if (item.status === "owner") {
            color = "#ff1493";
        }
        return '<span class="row" style="padding:5px">' +
            '<span class="avatar" style="margin-left: 10px;margin-right: 10px;">' +
            '<img src="{{avatar}}">' +
            "</span>" +
            '<span class="username">{{username}} <small style="color: ' + color + ';display:block">({{status}})</small></span>' +
            '<span class="id">({{id}})</span>' +
            "</span>"
    },
 emptyTemplate: "No he encontrado nada {{query}}",
            source: {
                user: {
                    display: "username",
                    href: "https://www.github.com/{{username|slugify}}",
                    data: [{
                        "id": 415849,
                        "username": "an inserted user that is not inside the database",
                        "avatar": "https://avatars3.githubusercontent.com/u/415849",
                    }],
                    ajax: function (query) {
                       return {
                           type: "GET",
                           url: '/api/usuario/getUsuariosByName/'+$(".js-typeahead ").val(),
                           path: "data",
                           callback: {
                               done: function (data) {
                                   for (var i = 0; i < data.data.length; i++) {
                                           data.data[i].username = 'owner';
                                           data.data[i].status = 'contributor';
                                   }
                                   return data;
                               }
                           }
                       }
                   }
                },

            },
    callback: {
        onClick: function (node, a, item, event) {

            // You can do a simple window.location of the item.href
            alert(JSON.stringify(item));

        },
        onSendRequest: function (node, query) {
            console.log('request is sent')
        },
        onReceiveRequest: function (node, query) {
            console.log('request is received')
        },

    },
    debug: true
});
```

**Comment by running-coder** [comment]
Hey @Alesan, you are changing the `username` inside the `done()` callback. Your `display: username` tells Typeahead to search though that changed key
![screen shot 2017-09-04 at 9 06 35 am](https://user-images.githubusercontent.com/7377382/30027794-65b601b8-9150-11e7-91e4-6fc5d5d68ac3.png)
.

**Comment by Alesan** [comment]
Hello @running-coder,

After a few days looking at the documentation, examples and debugging I have not been able to make it work.

The data arrives correctly through ajax but I can not execute the _template_ function and display the results.

Always search in this data using the key _username_ declared in `display: "username"`, but not the data obtained from the query

Always look here:
data: [{
                "id": 415849,
                "username": "an inserted user that is not inside the database",
                "avatar": "https://avatars3.githubusercontent.com/u/415849",
            }],

Could you tell me an example how I can do it?
Thank you very much

**Comment by running-coder** [comment]
you need to remove this part from your Typeahead init code

```
callback: {
  done: function (data) {
    for (var i = 0; i < data.data.length; i++) {
      data.data[i].username = 'owner';
      data.data[i].status = 'contributor';
    }
    return data;
  }
}
```

this callback is re-writing your data's username to owner

**Comment by Alesan** [comment]
Thank you very much, I had a problem with the format of the data and when receiving it but it is already solved and works great.
