### ISSUE TITLE
isContentEditable always `true` on IE11

### ISSUE THREAD

**Issue by Decklock** [running-coder/jquery-typeahead#367]
Hi Tom,

I'm having trouble getting the typeahead plugin (2.9.0 dist) to run correctly in IE11 (specifically version 11.0.9600.18762).

For example, the following jsfiddle runs fine for me in Chrome (v58), but returns nothing at all in IE11...

- [https://jsfiddle.net/runningcoder/ogr7e52r/](https://jsfiddle.net/runningcoder/ogr7e52r/)

When I trace the JavaScript, the issue appears appears to be the following section (line ~~716~~ 673 of jquery.typeahead.js)... 

```
   case "input":
      scope.deferred = $.Deferred();
      if (scope.node[0].isContentEditable) {
         scope.rawQuery = scope.node.text();
      } else {
         scope.rawQuery = scope.node.val().toString();
      }
```
IE11 returns **true** for `isContentEditable`, but `scope.node.text()` always returns an empty string no matter what is typed in for the search query.

Chrome returns **false** for `isContentEditable`, and then `scope.node.val().toString()` returns the correct query string.

Am I interpreting this right?

Note: The runningcoder.org Demo page works in IE11 because it's still running 2.8, I think.

Thanks in advance for the help! Let me know if you need any additional information for trouble-shooting.

-- Deck

**Comment by running-coder** [comment]
hey @Decklock thanks for letting me know! adding support for contenteditable elements was just added in 2.9.0. As your investigation shows that might be the source of the issue... I should have expected IE to behave differently, will investigate this in priority

**Comment by running-coder** [comment]
Could you have a look and confirm that the commit resolved the issue?

**Comment by Decklock** [comment]
This version pops a new error for me on the `href` option...

> 
> Uncaught TypeError: Cannot read property 'generateHref' of undefined
>     at jquery.typeahead.min.js:10
>     at a.buildHtmlLayout (jquery.typeahead.min.js:10)
>     at a.buildLayout (jquery.typeahead.min.js:10)
>     at HTMLInputElement.<anonymous> (jquery.typeahead.min.js:10)
>     at HTMLInputElement.dispatch (jquery.min.js:7)
>     at HTMLInputElement.r.handle (jquery.min.js:7)
>     at Object.trigger (jquery.min.js:11)
>     at HTMLInputElement.<anonymous> (jquery.min.js:11)
>     at Function.each (jquery.min.js:2)
>     at n.fn.init.each (jquery.min.js:2)
> 

Here's my current `href` line...

`href: 'http://localhost:12345/Site/{{site_Id}}',`

Works fine  in both IE and Chrome when I omit the `href`.

**Comment by running-coder** [comment]
There was a scope issue when using the `href` option with the refactored code for `multiselect` option coming in `2.10.0`. Can't believe there was no tests that would have caught it... I've added one in case it ever occurs again. Thanks for reporting

**Comment by Decklock** [comment]
Clean run with this version. Works for me in Chrome, IE, and Firefox. Thanks!!
