### ISSUE TITLE
maxItemPerGroup and option.group:"keyname",

### ISSUE THREAD

**Issue by jcf3x** [running-coder/jquery-typeahead#37]
There are two option for group:
"
If set to true, the results will grouped by the group name specified inside options.source.
If set to string, the results will be grouped by the corresponding object key.
"

---
However "maxItemPerGroup" behave as a maxItemPerDataSource.
that is maxItemPerGroup is only used when comparing to itemPerGroupCount
wich is reset to zero once per datasource.

for (group in this.source) {
//..
itemPerGroupCount = 0;

---
Above loop happens only once in the case of a single source but multiple group using option.group="keyname", so evrything is treated as one big group.

Some option include: 
- preprocessing source to build group from key values
- apply maxItemPerGroup as a post processing step.

**Comment by running-coder** [comment]
Hey jcf3x,

nice catch! The "maxItemPerGroup" option should indeed consider the "group" string (if defined so) instead of the source group name. Both of your solutions are good, I'll check which one would be better considering the context.

Thanks

**Comment by running-coder** [comment]
This commit should fix the grouping, I've tested on my side and the results appear to be displayed correctly now.

Let me know if it resolved your issue.

Thanks
