### ISSUE TITLE
 User v1 demo

### ISSUE THREAD

**Issue by komprehend** [running-coder/jquery-typeahead#371]
Question regarding your User v1 demo on page http://www.runningcoder.org/jquerytypeahead/demo/

It appears the code makes 2 ajax request,  can it be configure to make only 1 ajax request and depending on whats return the appropriate group/template are used?

thanks

**Comment by running-coder** [comment]
hey @komprehend, the `user_v1` indeed makes 2 ajax requests because the `source.user.ajax` configuration is a function that returns an object. Typeahead only combine requests if the ajax group are objects and if the url matches.

```javascript
user: {
    display: "username",
    href: "https://www.github.com/{{username|slugify}}",
    data: [{
        "id": 415849,
        "username": "an inserted user that is not inside the database",
        "avatar": "https://avatars3.githubusercontent.com/u/415849",
        "status":  "contributor"
    }],
    ajax: {
        type: "GET",
        url: "http://www.runningcoder.org/jquerytypeahead/user_v1.json",
        dataType: "jsonp",
        path: "data.user",
        data: {
            q: "{{query}}"
        }
    }

},
project: {
    ajax: [{
        type: "GET",
        url: "http://www.runningcoder.org/jquerytypeahead/user_v1.json",
        dataType: "jsonp",
        data: {
            q: "{{query}}"
        }
    }
}
```

using this configuration (removed the function and placed an object for the user group) makes only 1 ajax request

**Comment by komprehend** [comment]
running-coder, thanks for your help, i am embarrassed, i discover my error :) 

i have been entering data to search that didn't exist, so i keep getting to data returned!

thanks again
