### ISSUE TITLE
Help with using dynamic filters and arrays

### ISSUE THREAD

**Issue by Chryogenic** [running-coder/jquery-typeahead#372]
Hi there, 

I am having issues getting my dynamic filter (drop down) working with an array. 

For example I may want to filter and only show results that include the location Waihi. 
The item containing the following is not included in the results:

```
      "location": [
        "Hamilton - City",
        "Waihi",
        "Thames",
        "Te Kuiti",
        "Otorohanga"
      ]
```

However an item containing the following would be included in the results:
```
      "location": [
        "Waihi",
      ]
```

where my filter is:
```
        dynamicFilter: [{
            selector: '#locations',
            key: '&location'
        }]
```

**Comment by running-coder** [comment]
Hey @Chryogenic, the dynamic filter option might be removed in the future. The functionality of applying dynamic filters based on checkboxes, radios, etc is easier to acheive using the `[matcher](http://www.runningcoder.org/jquerytypeahead/documentation/#options-matcher)` option. Simply bind an on `change` function to your elements and trigger a Typeahead search.

```
$('input.radio, input.checkbox').on('change', function() {
  myTypeahead.node.trigger('input') // trigger a typeahead search
})

var myTypeahead = $.typeahead({
...

matcher: (item, key) {
  if (item.property !== radio.value) {
    return;
  }
return true;
// return undefined to skip to next item
// return false to attempt the matching function on the next displayKey
// return true to add the item to the result list
// return item object to modify the item and add it to the result list
}
...
source: {}
...
});
```

I'll update the Game_v3 demo when I get the chance
