### ISSUE TITLE
Reloading source option keeps "old" values lingering around.

### ISSUE THREAD

**Issue by ExcelNet-Public** [running-coder/jquery-typeahead#374]
We are using this to help assist with customers entering a city / state in our system.  When the form is initialized we default to the state of WI and load into the city field all of the city names for WI.  If however the customer then changes the state to something else, say FL for instance we then reinitialize the element with the new source data.  This is all taking place in a Meteor based application.

The issue seems that after loading in the FL state city list some of the old WI cities are still there.  Even worse it seems to totally break the typeahead feature.  We type one character say 'B' and it shows the two cities in FL with a B we have, but at the bottom shows Shorewood which does not even have a 'B'???

It is possible we are not changing the source data properly so that it works as expected but cannot find anything stating how we might go about doing this in the documentation.  Thanks in advance for the assistance!

Code for initializing the field is as follows, where cityList is a simple array containing all the cities for the state currently active:

```
        this.$('.js-city').typeahead({
          offset: true,
          minLength: 1,
          source: cityList,
        });
```

HTML is similar to:

```
<div class="typeahead__container">
  <div class="typeahead__field">
    <span class="typeahead__query">
      <input class="js-typeahead js-city" name="city" type="search" autocomplete="off" placeholder="City">
    </span>
  </div>
</div>

```

**Comment by running-coder** [comment]
hey @ExcelNet-Public, there is no way currently to dynamically change a Typeahead source but to manually do the operation (some steps might be missing along the way). Your use case seems to be similar to #312 where the data needs to be "refreshed". Here is how I'm doing it in the `source` test.

https://github.com/running-coder/jquery-typeahead/blob/master/test/option/source.test.js#L25

```javascript
beforeAll(() => {
  myTypeahead.options.source = ['data1', 'data2'];
  myTypeahead.unifySourceFormat();
  myTypeahead.node.trigger('generate');
});

// if you did not assigned your Typeahead to a variable (myTypeahead) you can get the object through the global window -> `window.Typeahead['.yourInitSelector'].options.source.group`
```

For now you should be able to switch your Typeahead source using this method or by re-initializing the Typeahead on your element

**Comment by pjominet** [comment]
I got the same issues as describe above, but I am confused on how your workaround works.

Got it more or less like this now: 

`let input = modal.find('.modal-body #tagInput')
// some other code
input.typeahead({
    source: {
        suggest: {
            data: dummy_data
        }
    }
});`

**Comment by pjominet** [comment]
OK Problem is gone, had some unnecessary event cascadation that cause the issue
