### ISSUE TITLE
data match

### ISSUE THREAD

**Issue by komprehend** [running-coder/jquery-typeahead#375]
i have a question i am using jquery-typeahead for address, for example the following 2 address are the same and in my back end search i treat them the same (I convert address to a specific format)

50 East 90 Street
50 E 90 Street

the issue is if user enter 50 E 90 street, my system back end knows its means 50 East 90 Street and return that as a result.

however jquery-typeahead won't display it since its not the same as  50 E 90 Street which is what the user type. So is there anything can be done about this?

thanks

**Comment by running-coder** [comment]
hey @komprehend, the [`filter: false`](www.runningcoder.org/jquerytypeahead/documentation/#options-filter) option was created specially for this situation.

>If set to false, Typeahead will skip any kind of filtering. This option is useful if you already filter the results in Backend.
