### ISSUE TITLE
Not Working in IE 10 or 11

### ISSUE THREAD

**Issue by bdjema** [running-coder/jquery-typeahead#376]
Dear,
Thanks for this plugin, but it not working in IE 10 or IE 11, Not Error show in web console.

Thanks and Regards,
Bdjema

**Comment by running-coder** [comment]
Hey @bdjema I only see a css problem on IE10 & 11, could it be possible that it's not working because of a combination of configuration? Could you provide me your configuration with test data?

**Comment by janderegg** [comment]
I've also got the css issue with IE (Loupe icon is too height; also in the demos). Will this be fixed soon?
![capto_capture 2017-10-04_05-16-42_pm](https://user-images.githubusercontent.com/1305988/31183749-cc9ff3e0-a927-11e7-859c-eb5717497f5d.png)

**Comment by running-coder** [comment]
How does the visual look now? I know it's not perfectly centered but this is as far as I could go without breaking the modern browsers. Feel free to open a PR and modify the code a bit if you feel like it needs more tweaking (keep in mind to validate all other browsers as well).

@bdjema Could you add more details / screenshots regarding your original issue?

**Comment by janderegg** [comment]
looks great now!

**Comment by running-coder** [comment]
Closing this issue, haven't got any replay regarding the original issue

**Comment by bdjema** [comment]
Sory for my late reply, i just come back from my holyday.
I configure this use custom template:
`$('.js-typeahead').typeahead({
                    minLength: 3,
                    maxItem: 20,
                    order: "asc",
                    dynamic: true,
                    highlight: true,
                    suggestion: true,
                    hint: true,
                    cancelButton: false,
                    backdrop: {
                        "background-color": "#fff"
                    },
                    template: function (query, item) {
                        return '<div class="row">\
                                 <div class="col-md-12">\
                                  <h4>{{Name}}</h4>\
                                  <h5>Code: {{Code}}<span class="label label-warning pull-right">{{Price}}</span></h5>\
                                </div>\
                                </div>';
                    },
                    emptyTemplate: "no result for {{query}}",
                    correlativeTemplate: true,
                    source: {
                        products: {
                            ajax: function (query) {
                                return {
                                    type: "POST",
                                    url: "/forms/getproduct",
                                    data: {
                                        code: "{{query}}"
                                    },
                                    callback: {
                                        done: function (data) {
                                            return data;
                                        }
                                    }
                                }
                            }
                        }
                    },
                    callback: {
                        onClick: function (node, a, item, event) {
                           ///append to table here
                        }
                    },
                });`

**But not data appears and when i debug it, it not call to server use ajax but work in all browser except IE **

**Comment by running-coder** [comment]
Thanks for the precision @bdjema , I'll have a look shortly

**Comment by running-coder** [comment]
Hey @bdjema I've just tested IE 10 & 11, works without any issue, I'm able to get results and the requests are sent. From your config it seems that you are missing the `display` config to tell Typeahead to search in which keys of your objects, ex: `display: ['Name', 'Code']`

![ie10_typeahead2 10 4](https://user-images.githubusercontent.com/7377382/31804277-2cbc9e72-b526-11e7-86d8-61d8fda5ab1f.png)

**Comment by bdjema** [comment]
Hi, Thanks for fast response, now it working, i update typeahead version to..and problem solved.

Thanks and best regards

**Comment by rockinteamf1824** [comment]
I was developing autosuggest with this plugin http://synapse.asia/voting_11942/typehead2.php

it works in chrome but in IE 10 when i type "a" it works first time. if i type a again it does not work in ie 10. see attached http://synapse.asia/voting_11942/ie10.png
