### ISSUE TITLE
How to add Custom option in jquery typeadhead

### ISSUE THREAD

**Issue by ChandrakantDevani** [running-coder/jquery-typeahead#377]
Hi,

how can i  add custom option end of list? 

see this image
![seach](https://user-images.githubusercontent.com/28138615/31005042-ad19a4a6-a514-11e7-9f26-5ceb27a6af1d.jpg)

**Comment by running-coder** [comment]
hey @ChandrakantDevani you might want to look into the [`onLayoutBuildBefore`](www.runningcoder.org/jquerytypeahead/documentation/#callback-onLayoutBuiltBefore) option. There is an example of how you could append an element to the `resultHtmlList` before the results gets displayed
