### ISSUE TITLE
Build a demo using dynamic sources

### ISSUE THREAD

**Issue by rodduralam** [running-coder/jquery-typeahead#378]
**Build a demo using dynamic sources** 
First time both auto-complete loading there all data individually. If nothing choice from first auto-complete then second auto-complete should be show all data, When select an item from first auto-complete input then second auto-complete data shorting depend on first auto-compete selection and if change selected item of first auto-complete then again resorted data of second auto-complete

**Comment by running-coder** [comment]
hey @rodduralam, this demo has been requested for some time when selecting a country, then a city, I'll see what I can do to quickly put one up!

**Comment by rodduralam** [comment]
Hey Dear owner, thanks a lot for your replay. Dear owner i am stuck with my project because of this. I have all ready wasted plenty of time. I can't leave it like this cause it's other features are really awesome. I have to use these sort of features all over the project of mine.   

When selecting a country, then a city it's fine. But when any country is not selected then all city would be loaded when city input node focus or click.
