### ISSUE TITLE
Autocomplete filter not working correctly with city list json

### ISSUE THREAD

**Issue by aberbenni** [running-coder/jquery-typeahead#379]
![autocomplete-at-ott-04-15-49-13](https://user-images.githubusercontent.com/1632412/31180130-128e2f66-a91e-11e7-93a4-6676d8dcc095.png)

config is:
```
        offset:true;
        cancelButton: false,
        cache: 'sessionStorage',
    	source: {
    		comuni: {
            	       ajax: {
            		     method: "GET",
                	     url: url_
            	       }
        	}
        },
        matcher: function (item, displayKey) {
                 console.log("matcher");
                 console.log(displayKey);
                 console.log(item);
        }
        generateOnLoad: true,
    	debug: true
```
Match is correct

**Comment by aberbenni** [comment]
adding:

```
                 callback: {
			onResult: function (node, query, result, resultCount, resultCountPerGroup) {
				console.log(node, query, result, resultCount, resultCountPerGroup);
			},
			onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
				console.log("onLayoutBuiltBefore")
				console.log(node)
				console.log(query)
				console.log(result)
				console.log(resultHtmlList)
			}
		}
```
gives me:

![screenshot at ott 04 16-27-22](https://user-images.githubusercontent.com/1632412/31181405-854f5e96-a921-11e7-917f-f92cea383b55.png)

Cannot filter those "Ghost" list elements.

**Comment by running-coder** [comment]
hey @aberbenni if you declare a [`matcher`](http://www.runningcoder.org/jquerytypeahead/documentation/#options-matcher) function by default you are returning undefined. You need to return true if you want those items to be added in the Typeahead list. I'm surprised they are showing in your example 🤔 

```javascript
// return undefined to skip to next item
// return false to attempt the matching function on the next displayKey
// return true to add the item to the result list
// return item object to modify the item and add it to the result list
```

Regarding those ghost items, you mean your listing starting with "PA*" in your first screenshot? How are they getting there? Anything declared in your Typeahead config? I don't get how they are getting there

**Comment by aberbenni** [comment]
Thanks for prompt reply @running-coder 
In matcher function there was a cut an paste error, `return true` was there. 
Ghost items were caused by faulty HTML. Issue closed.
Nice to know that this library is well supported.
