### ISSUE TITLE
callback "onLayoutBuiltBefore" doesn't return a list, but "true"

### ISSUE THREAD

**Issue by alery** [running-coder/jquery-typeahead#38]
Hey running-coder,

thank you for your framework, I like it.
Unfortunately "onLayoutBuiltBefore" doesn't work for me. I only see "true" in the result list on my page.

....
callback: {
                onLayoutBuiltBefore: function (node, query, result, resultHtmlList){
//result parameter has matched items,
//resultHtmlList ist an empty list
                    for (var i = 0; i < result.length; i++) {
                        console.log(result[i].display);
                    }
                }
            },
....

You are working on the release 2 and has changed many file last days. Would you recommend to use this new result on my production system or wait a couple weeks better, so you can fix bugs of the new features?

Thanks
Alery

**Comment by running-coder** [comment]
hey alery,

perhaps I've forgot to mention that resultHtmlList needs to be returned if you are using onLayoutBuiltBefore. This callback is meant to modify the result Html before inserting inside Typeahead.

``` javascript
onLayoutBuiltBefore: function (node, query, result, resultHtmlList){
    for (var i = 0; i < result.length; i++) {
        console.log(result[i].display);
    }
    return resultHtmlList;
}
```

**Comment by alery** [comment]
thanks, return resultHtmlList; works fine!
