### ISSUE TITLE
Suggestion box stays open on choosing an entry when using dynamic:true

### ISSUE THREAD

**Issue by benji** [running-coder/jquery-typeahead#380]
I am playing with the first demo example "Country v1": https://jsfiddle.net/qz7dfsku/

I am trying to have the suggestion box disappear when I select one of the choices.
It seems adding dynamic: true breaks it, if I set it to false then it works.

Any way to tweak that ?

**Comment by running-coder** [comment]
Hey @benji thanks for reporting the issue. Indeed that's an unwanted behaviour because of an extra request being sent when the item is selected, will patch that asap.

**Comment by running-coder** [comment]
Should be resolved now, I've also added a couple tests over this.

**Comment by benji** [comment]
Really appreciate the fast resolution, thanks a lot!
