### ISSUE TITLE
Search request being sent when an item is selected

### ISSUE THREAD

**Issue by ionesculiviucristian** [running-coder/jquery-typeahead#381]
In v.2.10.1, if I search a partial word (for ex: 12A) and the I click on one of the results (ex. Emil Racoviță :: 12A (Brasov, Brasov)) then the input will be filled with the selected text (as expected) BUT a new search request will be sent with the input's new value.

Could be here: https://github.com/running-coder/jquery-typeahead/commit/8248c9a53857c73a1f6abdea0892ff160a41600b at line 2447.

**Comment by running-coder** [comment]
hey @ionesculiviucristian, thanks for reporting the issue, indeed an extra request is sent but shouldn't. I'll apply a fix and add a couple tests around that asap.

**Comment by running-coder** [comment]
Should be resolved now, I've also added a couple tests over this.
