### ISSUE TITLE
onEnter  event

### ISSUE THREAD

**Issue by marccollin** [running-coder/jquery-typeahead#384]
Hi

onEnter event is still available?

because i never see it's been called.

```
onEnter: function (node, a, item, event) {
    console.log("onEnter:");
}
```

**Comment by tombertrand** [comment]
hey @marccollin, yes onEnter is still available when hovering a search result

```javascript
$.typeahead({
    input: ".js-typeahead",
    ...
    callback: {
        onEnter: function (node, a, item, event) {
            console.log(item);
        }
    }
});
```

![image](https://user-images.githubusercontent.com/19352322/31672191-dd1c5c8e-b329-11e7-8d72-a39ae8464c42.png)
