### ISSUE TITLE
clearOnHideIfNotSelected null check on this.item.key

### ISSUE THREAD

**Issue by 1lln3ss** [running-coder/jquery-typeahead#385]
In the latest version, at line 2337 of jquery.typeahead.js (method clearOnHideIfNotSelected), there is the following nullcheck: _if(this.item.key == null)_.

When no value is selected by the user, _this.item_ is null, causing a javascript error and preventing the form from being submitted.

In my use case, changing the condition to _if(this.item == null || this.item.key == null)_ seems to fix the problem.

I could reproduce in IE, Firefox and Chrome.

N.B.: There may also be other issues with _this.item_ being null in other use cases, when _staticDropdown: true_ is set.

**Comment by tombertrand** [comment]
hey @1lln3ss are you using the latest `2.10.4`? Can't find the code reference. Can you link it?

**Comment by 1lln3ss** [comment]
My bad, sorry about that.  I should drink more coffee.
