### ISSUE TITLE
Fontv1 Demo not working

### ISSUE THREAD

**Issue by Riad-Jarjour** [running-coder/jquery-typeahead#388]
I tried the Fontv1 Demo on both Firefox and Chrome but the spinner just keeps spinning and nothing happens. Could be a bug?

**Comment by tombertrand** [comment]
Indeed `enfont.com` (the data source) is not available anymore, will try to renew that

**Comment by tombertrand** [comment]
There, should be repaired! 👍  http://www.runningcoder.org/jquerytypeahead/demo/#form-font_v1
