### ISSUE TITLE
fix: Allow `onLayoutBuiltBefore` to return a custom template, wrap `<li>` inside other `<ul>` or `<div>`

### ISSUE THREAD

**Issue by martijn1k** [running-coder/jquery-typeahead#389]
Hey man, first of all... AWESOME plugin. It's really well written and documented.

However... I've been staring at the documentation for two days now, and I've been searching inside Github for a solution, but I cannot find it.

Is there a way to end up with:

```
<div class="typeahead__result">
      <div class="typeahead__list">
            <div class="row group">
                 <div class="col-md-3 typeahead__group">Group Name</div>
                 <div class="col-md-9 typeahead__items">
                        <ul>
                              <li class="typeahead__item">Item Stuff</li>
                        </ul>
                  </div>
            </div>
      </div>
</div>
```

I tried several things using template and groupTemplate but I always end up with 1 UL which holds the group names AND items for all groups, so there is no way to distinguish between different groups. 

What I'm trying to achieve is a 2 column layout, column 1 holds nothing but the group name, column 2 holds the corresponding items so I can display them next to eachother when there is enough screen real estate.

Maybe I'm overthinking or missing something.
Hope you can give me some advice.

Thanks in advance.
And once again, great work!

**Comment by running-coder** [comment]
Hey @martijn1k thanks for the kind words! I was able to acheive the desired result with a minor tweak to Typeahead using the beer_v1 demo

![screen shot 2017-10-27 at 11 19 56 am](https://user-images.githubusercontent.com/7377382/32111546-c943caf8-bb08-11e7-8984-556a5c86a4ef.png)

and this code snippet using the `onLayoutBuiltBefore` callback

```javascript
callback: {
    onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
        var newResultHtmlList = $('<div />', {
            'class': 'typeahead__list'
        });

        resultHtmlList.find('li').each(function( index ) {
            if ($(this).hasClass('typeahead__group')) {
                newResultHtmlList.append('<div class="row group">\
                <div class="col-md-3 typeahead__group">' + $(this).text().trim() + '</div>\
                <div class="col-md-9 typeahead__items"><ul></ul></div>\
                </div>')
            } else {
                newResultHtmlList.find('.typeahead__items:last ul').append($(this));
            }
        });

        return newResultHtmlList;
    }
}
```

**Comment by martijn1k** [comment]
Hey, thanks a lot for your reply! I just tested the code, but I'm only getting back the group names.
The items are not shown, I thought I was doing something wrong, so I downloaded the demo beer v1 and tried the code in there, but it is doing the same.

So luckly I'm not going crazy ;) am I missing something the onLayoutBuiltBefore?
Is there a call to populate the list needed or something?

Hope to hear from you soon. Have a nice weekend

**Comment by running-coder** [comment]
The reason why you would get only the group names is that you haven't picked up the commit cd225f48d30b068782f91f095ce6735d64b3213b on the develop branch, I did not changed the beer_v1 demo just made it work using it.

https://jsfiddle.net/runningcoder/ros1wcoy/

**Comment by martijn1k** [comment]
Mr Bertrand... I'm sorry, missed the comment about the dev branch!
Just fetched it and it works beautifully. Thank you so much! You are awesome!

**Comment by running-coder** [comment]
Np! glad it works let me know if you face any other issue
