### ISSUE TITLE
Manipulate data object in onDone callback function

### ISSUE THREAD

**Issue by alery** [running-coder/jquery-typeahead#39]
Hey running-coder,

I use this onDone callback (results are in object "term" of my response), that's why I use onDone()):

callback: {
   onDone: function (data) {
      var _data = [];
      for (var i = 0; i < data.result.length; i++) {
         _data.push(data.result[i].term);
      }
      return _data;
}

My manipulated _data object hasn't any impact on the internal function, so I don't see my changes on the data.

What is wrong with my function?

Alery

**Comment by running-coder** [comment]
Hey alery, indeed the data does not get re-assigned
https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L606
will fix that shortly.

can you paste your complete options.source object just so I'm sure this is the issue?

Thanks

**Comment by alery** [comment]
thank you running-coder!

...
source: {
                filter : false,
                url : [{
                    type: "POST",
                    url: "myURL",
                    data: {
                        term: "{{query}}"
                    },
                    callback: {
                        onDone: function (data) {
                            var _data = [];
                             for (var i = 0; i < data.result.length; i++) {
                                 _data.push(data.result[i].term);
                             }
                             return _data;
                        }
                    }
                }]
            },
....

**Comment by running-coder** [comment]
Hey alery,

I've fixed the issue and modified the ajax callback to match the naming from jquery http://api.jquery.com/jquery.ajax/

``` javascript
callback: {
    done: function (data, textStatus, jqXHR) {},
    fail: function (jqXHR, textStatus, errorThrown) {},
    complete: function (jqXHR, textStatus) {},
    always :function (data, textStatus, jqXHR) {}
}
```

Thanks
