### ISSUE TITLE
Need help with AJAX based remote data source

### ISSUE THREAD

**Issue by enno-au** [running-coder/jquery-typeahead#392]
Doing what I thought would be a fairly straight-forward sort of auto-completion task. Basically, need to select from a list of VM names kept in our CMDB. I have the input side of the job working as far as I can see from the server logs.

<pre>
        $.typeahead({
                input: '.ta-addhost',
                dynamic: true,
                hint: true,
                minLength: 1,
                order: "asc",
                offset: true,
                hint: true,
                debug: true,
                source: {
                        name: {
                                ajax:   function (query) {
                                                console.log("query: "+query)
                                                $.ajax({
                                                        url: 'action.php?verb=ajax&noun=variant_alert_threshold&action=findhost&host='+query,
                                                        success: function (r, s, x) {
                                                                console.log("query: "+ query +" --> resp: "+ r)
                                                                return(r,s,x);
                                                        }
                                                });
</pre>

which sees data like this coming back from AJAX url on the webserver...

<pre>
        splunksrch01-dcom:root [6] curl -ksSD - "https://localhost/alertmgr/action.php?verb=ajax&noun=variant_alert_threshold&action=findhost&host=act"
        HTTP/1.1 200 OK
        Date: Wed, 08 Nov 2017 22:34:41 GMT
        Server: Apache/2.2.15 (CentOS)
        X-Powered-By: PHP/5.3.3
        Access-Control-Allow-Origin: *
        Content-Length: 250
        Connection: close
        Content-Type: application/json
        
        { "hosts": ["activations-coles-web01-dev","activations-colesweb01-prod","activations-colesweb01-qa","activations-colesweb02-prod","activations-optusweb01-dev","activations-optusweb01-prod","activations-optusweb01-qa","activations-optusweb02-prod"] }

</pre>

Now from the debug in the javasrcipt consol in the browser it's clear I'm not telling the library how to identify where in the returned JSON data to find the output list. You'll note that I don't need to do any sorting or selection as the AJAX call has already done all that from the database. All I need to do is pass the entire return into the library to populate the list of alternatives...

I have tried various forms of <pre> return { } </pre> with little joy. Was just hoping for some hints as to what I should have there...

Thanks in advance.

**Comment by running-coder** [comment]
Hey @enno-au sry for the late reply, so indeed you are slightly configurating Typeahead the wrong way. Either you use the `ajax` property as an object or a function that returns an ajax configuration, you can see a bunch of example here: 

http://www.runningcoder.org/jquerytypeahead/documentation/#options-source

```javascript
ajax: {
  url: ...,
  data: {
    q: '{{query}}'
  },
  callback: {
    done: function () { ... }
  }
}
// vs
ajax: function () {
  // operations here
  return {
    url: ...,
    data: {
      q: '{{query}}'
    },
    callback: {
      done: function () { ... }
    }
  };
}
```

alternatively you can use a Promise object is the `data` property if you want to do your own call (not using ajax)
```javascript
data: function () {
 
            var deferred = $.Deferred();
 
            // Gather your data, and resolve the deferred object with an array of objects
            // setTimeout is used only to show that the data is async
            setTimeout(function () {
                if (Array.isArray(data) {
                    deferred.resolve(data);
                } else {
                    deferred.reject("Invalid data.");
                }
            }, 2000);
 
            deferred.always(function () {
                console.log('yay! :D')
            });
 
            return deferred;
        }
```

**Comment by ytoh** [comment]
Hi @running-coder, is there a way to get to the query string in the data function returning a promise?

**Comment by running-coder** [comment]
@ytoh this should do it 👍 
```javascript
data: function () {
    console.log(this.query)
}
```
