### ISSUE TITLE
onResult firing when clicking on result item

### ISSUE THREAD

**Issue by nuclearsiloman** [running-coder/jquery-typeahead#394]
Maybe I am interpreting onResult wrong, I think it means when results come back and before they are placed in the listing.

The issue I have is I get the resultCount to set paging in this call back.  All works fine until I click on an item in the results listing - it then fires the callback again (onResult) and sets the resultCount to 0.

More specifically, this is what I am doing.  I have 1 instance of typeahead:
```javascript
       $('#buydata').typeahead({
            minLength: 3,
            maxItem: 0,
            dynamic: true,
            delay: 300,
            offset: false,
            cache: false,
            filter: false,
            resultContainer: "#bresultsbuy",
            hint: false,
            cancelButton: false,
            highlight: false,
            source: {
                product: {
                    data: [],
                    ajax: function (query) {
                        return {
                            url: "GetProducts.asp?" + getparams('buy'),
                        }
                    }
                }
            },
            callback: {
                onClick: function (node, a, item, event) {
.......
```
I  show all the results in a scrollable div.  I use the onClick callback to add the item to another box.  Since the search is made of parameters, I create a string and append that to the URL being passed.  Works perfectly.  The database returns the proper records.

I set up the paging.  Next/Prev buttons work fine buy changing the string that is appended to the URL, typeahead sends the query, I get the results.  I use $('#buydata').trigger('input.typeahead'); on the prev/next buttons to fire the instance, works great.

Everything works perfect until I click one of the results (callback onClick).  Then nothing works.  Text input box, paging buttons, are just dead.  No errors in the console.

**Comment by nuclearsiloman** [comment]
OK, the problem turned out to be that .typeahead had issues with the input field being type='hidden'.  Once I unhid it, all worked fine. Why?

**Comment by running-coder** [comment]
hey @nuclearsiloman could you fork https://jsfiddle.net/runningcoder/hzr7uLse/ and put up a quick demo? Would help me to understand the issue, just put in some test data in the `source` config
