### ISSUE TITLE
limitTemplate doesn't display unless emptyTemplate is defined

### ISSUE THREAD

**Issue by corsacca** [running-coder/jquery-typeahead#396]
It took me a while to get the limitTemplate option to work. The code from the example worked but mine didn't. The difference is that i didn't have the emptyTemplate option defined. 
I don't know if this is a bug or just needs to be mentioned in the docs.

**Comment by tombertrand** [comment]
hey @corsacca you are right, the `limitTemplate` should be working without the `emptyTemplate`, that was a mistake 👍

**Comment by running-coder** [comment]
this commit on the `develop` branch should resolve the issue

**Comment by corsacca** [comment]
@running-coder Nice work! Tested the develop branch and the `limitTemplate` now works without having the `emptyTemplate`
