### ISSUE TITLE
onSendRequest callback needed

### ISSUE THREAD

**Issue by alery** [running-coder/jquery-typeahead#40]
Hey running-coder,

I need for my implementation one callback more. I have modified you code so I can already use it. It would be nice, if you can insert ist in you code.

....
callback: {
.....
   onSendRequest: null,
....
handleRequests: function () {

            this.helper.executeCallback(this.options.callback.onSendRequest, [this.node, this.query]);

....

Thanks,
alery

**Comment by running-coder** [comment]
Hey alery,

could you explain what manipulation you are trying to do? Perhaps there is another callback you can use? Having something inserted there means that if there are 3 sources, that callback would execute 3 times.

That reminds me I have to update the flowchart...

**Comment by alery** [comment]
I want to show a loader wenn request started (onSendRequest) and hide them wenn result will be shown (onResult)
