### ISSUE TITLE
display with an array of objects

### ISSUE THREAD

**Issue by xr280xr** [running-coder/jquery-typeahead#400]
Hi. I'm trying to do a customer account search. I have data like this:
```
[{
    id="1",
    FName: "John",
    LName: "Smith",
    students: [
      {
        id="1",
        FName: "Billy",
        LName: "Smith"
      },
      {
        id="2",
        FName: "Jenny",
        LName: "Smith"
      },]
    }]
```
I would like to search by either the outer account FName ("John") or the inner students' FName ("Billy" or "Jenny"). I tried setting display: ["FName", "students.FName"], but it doesn't look like that's supported? Is there any way to do this?

**Comment by running-coder** [comment]
Closing, let me know if this is still an issue
