### ISSUE TITLE
Prevent autocomplete on click result?

### ISSUE THREAD

**Issue by twistedpixel** [running-coder/jquery-typeahead#402]
I'm trying to prevent the result text from being entered into the search box when a result is clicked. I'm setting 'href' as I just want each result to be a link.

I'm currently setting a callback handler for onClick which simply returns false. It works but I'm wondering if there's a cleaner way to do it?

Thanks!

**Comment by running-coder** [comment]
hey @twistedpixel sorry for the delay, yes `templateValue` was built to have custom values when items are clicked, but your solution is good also. It always depends on what are your usecase etc.

Closing, let me know if you have more questions.
