### ISSUE TITLE
Set Default Value

### ISSUE THREAD

**Issue by Sourcenew** [running-coder/jquery-typeahead#405]
How set default value (Selected item) and fire onClickAfter event

**Comment by running-coder** [comment]
hey, setting the value is as easy as setting the `<input />` value. If you wanna set the item to be sent on the submit you can always push it manually to your Typeahead instance

```javascript
Typeahead['.js-typeahead-country_v1'].item = { key: 'abc', value: 'xyz', group: 'test' }
```

Closing, let me know if you have more questions

**Comment by pawan-embibe** [comment]
setting value on <input /> sets the value but doesnt show cancel button. How to display that?
