### ISSUE TITLE
Resetting programmatically

### ISSUE THREAD

**Issue by mikmanic** [running-coder/jquery-typeahead#407]
Is it possible to programmatically reset the input field and close result list? I'm using the component in SPA and want to reset it after user navigates to the url.

**Comment by running-coder** [comment]
yes! you can do `Typeahead['.js-typeahead'].node.val('').trigger('input');`. `js-typeahead` is your `input` option you used to initialize typeahead. you can also store your init in a variable.

```javascript

Typeahead['.js-typeahead'].node.val('').trigger('input');

VS

var myTypeahead = $.typeahead({
    input: '.js-typeahead',
    source: { ... }
    ...
});

myTypeahead.node.val('').trigger('input');
```
