### ISSUE TITLE
Feature request: Don't filter dropdown items by source.display

### ISSUE THREAD

**Issue by weenchehawk** [running-coder/jquery-typeahead#409]
I need to disable the filter based on keys as specified in source.display.

I have very many keys (over 30) and don't want to have to list them all.

The data is already filtered & ordered based on a web query, built from an underlying database query which accepts the search text. There seems to be no way to do this - right now I need to specify all keys in the JSON data in order to prevent the typeahead from further filtering my data.

If I have missed something in the docs, I do apologise.

**Comment by running-coder** [comment]
hey @weenchehawk, seems like yo uhave missed `filter: false` from the doc, let me know if that works.
