### ISSUE TITLE
different href for each result item

### ISSUE THREAD

**Issue by alery** [running-coder/jquery-typeahead#41]
Hey running-coder,

is there any possibility to set a different href for each result item. My response object from server contains strings then will be displayed and for each result string a href string.

if that's possible, which format of data must have my response object from server?

example:

var myResponseData = [];
myResponseData.display = ["result 1", "result 1"];
myResponseData.href = ["http://hrefForResult1", "http://hrefForResult2"];

Thanks,
alery

**Comment by running-coder** [comment]
have you tried using http://www.runningcoder.org/jquerytypeahead/documentation/#options-href?

**Comment by alery** [comment]
yes, but this will not work so, because my href string are completely different.

**Comment by running-coder** [comment]
ideally your server should return you an array of objects instead of an array of strings. It would allow you to do something like:

``` javascript
display: ["title", "subtitle"],  // search through multiple keys
href: "{{href}}",                   // assign the href key (adding |raw might be needed because it slugify by default)
source: {
    group: {
        data: [{
            "title": "this is a title",
            "subtitle": "my subtitle",
            "more": "etc."
            "href": "http://myurl"
        }]
    }
}
```

**Comment by alery** [comment]
it works :)

But my url will changed from "http://www.google.de" to "http-www-google-de"

**Comment by running-coder** [comment]
should work now

``` javascript
href: "{{href|raw}}",
```
