### ISSUE TITLE
Dropdown filter on mobile

### ISSUE THREAD

**Issue by pcout** [running-coder/jquery-typeahead#411]
When viewing on mobile (or custom breakpoint) can I hide the **dropdown filter** container ?
Also, can I hide the search button on **desktop view** (and use enter key) ?

thanks

**Comment by running-coder** [comment]
Hey yea, just use custom mediaqueries styles, outside of Typeahead's scope tho. Enter key will work with the input alone, the search button is mainly for esthetics
