### ISSUE TITLE
recent typed data on focus display on search bar

### ISSUE THREAD

**Issue by anglyeds** [running-coder/jquery-typeahead#415]
My objective is to get recent typed data during On focus on search bar.

I have tried the searchOnFocus = true , unfortunately, it doesn't work.

is there anyway to do it ?

**Comment by running-coder** [comment]
hey, Typeahead does not bind event handler, 
this can be done through regular jquery event binding

```javascript
$(".js-typeahead").focus(function(e) {
 	console.log(e.target.value);
});
```
