### ISSUE TITLE
Integrating with another plugin

### ISSUE THREAD

**Issue by dave7777** [running-coder/jquery-typeahead#416]
Hello!
I and having his error when I add the following plugin to a pahge whcih has your typehead script installed:

WHEN I CLICK ON THE IMAGE TO BE ZOOMED OR SCALED - THE POINTER MOVES TO THE TYPEHEAD ENTRY BOX....not sure why this is happening...((

https://codecanyon.net/item/jquery-giga-image-viewer-animated-zoom-and-pan/2970559?s_rank=5
https://codecanyon.net/item/uber-zoom-jquery-smooth-zoom-pan/9904215

I have attacheed  both plugins if you coudl test them it woudl be so great!

https://clicknupload.org/zudsbxnyz3sx
https://clicknupload.org/yln7no2of6uj

**Comment by dave7777** [comment]
I have uplodaed the webpage which has the two plugins included - test.html in this archieve...
can you please take a look Tom?

Not sure why the ciursor gets to the input field when I click on the image on my mobile.

https://sendit.cloud/0upgxcp768xu

**Comment by dave7777** [comment]
can you please take a look? maybe I can pay you to try to reconcile these two scripts?

**Comment by dave7777** [comment]
I amn getting this error when I click on mobile view

Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

si this has to do with the typeahed?

**Comment by running-coder** [comment]
hey dave, let me know if your issue is fixed or I should be having a look

**Comment by dave7777** [comment]
Glad to hear from you - yes there was soem kidn of a bug with thsi script so I wen ahead with another) workign fien now - thank you!)
