### ISSUE TITLE
Search Key use corresponding value. How?

### ISSUE THREAD

**Issue by suchislife801** [running-coder/jquery-typeahead#417]
Greetings Experts. 

After much research I've arrived at your page and I'm a bit overwhelmed by the examples. Basically I need to search an array of key/value pairs returned from a PHP/MySQL select query and submit the selection to a second PHP/MySQL search.

Here's my json file...

```
[
  {
    "name":"Sarah Connor",
    "client_id":"111"
  },
  {
    "name":"John Travolta",
    "client_id":"222"
  },
  {
    "name":"Tom Cruise",
    "client_id":"333"
  }
]
```

How can I make the plugin search for through the names above, and once the user clicks on one, pass the corresponding client_id to a function so that I can run an Ajax search on it?

Thank you for any help.

**Comment by running-coder** [comment]
hey I recomment going from top to bottom inside the demo page, they are by order of customization, what you are looking for is to start from something very simple and implement on top

```javascript
var data = [
    {
        "name":"Sarah Connor",
        "client_id":"111"
    },
    {
        "name":"John Travolta",
        "client_id":"222"
    },
    {
        "name":"Tom Cruise",
        "client_id":"333"
    }
];

typeof $.typeahead === 'function' && $.typeahead({
    input: ".js-typeahead",
    minLength: 1,
    order: "asc",
    display: ["name"],
    template: "{{name}} <var>{{client_id}}</var>",
    emptyTemplate: "no result for {{query}}",
    source: {
        myGroup: {
            data: data,
        }
    },
    callback: {
        onClick: function (node, a, item, event) {
            console.log(item)
            alert(item.client_id)
        },
    }
});
```
