### ISSUE TITLE
unknown error:  Missing keys for display, make sure options.display is set properly.

### ISSUE THREAD

**Issue by arcee123** [running-coder/jquery-typeahead#42]
I apologize for this being a noob question, but I am getting this error:

"Missing keys for display, make sure options.display is set properly."

I do not know what this parameter is looking for, nor how to troubleshoot it.  how do I set this property?

**Comment by running-coder** [comment]
Hey arcee123,

this is a warning meaning that one or more of your objects are missing the display key you have selected. You should have more details about the missing key under the "arguments" row of the debug outputs. If this behavior is intended you can ignore the warning and use the minified version on your production environment to disable the debug outputs.

``` javascript
// configuration
display: ["name", "conference"]
source: {
    hockey: {
        data: [{
            name: "canadiens",
            conference: "eastern"
        }, {
            name: "maple leafs"
            // object is missing "conference" key that the display is looking for
        }]
    }
}
```

**Comment by arcee123** [comment]
Thank you so much for this information.
What if you are using a URL source?

right now my JSON return looks like this:

{
    "COLUMNS": [
        "LOCATION"
    ],
    "DATA": [
        [
            "Ashaway, Washington County, RI 02804"
        ],
        [
            "Block Island, Washington County, RI 02807"
        ],
        [
            "Bradford, Washington County, RI 02808"
        ]
    ]
}

Thanks again very much

**Comment by running-coder** [comment]
Regarding your data, if you are using strings you should structure it like this:

``` javascript 
// Array of strings
data: [
    "Ashaway, Washington County, RI 02804",
    "Block Island, Washington County, RI 02807",
    "Bradford, Washington County, RI 02808"
]

// Array of objects
display: ["city", "state", "zip"]
template: "{{city}}, {{state}}, {{zip}}"
data: [
    {
        city: "Ashaway"
        state: "Washington County"
        zip: "02804"
    }, {
        // more objects
    }
]
```

I recommend to read the doc and look into the demo (you should see examples using URL as data source) http://www.runningcoder.org/jquerytypeahead/demo/

**Comment by ratebeer** [comment]
Thanks so much Running Coder for putting this together. Are you saying my JSON should be structured like this?
`
display: ["BrewerID","BrewerName"]
template: "{{BrewerID}}, {{BrewerName}}"
data: [{
 BrewerID: 76
BrewerName: 'Stone Brewing Company'
} ,{
 BrewerID: 398
BrewerName: 'Firestone Walker Brewing Co.'
} ,{
 BrewerID: 17232
BrewerName: 'Stone Brewing - Liberty Station'
} ,{
 BrewerID: 2922
BrewerName: 'Blackstone Restaurant & Brewery'
} ,{
 BrewerID: 17393
BrewerName: 'Millstone Cellars'
} ,{
 BrewerID: 18955
BrewerName: 'Stoneface Brewing Company'
} ,{
 BrewerID: 20033
BrewerName: 'Stone City Ales'
} ,{
 BrewerID: 10238
BrewerName: 'Stone & Wood'
} ,{
 BrewerID: 10122
BrewerName: 'Lymestone'
} ,{
 BrewerID: 17277
BrewerName: '5 Stones Artisan Brewery'
} ]
`

**Comment by running-coder** [comment]
hey ratebeer, indeed but depending on your case you might want your visitors to only search through the brewername and not confuse them with the ID. If it's a CMS then its fine.
