### ISSUE TITLE
Set the default dropdown menu setting

### ISSUE THREAD

**Issue by mmomtchev** [running-coder/jquery-typeahead#421]
Is there a way to set the default dropdown menu setting to something different than the all value? Or change it manually?

**Comment by mmomtchev** [comment]
I did it with a very ugly hack :
	window.Typeahead['#search'].filters.dropdown.key = 'group';
	window.Typeahead['#search'].filters.dropdown.value = item';
	window.Typeahead['#search'].filters.dropdown.template = 'item;
	window.Typeahead['#search'].container.removeClass("filter").find("." + window.Typeahead['#search'].options.selector.filterButton).html('item');
	$('#search').trigger('input.typeahead');
}

**Comment by eluce2** [comment]
Where did you add that code? I'm hoping to do a similar thing

**Comment by mmomtchev** [comment]
Immediately after initialization. 'item' shall be the group name you used in sources. Look at the _selectFilter function in the sources.

**Comment by eluce2** [comment]
Sorry, that's still not working for me. Hopefully, they can add this feature more natively.

**Comment by connectwithraj** [comment]
> Immediately after initialization. 'item' shall be the group name you used in sources. Look at the _selectFilter function in the sources.

Can you please share more on your approach. Not able to make it work as you described.

**Comment by mmomtchev** [comment]
Code has changed a little bit since I did it
This is the function that is called internally when selecting a new filter from the dropdown menu
https://github.com/running-coder/jquery-typeahead/blob/79c86e634d672441700b8ab52d562533e551022a/src/jquery.typeahead.js#L2856
Maybe @running-coder should export it and make this an official feature

Otherwise, did you replace all the ids when you copied the code ('#search' with your HTML element id)?
Make sure you are calling it after the element has been initialized

**Comment by corsacca** [comment]
I'm interested in selecting a default dropdown menu item as well.
I'm using dynamic source with many items. So limiting the scope of the search by default would help performance.

**Comment by corsacca** [comment]
This seems to work:
```
onReady(){
    this.filters.dropdown = {key: "my-key", value: "My Value", template: "My Template"}
    this.container
        .removeClass("filter")
        .find("." + this.options.selector.filterButton)
        .html("My Template");
},
```
