### ISSUE TITLE
groupOrder array doesn't work when group is a string

### ISSUE THREAD

**Issue by eluce2** [running-coder/jquery-typeahead#424]
In my options, I have:
`group: "category",`
`groupOrder: ["Indiana","Arizona"],`

And my data contains the following format:
`{"category":"Arizona","id":"1","name":"Phil"}`
`{"category":"Indiana","id":"3","name":"George"}`

But the plugin breaks when groupOrder is set to the array (no results found). If I remove the line, it works as expected. If I set `groupOrder: "desc",` I get results, but all of the Arizona results still show first.

**Comment by running-coder** [comment]
I've added a commit on the `develop` branch, let me know if it fixes your issue

**Comment by eluce2** [comment]
Thanks. I'll be able to restructure my data in order to resolve this.

However, in my use case, the ability to set a default option the dropdownFilter would be much more useful. Then I wouldn't care as much about which order the groups appeared.
