### ISSUE TITLE
Adding initial values to a multiselect via an ajax call instead of statically in the js file

### ISSUE THREAD

**Issue by mchupp** [running-coder/jquery-typeahead#425]
BACKGROUND:
I am using a combo of demo Hockey v2 and Hockey v1.  

- I added a hidden input field "q-hidden" that will store the values as they are selected and removed.
- I will be creating a form where the main input field will start out with an initial value that will be loaded in the value attribute in the q-hidden field like:

`<input class="js-typeahead" name="q" id="q" type="search" autocomplete="off">
<input name="q-hidden" id="q-hidden" type="hidden" value="MTL">`

So what I would like to do is to get that value (already did that part below setting it to tempInputValue and I added a custom function (removeValue) in order to remove the items from the hidden input as they are removed)  

I am doing all of this so that when I submit the form the hidden field will have the values so they can be seen in the backend without having to use javascript to submit the form.

MY QUESTION
- How do I replace the json in the hardcoded "deferred.resolve" below with json via an ajax call?

  

Here is the js code:
`// JavaScript Document

var removeValue = function(list, value, separator) {
	"use strict";
  separator = separator || ",";
  var values = list.split(separator);
  for(var i = 0 ; i < values.length ; i++) {
    if(values[i] === value) {
      values.splice(i, 1);
      return values.join(separator);
    }
  }
  return list;
}
  typeof $.typeahead === 'function' && $.typeahead({
            input: ".js-typeahead",
            minLength: 3,
            maxItem: 8,
            maxItemPerGroup: 6,
            order: "asc",
            hint: true,
            //cache: true,
            blurOnTab: false,
            searchOnFocus: true,
            //group: ["division", "{{group}} division"],
            group: {
                key: "conference",
                template: function (item) {

                    var conference = item.conference;
                    if (conference.toLowerCase() === "eastern") {
                        conference += " Yay!123";
                    }

                    return conference;
                }
            },
			            multiselect: {
//                limit: 2,
//                limitTemplate: 'You can\'t select more than 2 teams',
                matchOn: ["id", "name"],
                cancelOnBackspace: true,
//                href: '/{{name}}.html',
//                data: [{
//                    "matchedKey": "name",
//                    "name": "Canadiens",
//                    "img": "canadiens",
//                    "city": "Montreal",
//                    "id": "MTL",
//                    "conference": "Eastern",
//                    "division": "Northeast",
//                    "group": "teams"
//                }],
                data: function () {
                    var deferred = $.Deferred();

                    setTimeout(function () {
                        deferred.resolve([{
                            "matchedKey": "name",
                            "name": "Canadiens",
                            "img": "canadiens",
                            "city": "Montreal",
                            "id": "MTL",
                            "conference": "Eastern",
                            "division": "Northeast",
                            "group": "teams"
                        },{
                            "matchedKey": "name",
                            "name": "Canadiens3",
                            "img": "canadiens",
                            "city": "Montreal",
                            "id": "MTL",
                            "conference": "Eastern",
                            "division": "Northeast",
                            "group": "teams"
                        }]);
                    }, 1000);

                    deferred.always(function () {
                        console.log('data loaded from promise');
                    });

                    return deferred;

                },
                callback: {
					 
                    onClick: function (node, item, event) {
                        event.preventDefault();
                        console.log(item);
					    alert(item.name + ' Clicked!');
					
                    },
                    onCancel: function (node, item, event) {
                        // item was removed from list remove it from the hidden field
					var hiddenInputId = node.attr('id') + '-hidden';
					var thisHiddenInputValue = $('#' + hiddenInputId).val();
			         
			$('#' + hiddenInputId).val(removeValue(thisHiddenInputValue,item.id));
						
						console.log(item)
                    }
                }
            },

            emptyTemplate: 'no result for {{query}}',
            groupOrder: ["Eastern", "Western"],
			
			templateValue: "{{name}}",
            display: ["name", "city", "division"],
            correlativeTemplate: true,
//            dropdownFilter: true,
//            dropdownFilter: 'All Teams',
//            dropdownFilter: [{
//                key: 'conference',
//                template: '<strong>{{conference}}</strong> Conference',
//                all: 'All Teams'
//            }, {
//                key: 'division',
//                value: 'Northeast',
//                template: '<strong>{{division}}</strong> Division'
//            }],
            dropdownFilter: [
                {
                    key: 'conference',
                    value: 'Western',
                    template: '<strong>Western</strong> Conference',

                },
                {
                    key: 'conference',
                    value: 'Eastern',
                    template: '<strong>Eastern</strong> Conference',
                    all: 'All Teams'

                }
            ],
            template: '<span>' +
        '<span class="name">{{name}}</span>' +
        '<span class="division">({{city}}, {{division}} division, {{conference}} conferences) YO</span>' +
        '<span class="team-logo">' +
            //'<img src="/assets/jquerytypeahead/img/hockey_v1/{{img}}.gif">' +
        '</span>' +
    '</span>',
			dynamic: true,
	    callback: {
			onReady: function (node) {
				var intialValues = node.closest('.typeahead__query').find('input[id*=-hidden]').val();
	
                    alert('im ready!');
					//this.container.find('.' + this.options.selector.dropdownItem + '.group-ale a').trigger('click')
                },
        onClickAfter: function (node, a, item, event) {
            event.preventDefault();
            
			console.log(node);
			console.log(a);
			
			console.log(item);

			// User has selected the item from the list now get the ID of the selected item and add it to the hidden field
			var hiddenInputId = node.attr('id') + '-hidden';
			var tempInputValue = $('#' + hiddenInputId).val() + ',' + item.id;
			$('#' + hiddenInputId).val(tempInputValue);
            alert(item.name + ' Clicked!');
        },
        onCancel: function (node, item, event) {
            console.log(item)
        }
    },
            source: {
        teams: {
            // Ajax Request
            ajax: {
				
                url: "Foo.php",
				data: {
                q: '{{query}}'
            }
            }
        }
    },
            debug: true
        });
`

**Comment by tombertrand** [comment]
hey, as replied in https://github.com/running-coder/jquery-typeahead/issues/397#issuecomment-381666454 make sure you are setting objects, not strings into the multiselect add function.

If your data format is:
```json
[{
  customerId: 1
  customerName: 'John'
  customerData: 'xyz'
}]
```
you will need to add the same exact object format:
```javascript
Typeahead["yourTypeaheadInputSelector"].addMultiselectItemLayout({
  customerId: 2
  customerName: 'Suzan'
  customerData: 'abc'
})
```

**Comment by mchupp** [comment]
Thanks for the feedback. I have another issue know. I stepped through it back to the working start. Is there some reason why this wouldn't work given data with certain formatting?

I created a database with the default information in it and it was working fine via ajax. But for some reason I get the "no result for" response for my own data.  Formatting looks fine via chrome developer:
https://msi.gainmojo.com/mojo/tpsreport/jquery-typeahead/cf-example/demo-hockey_v1.cfm

**Comment by mchupp** [comment]
Okay. @tombertrand thanks for your help. I added this: 
```
Typeahead["#qinput"].addMultiselectItemLayout({
bylawarticlename: value.bylawarticlename,
bylawcode: value.bylawcode,
bylawname: value.bylawname,
bylawtext: value.bylawtext,
division: value.division,
id: value.id,
name: value.name
})
```
As the code to add since that now matches my object. And it calls the function but instead of displaying the correct information in the "tag" it displays and removing the item from selection it displays [object Object] and keeps the item in the listing.
