### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by JvK-94** [running-coder/jquery-typeahead#426]
This is a problem when the result field of a item is null

**line 1924**
Uncaught TypeError: Cannot read property 'toString' of null

add this to line 1916 to solve it
if(displayValue === null)  continue;

**Comment by tombertrand** [comment]
hey @JvK-94 is that something that was fixed in https://github.com/running-coder/jquery-typeahead/commit/f4b3f7c60f7de525c72da3b9aa9de06543e86c78?

It's currently on develop branch, should be making a tag & release soon 👍
