### ISSUE TITLE
Optional custom callback on enter keypress

### ISSUE THREAD

**Issue by Nitroxid** [running-coder/jquery-typeahead#427]
Currently, if the enter key is pressed, the parent form is submitted automatically.
I would suggest an option to override this behavior with a custom function.

**Comment by eluce2** [comment]
I believe if you enable the "mustSelectItem" option, the enter key will trigger the "onClick" callback.

**Comment by chat-du-cheshire** [comment]
Unfortunately this solutions not working. Form still submitting on enter.

**Comment by connectwithraj** [comment]
@chat-du-cheshire , were you able to work around this one? I am also stuck on similar implementation. Please let me know.

**Comment by running-coder** [comment]
could you provide a codesandbox with your issue? I'm unable to reproduce when using the above solution (`event.preventDefault()` in the `onSubmit`)
