### ISSUE TITLE
Issue in replicating typeahead for auto suggest of states as in http://www.runningcoder.org/jquerytypeahead/demo/

### ISSUE THREAD

**Issue by rohitdatla** [running-coder/jquery-typeahead#429]
**Error in browser:** 
jquery.typeahead.js:3772 Uncaught TypeError: Cannot read property 'value' of undefined
    at Object.typeahead (jquery.typeahead.js:3772)
    at Function.$.fn.typeahead.$.typeahead (jquery.typeahead.js:3723)
    at (index):37

**Line where error occurs: (line:3772)**
 if (typeof node[0].value === "undefined") {
                node[0].value = node.text();
            }

Please let me know if you see where the problem is

**Comment by running-coder** [comment]
hey @rohitdatla sry for the late reply, seems like you are missing the `input` definition where the Typeahead node will be initialized on

**Comment by anhnam00** [comment]
i'm using a single JS file for all view, so some view has not the input definition where the Typeahead node will be initialized on. i think this library should supports this case (if not input, no throw error) :D. Thanks for your wonderful library

**Comment by anhnam00** [comment]
@running-coder please reopen 👍
