### ISSUE TITLE
Can i keep a multiselect from automatically reopening after click

### ISSUE THREAD

**Issue by corsacca** [running-coder/jquery-typeahead#430]
I'm using the multiselect on mobile and it would help the UI to not have the layout automatically reopen when an entry is selected. Is this possible?
I tried using e.preventDefault() in the callbacks without much success.
Thanks!

**Comment by running-coder** [comment]
hey @corsacca sorry for the late reply, does that mean you have `minLength: 0`?

you can add a callback in your unit options to close the layout after selecting an item
```javascript
typeof $.typeahead === 'function' && $.typeahead({
    input: ".js-typeahead",
    minLength: 0,
    ...
    multiselect: {
        ...
    },
    ...
    source: {
        teams: {
            data: data
        }
    },
    callback: {
        onClickAfter: function () {
            this.hideLayout();
        },
    },
});
```

**Comment by corsacca** [comment]
Hey, Yeah i'm using minLength: 0. 
The callback does exactly what i want only if i'm not using `dynamic:true`. Is there a way to combine the 2?
Thanks!

**Comment by corsacca** [comment]
@running-coder i'm using searchOnFocus = true. When an item is clicked, the multiselect item is added and then focus is returned to the input.  When that happens a new search is made which opens the layout again.
My solution right now is to use manually call `addMultiselectItemLayout` in the onClick callback:
```
callback: {
      onClick: function(node, a, item, event){
          ... // save the changes with ajax
          this.addMultiselectItemLayout(item)
          event.preventDefault()
          this.hideLayout();
      }
}
```
This avoids calling `scope.node.val(scope.query).focus();`

I think this will work for me. But perhaps there is a better way? 
Thanks!
