### ISSUE TITLE
2 typeahead inputs on one page - how to trigger them separated?

### ISSUE THREAD

**Issue by jepster** [running-coder/jquery-typeahead#433]
I have two typeahead inputs on one page. If I am inserting a value to one of them, both are triggered. Because two typeahead autocompletion lists are visible in the browser ui at the same time.

I have set two different CSS classes in the init functions (input: '.js-typeahead-what-field' and input: '.js-typeahead-where-field'). Please take a look on my code below. What am I missing?

```
      $.typeahead({
        input: '.js-typeahead-what-field',
        minLength: 3,
        maxItem: 20,
        order: "asc",
        href: "https://en.wikipedia.org/?title={{display}}",
        template: "{{label}}",
        display: ["label"],
        dynamic: true,
        source: {
          label: {
            ajax: {
              url: "https://api.vsm.nrw/leika/request/complete-service-search",
              data: {
                term: '{{query}}'
              }
            }
          },
        },
      });

      $.typeahead({
        input: '.js-typeahead-where-field',
        minLength: 3,
        maxItem: 20,
        order: "asc",
        href: "https://en.wikipedia.org/?title={{display}}",
        template: "{{value}}",
        display: ["value"],
        dynamic: true,
        source: {
          label: {
            ajax: {
              url: "https://api.vsm.nrw/index/complete-commune-search",
              data: {
                term: '{{query}}'
              }
            }
          }
        }
      });
```

**Comment by jepster** [comment]
I have tried also to select them indiviually via jQuery:

`$('.js-typeahead-what-field').typeahead`

Both are still triggered.. I am considering this as a bug.

**Comment by jepster** [comment]
Both search result lists are shown. Not both are triggered.

**Comment by jepster** [comment]
As a workaround, this can be used:

```
        callback: {
          onHideLayout: function(node, query) {
            $('.typeahead__result ul').remove()
          }
        }
```

The results from the previous search should be hidden.

**Comment by running-coder** [comment]
hey @jepster every initialized typeaheads should be independent from another. Like on the demo page for example triggering a typeahead only interact with it's own instance... is there a demo page you could show me where the issue happens? also for reaching specific instance you can use `Typeahead['.js-typeahead-what-field']`

**Comment by running-coder** [comment]
Closing let me know if this is still an issue
