### ISSUE TITLE
Get Selected Datum/Data 

### ISSUE THREAD

**Issue by EMXavier** [running-coder/jquery-typeahead#435]
Is there a method to simply get the selected datum (or data in multiselect)? I am attempting to use this as a form input where other input elements will be submitted along with the content of the typeahead input. A search of issues comes up empty, nor has it been addressed on SO.

**Comment by running-coder** [comment]
hey @EMXavier yes, you can always get data from your Typeahead instance.

`Typeahead['typeahead init selector'].items`

<img width="809" alt="image" src="https://user-images.githubusercontent.com/7377382/42235095-a925d772-7ec4-11e8-8adf-a081369848a9.png">

Or you can also do 
```
var myTypeahead = $.typeahead({ ... });

// Be cautious of scope and async data changes
console.log(myTypeahead.items);
```

**Comment by EMXavier** [comment]
**Thank you for the quick response!**

I actually ended up doing just that (first suggestion) before creating this issue; I should have added that in the initial post. It didn't seem correct to do it that way—so I wanted to be sure there wasn't an inbuilt method I was missing. 

N.b., I know I'm using it like _BS Tags Input_, but it's just so powerful and well-built!
