### ISSUE TITLE
[REQ] Example Beer v2

### ISSUE THREAD

**Issue by schroef** [running-coder/jquery-typeahead#437]
I would like to see the Beer v2 in the example. I would like to try the image filter with groups as well.

**Comment by running-coder** [comment]
hey @schroef everything you need should be inside the javascript / html / php / css tabs -> http://www.runningcoder.org/jquerytypeahead/demo/#form-beer_v2

or perhaps you have a specific question?

**Comment by schroef** [comment]
I download this repo from here, there it is missing

<img width="981" alt="screen shot 2018-07-19 at 21 09 47" src="https://user-images.githubusercontent.com/6923008/42977955-2942f4e6-8b98-11e8-98c7-185348121486.png">

Also that link got tons of errors, i needed to use chrome webdev to make the taps works again.
PS the whole page doesnt seem to work, did something change there? Yesterday all examples worked fine, now nothing works.

Error is about jquery not defined

<img width="691" alt="screen shot 2018-07-19 at 21 21 18" src="https://user-images.githubusercontent.com/6923008/42978218-b3028574-8b99-11e8-8c7c-6fdadf32614b.png">

**Comment by schroef** [comment]
I also see the website show a link to version 2.10.5 while yesterday it was 2.10.4

<img width="728" alt="screen shot 2018-07-19 at 21 26 41" src="https://user-images.githubusercontent.com/6923008/42978351-72050a46-8b9a-11e8-986d-e4ebb0cd17d6.png">

**Comment by running-coder** [comment]
yea I've realeased a couple fixes, also the site deployment has some issues should be resolved now

**Comment by schroef** [comment]
Sorry but still no Beer v2 inside. The site does work, so i can copy paste now

<img width="672" alt="screen shot 2018-07-20 at 01 42 16" src="https://user-images.githubusercontent.com/6923008/42985190-5bc36fd8-8bbe-11e8-9d85-e3daa0a0187e.png">

**Comment by schroef** [comment]
PS the HTMl and PHP for v1 also looks different on the demo page than the actual html page?
The PHP code is different, in the demo-beer-v1.html the php is a script inside the html which looks is only data, not other variables are declared like in the php tab on the demo page.

Im no guru with coding so perhaps im missing something. I see a combination of the java and php on the downloadable version. The page on the website show one using external data

**Comment by schroef** [comment]
The CSS is a bit messed up, seems in common.css there is a part setting max-witdth:100%.
Also the look was different yesterday when i searched that beer. Color where white and blue i believe.

But i got it working hacking beer_v1 html
Adjusted CSS
<img width="1084" alt="screen shot 2018-07-20 at 02 17 26" src="https://user-images.githubusercontent.com/6923008/42986370-4655c9fc-8bc3-11e8-9d87-5f986e44b5b6.png">

Css from site
<img width="1404" alt="screen shot 2018-07-20 at 02 17 09" src="https://user-images.githubusercontent.com/6923008/42986371-466a6da8-8bc3-11e8-8092-8be08bf18cd0.png">
