### ISSUE TITLE
Too many ajax calls with multiple groups

### ISSUE THREAD

**Issue by merkjs** [running-coder/jquery-typeahead#438]
Hello,

I implemented this plugin to my project which has approx. 20 groups. Each one has different source. DropdownFilter is used but search makes 20 ajax call, even I select an item from filter dropdown.

Is it possible to make only one ajax call when filter is selected?

Thanks a lot! @running-coder

**Comment by running-coder** [comment]
hey @merkjs indeed that should not happen, will look at that

**Comment by running-coder** [comment]
I've pushed a fix on the `develop` branch, let me know if that works 👍

**Comment by merkjs** [comment]
Hello again @running-coder 

I checked develop branch, and it works very well now.

Thanks for your effort. 

I prepared a demo, if anyone wants to check live;
[http://workable-relation123.surge.sh](http://workable-relation123.surge.sh)

**Comment by running-coder** [comment]
awesome! will include that in the next release
