### ISSUE TITLE
Click off to make drop down disappear

### ISSUE THREAD

**Issue by adamcoffey** [running-coder/jquery-typeahead#44]
Hi,
Thanks for all your work on this. It's a handy script.

I upgraded from 1.7 to 2 and now have lost the hide function when I click off the drop down (if I don't want to select one of the results). I see this is working on all your demos but can't find the difference with my implementation. I'm using with bootstrap 3.3. There is a bit of other jQuery on my page but nothing that seems to interfere.
I could put a jQuery hack in but would prefer to get to the bottom of the problem. Any ideas on where I should be looking?

**Comment by running-coder** [comment]
hey adam thanks for using the plugin

in 2.0 the visibility of the dropdown filter is handeled in css.. when the button is clicked a class "filter" is applied to the main container making it visible. If you dont want to update the whole css perhaps you can only grab that chunk

**Comment by adamcoffey** [comment]
Thanks for taking a look;

                        minLength: 2,
			maxItem: 20,
			highlight: true,
			offset: false,
			dynamic: true,
			display: "productname",
			template: "<span>{{productname}} - ${{price}}</span>",
			source: {
				productdesc: {
					url: [{
						type: "POST",
						url: "POS_product_search.php",
						data: {
							desc: "{{query}}"
						}   
					}]
				}
			}, 
			callback: {
				
				onClick: function (node, a, obj, e) {
	
					obj.saleid = \''.$sale_id.'\';
					$.post(\'POS_add_product.php\',JSON.stringify(obj),
						function(data){
						// on return just reload the page
						 location.reload();
					});
				}
			}

HTML is:
<div class="form-group">
			<label for="productdesc">Find Product By Keyword:</label> 
				<div class="typeahead-container">  
						<div class="typeahead-field">  							
								<span class="typeahead-query">
<input class="form-pos" id="productdesc" name="productdesc[query]" type="search" autocomplete="off" placeholder="Enter Description">
											</span>
										</div>
									</div>
								</div>

**Comment by running-coder** [comment]
Oh I see ... the result list visibility is handled in css in 2.0 instead of a .show() and .hide() which might be causing trouble to the people who doesnt grab the css...

Not sure if I should revert that part of the code and simply call the jquery methods yet

Meanwhile you should update that css part and you are good to go https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.css#L356

(or regrab the whole css file would be better..)

Thanks!

**Comment by adamcoffey** [comment]
That was it. Thanks for your help.
