### ISSUE TITLE
Nested arrays in JSON

### ISSUE THREAD

**Issue by ZipporaE** [running-coder/jquery-typeahead#442]
Hello!
I can not set up searching within a nested array in JSON object, for example, my source is:
```
{
    "name":"John",
    "age":30,
    "cars": [
        { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
        { "name":"BMW", "models":[ "320", "X3", "X5" ] },
        { "name":"Fiat", "models":[ "500", "Panda" ] }
    ]
 }
```
I can not search by car name. Tried "path: 'cars'", putting "display: 'cars.name'", but still getting an empty list and this error in console "Missing keys for display, make sure options.display is set properly.". If it is just a nested JSON, everything works, but not if thats an array withing JSON. Any suggestions?

**Comment by tombertrand** [comment]
hey @ZipporaE the `path` param resets your data to that key.

you will need `path: cars` & `display: 'name'`

**Comment by ZipporaE** [comment]
That is the idea to search for "Ford, BMW or FIAT", I also tried setting what you suggested, no luck. Code is following now:
```
var data =  [{
    "name":"John",
    "age":30,
    "cars": [
        { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
        { "name":"BMW", "models":[ "320", "X3", "X5" ] },
        { "name":"Fiat", "models":[ "500", "Panda" ] }
    ]
 }];

        typeof $.typeahead === 'function' && $.typeahead({
            input: ".js-typeahead",
            minLength: 1,
            maxItem: 8,
            hint: true,
            searchOnFocus: true,
            display: 'name',
            emptyTemplate: 'no result for {{query}}',
            source: {
                cars: {
                    data: data,
                    path: 'cars'   
                }
            },           
            debug: true
        });
```
