### ISSUE TITLE
Matcher only works after second trigger in IE11

### ISSUE THREAD

**Issue by AndZyk** [running-coder/jquery-typeahead#444]
Hello jQuery Typeahead-Team,

I am not sure if this is a bug in jQuery Typeahead, but I have following issue:

I have set up a matcher function to filter my search results and call it, when a input changes:

`
$("input[type=checkbox]").on("change", function() {
    typeahead.node.trigger("input");
});
`

This works fine in every browser, but in the Internet Explorer 11, I have noticed that the matcher function works only after the second trigger. The first trigger doesn't call the matcher function.

I am using the latest version 2.10.6.

Can you reproduce this behavior?

Regards, Andreas

**Comment by tombertrand** [comment]
is it related to using a `placeholder` attribute? https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L663

**Comment by tombertrand** [comment]
yea I would rather not modify Typeahead to accomodate legacy browsers 👍
