### ISSUE TITLE
Edit the onSubmit functionality

### ISSUE THREAD

**Issue by bearsworth** [running-coder/jquery-typeahead#446]
I saw that there is a way to customize what occurs after a user presses enter on the search form. If the user does not click a selection, the search form will send the user to what appears to be the default form request. For me this page looks like this: "localhost:3000/trade?country_v1%5Bquery%5D=bested". Is it possible to make the form post to just "localhost:3000/bested".

I was thinking there would be some way to use the form parameter, but what is the best way to just search for what is entered if the user types in something that is not part of the list?

**Comment by running-coder** [comment]
hey @bearsworth, from inside the `onSubmit` callback you can cancel the regular form submit using `e.preventDefault()` and set a redirect url instead using a simple `window.location = "abc.com/" + this.query`. See [Hockey_v2](http://www.runningcoder.org/jquerytypeahead/demo/#form-hockey_v2) for an example

**Comment by bearsworth** [comment]
I hadn't realized you left me that. I really appreciate that thank you!
