### ISSUE TITLE
click off doesn't work on iPhone

### ISSUE THREAD

**Issue by alery** [running-coder/jquery-typeahead#45]
Hey running-coder,

I test with iPhone 6+. If the result has been showed i try to touch off but the result will not be hidden.
On your demo page the same behavior.

It works on Android and iPad.

Thanks
alery

**Comment by running-coder** [comment]
Hey alery, I've added the toutchstart event which should fix the issue, unfortunately i do not have an iphone to test the result. I've verified on my ipad and it seem to have fixed the issue.

Can you confirm? thanks
