### ISSUE TITLE
Disable previously initiated instance

### ISSUE THREAD

**Issue by pankamilr** [running-coder/jquery-typeahead#450]
I'm looking for option to disable loaded plugin. I've got two fields with `typeahead` enabled. When I use and select from one (with `onClick` method) I want to disable hinting in another. Is there any method to destroy other instances?

**Comment by tgice** [comment]
I'm thinking that a proper destroy method would be useful for me too.

I see that there is not one available, but I would suggest one be made for those of us who are dealing with multiple typeaheads on one page, or where we might want to re-initialize one with a new static source (not using AJAX directly, but one state changes on the page which causes some other code to run some AJAX to pull in new data that then gets assigned to the typeahead's source).

@running-coder, do you have any suggestions (that aren't overly elaborate) for how to hack either the on-the-fly source change (without creating usability problems on the typeahead input) or to do some sort of approximation of a destroy on an already-initialized typeahead?

I've noticed if I just call the typeahead initialize again on an already-init'd one, I start to get weird effects such as multiple popups and other undesired effects.
