### ISSUE TITLE
Dataset limit on json

### ISSUE THREAD

**Issue by connectwithraj** [running-coder/jquery-typeahead#456]
Hi 
Can you help me with the following - 

Service dataset I am trying to consume only outputs json for 5k items unless looped through to get back next json for next 5k results. 

How can that be used with ajax and URL property?
Has anyone done something like this?

**Comment by vmanickamus** [comment]
Hi,
I have the same question. Also can there be scroll bars for each group in autocomplete so that we can display more matches per group that the user can scroll and select?
