### ISSUE TITLE
IE8 bug on press down

### ISSUE THREAD

**Issue by jonaslarsen** [running-coder/jquery-typeahead#46]
When pressing down to navigate in dropdown, first item is selected instead of navigating through list. Bug only shows in IE8. Can reproduce on example page.

**Comment by running-coder** [comment]
Hey jonaslarsen,

It took me quite some time to find the issue... it was caused by a bug inside the jquery clone function.

**Comment by running-coder** [comment]
Hey jonaslarsen,

The issue should be resolved.

Thanks for pointing it out!

**Comment by jonaslarsen** [comment]
Hi running-coder.

Can confirm the issue has been resolved.
Thanks a lot for fast response. Excellent work.

/Jonas
