### ISSUE TITLE
Dynamically scroll page if resultlist is big

### ISSUE THREAD

**Issue by kopresh** [running-coder/jquery-typeahead#464]
When the resultlist is big and we navigate the result set via keyboard down arrow.. how can the make the page to scroll when the resultset view is bigger than page view.. Any help here?

**Comment by yogeshsaroya** [comment]
@kopresh  Use this simple CSS code 

.typeahead__list{max-height: 500px;overflow: auto;}

**Comment by matthewdolman** [comment]
@yogeshsaroya 

This method does not work well, the scrolling of the container does not follow the active elements.

I have tried to use some logic with `$.keydown()` to manage the scrolling, but after a while the list items lose focus making selection impossible.

Anyone else have a solution to this?

**Comment by n3tman** [comment]
You can find the answer in the demos, as answered in https://github.com/running-coder/jquery-typeahead/issues/185#issuecomment-213566188

This plugin has such a superb documentation!
