### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by gwomp** [running-coder/jquery-typeahead#468]
It looks like the site http://www.runningcoder.org/jquerytypeahead/documentation/ is down

I'm getting "This page isn’t working www.runningcoder.org didn’t send any data.
ERR_EMPTY_RESPONSE"

**Comment by bcolflesh** [comment]
Yeah, page is parked now - he must have let his domain registration lapse. Not good.

**Comment by tombertrand** [comment]
sorry, just renewed should be up shortly
