### ISSUE TITLE
Can I dynamically group in the source?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#47]
From the beer example:

```javascript
 source: {
        ale: ["/jquerytypeahead/beer_v1.json", "data.beer.ale"],
        lager: ["/jquerytypeahead/beer_v1.json", "data.beer.lager"],
        "stout and porter": ["/jquerytypeahead/beer_v1.json", "data.beer.stout"],
        malt: ["/jquerytypeahead/beer_v1.json", "data.beer.malt"]
    },
```
I essentially need to load ^^this^^ source from a URL.   Is that possible, or do I have to know my 'group names' in advance?

**Comment by running-coder** [comment]
Hey sdillinger,

I'm dynamically declaring the group names inside one of my projects with the following technique:

``` javascript
function initTypeahead(response, group) {
    
    var options = {
        input: '#search-' + group,
        resultContainer: '#' + group + '-result',
        maxItem: 0,
        minLength: 0,
        ...
        },
        generateOnLoad: true,
        source: {}
    };

    options.source[group] = {
        data: function () {
            var data = [];
            for (var i = 0; i < response.length; i++) {
                data.push({
                    reference: response[i].reference,
                    name: response[i].name
                })
            }
            return data;
        }
    };

    typeof $.typeahead === 'function' && $.typeahead(options);

}

```

so initTypeahead gets called with first param the data received from the Api call, second param the groupname. Perhaps that technique can help you but it depends how you are getting the group name... Currently the Typeahead plugin doesnt support dynamic group renaming

**Comment by sdillinger** [comment]
very helpful.  Thank you.

On Tue, Jun 23, 2015 at 4:02 PM, Tom Bertrand <notifications@github.com>
wrote:

> Hey sdillinger,
>
> I'm dynamically declaring the group names inside one of my projects with
> the following technique:
>
> function initTypeahead(response, group) {
>
>     var options = {
>         input: '#search-' + group,
>         resultContainer: '#' + group + '-result',
>         maxItem: 0,
>         minLength: 0,
>         ...
>         },
>         generateOnLoad: true,
>         source: {}
>     };
>
>     options.source[group] = {
>         data: function () {
>             var data = [];
>             for (var i = 0; i < response.length; i++) {
>                 data.push({
>                     reference: response[i].reference,
>                     name: response[i].name
>                 })
>             }
>             return data;
>         }
>     };
>
>     typeof $.typeahead === 'function' && $.typeahead(options);
>
> }
>
> so initTypeahead gets called with first param the data received from the
> Api call, second param the groupname. Perhaps that technique can help you
> but it depends how you are getting the group name... Currently the
> Typeahead plugin doesnt support dynamic group renaming
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/running-coder/jquery-typeahead/issues/47#issuecomment-114641101>
> .
>



-- 
*Steve Dillinger*
Founder & CEO

* <http://www.classroom-iq.com>*

CIQ Labs - ClassroomIQ
222 Merchandise Mart Plaza
Suite 1212
Chicago, IL 60654

steve@ciqlabs.com
(312) 804-4799

www.getclassroomiq.com <http://www.classroom-iq.com>
