### ISSUE TITLE
Clear input after submit with multiselect 

### ISSUE THREAD

**Issue by Quentintin** [running-coder/jquery-typeahead#474]
Hello,

I would like to know how to clear input (**multiselect** maybe it's important) after submit action.

I try this but unsuccessfully: :cry:
```
onSubmit: function (node, form, items, event) {
   var scope = this;
   scope.resetInput();
   node.val('');
   event.preventDefault(); 

   ....
}
```

Any idea ? :thinking: 
Thank you

**Comment by tombertrand** [comment]
hey @Quentintin have you tried to `console.log(this)` within the `onSubmit` function? it should give you a method to do so https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L3129 (that one clears single)

to clear every labels, all you to do a couple manual resets
```javascript 
this.items = [];                           // Multiselect selected items
this.comparedItems = [];          // Multiselect items stored for comparison
this.label.container.empty();    // span holding multiselect labels
this.adjustInputSize();             // recalculate input width
```

or you can always loop through label "x" and trigger a click (simulate cancels)

```javascript
// inside the onSubmit function
this.label.container.find('.' + this.options.selector.cancelButton).trigger('click');
```

**Comment by Quentintin** [comment]
Thank you. I try first method and it works fine !
