### ISSUE TITLE
Set input value to id instead of text

### ISSUE THREAD

**Issue by divan** [running-coder/jquery-typeahead#477]
Hey, 

thanks for an awesome plugin.

I have static JSON data in the format `[{"id", 1, "name": "Foo"},{"id", 2, "name": "Bar"},...]`, and I use jquery-typeahead with a bigger form, so I want it to only update input field.

When user selects items, they should see only textual representation (i.e. `name` field), but when form is sent over to the backend, I want value to be different (`id` in my case). How can I achieve this with this plugin?

My config is relatively simple:
```js
var data = [{"id", 1, "name": "Foo"},{"id", 2, "name": "Bar"},...];
$.typeahead({
            input: "#js-typeahead",
            order: "asc",
            display: ["name"],
            template: '<span>{{name}}</span>',
            templateValue: "{{name}}",
            source: {
                data: data,
            },
});
```

```html
    <div class="typeahead__container">
        <div class="typeahead__field">
            <div class="typeahead__query">
                <input id="js-typeahead" name="test-input" type="search" autocomplete="off">
            </div>
        </div>
    </div>
```

Currently, the `value` of the input is set to `name`, which is not what is needed.

**Comment by running-coder** [comment]
hey @divan, there are a few ways you can achieve this result but with your use-case considering that your Typeahead is part of a bigger form.

Solution A: adding a `<input type="hidden" name="id" value="" />` in which you update its value when a use selects an item from the typeahead, ex you could be using `onClickBefore (node, a, item, event)` callback to get that item and populate your hidden input.

Solution B: in the submit function of your big form, you can retrieve the Typeahead's selected item on the window scope by reaching the selected item `window.Typeahead['YOUR_INIT_INPUT_SELECTOR'].item` and adding it in your BE request parameters. All your object keys should be in the `item` object including `id`.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/7377382/67162327-dfc94480-f330-11e9-992c-e7131f17dd74.png">

https://codesandbox.io/s/jquery-typeahead-q2f5z

**Comment by divan** [comment]
Thanks for the help! I realized that what I was looking for is the Select tag typeahead (where "value" sent to backend and "label" shown to user are different things), and ended up switching to Select2.
