### ISSUE TITLE
Input box on Chrome

### ISSUE THREAD

**Issue by steveshourds** [running-coder/jquery-typeahead#478]
Click on the input field js-typeahead and the cursor does not position properly.

Only happens on Chrome

try going to my site
https://pbeorders.com/psweb
Type in CLEAR COAT
then try to position the cursor on the E in CLEAR and you will see it positions after the A.

Try same thing in Edge and it works normally. Try other input fields in Chrome and they all work fine.

Thanks for any ideas!

**Comment by tombertrand** [comment]
hey @steveshourds, I've just reproed on the documentation website, that's really weird, must be caused by a recent Chrome update... indeed seem to only happen on Chrome...

**Comment by tombertrand** [comment]
The issue is coming from the fact that the input is of `type="search"` (can't remember why that was used for but removing it causes no issue), Chrome broke it... to solve just remove that type from your typeahead input, I'll add a commit to remove this from the examples & website

**Comment by steveshourds** [comment]
worked! Thanks...
