### ISSUE TITLE
Suppress the Typeahead event From onSubmit callback function?

### ISSUE THREAD

**Issue by vmanickamus** [running-coder/jquery-typeahead#479]
We are implementing a custom functionality on Enter Key Press (onSubmit) event. Once Enter key is pressed and the control enters OnSubmit event, we do not want to process any other events in the Typeahead control.
We have Dynamic Ajax calls set for the Source attribute and the "Done" call back are internally calling onSearch callback which displays the search results in the "Results_Container". We are trying to hide/stop this behavior when ever Enter Key is pressed. Need help/directions.

**Comment by running-coder** [comment]
hey @vmanickamus, could you provide a codesandbox with a sample of the above code you are using?

**Comment by vmanickamus** [comment]
Hello thanks for the response.

Here is how we are trying to perform our search:

Typeahead Config:

 typeof $.typeahead === 'function' && $.typeahead({
			input: '.js-typeahead-groupstemplate',
		    minLength:2,
		    hint:true,
			cancelButton: true, 
			maxItem: 0,
			maxItemPerGroup:30,
			dynamic:true,
			highlight: "any",
			mustSelectItem: false,
			
			accent: {from:"-/'",to:"   "},
		    group: {
		    template: "{{group}}",
		     correlativeTemplate: true,
		    },
		    backdrop: {
		        "background-color": "#fff"
		    },
		    dropdownFilter:true,
		    emptyTemplate: 'No result for "{{query}}" in the selected scope. Please verify scope dropdown',
		    templateValue: "{{SearchTerm}} | {{SearchAttribute}}",
		    display: ["DisplayTitle", "DisplayText", "DisplayType", "DisplaySource"] ,
		   
		    source: {
		    	"Projects": {
		    	
		    	 ajax: {
		    	 		url: urlconfig.SearchDataUrls.ProjectsSearchDataUrl, 
			            callback: {
			                done: function (data, textStatus, jqXHR) {
									//Build return array and return
			                 }
							 
						}
				}
				//More Dynamic Ajax calls for different groups
				 callback: {
					 onClickAfter: function (node, a, item, event) {
		 
		            event.preventDefault;
						//Doing some actions to display selected entity details
					}
					
					 onSubmit: function (node, form, item, event){
		       		 event.preventDefault();
						//making a Ajax call to find more results and perform different options.
					}
			});
			
			The Issue: 
			When ever a user presses the Enter key we want to do our own search and present the details a single item below the Search box.
			But:
				1) The search result list is being displayed with the search results list. I have tried soo many options that I could find in your Demo and documentation pages and other Related blogs. but not able to supress this behaviour.
				
				Since there are more than 5 dynamic Ajax calls made during the search, when ever the search results are returned, The onResult event is fired and it is automatically displaying the search results list container. I am not able to suppress this behavior
				
				2) When the user is typing a search query, the typeahed is trying to find the exact match in the search results of our Search REST API. When the user hits ENTER and typeahead is not able to find a exact match in the Serch result records, The onSubmit event is not getting fired, which is preventing us to do our own custom search for the search query entered. 
			
			Is there a help line where we can get in touch with you and work separately on this issue. We have implemented Typeahead control as our search tool for this important application and now we are blocked. Hoping to get this sorted out at the earliest.
			Thanks,
			Valar

**Comment by vmanickamus** [comment]
Also,
we are getting the following runtime error, every other call. What is being missed? Can you advise.

WebResource.axd?d=2Yv99PmfPNdj9EpXWPKP9XE242pLXqRWKSLwqE3qMyCB9a3kOja9wv2L1u4lwzT4WUciQ-n1fHpwS7p9eAFkczeXjJYen19OsD727psiZ5E1&t=636939701749177621:411 Uncaught TypeError: Cannot set property 'value' of undefined
    at HTMLFormElement.WebForm_SaveScrollPositionOnSubmit (WebResource.axd?d=2Yv99PmfPNdj9EpXWPKP9XE242pLXqRWKSLwqE3qMyCB9a3kOja9wv2L1u4lwzT4WUciQ-n1fHpwS7p9eAFkczeXjJYen19OsD727psiZ5E1&t=636939701749177621:411)
    at Object.trigger (jquery-3.3.1.js?v=09.05:8255)
    at HTMLFormElement.<anonymous> (jquery-3.3.1.js?v=09.05:8327)
    at Function.each (jquery-3.3.1.js?v=09.05:354)
    at jQuery.fn.init.each (jquery-3.3.1.js?v=09.05:189)
    at jQuery.fn.init.trigger (jquery-3.3.1.js?v=09.05:8326)
    at Typeahead.navigate (jquery.typeahead.js?v=09.05:1600)
    at HTMLInputElement.<anonymous> (jquery.typeahead.js?v=09.05:710)
    at HTMLInputElement.dispatch (jquery-3.3.1.js?v=09.05:5183)
    at HTMLInputElement.elemData.handle (jquery-3.3.1.js?v=09.05:4991)

**Comment by vmanickamus** [comment]
Is there a help line where we can get in touch with you and work separately on this issue. We have implemented Typeahead control as our search tool for this important application and now we are blocked. Hoping to get this sorted out at the earliest.
		Thanks,
		Valar
