### ISSUE TITLE
Second parameter for AJAX request when searching with dynamic=true

### ISSUE THREAD

**Issue by neolution-ch** [running-coder/jquery-typeahead#48]
Hi Tom

I need to issue a second parameter (besides the {{query}}) to my search API. The second parameter (location) is in an input field, which I read via JQuery:

    $('#search-location-input').val()

Full code:
   
    $('#search-query-input').typeahead({
        minLength: 1,
        group: "Section",
        dynamic: true,
        delay: 0,
        display: "Text",
        source: {
            results: {
                url: {
                    type: "GET",
                    url: "/api/search/",
                    data: {
                        searchTerm: "{{query}}",
                        location: $('#search-location-input').val()
                    },
                    callback: {
                        done: function (data) {
                            return data;
                        }
                    }
                }
            }
        }
    });

It seems, that the `data` object is kinda cached. The `searchTerm` property changes according to the users input. But the `location` property does not. It looks like it gets the value of my location input field just once (when initializing typeahead for the input). If I change the value of the location input and search again, it just sends the value of the location input (value at initialization time) to the search API.

Kind Regards
Sandro

**Comment by running-coder** [comment]
Hey neolution-ch,

thanks for using the plugin, indeed the requests have internal cache to they are not re-built everytime to save some processing and access the search results even faster.

There is a way for you to bypass this cache simply by defining a return function instead of directly reading the input.

``` javascript
$('#search-query-input').typeahead({
    minLength: 1,
    group: "Section",
    dynamic: true,
    delay: 0,
    display: "Text",
    source: {
        results: {
            url: {
                type: "GET",
                url: "/api/search/",
                data: {
                    searchTerm: "{{query}}",
                    location: function () { return $('#search-location-input').val(); }
                },
                callback: {
                    done: function (data) {
                        return data;
                    }
                }
            }
        }
    }
});
```

Should work and send the updated input value everytime

Thanks

**Comment by neolution-ch** [comment]
Worked perfectly, thanks for your quick response!
