### ISSUE TITLE
Styles not showing on overflow

### ISSUE THREAD

**Issue by steveshourds** [running-coder/jquery-typeahead#489]
I added overflow: scroll to typeahead-list and it works fine except that the styles do not apply to the overflow (see image below).

Go here on a small mobile device to see it in action:

https://pbeorders.com/PSweb/Home/MobileIndex

Type Primer into search..

Is there a way to apply css to overflow?

Thanks for any help!

-----

Here's my override css:

<style type="text/css">
    .typeahead__dropdown .typeahead__dropdown-item:not([disabled]).active > a,
    .typeahead__dropdown .typeahead__dropdown-item:not([disabled]) > a:focus,
    .typeahead__dropdown .typeahead__dropdown-item:not([disabled]) > a:hover,
    .typeahead__list .typeahead__item:not([disabled]).active > a,
    .typeahead__list .typeahead__item:not([disabled]) > a:focus,
    .typeahead__list .typeahead__item:not([disabled]) > a:hover {
        background-color: #b7bda2;
    }

    .typeahead__list li:nth-child(even) {
        background-color: #f5f5f5;
    }

    .typeahead__list li:last-child {
        background-color: #a6a297;
    }

        .typeahead__list li:last-child span {
            color: white !important;
        }

    .typeahead__list {
        padding: 0;
        box-shadow: 1px 1px 4px rgba(0,0,0,0.3);
        overflow: scroll;
    }
</style>
![image](https://user-images.githubusercontent.com/30128057/67395679-64f06b80-f574-11e9-92bc-6404fdbbee15.png)

**Comment by running-coder** [comment]
hey @steveshourds I've spent some time looking for a potential solution to display child 100% of a overflow parent and couldn't find any (display inline-block only stretches the longuest li to the parent ul)... do you have a suggestion?

**Comment by steveshourds** [comment]
Hello, I have not found anything either...
Nothing to suggest since this seems to be the way it is for overflow!
Just wanted to see if you had any tricks up your sleeve!
Thanks for checking it out.
