### ISSUE TITLE
typeahead not feeded

### ISSUE THREAD

**Issue by marccollin** [running-coder/jquery-typeahead#49]
hi, 

i'm starting with jquery-typeahead.

My first typeahead will display brand car, result will not change often.

I tried two different way and get same result, typeahead is empty.

I see my ajax call return data 

[{"brandId":1,"brand":"Acura"},{"brandId":2,"brand":"Alfa Romeo"},{"brandId":3,"brand":"AMC"},{"brandId":4,"brand":"Aston Martin"},{"brandId":5,"brand":"Audi"},{"brandId":6,"brand":"Avanti"}]

    <div class="form-group">
        <label for="brand" class="col-sm-2 control-label">Marque</label>
        <div class="col-sm-10">
            <div class="typeahead-container">
                <div class="typeahead-field">
                    <span class="typeahead-query">
                        <input id="brand" name="brand" class="form-control" type="search" placeholder="Entrer la marque" autocomplete="off">
                   </span>
               </div>
           </div>
       </div>
 </div>  

 $('#brand').typeahead({
     minLength: 3,
     source: {
         url: {
             type: 'GET',
             url: '/brands'
         }
      }
 });

i tried also this way

getAllBrand().done(brandTypeahead);

    function getAllBrand(){
        return $.ajax({
            url:'http://localhost:8080/brands',
            type:'GET'
        });
    }
    
    function brandTypeahead(data){
         $('#brand').typeahead({
                minLength: 3,
                source: data
         });
    }

**Comment by running-coder** [comment]
hello mark,

it simply looks like you forgot to define the display option.. by default it search your objects for a display property but you can redefine it to be "brand"

**Comment by marccollin** [comment]
ok thanks a lot
