### ISSUE TITLE
Non correlative words

### ISSUE THREAD

**Issue by AntoineR951** [running-coder/jquery-typeahead#495]
Hi, I reopen this topic : 
https://github.com/running-coder/jquery-typeahead/issues/30

I would like to have this suggestion : 
"Paris is the capital of France"
If I typed "Paris France".

I have tried with "matcher"  but I think solution is a combination of "filter : false" and "matcher" but I don't find it in issue.

**Comment by AntoineR951** [comment]
When I use "correlativeTemplate: true," that doesn't works. I don't use template.

**Comment by AntoineR951** [comment]
This function seems to do that :

`filter: function (item, displayKey) {
				var queryArray = this.query.split(' ');

				for (var i = 0, ii = queryArray.length; i < ii; ++i) {
				if (displayKey.toLowerCase().includes(queryArray[i].toLowerCase())) {
            
				}
				else {return false;}
				}
				return true;
				}`

**Comment by tombertrand** [comment]
hey @AntoineR951, I was able to achieve the desired result, the trick is that you have to specify a `template` when using that option (Perhaps I should make it obvious in the doc)

![image](https://user-images.githubusercontent.com/19352322/72089718-8abb2000-32da-11ea-8bdf-63fdad5067d8.png)

```
$.typeahead({
  input: ".js-typeahead",
  minLength: 0,
  template: "{{description}}",
  display: "description",
  correlativeTemplate: true,
  source: {
    data: [
      {
        description: "Paris is the capital of France"
      },
      {
        description: "Ottawa is the capital of Canada"
      }
    ]
  }
});
```

**Comment by AntoineR951** [comment]
Yes, that works. Awesome. I think my solution has the same results but your method is better. Thanks.

**Comment by AntoineR951** [comment]
I have open a stackoverflow issue. I update it. 
https://stackoverflow.com/questions/59655559/jquerytypeahead-working-with-non-correlative-words

**Comment by AntoineR951** [comment]
Hi, I reopen it. Your solution doesn't works with accents. (é=>e).
I keep this : 

`filter: function (item, displayKey) { var queryArray = this.query.split(' '); var aa=displayKey.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); for (var i = 0, ii = queryArray.length; i < ii; ++i) { var bb= queryArray[i].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); if (!aa.includes(bb)) {return false} } return true; }`

**Comment by AntoineR951** [comment]
Other thing : I added in the list of accented characters the character "-" to match it with " ". Thus "street-of" corresponds well to "street of".
