### ISSUE TITLE
Prevent / Destroy Behaviour

### ISSUE THREAD

**Issue by 98004702** [running-coder/jquery-typeahead#50]
So far my experience with this has been perfect (it's everything that Twitter's typeahead should be). I'm struggling to find a 'destroy' type behaviour for the following scenario.

1) User clicks in the email field and starts typing. Typeahead calls the server and attempts to return results. 

2) Server is possibly slow or the user is very quick but they type the full address before results are rendered and leave this field.

3) The typeahead results (including the backdrop) pop up when the user is now in another field. 

Is there a way to do a destroy or preventDefault style action on blur - when the user leaves the type ahead field?

Thanks

**Comment by running-coder** [comment]
Hey,

thanks for the good feedback, unfortunately the Typeahead does not have a destroy function atm. It might be possible for you to code a workaround which would be as efficient inside the onLayoutBuiltBefore callback and prevent you from re-init if the user clicks back inside the feild.

``` javascript
onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
    if ($("#q").is(":focus")) {
        resultHtmlList.addClass('hidden');
    } else {
        resultHtmlList.removeClass('hidden');
    }
    return resultHtmlList;
}
```

I've not tested the code but something similar to this should work and provide the result you are expecting.

Thanks

**Comment by 98004702** [comment]
Thanks for the quick response. I've managed to hack it by killing all ajax requests when the user leaves the form field - 

$(document).on('focus','#email', function() { 

        $.ajaxSetup({
            beforeSend: function(jqXHR) {
                $.xhrPool.push(jqXHR);
            },
            complete: function(jqXHR) {
                var index = $.xhrPool.indexOf(jqXHR);
                if (index > -1) {
                    $.xhrPool.splice(index, 1);
                }
            }
        });


        $.xhrPool = [];
        $.xhrPool.abortAll = function() {
            $(this).each(function(idx, jqXHR) {
                jqXHR.abort();
            });
            $.xhrPool = [];
        };
});

$(document).on('blur','#email', function() { 
	$.xhrPool.abortAll();
});

**Comment by running-coder** [comment]
even better :+1:
