### ISSUE TITLE
Trim whitespaces in {{query}} using dynamic search

### ISSUE THREAD

**Issue by Harish01303** [running-coder/jquery-typeahead#501]
I am using dynamic search. the search text with space at the end has to be trim.
For example:
if the search text was 'hello '. I want to trim the last space. In ajax the search text has to go like 'hello'.
Suggest me a solution to trim spaces.

**Comment by tombertrand** [comment]
hey @Harish01303, it is very possible to modify your query before it hits the internal search functionality using the `onSearch` callback

```javascript
onSearch: function() {
  this.query = this.query.trim();
}
```
