### ISSUE TITLE
Paginations with lazy load

### ISSUE THREAD

**Issue by dmbehrouz** [running-coder/jquery-typeahead#504]
Hi
Thanks for your usable plugin.I want to request to service with pagination. how can i lazy load with scroll first result of search?
thanks

**Comment by tombertrand** [comment]
hey @dmbehrouz, this typeahead doesn't has such functionality out of the box, you'd need to hook in multiple callbacks and have a highly customized instance. Would be doable (with a lot of work on your part), but perhaps this is not the right plugin for what you are trying to achieve.

**Comment by dmbehrouz** [comment]
Thanks
