### ISSUE TITLE
Use plugin to just show results set from API

### ISSUE THREAD

**Issue by kopresh** [running-coder/jquery-typeahead#508]
Hi,

Can i use this plugin to just show the resultset and not search from the result set?

I am calling an external api, which is doing all the search for me. All i need to do is just display the results set. But i want to use the plugin to display results. Is it possible?

**Comment by tombertrand** [comment]
Absolutely,

![image](https://user-images.githubusercontent.com/19352322/83409831-39274500-a3e3-11ea-8d25-87b7ed5be7fa.png)
