### ISSUE TITLE
help for use .php file in source

### ISSUE THREAD

**Issue by balloon-man** [running-coder/jquery-typeahead#51]
hi 
I recently met with your plug-in, but I could not use the php file on the source and all demo used of json file or string. please help me to make the simplest form of php output file on the source.

**Comment by running-coder** [comment]
hello balloon-man, most of the plugins actually link to a php file that outputs json. You can check country_v2 demo, and click on the php code tab, im enforcing a json header for the output.
 "/jquerytypeahead/country_v2.json" links to that php file in my vhost server configuration.

**Comment by balloon-man** [comment]
Thanks for Quick answer
My problem is precisely the connection between json and php 
i tried  to change name extension from json to php  with mod_rewrite but dont work
namely with type the name direct in browser that work (x.json open x.php) but in your plugin no

**Comment by running-coder** [comment]
can you provide me your init code? perhaps there is something there that shouldnt be

**Comment by balloon-man** [comment]
my problem solved ! 
I was wrong local address in the browser for run html file and solved with host address
thanks for a great plugin excellent
Good luck!

**Comment by running-coder** [comment]
thanks man!
