### ISSUE TITLE
Forcing a form submit on enter key (with no override possible) seems wrong

### ISSUE THREAD

**Issue by J0nKn1ght** [running-coder/jquery-typeahead#510]
**Question / Help request**
Maybe our scenario is different to the one that the TypeAhead is designed for, but hard-coding the key handling to force a submit of the closest form when enter is pressed and no items are active, and with no option to override it, seems wrong to me.

We use the TypeAhead in a form containing many fields that the user may have updated.  When they come use the TypeAhead, if they start to type something and then press enter before selecting an item, the form is submitted, committing all of the changes they have made, and losing the context of the page.

I understand that the querystring is updated to include the characters typed, but that doesn't help us, as we don't want the other changes to the form submitted at this point.

You can test this by going to http://www.runningcoder.org/jquerytypeahead/demo, clicking in the first Search input field, and typing 'af{enter}' without touching any other keys.  The page is reloaded (in fact I've also been getting a 404 returned whilst trying this), which I don't think is the action that the user would expect.

**Describe the solution you'd like**
Could there be an initialisation option to prevent the form being submitted if enter is pressed when there are no selected items?

**Describe alternatives you've considered**
I guess that we could try to set some kind of flag in the onSubmit event, and then add a submit handler to the form that prevents the submit if it originates from the TypeAhead, but that seems sub-optimal.

**Additional context**
I just want to say that this library is great, so keep up the good work!

**Comment by neobenedict** [comment]
Bump.

**Comment by J0nKn1ght** [comment]
Bump

**Comment by neobenedict** [comment]
bump
