### ISSUE TITLE
Get all selected options

### ISSUE THREAD

**Issue by dmbehrouz** [running-coder/jquery-typeahead#511]
Hi
I want to get all selected options and send those  inside param of ajax request.
How can i get all selected options?
thanks :)

**Comment by tombertrand** [comment]
hey @dmbehrouz, are you talking about a multiselect typeahead? those selected items should be in your `this` scope inside any callback

**Comment by dmbehrouz** [comment]
Thank's Bro

> 
> 
> hey @dmbehrouz, are you talking about a multiselect typeahead? those selected items are in your `this` scope inside any callback
