### ISSUE TITLE
Multiple ajax calls for one group item (Access multiple data sources for one group item)

### ISSUE THREAD

**Issue by vmanickamus** [running-coder/jquery-typeahead#529]
Hi, I am trying to solve the following scenario. We have some search scopes (source group items) to perform autocomplete search. We have a case where for one of the group item, we need to bring data from totally two different servers and data source. this method is failing why because 
your code in typeahead.js file line number 917, 918 is executed synchronously 
     if (typeof groupSource.data === "function") {
                        groupData = groupSource.data.call(this);
                        if (Array.isArray(groupData)) {
                            scope.populateSource(groupData, group);
Also the system is taking the ajax object of the subsequent scope group object and trying to execute the URL call and the system is failing

source: {
     grpt1: {
       data: function () {
 
            var deferred = $.Deferred();
 
            // Gather your data, and resolve the deferred object with an array of objects
            // setTimeout is used only to show that the data is async
            setTimeout(function () {               
                    deferred.resolve(Getdata);               
                }
            }, 2000);
 
            deferred.always(function () {
                console.log('yay! :D')
            });
 
            return deferred;
        }
    }
     }
     } 

function Getdata(){
   var deferreds= [];
deferreds[0] = ajaxcall1;
deferreds[1] = ajaxcall2;
 $.when.apply($, deferreds).then(function () {
   return responsejson;
}

}
     Thanks

**Comment by connectwithraj** [comment]
Is anyone available to help? @running-coder
