### ISSUE TITLE
How can i get the empty message with dynamic as true

### ISSUE THREAD

**Issue by CREAZ-NET** [running-coder/jquery-typeahead#53]
Hi,

I wanted to thank you first of all for your work,

I'm trying to use EmptyTemplate with my Ajax Call but i can't get the message "No result for query". 

What's the best solution ?
How can we do it ? 

		$('#autocomplete-towns').typeahead({
			minLength: 3,
			maxItem: 10,
			order: "asc",
			dynamic: true,
			emptyTemplate: 'No result for "{{query}}"',
			source: {
				url: {
					type: "POST",
					dataType: "json",
					url: $("#autocomplete-towns").attr("data-url"),
					data: {
						q: "{{query}}"
					}
				}
			}
		});

I'm getting an array like this : 

[
    "Saint-Germain-les-Paroisses, 01300",
    "Parves, 01300",
    "Parcieux, 01600",
    "Pargny-les-Bois, 02270",
    "Pargny-la-Dhuys, 02330",
    "\u00c9parcy, 02500",
    "Pargny-Filain, 02000",
    "Parcy-et-Tigny, 02210",
    "Parfondeval, 02360",
    "Parfondru, 02840"
]

It works fine, i just can't see the EmptyTemplate message when dynamic is as true. 
Thanks !

**Comment by CREAZ-NET** [comment]
Hey, it's weird because sometimes i can see it , i mean 1 one time each 50 try, maybe a layout problem ?

**Comment by running-coder** [comment]
Hi creaz,

Thanks for using the plugin!
I've tried to reproduce your error on 2 different demos and they both show the emptyTemplate with dynamic true and I don't see any error in your init code.

could you verify if the html is built in case of no result? perhaps it is simply a css conflict

![2015-07-19_0804](https://cloud.githubusercontent.com/assets/7377382/8765810/500b59c6-2ded-11e5-8633-a80c25d08c35.png)

**Comment by CREAZ-NET** [comment]
Thanks for you reply !
I was thinking aboit the same thing but this is the HTML and the message is not put inside the li.

The HTML : 
![img2](https://cloud.githubusercontent.com/assets/10393838/8766180/eb3815ca-2e2d-11e5-961a-062cdd976bbd.png)

Screenshot : 
![img](https://cloud.githubusercontent.com/assets/10393838/8766169/583f6854-2e2d-11e5-9f91-2a1ad4ad3e8f.png)

JS Code (i've changed some stuff for the try) 

		$('#autocomplete-towns').typeahead({
			minLength: 3,
			maxItem: 5,
			order: "asc",
			dynamic: true,
			delay: 500,
			group: [true, "Liste des villes"],
			emptyTemplate: 'No result for "{{query}}"',
			source: {
				url: [{
					type: "POST",
					dataType: "json",
					url: $("#autocomplete-towns").attr("data-url"),
					data: {
						q: "{{query}}"
					}
				}, "data"]
			}
		});

PHP Code  (Cakephp 3)

public function autocomplete()
	{
		
		$keyword = strtolower($this->request->data['q']);
		$towns = $this->Towns
			->find()
			->where(function ($q) use ($keyword) {
				return $q
				->like('LOWER(Towns.name)', "%$keyword%");
			})
			->limit(5)
			->toArray();
		
		$json['status'] = true;
		$json['error'] = null;
		
		foreach ($towns as $town) {
			$json['data'][] = h($town->name) . ", " . h($town->postal_code);
		}
				
		$this->set(compact('json'));
		$this->set('_serialize', 'json');
	    
	}

**Comment by running-coder** [comment]
Oh, found out the issue from the Typeahead debug console message in your screenshot... in the demos an empty array is being returned even if there is no result and the internal Typeahead populate() function expects an array type. I assume your Towns->find() function returns null if there is no match? 

```javascript
if (!(data instanceof Array)) {
    // {debug}
    _debug.log({
        'node': this.node.selector,
        'function': 'populateSource()',
        'arguments': JSON.stringify({group: group}),
        'message': 'Invalid data type, must be Array type.'
    });
    _debug.print();
    // {/debug}
    return;
}
```

**Comment by CREAZ-NET** [comment]
Hey running-coder you're right ! If there is no items, i'm gonna get a null ! Do i Have to edit my js/php code ? Otherwise in case it's happen you can edit small code in the library ? Thanks

**Comment by running-coder** [comment]
I've modified Typeahead to force an empty array if the data is not an array so you should be good to go if you grab the latest version

**Comment by CREAZ-NET** [comment]
Hey, thanks it's fixed :) Working fine !

**Comment by running-coder** [comment]
cool, ty for the feedback
