### ISSUE TITLE
Submit on item select (enter)

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#54]
If I arrow down to select an item and then hit enter I feel a submit event should be triggered.  As it stands now I have to hit enter twice- once to bring the item to the top and then again to submit.   I'm not sure I understand the use case where I'd hit enter on a item and want to do anything other than submit (?)

Is there a way to do this that I missing?

Thanks.

**Comment by running-coder** [comment]
true, I've received that comment from another people too.. the goal behind it was to trigger a onclick callback and from there you decide what to do: manually submit or do other operation depending on your typeahead instance. Some people uses it as a form input to select a country so triggering submit if they press enter would submit the form even if the user is not finished filling it up. Unfortunately I cant make everyone happy but perhaps there is a better way to do this?

**Comment by ThiefMaster** [comment]
> I'm not sure I understand the use case where I'd hit enter on a item and want to do anything other than submit (?)

What if you have more fields in the form? You might expect enter to simply close the suggestions and put the selected value in the field.

**Comment by sdillinger** [comment]
Ahh. Ok.  I understand the use case.   How about adding submitOnEnter [t/f]?   It would submit the list item if the user hit enter while focused on that item.   If the input box has focus and the selection is not complete, but is hinted, it would submit the hinted item.   Ex:  app[le]   would submit apple.

**Comment by running-coder** [comment]
seems like a very reasonnable approach, it would allow people to easily do it without adding a callback.. my only concern with this extra option is that it can easily be done otherway without addind another option (I think we are closing to 25) perhaps having at least 2 callback examples (one with onClick and one with onNavigate) and add documentation would do it?

**Comment by sdillinger** [comment]
I guess that's your call.   Your documentation is excellent.  Very clear and precise.   As a user I don't see additional options that are targeted and easy to explain as being a negative.   Requiring callback code to implement the functionality is a de facto option, just a lot more obtuse and difficult to explain.

Having said all that, I'm +1 for option, but either way works for me.

**Comment by sdillinger** [comment]
I've played around with this a bit.  Going with your suggestion it seems I can simply capture the onClickBefore event and trigger the onSubmit callback (I process the item being sending to the server).

How do I trigger the onSubmit event?

Also- quick question.  Why does right-arrow trigger onClick?  It's not a click and it seems to be something that would be handled via onNavigate.  I assume there is a good reason.  Just curious what it is.

Thanks.

**Comment by sdillinger** [comment]
Ok.. so maybe it was blindingly obvious I need  $(typeahead).trigget('submit').   Which gets me to the onSubmit callback,  except the item parameter is empty.

**Comment by running-coder** [comment]
The onsubmit should receive the selected item object from the onclickbefore function and as you mentionned it is currently not (I've just spotted why)

regarding the right arrow (if your text carret is at the end of your string) triggers a click to select the item and I admit not thinking of any usecase where it should be doing otherwise. Also If I remember correctly it was Google's search bar behavior... or perhaps Ive seen it somewhere else.
