### ISSUE TITLE
external request

### ISSUE THREAD

**Issue by halukkaramete** [running-coder/jquery-typeahead#543]
Is there a demo where there is no JSON file involved and the user typed characters are sent to MySQL and MySQL makes returns? So far, all examples I've looked at makes use of a json file. I know how to database queries and PHP but could not figure out how I can connect the server-side technologies with your typehead tool

**Comment by ChaerilM** [comment]
on laravel or another php framework, just return a json_encode or json response. on pure vanilla PHP. use echo json_encode I think
