### ISSUE TITLE
Reinitialize

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#56]
I have a problem implementing this use case:

*User searches for and finds item using typeahead.  The result is in the input box and is the only match.
*User deletes the item using other functionality on the page

How do I remove the item from the input?   It has been deleted, so I don't want to leave it there.  I'd like to get back to the beginning state.  Essentially the state I'd be in if I clicked the 'x' in the input box.

I tried $('input').val(''), but that screws things up.

If there is not an easy way to clear the input, is it possible to reinit the plugin?

Thanks for answering my questions today.  This is an excellent piece of software and a great fit for what I'm building.

**Comment by running-coder** [comment]
Hey, Im not 100% sure to understand the usecase but perhaps triggering a manual search event after the input has been modified .val('') would solve your issue? normally the search function would be auto triggered by typing text but in that case you are modifying the dom so it needs to be triggered otherway. An example of such trigger can be found at the very end of game_v2 trigger typeahead.input, in that demo im clearing the filters and I need the trigger a search afterwards to update the results

**Comment by sdillinger** [comment]
Sorry for not being clear.  I was simply looking for a way to 'reset' the search- essential clear the input box back to a virgin state.

Your suggestion to follow  .val('') with $(typeahead).trigger('input.typeahead');   Worked great.  Thanks.
