### ISSUE TITLE
ESC does not propagate even after closing suggestions

### ISSUE THREAD

**Issue by ThiefMaster** [running-coder/jquery-typeahead#57]
Initially an ESC keypress in the text field propagates up the dom tree. When suggestions are displayed, it closes the suggestions instead. Another ESC keypress afterwards doesn't propagate up anymore.

I think ESC should propagate normally while no suggestions are shown. For example, we're showing a form in a dialog that can be closed with ESC, but that doesn't work while focusing the typeahead-enhanced field once suggestions had been shown.

**Comment by running-coder** [comment]
Hey ThiefMaster,

Good call!

I'm not using .stopPropagation but .preventDefault for the ESC case, 
https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L859

I'll look into .stopImmediatePropagation() my goal is to close the Typeahead result list but indeed I'm blocking for further actions

**Comment by ThiefMaster** [comment]
Ah.. Apparently the jQuery UI dialog ignores ESC if the default action is prevented:

```javascript
			keydown: function( event ) {
				if ( this.options.closeOnEscape && !event.isDefaultPrevented() && event.keyCode &&
						event.keyCode === $.ui.keyCode.ESCAPE ) {
```

**Comment by ThiefMaster** [comment]
I think the only problem is that the event is preventDefaulted even if the result list wasn't open (if it is open, then preventDefault/stopPropagation makes lots of sense)
