### ISSUE TITLE
`debug` option is ignored

### ISSUE THREAD

**Issue by ThiefMaster** [running-coder/jquery-typeahead#58]
Right now the `src` version ALWAYS logs debug information, even if `debug` is set to false (apparently this option is completely ignored in favor of the `{debug}` comments).

I think it would be much cleaner to also add a check for the `debug` option the debug code really only runs if debugging is enabled.

**Comment by running-coder** [comment]
Yea, I was expecting people to use the src version to setup their Typeaheads and once its done to switch to the build version as explained in the first line of the documentation... perhaps I was too ambitious over that...

**Comment by ThiefMaster** [comment]
In our application we use the `src` version since we have a custom build step for production which minifies all the js/css files (instead of using the minified upstream versions).

**Comment by running-coder** [comment]
there is a unminified version that strips all the debug info and dramatically reduce the file size (you can see what it does inside Gruntfile.js) but i guess you are right I should re-enable the debug parameter and not force it

p.s. you should try to find a way to use the build version, its much lighter but I guess that if you minify and gzip there is not much impact at the end

**Comment by ThiefMaster** [comment]
From what I've see the only difference is the lack of comments in the build version. These are already stripped when we minify everything so I guess the end result is pretty much the same.

**Comment by running-coder** [comment]
i doubt your application minification is doing this

 ```javascript
           removeDebug: {
                options: {
                    patterns: [
                        {
                            match: /\/\/\s?\{debug}[\s\S]*?\{\/debug}/g,
                            replacement: ''
                        }
                    ]
                },
```
but then I could be wrong..

**Comment by ThiefMaster** [comment]
You're right, we aren't doing that ;)

**Comment by running-coder** [comment]
at this point as mentionned it is very trivial if your application prod environment is serving gzipped files from a cdn

I'll fix the debug option as it may prevent some unwanted console message and lead to missunderstanding

thanks for your input

**Comment by running-coder** [comment]
There we go :+1: , I've removed the unminified version inside /dist/ to avoid confusion

**Comment by ThiefMaster** [comment]
What about `debug: undefined` as a default which shows the warning message about using a debug version in production, and not showing it when explicitly setting a value for `debug`? That way the typical user gets the information, but if you use the debug version on purpose (maybe you want to enable debug in certain cases but not in others) and set the `debug` option the warning wouldn't show up.

**Comment by running-coder** [comment]
That could work, I was worried that people would forget and use the larger file

**Comment by stevanradakovic** [comment]
I'm sorry for bringing this up again, but in debian packaging there's both jquery.typeahead.js and the minified version. Unfortunately they both include the 'debug' section which prints debug logs to the console when typeahead js is loaded. Is there any way to explicitly turn this off without modifying the source files?

**Comment by stevanradakovic** [comment]
@running-coder yes I realized that this is a debian problem I'll have to ping the package maintainers in debian, thank you
