### ISSUE TITLE
Minor Annoyance

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#59]
This is a minor issue, but it's something I encounter a dozen times a day so I wanted to point it out.   The code for the demos is clipped on the right side of my screen on my browser (Chrome 44).  R/L scrolling the small are isn't fun.  

Here's  a screenshot.   Takes nothing away from what is a great plugin. 

![image](https://cloud.githubusercontent.com/assets/2574161/8879909/6401f9e2-31fa-11e5-8f1b-20cbde3c28c2.png)

**Comment by running-coder** [comment]
Hey sdillinger,

thanks for pointing it out! I found it a bit annoying too at first but somehow got used to it... and since I'm not reading code from that window maybe I got lazy and forgot to re-arrange it.

Constructive comments as always, keep it coming.

thanks again!
