### ISSUE TITLE
Can I store a key:value pair and retrieve the key on change

### ISSUE THREAD

**Issue by pradeshc** [running-coder/jquery-typeahead#60]
I've scoured the documentation to find how to use a key:value pair for the item data, but I cannot find an example.

Currently, my code looks like the countries example:
```php
$(document).ready(function() {
  // Typeahead
  $('#pickup').typeahead({
    order: "desc",
    source: {
      data: [
        "Afghanistan", "Albania", "Algeria"
      ]
    },
    callback: {
      onInit: function(node) {
        console.log('Typeahead Initiated on ' + node.selector);
      }
    }
  });
```

What I want is to send the database id together with the country name in the above example.

Currently, because I am retrieving the name of the selected country, I am forced to do an additional text lookup on the database to retrieve the id upon selection. The ability to store and retrieve the id will avoid the database lookup.

**Comment by running-coder** [comment]
Hey pradeshc,

the source.data accepts an array of strings (as your example) or an array of objects.

``` javascript
$(document).ready(function() {
  // Typeahead
  $('#pickup').typeahead({
    order: "desc",
    display: "name", // Typeahead will search through "name" object property
    source: {
      data: [{
        id: 1,
        name: "Afghanistan"
        }, {
        id: 2,
        name: "Albania"
        }, etc.
      ]
    },
    callback: {
      onInit: function(node) {
        console.log('Typeahead Initiated on ' + node.selector);
      }
    }
  });
```

**Comment by pradeshc** [comment]
Thank you
I suppose this is a common usage and perhaps deserve an example in the documentation.
I would propose a simple example of an id:value data source to render the plugin, and retrieval of the id being populated in the form, the common way a &lt;select&gt; tag will be used in a form,

I was able to use your example, and then populate a hidden field in my form with the id value.

The one think I noticed about the Click event is that *node* will give you the value you typed (eg. 'Mi') and *obj* will give you the value you selected from the list (eg. "Miami").

```javascript
$(document).ready(function() {
  // Typeahead
  $('#pickup').typeahead({
    order: "desc",
    display: "name", // Typeahead will search through "name" object property
    source: {
      data: [{
        id: 1,
        name: "Afghanistan"
        }, {
        id: 2,
        name: "Albania"
        }
      ]
    },
    callback: {
      onInit: function(node) {
        console.log('Typeahead Initiated on ' + node.selector);
      },
	onClick: function (node, a, obj, e) {	            
		  $('#city_list-query').val(obj.display);
		  $('#city_list-query').select();
        }
    }
  });
```
