### ISSUE TITLE
Backspace in IE9 has no functionality

### ISSUE THREAD

**Issue by mschneck** [running-coder/jquery-typeahead#62]
If I type a few characters I'll get the suggestions list. But if I delete the last character with backspace no update event is fired. I see the same results as before even if I delete all characters. Entering a new character updates the list again.

The behaviour can be reproduced on the demo page with the Country v1 demo.

**Comment by running-coder** [comment]
Hey mschneck,

found out that IE9 has some issue triggering "input" event when text gets deleted:
http://stackoverflow.com/questions/6382389/oninput-in-ie9-doesnt-fire-when-we-hit-backspace-del-do-cut

I've made an ugly hack to get around it, should work now

Thanks

**Comment by mschneck** [comment]
Hi Running-Coder Team,

it works like charm - but your right, it's an ugly hack. I'll hope IE9 won't be a target browser as soon as possible.


Thanks lot for the very fast solution
