### ISSUE TITLE
Template {{string}} does not work when false

### ISSUE THREAD

**Issue by nateperry** [running-coder/jquery-typeahead#64]
Hello again,

I am using the following template string:
```
template: '<span class="active-{{active|raw}}">{{name}}</span>'
```

The property `active` is a boolean and is read from a json file. I want to setup a class for `.active-false` in my css to slightly change the color on items in the typeahead but still allow them to be clickable. 

The rendered HTML ends up being the following
```
// when active == true
<span class="active-true">Some Name</span>

// when active == false
<span class="active-{{active|raw}}">Some Name</span>

// what I would expect to happen when active == false
<span class="active-false">Some Name</span>
```

Any thoughts on this? Seems like a bug, but I could see a reason for 'false' not being a valid input.

**Comment by running-coder** [comment]
Behaviour slightly changed, now if the key is not found Typeahead will display "" (empty string) instead of {{missingkey}}

**Comment by nateperry** [comment]
Thanks for the quick fix!
