### ISSUE TITLE
Bootstrap 3 Documentation with Navbar Search Field example

### ISSUE THREAD

**Issue by gittix09** [running-coder/jquery-typeahead#65]
Hi!! Thank you for this project.
I'm struggling to implement this jquery plugin with the current version of bootstrap.
I can't find any reference in the documentation, aside from this link (http://www.runningcoder.org/jquerytypeahead/demo/#form-bootstrap_v1) which refers to a non existent section of the demo page.

Could you please write a basic example of how to use this plugin with Bootstrap 3?
Two use-cases: 
- search field inside navbar
- horizontal/vertical form inside the page

**Comment by running-coder** [comment]
Hey gittix,

indeed I had a bootstrap integration demo in the past and I think it's still in my repo somewhere... I'll check if I can make it available soon.

Thanks

**Comment by gittix09** [comment]
Hi!! Thank you very much for your kind reply. 
I really appreciate your feedback. I was really hoping to be able to implement this plugin in a bootstrap page.   
Your project is simply "the best" out there. It is true what you wrote in the overview section of your website: "...The most advanced Typeahead plugin, nowhere you will see that many options..."

**Comment by running-coder** [comment]
Thanks for the kind words!. 

Regarding the Bootstrap integration I've tried and it's working pretty much out of the box when both (bootstrap.css & jquery.typeahead.css) are included. Have you had difficulties to integrate it a certain way? Perhaps you have an integration I can look at?

Also I just saw that Bootstrap 4 is on it's way, this one might require some adjustments inside Typeahead's css file.

**Comment by gittix09** [comment]
Hi!!
Unfortunately I am developing on my local machine but my goal is very simple. Here are some details:
- look at the Bootstrap 3 default navbar http://getbootstrap.com/components/#navbar-default 
- substitute the search field with your jquery typeahead
That's it!! 

Could you please write here (or in the docs) what html and js code do we need to use?

Thanks

**Comment by running-coder** [comment]
I've added a basic bootstrap implementation, basically it was only about replacing their form by the Typeahead form.

Cheers
