### ISSUE TITLE
dropDownFilter stuck on screen

### ISSUE THREAD

**Issue by lmatra** [running-coder/jquery-typeahead#66]
Is there a way to remove the dropDownFilter and then use a different configuration for the dropDownFilter?

I have multiple typeahead fields on my page, and I've noticed that if I try to change the items via jquery typeahead to use a different dropDownFilter, the first filter stays resident on the screen and shows as undefined

![screen shot 2015-08-20 at 10 17 57 am](https://cloud.githubusercontent.com/assets/6183083/9385515/e4780622-4724-11e5-9758-d0b1849f3aac.png)

**Comment by running-coder** [comment]
Hey lmatra,

this is very strange...  you can change the filtering keys from inside your objects instead of the default source.groups as specified in the documentation

``` javascript
dropdownFilter: [
    {
        key: 'conference',
        value: 'Western',
        display: '<strong>Western</strong> Conference Teams'
    },{
        key: 'conference',
        value: 'Eastern',
        display: '<strong>Eastern</strong> Conference Teams'
    },{
        key: 'division',
        value: 'Northeast',
        display: '<strong>Northeast</strong> Division Teams'
    },{
        value: '*',
        display: 'All Teams'
    }
]
```

there is also http://www.runningcoder.org/jquerytypeahead/demo/#form-game_v2 that shows how to use data filtering based on select/radio/checkbox

I might need more details about your integration our a plunkr (http://plnkr.co/edit/?p=catalogue) to help you further...

**Comment by lmatra** [comment]
Thanks Tom,


I am using exactly the same Demo you referenced - Hockey.

What I need to do differently is to change the dropdownFilter based on a select box displayed elsewhere on the page.

So for instance, if the chosen select item was say “Northeast”, the dropdownFilter would change from displaying all to  this

> dropdownFilter: [
> {
>         key: 'conference',
>         value: 'Eastern',
>         display: '<strong>Eastern</strong> Conference Teams'
>     },{
>         key: 'division',
>         value: 'Northeast',
>         display: '<strong>Northeast</strong> Division Teams'
>     },{
>         value: '*',
>         display: 'All Teams'
>     }
> ]

and if the user changes it to All, it would show all again.

In my example I have transit methods of Air, Sea, Land as the filters, and I want to change the dropdown filter to include:
All    -> If user selects Land,
Only Sea  -> If user selects  Sea Cargo, or
Only Air   -> If user selects  Air Cargo.
Is there a simple example you can point me to, that will allow me to change either the dropdownFIlter and/or the Ajax url?

**Comment by running-coder** [comment]
Ah! so "dynamic" dropdownFilter.. It is currently not supported but I will consider it for a future version. Other people have also requested dynamic source switching. As of now once the Typeahead is instanciated there is now way to update the configuration, unfortunatly.
