### ISSUE TITLE
Query in URL path instead of parameter

### ISSUE THREAD

**Issue by klawry** [running-coder/jquery-typeahead#67]
Hello,

I was curious if it's possible to pass the user's search input as part of the URL path instead of as a query string parameter.

All of the examples in the documentation show adding a query string parameter "d" by using the data property.  Example:
```javascript
url: [{
    type: "POST",
    url: "http://server/user",
    data: {
        q: "{{query}}"
    }
}, "data.user"]
```
This produces a URL that looks like:  `http://server/user?q=john`  However I need the user's search to appear in the path.  I want the URL to be:  `http://server/user/john`

Can this be accomplished without changing the typeahead source code?  Ideally, the {{query}} tag could be added to the URL setting instead like `url: "http://server/user/{{query}}"`.

Thanks!

**Comment by running-coder** [comment]
Hey klawry,

wasn't too complicated, I've tested it with dynamic: true option and it seemed to work as expected, let me know.

Thanks

**Comment by klawry** [comment]
Awesome!  Thanks so much for your help.

**Comment by mockingjs** [comment]
This is *exactly* what I was looking for! Thank you!
