### ISSUE TITLE
It is possible to populate dropdown using same object key used in groups?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#70]
If I provide a string (key) to the groups option - for example, 'division' in the hockey example, the query result sorts and groups by the values it finds.

I want to also filter by those same values using the dropdown.  But I can't find a way to associate the two.  In the example the dropdown values are 'hard coded' via an array.

Is it possible to associate groups and dropdown so that the dropdown values are the same values from groups?  

If not I'd like to suggest it as a new feature as it would be uber-useful for situations where the group values are not known in advance, but are found via a key lookup (as works in groups).  

Perhaps it would be a straight-forward hack as you already have the values in context if the user provided a key to the groups option.

**Comment by running-coder** [comment]
Hey sdillinger,

sounds like a great plan, perhaps it should have been like this from the get-go

**Comment by running-coder** [comment]
I've started working on it thinking it was a great idea to realize 2 hours after that in the case of dynamic data it would not work because only a subset of items is received at a time (10 items only for example) and would not offer all the available groups. This option to "self discover groups" only works if the data is all gathered at once... Might consider allowing the system to have both possibilities but not sure if it would lead to confusion...

``` javascript
// Regular dropdownFilter, fits for dynamic & static data
dropdownFilter: [
    {
        key: 'conference',
        value: 'Western',
        display: '<strong>Western</strong> Conference'
    },
    {
        key: 'conference',
        value: 'Eastern',
        display: '<strong>Eastern</strong> Conference'
    },
    {
        value: '*',
        display: 'All Teams'
    }
],

// Static data only, self discovering groups
dropdownFilter: {
    key: 'division',
    template: '<strong>{{division}}</strong> division',
    all: 'All Teams'
},
```

**Comment by sdillinger** [comment]
It's been awhile since I've had my head around this...

In my particular use case the data was static, but I see the issue re: dynamic data. 

IMO it's pretty powerful and useful functionality, so it may be worth the uptick in complexity...

**Comment by running-coder** [comment]
Yea mb it's been a while, I've finally got some free time to clean the backlog. Alright will implement both ways. Will probably update the `group` option parameters also to accept the same object structure instead of an array where index 0 is assumed group and index 1 assumed template.

**Comment by running-coder** [comment]
should be good with the upcoming 2.5.0 version, documentation will be updated upon release

**Comment by sdillinger** [comment]
Great.  Thanks for all you do.

On Mon, Apr 4, 2016 at 8:29 PM, Tom Bertrand <notifications@github.com>
wrote:

> should be good with the upcoming 2.5.0 version, documentation will be
> updated upon release
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/running-coder/jquery-typeahead/issues/70#issuecomment-205581115>
>



-- 
*Steve Dillinger*
Founder & CEO

* <http://www.classroom-iq.com>*

steve@ciqlabs.com
(312) 804-4799

www.getclassroomiq.com

https://www.youtube.com/watch?v=lfTvwbFXVlg

**Comment by running-coder** [comment]
yw, this task was quite challenging at different levels. thanks for suggesting!
