### ISSUE TITLE
Search by words

### ISSUE THREAD

**Issue by Trojda** [running-coder/jquery-typeahead#72]
Hi,
is it possible to search in dataset by words? - in dynamic search I can query database records by words parsed from input string, but typeahead will not display that result, for example a database record named "the best and really awesome plugin" won't be displayed in typeahead by query "best plugin" - this greatly reduce usability.

Thanks,
Martin

**Comment by running-coder** [comment]
hey Trojda,

if you are filtering the data in backend and you want to display the results "as is" from the dynamic request you can use filter: false to disable Typeahead filtering.

``` javascript
$.typeahead({
    input: "#q",
    source: {
        game: {
            data: [...],
            filter: false, // Disable filtering for "game" group
            url: [{
                url: "...",
                dataType: "jsonp"
            }
       }
    }
)}
```

regarding having a suggestion / part matching as part of Typeahead, it is not yet implemented.

Thx.

**Comment by Trojda** [comment]
Hi Tom,
thank you, that is all I needed. And sorry for your time - I've completely overlooked the source.filter option. 

BR,
Martin

**Comment by running-coder** [comment]
Np Martin! 
Always cool to hear how devs are using Typeahead.
