### ISSUE TITLE
Is there a way to capture the remote data in source?

### ISSUE THREAD

**Issue by amJustCoding** [running-coder/jquery-typeahead#73]
I'd like to capture the data returned in the remote url... Not sure how to do this.
Basically, I'd like to extract the returned data in a variable so that I can check later if the user entered a value that is found in that data list which was originally from remote ajax call.

Any help would be appreciated!  Thanks!

source: {
            remote: {
                url: [{
                    url: url,
                    data: {
                        term: "{{query}}"
                    }
                }]
            }
        },

**Comment by running-coder** [comment]
hey amJustCoding,

indeed you can! You can refer to user_v1 demo or the documentation of "options.source"

``` javascript
source: {
    remote: {
        url: [{
            url: url,
            data: {
                term: "{{query}}"
            },
            callback: {
                done: function (data, textStatus, jqXHR) {
                    console.log(data);
                    // data has to be returned
                    return data;
                },
                fail: function (jqXHR, textStatus, errorThrown) {},
                complete: function (jqXHR, textStatus) {},
                always :function (data, textStatus, jqXHR) {}
            }
        }]
    }
}
```
