### ISSUE TITLE
Query term in source url

### ISSUE THREAD

**Issue by aviaialon** [running-coder/jquery-typeahead#74]
Hi. (Possibly a noob question).
I need to have the query added to the source url,
Example: /api/cars/search/<search_query>
I havent found a way to do that. It would be cool if the source url could be a function, such as:
{
Source: {
    url: function  (term) {
          return '/api/cars/search' + term;
     }
   }
}

**Comment by aviaialon** [comment]
Sorry, the example url should be: /api/cars/search/{{term}}

**Comment by running-coder** [comment]
hey aviailon, someone recently requested the {{query}} to be a part of the url inside #67 , perhaps I've forgot to update the doc.
