### ISSUE TITLE
New feature please

### ISSUE THREAD

**Issue by ichuot** [running-coder/jquery-typeahead#81]
"CPU Intel Pentium E2140". It can be found with keyword "Intel 2140" or "CPU E2140" or "Pen 2140"... Please add this feature. Thank you so much! this plugin is great.

**Comment by running-coder** [comment]
hey ichuot,

have you tried the option correlativeTemplate: true? It should enable what you are looking for.

**Comment by ichuot** [comment]
I have upgraded to 2.1.0. Awesome! thank you again!

**Comment by running-coder** [comment]
np, enjoy
