### ISSUE TITLE
How to use JSON?

### ISSUE THREAD

**Issue by rajlaksh** [running-coder/jquery-typeahead#82]
I'm just started to use it. I want to use JSON how to use it,

My JS CODE
`$('#search').typeahead({`
`minLength: 1,	`
`source: {`
`            url: [{`
`                type: "post",`
`                dataType: "json",`
`                url: base_url+'/ajax/search',`
`                data: {`
`                    q: "{{query}}"`
`                }`
`            }, "user"]`
`        },`
`debug : true		`
`});`

Old JSON Output

`[{"full_name":"admin","user_name":"admin","avatar":"http:\/\/localhost\/uploads\/1\/profile_pic\/avatar.jpg"}]` 

New JSON output

`{"status":true,"error":null,"user":[{"full_name":"admin","user_name":"admin","avatar":"http:\/\/localhost\/uploads\/1\/profile_pic\/avatar.jpg"}]}`

**Comment by running-coder** [comment]
hey rajlaksh, 

It seems you are missing a display option: display: ["full_name", "user_name"]

**Comment by rajlaksh** [comment]
Thanks. It works.
