### ISSUE TITLE
Getting name of array from which the data is selected

### ISSUE THREAD

**Issue by vashudev92** [running-coder/jquery-typeahead#84]
$('#search_restaurant').typeahead({
    minLength: 1,
    order: "asc",
    template: "{{display}} <small style='color:#999;' id='{{group}}'>{{group}}</small>",
    source: {
        Restaurant: {
            url: ["sqlfiles/search_data.php", "data.country"]
        },
		Estb: {
            url: ["sqlfiles/search_data.php", "data.dish"]
        },
		Sub: {
            url: ["sqlfiles/search_data.php", "data.sub"]
        },
        Cusines: {
            url: [
                {
                    type: "POST",
                    url: "sqlfiles/search_data.php",
                    data: {myKey: "myValue"}
                },
                "data.capital"
            ]
        }
    },
	
});

In the above code runner code what i want is the name of the array variable like restaurant,cusines,sub,Estb in an java script variable on clicking in its result data. i have refer your documents many time but cant find solution for that.

**Comment by running-coder** [comment]
hey,

have you looked into the onClickAfter callback?

```javascript
$('#search_restaurant').typeahead({
    minLength: 1,
    order: "asc",
    template: "{{display}} {{group}}",
    source: {
        Restaurant: {
            url: ["sqlfiles/search_data.php", "data.country"]
        },
        Estb: {
            url: ["sqlfiles/search_data.php", "data.dish"]
        },
        Sub: {
            url: ["sqlfiles/search_data.php", "data.sub"]
        },
        Cusines: {
            url: [
                {
                    type: "POST",
                    url: "sqlfiles/search_data.php",
                    data: {myKey: "myValue"}
                },
                "data.capital"
            ]
        }
    },
    callback: {
        onClickAfter: function (node, a, item, event) {
            // item.group should be what you are looking for
            console.log(item)
        }
    }
});
```

**Comment by vashudev92** [comment]
Thanks tom for this suggestion  i am aware of onClickAfter callback but i haven't tried the item.group. by the way thanks again your comment is really helpful to me.
