### ISSUE TITLE
{{query}} on url does not get updated on the second search

### ISSUE THREAD

**Issue by bichotll** [running-coder/jquery-typeahead#87]
I found out that {{query}} in url parameter does not change every time query changes.
I've tested it and it does with data but not on the url. It just goes once to url:

https://github.com/running-coder/jquery-typeahead/blob/master/src/jquery.typeahead.js#L647

Documentation:
```
url: [{
            type: "POST",
            // The {{query}} can also be replaced inside the URL
            // url: "/jquerytypeahead/{{query}}",
            url: "/jquerytypeahead/user_v1.json",
            data: {
                q: "{{query}}",
                type: function () { return $('#user-type').val(); }
            }
        }, "data.user"]
```

I've tried to debug it and then solve...but the code does not look familiar for me.
Let me know.

**Comment by running-coder** [comment]
hey bichotll, can you paste your typeahead init code? the problem may be there.

**Comment by bichotll** [comment]
I've even tried to apply the example one without luck ;)

```
  var $searchInput = $("#search-input");
  $searchInput.typeahead({
    minLength: 2,
    delay: 300,
    dynamic: true,
    source: {
      streets: {
        display: 'street_name',
        url: [{
          type: "GET",
          url: "/jquerytypeahead/{{query}}"
        }, 'streets']
      }
    }
  });
```

**Comment by running-coder** [comment]
Cool, I'll have a look. Thought this got solved when doing #67

**Comment by bichotll** [comment]
Nice! Cheers!

I've just created a workaround on my temporally branch:
https://github.com/bichotll/jquery-typeahead/blob/master/src/jquery.typeahead.js#L551

**Comment by running-coder** [comment]
Thanks for reporting the issue, should be fixed now
