### ISSUE TITLE
Reload the source

### ISSUE THREAD

**Issue by fairly99** [running-coder/jquery-typeahead#89]
Hey,
is there a way to reload the source, everytime the user clicks in the input box or starts typing a new search? Thanks.

**Comment by running-coder** [comment]
Hey,

have you looked into the `searchOnFocus` and `dynamic` options?

**Comment by fairly99** [comment]
Thank you. 
I have another question. I had to create the HTML structure dynamically, through Javascript 
(``` td.innerHTML = "<div class= 'typeahead-container'><div class='typeahead-field'><span class='typeahead-query'><input type='search'  name='name0' id='valueField"+i+"' autocomplete='off'  /></span></div></div>"```) but now it wont work anymore, even though its the same code! Why would be that the case?

**Comment by fairly99** [comment]
Solved it
