### ISSUE TITLE
Need Help AutoComplet

### ISSUE THREAD

**Issue by sergefabre** [running-coder/jquery-typeahead#91]
Hello, 
sorry for my english, I am french...
I want than first résult of my search is autoselect, and when I press Enter, this first result is submit.
Can you help me ?

**Comment by sergefabre** [comment]
Hello,
I think this is a solution... :

//Rames Auto-complete
    function getAllRames(){
        $.getJSON("Set/GetAllRames", { IDstf: $('#stfsList').val() })
        .done(function (json) {

            StfSelected = { ID: json.STF.ID, STF: json.STF.STF, IdStfRm: json.STF.IdStfRm, OsmStf: json.STF.OsmStf };

            var tabFilter = new Array();
            var newData = _.chain(json.data).pluck('SousSerie').unique().value();
            for (var i = 0; i <= newData.length - 1; i++) { tabFilter.push({ key: "SousSerie", value: newData[i], display: '<strong>SousSerie </strong>' + newData[i] }); }
            tabFilter.push({ value: "*", display: 'Toutes' });

            $.typeahead({
                input:              "#RameInput",
                offset:             true,
                searchOnFocus:      true,
                highlight :         true,
                minLength:          1,
                maxItem:            8,
                maxItemPerGroup:    6,
                order:              "asc",
                hint:               true,
                emptyTemplate:      "Aucune rame n'existe avec {{query}}",
                group:              ["SousSerie", "Sous-Série : {{group}} "],
                display:            ["EAB", "numEF"],
                template:           "{{EAB}}",
                source:             json,
                dropdownFilter:     tabFilter,
                callback: {
                    onClickAfter: function (node, a, item, event) {
                        RameSelected = item;
                        ActualiseData();
                        GetLibRest();
                    },
                    onResult: function (node, query, result, resultCount) { RameSelected = result[0]; },
                    onNavigate: function (node, query, event) {
                        if (event.keyCode == 13) {
                            $("#RameInput").val(RameSelected.EAB);
                            ActualiseData();
                            GetLibRest();
                        }
                    }
                }
            });
        })
        .fail(function (jqxhr, textStatus, error) { alert("Request Failed: " + err);});
    }

Are you ok ?

**Comment by running-coder** [comment]
Hey sergefabre,

is this solution giving the expected result? I was thinking of simply adding the active class manually on the first element of the result list.

``` javascript
callback: {
    onLayoutBuiltBefore: function (node, query, result, resultHtmlList) {
        return resultHtmlList.find('li:first').addClass('active');
    }
}
```

I believe that when the enter key is pressed and if there is an element with active class it will select that element. I did not test the code above but a similar solution might help you achieve your objective!

Thanks
