### ISSUE TITLE
resultContainer wont dismiss on blur

### ISSUE THREAD

**Issue by giorgoc** [running-coder/jquery-typeahead#92]
Plugin works perfectly no issues at all. My only issue is that the resultContainer wont dismiss on blur, when users use the tab to move to the next field. They have to click to the suggested option, thats the only way to get it dismissed.

Any syggestion how to resolve this?

Thanks!

**Comment by running-coder** [comment]
Hey giorgoc,

indeed I did not tested the "tab" key in a form context where there would be multiple input fields around. I'll take a look as soon as I have time.

Thanks!

**Comment by giorgoc** [comment]
Great thanks! :)

**Comment by running-coder** [comment]
I've added the tab keycode (9) to behave the same as Esc meaning that if there is results they will hide on the first keystroke and the second will behave as the browser would expect, in your case going to the next input.
