### ISSUE TITLE
onLayoutBuiltBefore:  window.Typeahead['#name-match-input']['hintIndex'] returns null

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#94]
I have a setup where the user can search by initials or name.   I want to highlight the current hinted selection.   In my case the hinted selection isn't always the first selection.  

Like here:

![image](https://cloud.githubusercontent.com/assets/2574161/10649397/7f85efc0-7809-11e5-9bec-2c99ee1d0947.png)

To fix this I do the following in onLayoutBulidBefore:

```
//get the index of the hinted record
var index = window.Typeahead['#name-match-input']['hintIndex'];

//remove the element from dom & style it
var hinted_el = resultHtmlList.find('li a[data-index="' + index + '"]').parents('li').addClass('top-selection').detach();

//add back to top of list
$(hinted_el).prependTo(resultHtmlList);
```

Problem:

On entry of the first query letter ('m' above) this line:

```
var index = window.Typeahead['#name-match-input']['hintIndex'];
```

return null;

For all subsequent letters it returns the correct index.

![image](https://cloud.githubusercontent.com/assets/2574161/10649571/6b459d2a-780a-11e5-9182-693cde4f72bf.png)

As a side note I think the hinted selection should be the first one in the list by default- not a big deal really, just a gut feeling.

Thanks.

**Comment by sdillinger** [comment]
update:

Playing with this a bit more it seems the hintIndex is indeterminate.   Using the example above.  If I search mu I get an hintIndex of 1.

![image](https://cloud.githubusercontent.com/assets/2574161/10651435/27bd24e6-7815-11e5-8fb9-440e24e1ad1e.png)

values in onLayoutBuiltBefore:

![image](https://cloud.githubusercontent.com/assets/2574161/10651490/6edcf18a-7815-11e5-8dcc-563905d43779.png)

**Comment by running-coder** [comment]
hey dillinger,

I think your issue was caused by the fact that the callback was called before assigning the hintIndex. So everytime you would receive it, it would be the hint index of the previous search and not the current one.

Let me know

Thanks.

**Comment by sdillinger** [comment]
That could definitely be the issue.

Any suggestions on how to handle this?​

On Wed, Oct 21, 2015 at 5:20 PM, Tom Bertrand <notifications@github.com>
wrote:

> hey dillinger,
>
> I think your issue was caused by the fact that the callback was called
> before assigning the hintIndex. So everytime you would receive it, it would
> be the hint index of the previous search and not the current one.
>
> Let me know
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/running-coder/jquery-typeahead/issues/94#issuecomment-150041094>
> .
>



-- 
*Steve Dillinger*
Founder & CEO

* <http://www.classroom-iq.com>*

CIQ Labs - ClassroomIQ
222 Merchandise Mart Plaza
Suite 1212
Chicago, IL 60654

steve@ciqlabs.com
(312) 804-4799

www.getclassroomiq.com <http://www.classroom-iq.com>

**Comment by running-coder** [comment]
Try to update to the latest Master code, I've pushed a potential fix

**Comment by sdillinger** [comment]
While I haven't done crazy robust testing, it seems to be working now.  

Thanks for the quick support!!

**Comment by running-coder** [comment]
Cool! Glad I don't have to re-tag 2.1.3 hehe
