### ISSUE TITLE
Can I order group layout?

### ISSUE THREAD

**Issue by sdillinger** [running-coder/jquery-typeahead#95]
Hi,

Other than reworking the resultHtml, is there a way to order the grouping in the result dropdown?

In my use case there are two group - 'available' and 'not available'.  I need to show both (long story), but the user will attempt to match against the available group, so I need that one on top.  

I'm grouping by an object key.

Hopefully what I am asking makes sense.

Thanks.

**Comment by sdillinger** [comment]
it's easy to do this with resultHtml, so just asking out of curiosity...

**Comment by running-coder** [comment]
Perhaps related to #76 ?

**Comment by sdillinger** [comment]
It seems like it might be.. I don't follow the code though.   Do I add an orderedKeys  option to the typeahead object?

**Comment by sdillinger** [comment]
it turns out it is not easy to do this with resultHtml as I need to search the groups in a particular order, not just display them in order.

**Comment by sdillinger** [comment]
Yes that's it... any chance you can merge it in?

**Comment by running-coder** [comment]
Yea, but I want to also take time to maybe build it as a callback or a function so it is possible to control the ordering based on your custom conditions.

**Comment by sdillinger** [comment]
Ok.. Thanks...  I realized that since I control the server json creation I
could just order it there, which seems to work.

Having said that I still think it would be a useful feature.

On Thu, Oct 22, 2015 at 3:58 PM, Tom Bertrand <notifications@github.com>
wrote:

> Yea, but I want to also take time to maybe build it as a callback or a
> function so it is possible to control the ordering based on your custom
> conditions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/running-coder/jquery-typeahead/issues/95#issuecomment-150354349>
> .
>



-- 
*Steve Dillinger*
Founder & CEO

* <http://www.classroom-iq.com>*

CIQ Labs - ClassroomIQ
222 Merchandise Mart Plaza
Suite 1212
Chicago, IL 60654

steve@ciqlabs.com
(312) 804-4799

www.getclassroomiq.com <http://www.classroom-iq.com>

**Comment by sdillinger** [comment]
I take that back.  When I change the group of a source item it blows up the order again.  

Thanks for slotting it into 2.1.4

**Comment by running-coder** [comment]
hey sdillinger, lmk if the feature behave properly (develop branch for now, will release the tag later tonight / tomorrow)

Thanks

**Comment by running-coder** [comment]
By default, the groups will be output in the same order as they are defined them in options.source
Set "asc" or "desc" to have the group name sorted ascending or descending
Set an Array to specify the group order to appear in the search result
Set a Function that returns an Array

**Comment by sdillinger** [comment]
I think this looks good.   Thanks!
