### ISSUE TITLE
Loading data from JSON file

### ISSUE THREAD

**Issue by lorenscott** [running-coder/jquery-typeahead#97]
I am having trouble getting my data to load from an external JSON file (http://www.livemusichq.com/getvenuelistJSON.txt).  The format is like this: 

[
{ id: '7402', name: 'Pale Eddie\'s Pour House', city: 'Birmingham', state: 'AL'},
{ id: '8058', name: 'The River Shack', city: 'Mobile', state: 'AL'},
{ id: '8057', name: 'Tropics', city: 'Spanish Fort', state: 'AL'},
{ id: '7593', name: 'Blackbird Cafe', city: 'Mountain Home', state: 'AR'},
{ id: '7799', name: 'Beale Street Brews', city: 'Kingman', state: 'AZ'},
{ id: '8183', name: 'Juicy\'s', city: 'Lake Havasu City', state: 'AZ'}
]

I've tried a few different ways to reference that file in the "source" attribute, ending up with this (which also does not work):

source: {
    url: ["getVenueListJSON.txt","data"]
},

Any suggestions would  be welcome.

Thanks!

**Comment by running-coder** [comment]
Hey loren, make sure to quote your object keys as well, else it will not be a valid JSON.

``` javascript
[
{ 'id': '7402', 'name': 'Pale Eddie\'s Pour House', 'city': 'Birmingham', 'state': 'AL'},
...
]
```

![2015-10-26_1113](https://cloud.githubusercontent.com/assets/7377382/10732908/b52746fc-7bd2-11e5-9423-fed066ef13a6.png)

also

``` javascript
// "data" as the second index means that Typeahead will search the main object for "data" key and use these values to populate source, in your case since there is data object, simply write the url
source: {
    url: "getVenueListJSON.txt"
},
```

**Comment by lorenscott** [comment]
Yes!!!!  Tom, you are the man!  

I can't believe I missed something so simple as the quotes. And, as it turns out, they needed to be double quotes as well, meaning that I also no longer needed to escape the apostrophes within my venue names.  So, now it looks sort of like this:  

[{ "id": "7402", "name": "Pale Eddie's Pour House", city: "Birmingham", state: "AL"},
{ "id": "8058", "name": "The River Shack", city: "Mobile", state: "AL"},
...

And, also changing the "url" attribute exactly as you suggested did the trick.

Thank you VERY much for the assist.  I appreciate it very much.

**Comment by running-coder** [comment]
Welcome
