### ISSUE TITLE
[question] Search Results

### ISSUE THREAD

**Issue by kavin-90** [running-coder/jquery-typeahead#99]
Is this plugin look in template for matching or query?

2nd. How to show loading indicator until ajax does not show results

**Comment by running-coder** [comment]
hi kavin it looks for the user query also to implement a loading indicator you can use these 2 callbacks onSendRequest and onReceiveRequest as defined in #101 inside A-contresens Typeahead init

**Comment by kavin-90** [comment]
@running-coder thanks.

**Comment by kavin-90** [comment]
Can you please answer 1st question.
**Is this plugin look in template for matching or query?**

**Comment by running-coder** [comment]
you submit a source (array of objects or array of strings) then the query will loop through the source and build the template with the results

**Comment by kavin-90** [comment]
highlight code added to no need template result.

I've template like but it add highlight code in `<span class="author">by {{author}}</span> `

`emptyTemplate: 'No result for "{{query}}"',`
`display: ["title","alt_name"],`
`template: '<span class="result">' +`
`'<div class="info">' +`
`'<span class="cover">' +`
`'<img src="{{img}}">' +`
`"</span>" +`
`'<span class="desc" title="{{title}}">' +`
`'<span class="title" title="{{title}}">{{title}} <span class="author">by {{author}}</span></span>'  +`
`'<p>{{categories}}</p>'+`
`'</span>'+`
`'</div>' +`
`"</span>",`

**Comment by kavin-90** [comment]
@running-coder can you please help me?

**Comment by running-coder** [comment]
Seems to be an issue with Typeahead, I'll try fix it ~tomorrow

**Comment by running-coder** [comment]
Should work now, let me know

Thanks.

**Comment by kavin-90** [comment]
Thanks for Update.
